MOM6: src/framework/bitcount.c File Reference
bitcount.c File Reference
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
Functions
int bitcount_ (double *x)
int bitcount (double *x)
Function Documentation
int bitcount (double * x)
Definition at line 22 of file bitcount.c.
References bitcount_().
Referenced by mom_checksums::chksum1d(), mom_checksums::chksum2d(), mom_checksums::chksum3d(), hsubsum2d(), hsubsum3d(), and subchk().
 {
   return bitcount_(x);
 }
int bitcount_ (double * x)
Definition at line 7 of file bitcount.c.
Referenced by bitcount().
 {
 int b;
 unsigned long *y;
 double z;
 z = *x;
 y = (unsigned long *) &z;
 for (b = 0; *y !=0; *y >>= 1)
   if (*y & 01)
     b++;
 return b;
 }