MOM6: p3m_functions Module Reference
p3m_functions Module Reference
Public Member Functions
subroutine, public p3m_interpolation (N, h, u, ppoly)
subroutine, public p3m_boundary_extrapolation (N, h, u, ppoly)
Private Member Functions
subroutine p3m_limiter (N, h, u, ppoly)
subroutine build_cubic_interpolant (h, k, ppoly)
integer function is_cubic_monotonic (ppoly, k)
subroutine monotonize_cubic (h, u0_l, u0_r, sigma_l, sigma_r, slope, u1_l, u1_r)
Detailed Description
Definition at line 1 of file P3M_functions.F90.
Member Function/Subroutine Documentation
subroutine p3m_functions::build_cubic_interpolant (real, dimension(:), intent(in) h, integer, intent(in) k, type(ppoly_t), intent(inout) ppoly) private
Definition at line 351 of file P3M_functions.F90.
Referenced by p3m_boundary_extrapolation(), and p3m_limiter().
integer function p3m_functions::is_cubic_monotonic (type(ppoly_t), intent(in) ppoly, integer, intent(in) k) private
Definition at line 394 of file P3M_functions.F90.
Referenced by p3m_boundary_extrapolation(), and p3m_limiter().
subroutine p3m_functions::monotonize_cubic (real, intent(in) h, real, intent(in) u0_l, real, intent(in) u0_r, real, intent(in) sigma_l, real, intent(in) sigma_r, real, intent(in) slope, real, intent(inout) u1_l, real, intent(inout) u1_r) private
Definition at line 465 of file P3M_functions.F90.
Referenced by p3m_boundary_extrapolation(), and p3m_limiter().
subroutine, public p3m_functions::p3m_boundary_extrapolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 195 of file P3M_functions.F90.
References build_cubic_interpolant(), is_cubic_monotonic(), and monotonize_cubic().
Referenced by mom_regridding::regridding_iteration().
subroutine, public p3m_functions::p3m_interpolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 30 of file P3M_functions.F90.
References p3m_limiter().
Referenced by mom_regridding::regridding_iteration().
subroutine p3m_functions::p3m_limiter (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly) private
Definition at line 61 of file P3M_functions.F90.
References regrid_edge_values::average_discontinuous_edge_values(), regrid_edge_values::bound_edge_values(), build_cubic_interpolant(), is_cubic_monotonic(), and monotonize_cubic().
Referenced by p3m_interpolation().
The documentation for this module was generated from the following file:
src/ALE/P3M_functions.F90