MOM6: mom_entrain_diffusive Module Reference
mom_entrain_diffusive Module Reference
Data Types
type entrain_diffusive_cs
Public Member Functions
subroutine, public entrainment_diffusive (u, v, h, tv, fluxes, dt, G, CS, ea, eb, kb_out, Kd_Lay, Kd_int)
subroutine, public entrain_diffusive_init (Time, G, param_file, diag, CS)
subroutine, public entrain_diffusive_end (CS)
Private Member Functions
subroutine f_to_ent (F, h, kb, kmb, j, G, CS, dsp1_ds, eakb, Ent_bl, ea, eb, do_i_in)
subroutine set_ent_bl (h, dtKd_int, tv, kb, kmb, do_i, G, CS, j, Ent_bl, Sref, h_bl)
subroutine determine_dskb (h_bl, Sref, Ent_bl, E_kb, is, ie, kmb, G, limit, dSkb, ddSkb_dE, dSlay, ddSlay_dE, dS_anom_lim, do_i_in)
subroutine f_kb_to_ea_kb (h_bl, Sref, Ent_bl, I_dSkbp1, F_kb, kmb, i, G, CS, ea_kb, tol_in)
subroutine determine_ea_kb (h_bl, dtKd_kb, Sref, I_dSkbp1, Ent_bl, ea_kbp1, min_eakb, max_eakb, kmb, is, ie, do_i, G, CS, Ent, error, err_min_eakb0, err_max_eakb0, F_kb, dFdfm_kb)
subroutine find_maxf_kb (h_bl, Sref, Ent_bl, I_dSkbp1, min_ent_in, max_ent_in, kmb, is, ie, G, CS, maxF, ent_maxF, do_i_in, F_lim_maxent, F_thresh)
Detailed Description
Definition at line 1 of file MOM_entrain_diffusive.F90.
Member Function/Subroutine Documentation
subroutine mom_entrain_diffusive::determine_dskb (real, dimension(nimem_,nkmem_), intent(in) h_bl, real, dimension(nimem_,nkmem_), intent(in) Sref, real, dimension(nimem_,nkmem_), intent(in) Ent_bl, real, dimension(nimem_), intent(in) E_kb, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) kmb, type(ocean_grid_type), intent(in) G, logical, intent(in) limit, real, dimension(nimem_), intent(inout) dSkb, real, dimension(nimem_), intent(inout), optional ddSkb_dE, real, dimension(nimem_), intent(inout), optional dSlay, real, dimension(nimem_), intent(inout), optional ddSlay_dE, real, dimension(nimem_), intent(inout), optional dS_anom_lim, logical, dimension(nimem_), intent(in), optional do_i_in) private
Definition at line 1177 of file MOM_entrain_diffusive.F90.
References mom_error_handler::mom_error().
Referenced by determine_ea_kb(), entrainment_diffusive(), f_kb_to_ea_kb(), and find_maxf_kb().
subroutine mom_entrain_diffusive::determine_ea_kb (real, dimension(nimem_,nkmem_), intent(in) h_bl, real, dimension(nimem_), intent(in) dtKd_kb, real, dimension(nimem_,nkmem_), intent(in) Sref, real, dimension(nimem_), intent(in) I_dSkbp1, real, dimension(nimem_,nkmem_), intent(in) Ent_bl, real, dimension(nimem_), intent(in) ea_kbp1, real, dimension(nimem_), intent(in) min_eakb, real, dimension(nimem_), intent(in) max_eakb, integer, intent(in) kmb, integer, intent(in) is, integer, intent(in) ie, logical, dimension(nimem_), intent(in) do_i, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), pointer CS, real, dimension(nimem_), intent(inout) Ent, real, dimension(nimem_), intent(out), optional error, real, dimension(nimem_), intent(in), optional err_min_eakb0, real, dimension(nimem_), intent(in), optional err_max_eakb0, real, dimension(nimem_), intent(out), optional F_kb, real, dimension(nimem_), intent(out), optional dFdfm_kb) private
Definition at line 1520 of file MOM_entrain_diffusive.F90.
References determine_dskb(), and mom_error_handler::mom_error().
Referenced by entrainment_diffusive().
subroutine, public mom_entrain_diffusive::entrain_diffusive_end (type(entrain_diffusive_cs), pointer CS)
Definition at line 2060 of file MOM_entrain_diffusive.F90.
Referenced by mom_diabatic_driver::diabatic_driver_end().
subroutine, public mom_entrain_diffusive::entrain_diffusive_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(entrain_diffusive_cs), pointer CS)
Definition at line 2004 of file MOM_entrain_diffusive.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
subroutine, public mom_entrain_diffusive::entrainment_diffusive (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(out) ea, real, dimension(nimem_,njmem_,nkmem_), intent(out) eb, integer, dimension(nimem_,njmem_), intent(inout), optional kb_out, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional Kd_Lay, real, dimension(nimem_,njmem_,nk_interface_), intent(in), optional Kd_int)
Definition at line 102 of file MOM_entrain_diffusive.F90.
References mom_eos::calculate_density_derivs(), determine_dskb(), determine_ea_kb(), f_kb_to_ea_kb(), f_to_ent(), find_maxf_kb(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and set_ent_bl().
Referenced by mom_diabatic_driver::diabatic().
subroutine mom_entrain_diffusive::f_kb_to_ea_kb (real, dimension(nimem_,nkmem_), intent(in) h_bl, real, dimension(nimem_,nkmem_), intent(in) Sref, real, dimension(nimem_,nkmem_), intent(in) Ent_bl, real, dimension(nimem_), intent(in) I_dSkbp1, real, dimension(nimem_), intent(in) F_kb, integer, intent(in) kmb, integer, intent(in) i, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), pointer CS, real, dimension(nimem_), intent(inout) ea_kb, real, intent(in), optional tol_in) private
Definition at line 1405 of file MOM_entrain_diffusive.F90.
References determine_dskb(), and find_maxf_kb().
Referenced by entrainment_diffusive().
subroutine mom_entrain_diffusive::f_to_ent (real, dimension(nimem_,nkmem_), intent(in) F, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, integer, dimension(nimem_), intent(in) kb, integer, intent(in) kmb, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), intent(in) CS, real, dimension(nimem_,nkmem_), intent(in) dsp1_ds, real, dimension(nimem_), intent(in) eakb, real, dimension(nimem_,nkmem_), intent(in) Ent_bl, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) eb, logical, dimension(nimem_), intent(in), optional do_i_in) private
Definition at line 909 of file MOM_entrain_diffusive.F90.
Referenced by entrainment_diffusive().
subroutine mom_entrain_diffusive::find_maxf_kb (real, dimension(nimem_,nkmem_), intent(in) h_bl, real, dimension(nimem_,nkmem_), intent(in) Sref, real, dimension(nimem_,nkmem_), intent(in) Ent_bl, real, dimension(nimem_), intent(in) I_dSkbp1, real, dimension(nimem_), intent(in) min_ent_in, real, dimension(nimem_), intent(in) max_ent_in, integer, intent(in) kmb, integer, intent(in) is, integer, intent(in) ie, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), pointer CS, real, dimension(nimem_), intent(out) maxF, real, dimension(nimem_), intent(out), optional ent_maxF, logical, dimension(nimem_), intent(in), optional do_i_in, real, dimension(nimem_), intent(out), optional F_lim_maxent, real, dimension(nimem_), intent(in), optional F_thresh) private
Definition at line 1717 of file MOM_entrain_diffusive.F90.
References determine_dskb().
Referenced by entrainment_diffusive(), and f_kb_to_ea_kb().
subroutine mom_entrain_diffusive::set_ent_bl (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,nk_interface_), intent(in) dtKd_int, type(thermo_var_ptrs), intent(in) tv, integer, dimension(nimem_), intent(inout) kb, integer, intent(in) kmb, logical, dimension(nimem_), intent(in) do_i, type(ocean_grid_type), intent(in) G, type(entrain_diffusive_cs), pointer CS, integer, intent(in) j, real, dimension(nimem_,nk_interface_), intent(out) Ent_bl, real, dimension(nimem_,nkmem_), intent(out) Sref, real, dimension(nimem_,nkmem_), intent(out) h_bl) private
Definition at line 1016 of file MOM_entrain_diffusive.F90.
Referenced by entrainment_diffusive().
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_entrain_diffusive.F90