MOM6: mom_tracer_z_init Module Reference
mom_tracer_z_init Module Reference
Public Member Functions
logical function, public tracer_z_init (tr, h, filename, tr_name, G, missing_val, land_val)
Private Member Functions
subroutine read_z_edges (filename, tr_name, z_edges, nz_out, has_edges, use_missing, missing)
Detailed Description
Definition at line 1 of file MOM_tracer_Z_init.F90.
Member Function/Subroutine Documentation
subroutine mom_tracer_z_init::read_z_edges (character(len=*), intent(in) filename, character(len=*), intent(in) tr_name, real, dimension(:), intent(out), allocatable z_edges, integer, intent(out) nz_out, logical, intent(out) has_edges, logical, intent(inout) use_missing, real, intent(inout) missing) private
Definition at line 309 of file MOM_tracer_Z_init.F90.
References mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by tracer_z_init().
logical function, public mom_tracer_z_init::tracer_z_init (real, dimension(nimem_,njmem_,nkmem_), intent(out) tr, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, character(len=*), intent(in) filename, character(len=*), intent(in) tr_name, type(ocean_grid_type), intent(in) G, real, intent(in), optional missing_val, real, intent(in), optional land_val)
Definition at line 59 of file MOM_tracer_Z_init.F90.
References mom_diag_to_z::find_limited_slope(), mom_diag_to_z::find_overlap(), mom_error_handler::mom_error(), read_z_edges(), and midas_vertmap::tracer_z_init().
The documentation for this module was generated from the following file:
src/tracer/MOM_tracer_Z_init.F90