MOM6: mom_tidal_forcing Module Reference
mom_tidal_forcing Module Reference
Data Types
type tidal_forcing_cs
Public Member Functions
subroutine, public tidal_forcing_init (Time, G, param_file, CS)
subroutine, public tidal_forcing_sensitivity (G, CS, deta_tidal_deta)
subroutine, public calc_tidal_forcing (Time, eta, eta_tidal, G, CS, deta_tidal_deta)
subroutine, public tidal_forcing_end (CS)
Public Attributes
integer id_clock_tides
Private Member Functions
subroutine find_in_files (tidal_input_files, varname, array, G)
Private Attributes
integer, parameter max_constituents = 10
Detailed Description
Definition at line 1 of file MOM_tidal_forcing.F90.
Member Function/Subroutine Documentation
subroutine, public mom_tidal_forcing::calc_tidal_forcing (type(time_type), intent(in) Time, real, dimension(nimem_,njmem_), intent(in) eta, real, dimension(nimem_,njmem_), intent(out) eta_tidal, type(ocean_grid_type), intent(in) G, type(tidal_forcing_cs), pointer CS, real, intent(out), optional deta_tidal_deta)
Definition at line 444 of file MOM_tidal_forcing.F90.
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss(), mom_pressureforce_afv::pressureforce_afv_nonbouss(), mom_pressureforce_mont::pressureforce_mont_bouss(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
subroutine mom_tidal_forcing::find_in_files (character(len=*), dimension(:), intent(in) tidal_input_files, character(len=*), intent(in) varname, real, dimension(nimem_,njmem_), intent(out) array, type(ocean_grid_type), intent(in) G) private
Definition at line 393 of file MOM_tidal_forcing.F90.
References mom_error_handler::mom_error().
Referenced by tidal_forcing_init().
subroutine, public mom_tidal_forcing::tidal_forcing_end (type(tidal_forcing_cs), pointer CS)
Definition at line 538 of file MOM_tidal_forcing.F90.
subroutine, public mom_tidal_forcing::tidal_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tidal_forcing_cs), pointer CS)
Definition at line 105 of file MOM_tidal_forcing.F90.
References find_in_files(), mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
subroutine, public mom_tidal_forcing::tidal_forcing_sensitivity (type(ocean_grid_type), intent(in) G, type(tidal_forcing_cs), pointer CS, real, intent(out) deta_tidal_deta)
Definition at line 422 of file MOM_tidal_forcing.F90.
Referenced by mom_barotropic::btstep(), mom_legacy_barotropic::legacy_btstep(), mom_legacy_barotropic::legacy_set_dtbt(), and mom_barotropic::set_dtbt().
Member Data Documentation
integer mom_tidal_forcing::id_clock_tides
Definition at line 101 of file MOM_tidal_forcing.F90.
integer, parameter mom_tidal_forcing::max_constituents = 10 private
Definition at line 67 of file MOM_tidal_forcing.F90.
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_tidal_forcing.F90