MOM6: coupler_util Module Reference
coupler_util Module Reference
Public Member Functions
subroutine, public extract_coupler_values (BC_struc, BC_index, BC_element, array_out, is, ie, js, je, conversion)
subroutine, public set_coupler_values (array_in, BC_struc, BC_index, BC_element, is, ie, js, je, conversion)
subroutine, public extract_coupler_values (BC_struc, BC_index, BC_element, array_out, is, ie, js, je, conversion)
subroutine, public set_coupler_values (array_in, BC_struc, BC_index, BC_element, is, ie, js, je, conversion)
subroutine, public extract_coupler_values (BC_struc, BC_index, BC_element, array_out, is, ie, js, je, conversion)
subroutine, public set_coupler_values (array_in, BC_struc, BC_index, BC_element, is, ie, js, je, conversion)
Detailed Description
Definition at line 1 of file coupler_util.F90.
Member Function/Subroutine Documentation
subroutine, public coupler_util::extract_coupler_values (type(coupler_2d_bc_type), intent(in) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, real, dimension(:,:), intent(out) array_out, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 35 of file coupler_util.F90.
References mom_error_handler::mom_error().
Referenced by mom_ocmip2_cfc::ocmip2_cfc_column_physics().
subroutine, public coupler_util::extract_coupler_values (type(coupler_2d_bc_type), intent(in) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, real, dimension(:,:), intent(inout) array_out, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 39 of file coupler_types.F90.
References mom_error_handler::mom_error().
subroutine, public coupler_util::extract_coupler_values (type(coupler_2d_bc_type), intent(in) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, real, dimension(:,:), intent(inout) array_out, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 42 of file coupler_types.F90.
References mom_error_handler::mom_error().
subroutine, public coupler_util::set_coupler_values (real, dimension(:,:), intent(in) array_in, type(coupler_2d_bc_type), intent(inout) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 65 of file coupler_types.F90.
References mom_error_handler::mom_error().
subroutine, public coupler_util::set_coupler_values (real, dimension(:,:), intent(in) array_in, type(coupler_2d_bc_type), intent(inout) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 98 of file coupler_util.F90.
References mom_error_handler::mom_error().
Referenced by advection_test_tracer::advection_test_tracer_surface_state(), dome_tracer::dome_tracer_surface_state(), ideal_age_example::ideal_age_tracer_surface_state(), mom_ocmip2_cfc::ocmip2_cfc_surface_state(), oil_tracer::oil_tracer_surface_state(), and user_tracer_example::user_tracer_surface_state().
subroutine, public coupler_util::set_coupler_values (real, dimension(:,:), intent(in) array_in, type(coupler_2d_bc_type), intent(inout) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 63 of file coupler_types.F90.
References mom_error_handler::mom_error().
The documentation for this module was generated from the following files:
config_src/coupled_driver/coupler_util.F90
config_src/ice_solo_driver/coupler_types.F90