MOM6: mom_coms Module Reference
mom_coms Module Reference
Data Types
interface assignment(=)
type efp_type
interface operator(+)
interface operator(-)
interface reproducing_sum
Public Member Functions
logical function, public query_efp_overflow_error ()
subroutine, public reset_efp_overflow_error ()
type(efp_type) function, public efp_plus (EFP1, EFP2)
type(efp_type) function, public efp_minus (EFP1, EFP2)
real function, public efp_to_real (EFP1)
real function, public efp_real_diff (EFP1, EFP2)
type(efp_type) function, public real_to_efp (val, overflow)
subroutine, public efp_list_sum_across_pes (EFPs, nval, errors)
subroutine, public mom_infra_end
Private Member Functions
real function reproducing_sum_2d (array, isr, ier, jsr, jer, EFP_sum, reproducing, overflow_check, err)
real function reproducing_sum_3d (array, isr, ier, jsr, jer, sums, EFP_sum, err)
integer(kind=8) function,
dimension(ni) real_to_ints (r, prec_error, overflow)
real function ints_to_real (ints)
subroutine increment_ints (int_sum, int2, prec_error)
subroutine increment_ints_faster (int_sum, r, max_mag_term)
subroutine carry_overflow (int_sum, prec_error)
subroutine regularize_ints (int_sum)
subroutine efp_assign (EFP1, EFP2)
Private Attributes
integer(kind=8), parameter prec =2_8**46
real, parameter r_prec =2.0**46
real, parameter i_prec =1.0/(2.0**46)
integer, parameter max_count_prec =2**(63-46)-1
integer, parameter ni =6
real, dimension(ni), parameter pr = (/ r_prec**2, r_prec, 1.0, 1.0/r_prec, 1.0/r_prec**2, 1.0/r_prec**3 /)
real, dimension(ni), parameter i_pr = (/ 1.0/r_prec**2, 1.0/r_prec, 1.0, r_prec, r_prec**2, r_prec**3 /)
logical overflow_error = .false.
logical nan_error = .false.
logical debug = .false.
Detailed Description
Definition at line 1 of file MOM_coms.F90.
Member Function/Subroutine Documentation
subroutine mom_coms::carry_overflow (integer(kind=8), dimension(ni), intent(inout) int_sum, integer(kind=8), intent(in) prec_error) private
Definition at line 480 of file MOM_coms.F90.
Referenced by efp_list_sum_across_pes(), reproducing_sum_2d(), and reproducing_sum_3d().
subroutine mom_coms::efp_assign (type(efp_type), intent(out) EFP1, type(efp_type), intent(in) EFP2) private
Definition at line 563 of file MOM_coms.F90.
subroutine, public mom_coms::efp_list_sum_across_pes (type(efp_type), dimension(:), intent(inout) EFPs, integer, intent(in) nval, logical, dimension(:), intent(out), optional errors)
Definition at line 614 of file MOM_coms.F90.
References carry_overflow(), efp_to_real(), and mom_error_handler::mom_error().
Referenced by mom_spatial_means::global_i_mean(), and mom_spatial_means::global_j_mean().
type(efp_type) function, public mom_coms::efp_minus (type(efp_type), intent(in) EFP1, type(efp_type), intent(in) EFP2)
Definition at line 553 of file MOM_coms.F90.
References mom_coms::operator(-)::efp_minus(), and increment_ints().
type(efp_type) function, public mom_coms::efp_plus (type(efp_type), intent(in) EFP1, type(efp_type), intent(in) EFP2)
Definition at line 544 of file MOM_coms.F90.
References mom_coms::operator(+)::efp_plus(), and increment_ints().
real function, public mom_coms::efp_real_diff (type(efp_type), intent(in) EFP1, type(efp_type), intent(in) EFP2)
Definition at line 582 of file MOM_coms.F90.
References efp_to_real().
real function, public mom_coms::efp_to_real (type(efp_type), intent(inout) EFP1)
Definition at line 574 of file MOM_coms.F90.
References ints_to_real(), and regularize_ints().
Referenced by efp_list_sum_across_pes(), efp_real_diff(), mom_spatial_means::global_i_mean(), mom_spatial_means::global_j_mean(), mom_main(), and mom_sum_output::write_energy().
subroutine mom_coms::increment_ints (integer(kind=8), dimension(ni), intent(inout) int_sum, integer(kind=8), dimension(ni), intent(in) int2, integer(kind=8), intent(in), optional prec_error) private
Definition at line 426 of file MOM_coms.F90.
Referenced by efp_minus(), efp_plus(), reproducing_sum_2d(), and reproducing_sum_3d().
subroutine mom_coms::increment_ints_faster (integer(kind=8), dimension(ni), intent(inout) int_sum, real, intent(in) r, real, intent(inout) max_mag_term) private
Definition at line 455 of file MOM_coms.F90.
Referenced by reproducing_sum_2d(), and reproducing_sum_3d().
real function mom_coms::ints_to_real (integer(kind=8), dimension(ni), intent(in) ints) private
Definition at line 415 of file MOM_coms.F90.
Referenced by efp_to_real(), reproducing_sum_2d(), and reproducing_sum_3d().
subroutine, public mom_coms::mom_infra_end ()
Definition at line 659 of file MOM_coms.F90.
Referenced by mom_main(), and shelf_main().
logical function, public mom_coms::query_efp_overflow_error ()
Definition at line 535 of file MOM_coms.F90.
Referenced by mom_spatial_means::global_i_mean(), and mom_spatial_means::global_j_mean().
type(efp_type) function, public mom_coms::real_to_efp (real, intent(in) val, logical, intent(inout), optional overflow)
Definition at line 593 of file MOM_coms.F90.
References mom_error_handler::mom_error(), and real_to_ints().
Referenced by mom_spatial_means::global_i_mean(), mom_spatial_means::global_j_mean(), mom_main(), and mom_sum_output::write_energy().
integer(kind=8) function, dimension(ni) mom_coms::real_to_ints (real, intent(in) r, integer(kind=8), intent(in), optional prec_error, logical, intent(inout), optional overflow) private
Definition at line 379 of file MOM_coms.F90.
References mom_error_handler::mom_error().
Referenced by real_to_efp(), reproducing_sum_2d(), and reproducing_sum_3d().
subroutine mom_coms::regularize_ints (integer(kind=8), dimension(ni), intent(inout) int_sum) private
Definition at line 498 of file MOM_coms.F90.
Referenced by efp_to_real(), reproducing_sum_2d(), and reproducing_sum_3d().
real function mom_coms::reproducing_sum_2d (real, dimension(:,:), intent(in) array, integer, intent(in), optional isr, integer, intent(in), optional ier, integer, intent(in), optional jsr, integer, intent(in), optional jer, type(efp_type), intent(out), optional EFP_sum, logical, intent(in), optional reproducing, logical, intent(in), optional overflow_check, integer, intent(out), optional err) private
Definition at line 77 of file MOM_coms.F90.
References carry_overflow(), increment_ints(), increment_ints_faster(), ints_to_real(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), real_to_ints(), and regularize_ints().
real function mom_coms::reproducing_sum_3d (real, dimension(:,:,:), intent(in) array, integer, intent(in), optional isr, integer, intent(in), optional ier, integer, intent(in), optional jsr, integer, intent(in), optional jer, real, dimension(:), intent(out), optional sums, type(efp_type), intent(out), optional EFP_sum, integer, intent(out), optional err) private
Definition at line 216 of file MOM_coms.F90.
References carry_overflow(), increment_ints(), increment_ints_faster(), ints_to_real(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), real_to_ints(), and regularize_ints().
subroutine, public mom_coms::reset_efp_overflow_error ()
Definition at line 540 of file MOM_coms.F90.
Referenced by mom_spatial_means::global_i_mean(), and mom_spatial_means::global_j_mean().
Member Data Documentation
logical mom_coms::debug = .false. private
Definition at line 59 of file MOM_coms.F90.
real, dimension(ni), parameter mom_coms::i_pr = (/ 1.0/r_prec**2, 1.0/r_prec, 1.0, r_prec, r_prec**2, r_prec**3 /) private
Definition at line 55 of file MOM_coms.F90.
real, parameter mom_coms::i_prec =1.0/(2.0**46) private
Definition at line 45 of file MOM_coms.F90.
integer, parameter mom_coms::max_count_prec =2**(63-46)-1 private
Definition at line 46 of file MOM_coms.F90.
logical mom_coms::nan_error = .false. private
Definition at line 58 of file MOM_coms.F90.
integer, parameter mom_coms::ni =6 private
Definition at line 51 of file MOM_coms.F90.
logical mom_coms::overflow_error = .false. private
Definition at line 58 of file MOM_coms.F90.
real, dimension(ni), parameter mom_coms::pr = (/ r_prec**2, r_prec, 1.0, 1.0/r_prec, 1.0/r_prec**2, 1.0/r_prec**3 /) private
Definition at line 53 of file MOM_coms.F90.
integer(kind=8), parameter mom_coms::prec =2_8**46 private
Definition at line 43 of file MOM_coms.F90.
real, parameter mom_coms::r_prec =2.0**46 private
Definition at line 44 of file MOM_coms.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_coms.F90