MOM6: mom_sum_output Module Reference
mom_sum_output Module Reference
Data Types
type depth_list
type sum_output_cs
Public Member Functions
subroutine, public mom_sum_output_init (G, param_file, directory, ntrnc, Input_start_time, CS)
subroutine, public write_energy (u, v, h, tv, day, n, G, CS, tracer_CSp)
subroutine, public accumulate_net_input (fluxes, state, dt, G, CS)
Private Member Functions
subroutine mom_sum_output_end (CS)
subroutine depth_list_setup (G, CS)
subroutine create_depth_list (G, CS, max_list_size)
subroutine write_depth_list (G, CS, filename, list_size)
subroutine read_depth_list (G, CS, filename)
Private Attributes
integer, parameter num_fields = 17
Detailed Description
Definition at line 1 of file MOM_sum_output.F90.
Member Function/Subroutine Documentation
subroutine, public mom_sum_output::accumulate_net_input (type(forcing), intent(in) fluxes, type(surface), intent(in) state, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS)
Definition at line 935 of file MOM_sum_output.F90.
References mom_error_handler::mom_error().
Referenced by mom_main(), and ocean_model_mod::update_ocean_model().
subroutine mom_sum_output::create_depth_list (type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS, integer, intent(in) max_list_size) private
Definition at line 1087 of file MOM_sum_output.F90.
Referenced by depth_list_setup().
subroutine mom_sum_output::depth_list_setup (type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS) private
Definition at line 1055 of file MOM_sum_output.F90.
References create_depth_list(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), read_depth_list(), and write_depth_list().
Referenced by mom_sum_output_init().
subroutine mom_sum_output::mom_sum_output_end (type(sum_output_cs), pointer CS) private
Definition at line 269 of file MOM_sum_output.F90.
subroutine, public mom_sum_output::mom_sum_output_init (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) directory, integer, intent(inout), target ntrnc, type(time_type), intent(in) Input_start_time, type(sum_output_cs), pointer CS)
Definition at line 159 of file MOM_sum_output.F90.
References depth_list_setup(), mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_main(), and ocean_model_mod::ocean_model_init().
subroutine mom_sum_output::read_depth_list (type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS, character(len=*), intent(in) filename) private
Definition at line 1311 of file MOM_sum_output.F90.
References mom_error_handler::mom_error().
Referenced by depth_list_setup().
subroutine mom_sum_output::write_depth_list (type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS, character(len=*), intent(in) filename, integer, intent(in) list_size) private
Definition at line 1231 of file MOM_sum_output.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by depth_list_setup().
subroutine, public mom_sum_output::write_energy (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(time_type), intent(inout) day, integer, intent(in) n, type(ocean_grid_type), intent(in) G, type(sum_output_cs), pointer CS, type(tracer_flow_control_cs), optional, pointer tracer_CSp)
Definition at line 285 of file MOM_sum_output.F90.
References mom_tracer_flow_control::call_tracer_stocks(), mom_io::create_file(), mom_coms::efp_to_real(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_coms::real_to_efp(), and mom_io::reopen_file().
Referenced by mom_main(), ocean_model_mod::ocean_model_init(), and ocean_model_mod::update_ocean_model().
Member Data Documentation
integer, parameter mom_sum_output::num_fields = 17 private
Definition at line 83 of file MOM_sum_output.F90.
The documentation for this module was generated from the following file:
src/diagnostics/MOM_sum_output.F90