MOM6: dome_initialization Module Reference
dome_initialization Module Reference
Public Member Functions
subroutine, public dome_initialize_topography (D, G, param_file, max_depth)
subroutine, public dome_initialize_thickness (h, G, param_file)
subroutine, public dome_initialize_sponges (G, tv, PF, CSp)
subroutine, public dome_set_open_bdry_conds (OBC, tv, G, param_file, tr_Reg)
Detailed Description
Definition at line 1 of file DOME_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public dome_initialization::dome_initialize_sponges (type(ocean_grid_type), intent(in) G, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) PF, type(sponge_cs), pointer CSp)
Definition at line 145 of file DOME_initialization.F90.
References mom_sponge::initialize_sponge(), mom_error_handler::mom_error(), and mom_sponge::set_up_sponge_field().
Referenced by mom_initialization::mom_initialize().
subroutine, public dome_initialization::dome_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 97 of file DOME_initialization.F90.
References mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize().
subroutine, public dome_initialization::dome_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Definition at line 49 of file DOME_initialization.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize_topography().
subroutine, public dome_initialization::dome_set_open_bdry_conds (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
Definition at line 249 of file DOME_initialization.F90.
References mom_tracer_registry::add_tracer_obc_values(), and mom_eos::calculate_density_derivs().
Referenced by mom_initialization::mom_initialize().
The documentation for this module was generated from the following file:
src/user/DOME_initialization.F90