MOM6: mom_set_visc Module Reference
mom_set_visc Module Reference
Data Types
type set_visc_cs
Public Member Functions
subroutine, public set_viscous_bbl (u, v, h, tv, visc, G, CS)
subroutine, public set_viscous_ml (u, v, h, tv, fluxes, visc, dt, G, CS)
subroutine, public set_visc_register_restarts (G, param_file, visc, restart_CS)
subroutine, public set_visc_init (Time, G, param_file, diag, visc, CS)
subroutine, public set_visc_end (visc, CS)
Private Member Functions
real function set_v_at_u (v, h, G, i, j, k)
real function set_u_at_v (u, h, G, i, j, k)
Detailed Description
Definition at line 1 of file MOM_set_viscosity.F90.
Member Function/Subroutine Documentation
real function mom_set_visc::set_u_at_v (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, integer, intent(in) i, integer, intent(in) j, integer, intent(in) k) private
Definition at line 800 of file MOM_set_viscosity.F90.
Referenced by set_viscous_bbl(), and set_viscous_ml().
real function mom_set_visc::set_v_at_u (real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, integer, intent(in) i, integer, intent(in) j, integer, intent(in) k) private
Definition at line 779 of file MOM_set_viscosity.F90.
Referenced by set_viscous_bbl(), and set_viscous_ml().
subroutine, public mom_set_visc::set_visc_end (type(vertvisc_type), intent(inout) visc, type(set_visc_cs), pointer CS)
Definition at line 1725 of file MOM_set_viscosity.F90.
subroutine, public mom_set_visc::set_visc_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(vertvisc_type), intent(inout) visc, type(set_visc_cs), pointer CS)
Definition at line 1511 of file MOM_set_viscosity.F90.
References mom_diabatic_driver::adiabatic(), mom_kappa_shear::kappa_shear_is_used(), mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
subroutine, public mom_set_visc::set_visc_register_restarts (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(vertvisc_type), intent(inout) visc, type(mom_restart_cs), pointer restart_CS)
Definition at line 1463 of file MOM_set_viscosity.F90.
References mom_diabatic_driver::adiabatic(), and mom_kappa_shear::kappa_shear_is_used().
Referenced by mom::initialize_mom().
subroutine, public mom_set_visc::set_viscous_bbl (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(vertvisc_type), intent(inout) visc, type(ocean_grid_type), intent(inout) G, type(set_visc_cs), pointer CS)
Definition at line 131 of file MOM_set_viscosity.F90.
References mom_eos::calculate_density_derivs(), mom_error_handler::mom_error(), set_u_at_v(), and set_v_at_u().
Referenced by mom::step_mom(), mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_set_visc::set_viscous_ml (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(inout) visc, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(set_visc_cs), pointer CS)
Definition at line 821 of file MOM_set_viscosity.F90.
References mom_eos::calculate_density_derivs(), mom_error_handler::mom_error(), set_u_at_v(), and set_v_at_u().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_set_viscosity.F90