MOM6: mom_lateral_mixing_coeffs Module Reference
mom_lateral_mixing_coeffs Module Reference
Data Types
interface calc_slope_function
type varmix_cs
Public Member Functions
subroutine, public calc_resoln_function (h, tv, G, CS)
subroutine, public varmix_init (Time, G, param_file, diag, CS)
Private Member Functions
subroutine calc_slope_function_need_e (h, tv, G, CS)
subroutine calc_slope_function_ (h, tv, G, CS, e)
Detailed Description
Definition at line 1 of file MOM_lateral_mixing_coeffs.F90.
Member Function/Subroutine Documentation
subroutine, public mom_lateral_mixing_coeffs::calc_resoln_function (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(inout) G, type(varmix_cs), pointer CS)
Definition at line 98 of file MOM_lateral_mixing_coeffs.F90.
References mom_error_handler::mom_error(), mom_diag_mediator::query_averaging_enabled(), and mom_wave_speed::wave_speed().
Referenced by mom::step_mom().
subroutine mom_lateral_mixing_coeffs::calc_slope_function_ (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(inout) G, type(varmix_cs), pointer CS, real, dimension(nimem_,njmem_,nk_interface_), intent(in) e) private
Definition at line 245 of file MOM_lateral_mixing_coeffs.F90.
References mom_error_handler::mom_error(), and mom_diag_mediator::query_averaging_enabled().
subroutine mom_lateral_mixing_coeffs::calc_slope_function_need_e (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(inout) G, type(varmix_cs), pointer CS) private
Definition at line 228 of file MOM_lateral_mixing_coeffs.F90.
References mom_lateral_mixing_coeffs::calc_slope_function::calc_slope_function_().
subroutine, public mom_lateral_mixing_coeffs::varmix_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(varmix_cs), pointer CS)
Definition at line 377 of file MOM_lateral_mixing_coeffs.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), mom_diag_mediator::register_diag_field(), and mom_wave_speed::wave_speed_init().
Referenced by mom::initialize_mom().
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90