MOM6: mom_initialization Module Reference
mom_initialization Module Reference
Data Types
type mom_initialization_struct
Public Member Functions
subroutine, public mom_initialize (u, v, h, tv, Time, G, PF, dirs, restart_CS, CS, Time_in)
subroutine, public mom_initialize_rotation (f, G, PF)
subroutine, public mom_initialize_topography (D, max_depth, G, PF)
Private Member Functions
subroutine set_coord_from_gprime (Rlay, g_prime, G, param_file)
subroutine set_coord_from_layer_density (Rlay, g_prime, G, param_file)
subroutine set_coord_from_ts_ref (Rlay, g_prime, G, param_file, eqn_of_state, P_Ref)
subroutine set_coord_from_ts_profile (Rlay, g_prime, G, param_file, eqn_of_state, P_Ref)
subroutine set_coord_from_ts_range (Rlay, g_prime, G, param_file, eqn_of_state, P_Ref)
subroutine set_coord_from_file (Rlay, g_prime, G, param_file)
subroutine set_coord_linear (Rlay, g_prime, G, param_file)
real function diagnosemaximumdepth (D, G)
subroutine initialize_topography_from_file (D, G, param_file)
subroutine initialize_topography_named (D, G, param_file, topog_config, max_depth)
subroutine limit_topography (D, G, param_file, max_depth)
subroutine set_rotation_planetary (f, G, param_file)
subroutine set_rotation_beta_plane (f, G, param_file)
subroutine initialize_thickness_from_file (h, G, param_file, file_has_thickness)
subroutine adjustetatofitbathymetry (G, eta, h)
Adjust interface heights to fit the bathymetry and diagnose layer thickness. If the bottom most interface is below the topography then the bottom-most layers are contracted to GAngstrom_z. If the bottom most interface is above the topography then the entire column is dilated (expanded) to fill the void.
subroutine initialize_thickness_uniform (h, G, param_file)
subroutine initialize_thickness_search
subroutine convert_thickness (h, G, param_file, tv)
subroutine depress_surface (h, G, param_file, tv)
subroutine initialize_velocity_from_file (u, v, G, param_file)
subroutine initialize_velocity_zero (u, v, G, param_file)
subroutine initialize_velocity_uniform (u, v, G, param_file)
subroutine initialize_velocity_circular (u, v, G, param_file)
subroutine initialize_temp_salt_from_file (T, S, G, param_file)
subroutine initialize_temp_salt_from_profile (T, S, G, param_file)
subroutine initialize_temp_salt_fit (T, S, G, param_file, eqn_of_state, P_Ref)
subroutine initialize_temp_salt_linear (T, S, G, param_file)
subroutine initialize_sponges_file (G, use_temperature, tv, param_file, CSp)
subroutine set_open_bdry_conds (OBC, tv, G, param_file, tracer_Reg)
subroutine set_flather_bdry_conds (OBC, tv, h, G, PF, tracer_Reg)
subroutine reset_face_lengths_named (G, param_file, name)
subroutine reset_face_lengths_file (G, param_file)
subroutine reset_face_lengths_list (G, param_file)
subroutine read_face_length_list (iounit, filename, num_lines, lines)
subroutine set_velocity_depth_max (G)
subroutine compute_global_grid_integrals (G)
subroutine set_velocity_depth_min (G)
subroutine write_ocean_geometry_file (G, param_file, directory)
subroutine write_vertgrid_file (G, param_file, directory)
subroutine mom_temp_salt_initialize_from_z (h, tv, G, PF, dirs)
Detailed Description
Definition at line 1 of file MOM_initialization.F90.
Member Function/Subroutine Documentation
subroutine mom_initialization::adjustetatofitbathymetry (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) eta, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h) private
Adjust interface heights to fit the bathymetry and diagnose layer thickness. If the bottom most interface is below the topography then the bottom-most layers are contracted to GAngstrom_z. If the bottom most interface is above the topography then the entire column is dilated (expanded) to fill the void.
Remarks
{There is a (hard-wired) "tolerance" parameter such that the criteria for adjustment must equal or exceed 10cm.}
Parameters
[in] G Grid type
[in,out] eta Interface heights
[out] h Layer thicknesses
Definition at line 1467 of file MOM_initialization.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by initialize_thickness_from_file(), and mom_temp_salt_initialize_from_z().
subroutine mom_initialization::compute_global_grid_integrals (type(ocean_grid_type), intent(inout) G) private
Definition at line 3234 of file MOM_initialization.F90.
Referenced by mom_initialize().
subroutine mom_initialization::convert_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(thermo_var_ptrs), intent(in) tv) private
Definition at line 1584 of file MOM_initialization.F90.
References mom_eos::int_specific_vol_dp(), and mom_error_handler::mom_error().
Referenced by mom_initialize().
subroutine mom_initialization::depress_surface (real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(thermo_var_ptrs), intent(in) tv) private
Definition at line 1654 of file MOM_initialization.F90.
References mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
real function mom_initialization::diagnosemaximumdepth (real, dimension(nimem_,njmem_), intent(in) D, type(ocean_grid_type), intent(in) G) private
Definition at line 1089 of file MOM_initialization.F90.
Referenced by mom_initialize_topography().
subroutine mom_initialization::initialize_sponges_file (type(ocean_grid_type), intent(in) G, logical, intent(in) use_temperature, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CSp) private
Definition at line 2108 of file MOM_initialization.F90.
References mom_sponge::initialize_sponge(), mom_error_handler::mom_error(), mom_sponge::set_up_sponge_field(), mom_sponge::set_up_sponge_ml_density(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_temp_salt_fit (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_Ref) private
Definition at line 1988 of file MOM_initialization.F90.
References mom_eos::calculate_density_derivs(), mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_temp_salt_from_file (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1888 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_temp_salt_from_profile (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1942 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_temp_salt_linear (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 2054 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_thickness_from_file (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in) file_has_thickness) private
Definition at line 1379 of file MOM_initialization.F90.
References adjustetatofitbathymetry(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_thickness_search () private
Definition at line 1578 of file MOM_initialization.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_thickness_uniform (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1526 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and mom_error_handler::mom_error().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_topography_from_file (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1106 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize_topography().
subroutine mom_initialization::initialize_topography_named (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) topog_config, real, intent(in) max_depth) private
Definition at line 1144 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by mom_initialize_topography().
subroutine mom_initialization::initialize_velocity_circular (real, dimension(nimemb_,njmem_, nkmem_), intent(out) u, real, dimension(nimem_,njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1835 of file MOM_initialization.F90.
References my_psi().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_velocity_from_file (real, dimension(nimemb_,njmem_, nkmem_), intent(out) u, real, dimension(nimem_,njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1733 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::initialize_velocity_uniform (real, dimension(nimemb_,njmem_, nkmem_), intent(out) u, real, dimension(nimem_,njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1800 of file MOM_initialization.F90.
Referenced by mom_initialize().
subroutine mom_initialization::initialize_velocity_zero (real, dimension(nimemb_,njmem_, nkmem_), intent(out) u, real, dimension(nimem_,njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1770 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::limit_topography (real, dimension(nimem_,njmem_), intent(inout) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth) private
Definition at line 1256 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize_topography().
subroutine, public mom_initialization::mom_initialize (real, dimension(nimemb_,njmem_,nkmem_), intent(out) u, real, dimension(nimem_,njmemb_,nkmem_), intent(out) v, real, dimension(nimem_,njmem_,nkmem_), intent(out) h, type(thermo_var_ptrs), intent(inout) tv, type(time_type), intent(inout) Time, type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) PF, type(directories), intent(in) dirs, type(mom_restart_cs), pointer restart_CS, type(mom_initialization_struct), intent(inout) CS, type(time_type), intent(in), optional Time_in)
Definition at line 161 of file MOM_initialization.F90.
References adjustment_initialization::adjustment_initialize_temperature_salinity(), adjustment_initialization::adjustment_initialize_thickness(), benchmark_initialization::benchmark_init_temperature_salinity(), benchmark_initialization::benchmark_initialize_thickness(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), circle_obcs_initialization::circle_obcs_initialize_thickness(), compute_global_grid_integrals(), convert_thickness(), depress_surface(), dome2d_initialization::dome2d_initialize_temperature_salinity(), dome2d_initialization::dome2d_initialize_thickness(), dome_initialization::dome_initialize_sponges(), dome_initialization::dome_initialize_thickness(), dome_initialization::dome_set_open_bdry_conds(), external_gwave_initialization::external_gwave_initialize_thickness(), mom_grid_initialize::initialize_masks(), initialize_sponges_file(), initialize_temp_salt_fit(), initialize_temp_salt_from_file(), initialize_temp_salt_from_profile(), initialize_temp_salt_linear(), initialize_thickness_from_file(), initialize_thickness_search(), initialize_thickness_uniform(), initialize_velocity_circular(), initialize_velocity_from_file(), initialize_velocity_uniform(), initialize_velocity_zero(), lock_exchange_initialization::lock_exchange_initialize_thickness(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_initialize_rotation(), mom_initialize_topography(), mom_error_handler::mom_mesg(), mom_temp_salt_initialize_from_z(), phillips_initialization::phillips_initialize_sponges(), phillips_initialization::phillips_initialize_thickness(), phillips_initialization::phillips_initialize_velocity(), reset_face_lengths_file(), reset_face_lengths_list(), reset_face_lengths_named(), mom_restart::restore_state(), seamount_initialization::seamount_initialize_temperature_salinity(), seamount_initialization::seamount_initialize_thickness(), set_coord_from_file(), set_coord_from_gprime(), set_coord_from_layer_density(), set_coord_from_ts_profile(), set_coord_from_ts_range(), set_coord_from_ts_ref(), set_coord_linear(), set_flather_bdry_conds(), mom_grid_initialize::set_grid_metrics(), set_open_bdry_conds(), set_velocity_depth_max(), set_velocity_depth_min(), mom_verticalgrid::setverticalgridaxes(), mom_io::slasher(), sloshing_initialization::sloshing_initialize_temperature_salinity(), sloshing_initialization::sloshing_initialize_thickness(), user_initialization::user_init_temperature_salinity(), user_initialization::user_initialize_sponges(), user_initialization::user_initialize_thickness(), user_initialization::user_initialize_velocity(), user_initialization::user_set_coord(), user_initialization::user_set_open_bdry_conds(), write_ocean_geometry_file(), and write_vertgrid_file().
Referenced by mom::initialize_mom().
subroutine, public mom_initialization::mom_initialize_rotation (real, dimension(g%isdb:g%iedb,g%jsdb:g%jedb), intent(out) f, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF)
Definition at line 987 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), set_rotation_beta_plane(), and set_rotation_planetary().
Referenced by mom_initialize().
subroutine, public mom_initialization::mom_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, real, intent(out) max_depth, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF)
Definition at line 1022 of file MOM_initialization.F90.
References benchmark_initialization::benchmark_initialize_topography(), diagnosemaximumdepth(), dome2d_initialization::dome2d_initialize_topography(), dome_initialization::dome_initialize_topography(), initialize_topography_from_file(), initialize_topography_named(), limit_topography(), mom_error_handler::mom_error(), seamount_initialization::seamount_initialize_topography(), sloshing_initialization::sloshing_initialize_topography(), and user_initialization::user_initialize_topography().
Referenced by mom_initialize().
subroutine mom_initialization::mom_temp_salt_initialize_from_z (real, dimension(nimem_,njmem_,nkmem_), intent(out) h, type(thermo_var_ptrs), intent(inout) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF, type(directories), intent(in) dirs) private
Definition at line 3436 of file MOM_initialization.F90.
References adjustetatofitbathymetry(), mom_ale::ale_initregridding(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), midas_vertmap::determine_temperature(), mom_remapping::dzfromh1h2(), midas_vertmap::fill_miss_2d(), midas_vertmap::find_interfaces(), mom_remapping::initialize_remapping(), mom_error_handler::is_root_pe(), mom_file_parser::log_version(), midas_vertmap::meshgrid(), mom_error_handler::mom_error(), mystats(), mom_remapping::remapdisableboundaryextrapolation(), mom_remapping::remapping_core(), mom_io::slasher(), and midas_vertmap::tracer_z_init().
Referenced by mom_initialize().
subroutine mom_initialization::read_face_length_list (integer, intent(in) iounit, character(len=*), intent(in) filename, integer, intent(out) num_lines, character(len=120), dimension(:), pointer lines) private
Definition at line 3163 of file MOM_initialization.F90.
References mom_error_handler::mom_error(), and mom_string_functions::uppercase().
Referenced by reset_face_lengths_list().
subroutine mom_initialization::reset_face_lengths_file (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 2890 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::reset_face_lengths_list (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 2958 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), read_face_length_list(), mom_io::slasher(), and mom_string_functions::uppercase().
Referenced by mom_initialize().
subroutine mom_initialization::reset_face_lengths_named (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) name) private
Definition at line 2764 of file MOM_initialization.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_file (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 886 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), mom_io::read_axis_data(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_gprime (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 605 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_layer_density (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 643 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_ts_profile (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_Ref) private
Definition at line 745 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_ts_range (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_Ref) private
Definition at line 798 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_from_ts_ref (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_Ref) private
Definition at line 689 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::set_coord_linear (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 937 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize().
subroutine mom_initialization::set_flather_bdry_conds (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(inout) tv, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) PF, type(tracer_registry_type), pointer tracer_Reg) private
Definition at line 2414 of file MOM_initialization.F90.
References mom_tracer_registry::add_tracer_obc_values(), and mom_io::slasher().
Referenced by mom_initialize().
subroutine mom_initialization::set_open_bdry_conds (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tracer_Reg) private
Definition at line 2242 of file MOM_initialization.F90.
References mom_tracer_registry::add_tracer_obc_values(), and mom_eos::calculate_density_derivs().
Referenced by mom_initialize().
subroutine mom_initialization::set_rotation_beta_plane (real, dimension(g%isdb:g%iedb,g%jsdb:g%jedb), intent(out) f, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1333 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and mom_error_handler::mom_error().
Referenced by mom_initialize_rotation().
subroutine mom_initialization::set_rotation_planetary (real, dimension(g%isdb:g%iedb,g%jsdb:g%jedb), intent(out) f, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file) private
Definition at line 1304 of file MOM_initialization.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by mom_initialize_rotation().
subroutine mom_initialization::set_velocity_depth_max (type(ocean_grid_type), intent(inout) G) private
Definition at line 3216 of file MOM_initialization.F90.
Referenced by mom_initialize().
subroutine mom_initialization::set_velocity_depth_min (type(ocean_grid_type), intent(inout) G) private
Definition at line 3249 of file MOM_initialization.F90.
Referenced by mom_initialize().
subroutine mom_initialization::write_ocean_geometry_file (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) directory) private
Definition at line 3267 of file MOM_initialization.F90.
References mom_io::create_file().
Referenced by mom_initialize().
subroutine mom_initialization::write_vertgrid_file (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) directory) private
Definition at line 3406 of file MOM_initialization.F90.
References mom_io::create_file().
Referenced by mom_initialize().
The documentation for this module was generated from the following file:
src/initialization/MOM_initialization.F90