MOM6: mom Module Reference
mom Module Reference
Data Types
type mom_control_struct
Public Member Functions
subroutine, public step_mom (fluxes, state, Time_start, time_interval, CS)
subroutine, public initialize_mom (Time, param_file, dirs, CS, Time_in)
subroutine register_diags (Time, G, CS, ADp)
subroutine, public calculate_surface_state (state, u, v, h, ssh, G, CS, p_atm)
subroutine, public mom_end (CS)
Public Attributes
integer id_clock_ocean
Private Member Functions
subroutine unittests
subroutine mom_timing_init (CS)
subroutine write_static_fields (G, diag)
subroutine set_restart_fields (G, param_file, CS)
subroutine smooth_ssh (ssh, G, smooth_passes)
Private Attributes
integer id_clock_dynamics
integer id_clock_thermo
integer id_clock_tracer
integer id_clock_diabatic
integer id_clock_continuity
integer id_clock_thick_diff
integer id_clock_ml_restrat
integer id_clock_diagnostics
integer id_clock_z_diag
integer id_clock_init
integer id_clock_mom_init
integer id_clock_pass
integer id_clock_pass_init
integer id_clock_ale
integer id_clock_other
Detailed Description
Definition at line 1 of file MOM.F90.
Member Function/Subroutine Documentation
subroutine, public mom::calculate_surface_state (type(surface), intent(inout) state, real, dimension(nimemb_,njmem_,nkmem_), intent(in), target u, real, dimension(nimem_,njmemb_,nkmem_), intent(in), target v, real, dimension(nimem_,njmem_,nkmem_), intent(in), target h, real, dimension(nimem_,njmem_), intent(inout), target ssh, type(ocean_grid_type), intent(inout) G, type(mom_control_struct), intent(in) CS, real, dimension(:,:), optional, pointer p_atm)
Definition at line 2290 of file MOM.F90.
References mom_tracer_flow_control::call_tracer_surface_state(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and smooth_ssh().
Referenced by mom_main(), ocean_model_mod::ocean_model_init_sfc(), and step_mom().
subroutine, public mom::initialize_mom (type(time_type), intent(inout), target Time, type(param_file_type), intent(out) param_file, type(directories), intent(out) dirs, type(mom_control_struct), pointer CS, type(time_type), intent(in), optional Time_in)
Definition at line 1359 of file MOM.F90.
References mom_tracer_registry::add_tracer_diagnostics(), mom_diabatic_driver::adiabatic_driver_init(), mom_ale::adjustgridforintegrity(), mom_ale::ale_main(), mom_ale::ale_updateverticalgridtype(), mom_ale::ale_writecoordinatefile(), mom_tracer_flow_control::call_tracer_register(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::calltree_waypoint(), mom_diabatic_driver::diabatic_driver_init(), mom_diag_mediator::diag_masks_set(), mom_diag_mediator::diag_mediator_init(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom_obsolete_params::find_obsolete_params(), mom_get_input::get_mom_input(), mom_sponge::init_sponge_diags(), mom_ale::initialize_ale(), mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2(), mom_file_parser::log_version(), mom_meke::meke_alloc_register_restart(), mom_meke::meke_init(), mom_mixed_layer_restrat::mixedlayer_restrat_init(), mom_checksums::mom_checksums_init(), mom_diag_to_z::mom_diag_to_z_init(), mom_diagnostics::mom_diagnostics_init(), mom_domains::mom_domains_init(), mom_error_handler::mom_error(), mom_grid::mom_grid_init(), mom_initialization::mom_initialize(), mom_io::mom_io_init(), mom_error_handler::mom_set_verbosity(), mom_timing_init(), register_diags(), mom_dynamics_legacy_split::register_restarts_dyn_legacy_split(), mom_dynamics_split_rk2::register_restarts_dyn_split_rk2(), mom_dynamics_unsplit::register_restarts_dyn_unsplit(), mom_dynamics_unsplit_rk2::register_restarts_dyn_unsplit_rk2(), mom_tracer_registry::register_tracer(), mom_diag_to_z::register_z_tracer(), mom_restart::restart_init(), mom_restart::save_restart(), mom_eos::select_eqn_of_state(), mom_diag_mediator::set_axes_info(), set_restart_fields(), mom_set_visc::set_visc_register_restarts(), mom_thickness_diffuse::thickness_diffuse_init(), mom_tracer_advect::tracer_advect_init(), mom_tracer_flow_control::tracer_flow_control_init(), mom_tracer_hor_diff::tracer_hor_diff_init(), mom_tracer_registry::tracer_registry_init(), unittests(), mom_lateral_mixing_coeffs::varmix_init(), and write_static_fields().
Referenced by mom_main(), and ocean_model_mod::ocean_model_init().
subroutine, public mom::mom_end (type(mom_control_struct), pointer CS)
Definition at line 2598 of file MOM.F90.
References mom_ale::end_ale(), mom_dynamics_legacy_split::end_dyn_legacy_split(), mom_dynamics_split_rk2::end_dyn_split_rk2(), mom_dynamics_unsplit::end_dyn_unsplit(), mom_dynamics_unsplit_rk2::end_dyn_unsplit_rk2(), mom_tracer_advect::tracer_advect_end(), mom_tracer_hor_diff::tracer_hor_diff_end(), and mom_tracer_registry::tracer_registry_end().
Referenced by mom_main(), and ocean_model_mod::ocean_model_end().
subroutine mom::mom_timing_init (type(mom_control_struct), intent(in) CS) private
Definition at line 2120 of file MOM.F90.
Referenced by initialize_mom().
subroutine mom::register_diags (type(time_type), intent(in) Time, type(ocean_grid_type), intent(inout) G, type(mom_control_struct), pointer CS, type(accel_diag_ptrs), intent(inout) ADp)
Definition at line 1971 of file MOM.F90.
References mom_grid::get_flux_units(), mom_grid::get_thickness_units(), mom_grid::get_tr_flux_units(), mom_diag_mediator::register_diag_field(), and mom_diag_mediator::register_scalar_field().
Referenced by initialize_mom().
subroutine mom::set_restart_fields (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(mom_control_struct), intent(in) CS) private
Definition at line 2233 of file MOM.F90.
References mom_grid::get_flux_units(), and mom_grid::get_thickness_units().
Referenced by initialize_mom().
subroutine mom::smooth_ssh (real, dimension(nimem_,njmem_), intent(inout) ssh, type(ocean_grid_type), intent(inout) G, real, intent(in) smooth_passes) private
Definition at line 2536 of file MOM.F90.
Referenced by calculate_surface_state().
subroutine, public mom::step_mom (type(forcing), intent(inout) fluxes, type(surface), intent(inout) state, type(time_type), intent(in) Time_start, real, intent(in) time_interval, type(mom_control_struct), pointer CS)
Definition at line 591 of file MOM.F90.
References mom_diabatic_driver::adiabatic(), mom_dynamics_legacy_split::adjustments_dyn_legacy_split(), mom_tracer_advect::advect_tracer(), mom_ale::ale_main(), mom_lateral_mixing_coeffs::calc_resoln_function(), mom_diagnostics::calculate_diagnostic_fields(), calculate_surface_state(), mom_diag_to_z::calculate_z_diag_fields(), mom_diag_to_z::calculate_z_transport(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::calltree_showquery(), mom_error_handler::calltree_waypoint(), mom_diabatic_driver::diabatic(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom_mixed_layer_restrat::mixedlayer_restrat(), mom_checksum_packages::mom_thermo_chksum(), mom_set_visc::set_viscous_bbl(), mom_meke::step_forward_meke(), mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2(), mom_thickness_diffuse::thickness_diffuse(), and mom_tracer_hor_diff::tracer_hordiff().
Referenced by mom_main(), and ocean_model_mod::update_ocean_model().
subroutine mom::unittests () private
Definition at line 1952 of file MOM.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_remapping::remappingunittests(), and mom_string_functions::stringfunctionsunittests().
Referenced by initialize_mom().
subroutine mom::write_static_fields (type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(in), target diag) private
Definition at line 2149 of file MOM.F90.
References mom_diag_mediator::register_static_field().
Referenced by initialize_mom().
Member Data Documentation
integer mom::id_clock_ale private
Definition at line 586 of file MOM.F90.
integer mom::id_clock_continuity private
Definition at line 581 of file MOM.F90.
integer mom::id_clock_diabatic private
Definition at line 580 of file MOM.F90.
integer mom::id_clock_diagnostics private
Definition at line 583 of file MOM.F90.
integer mom::id_clock_dynamics private
Definition at line 579 of file MOM.F90.
integer mom::id_clock_init private
Definition at line 584 of file MOM.F90.
integer mom::id_clock_ml_restrat private
Definition at line 582 of file MOM.F90.
integer mom::id_clock_mom_init private
Definition at line 584 of file MOM.F90.
integer mom::id_clock_ocean
Definition at line 579 of file MOM.F90.
integer mom::id_clock_other private
Definition at line 587 of file MOM.F90.
integer mom::id_clock_pass private
Definition at line 585 of file MOM.F90.
integer mom::id_clock_pass_init private
Definition at line 585 of file MOM.F90.
integer mom::id_clock_thermo private
Definition at line 579 of file MOM.F90.
integer mom::id_clock_thick_diff private
Definition at line 582 of file MOM.F90.
integer mom::id_clock_tracer private
Definition at line 580 of file MOM.F90.
integer mom::id_clock_z_diag private
Definition at line 583 of file MOM.F90.
The documentation for this module was generated from the following file:
src/core/MOM.F90