MOM6: mom_sponge Module Reference
mom_sponge Module Reference
Data Types
type p2d
type p3d
type sponge_cs
Public Member Functions
subroutine, public initialize_sponge (Iresttime, int_height, G, param_file, CS, Iresttime_i_mean, int_height_i_mean)
subroutine, public init_sponge_diags (Time, G, diag, CS)
subroutine, public set_up_sponge_field (sp_val, f_ptr, nlay, CS, sp_val_i_mean)
subroutine, public set_up_sponge_ml_density (sp_val, CS, sp_val_i_mean)
subroutine, public apply_sponge (h, dt, G, ea, eb, CS, Rcv_ml)
subroutine, public sponge_end (CS)
Detailed Description
Definition at line 1 of file MOM_sponge.F90.
Member Function/Subroutine Documentation
subroutine, public mom_sponge::apply_sponge (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, real, dimension(nimem_,njmem_,nkmem_), intent(out) ea, real, dimension(nimem_,njmem_,nkmem_), intent(out) eb, type(sponge_cs), pointer CS, real, dimension(nimem_,njmem_), intent(inout), optional Rcv_ml)
Definition at line 376 of file MOM_sponge.F90.
References mom_spatial_means::global_i_mean(), mom_error_handler::mom_error(), and mom_diag_mediator::query_averaging_enabled().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_sponge::init_sponge_diags (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(inout), target diag, type(sponge_cs), pointer CS)
Definition at line 245 of file MOM_sponge.F90.
References mom_diag_mediator::register_diag_field().
Referenced by mom::initialize_mom().
subroutine, public mom_sponge::initialize_sponge (real, dimension(nimem_,njmem_), intent(in) Iresttime, real, dimension(nimem_,njmem_,nk_interface_), intent(in) int_height, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CS, real, dimension(njmem_), intent(in), optional Iresttime_i_mean, real, dimension(njmem_,nk_interface_), intent(in), optional int_height_i_mean)
Definition at line 139 of file MOM_sponge.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by dome_initialization::dome_initialize_sponges(), mom_initialization::initialize_sponges_file(), and phillips_initialization::phillips_initialize_sponges().
subroutine, public mom_sponge::set_up_sponge_field (real, dimension(nimem_,njmem_,nkmem_), intent(in) sp_val, real, dimension(nimem_,njmem_,nkmem_), intent(in), target f_ptr, integer, intent(in) nlay, type(sponge_cs), pointer CS, real, dimension(njmem_,nkmem_), intent(in), optional sp_val_i_mean)
Definition at line 269 of file MOM_sponge.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by dome_initialization::dome_initialize_sponges(), dome_tracer::initialize_dome_tracer(), mom_initialization::initialize_sponges_file(), and user_tracer_example::user_initialize_tracer().
subroutine, public mom_sponge::set_up_sponge_ml_density (real, dimension(nimem_,njmem_), intent(in) sp_val, type(sponge_cs), pointer CS, real, dimension(njmem_), intent(in), optional sp_val_i_mean)
Definition at line 336 of file MOM_sponge.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialization::initialize_sponges_file().
subroutine, public mom_sponge::sponge_end (type(sponge_cs), pointer CS)
Definition at line 640 of file MOM_sponge.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_sponge.F90