MOM6: mom_pressureforce_mont Module Reference
mom_pressureforce_mont Module Reference
Data Types
type pressureforce_mont_cs
Public Member Functions
subroutine, public pressureforce_mont_nonbouss (h, tv, PFu, PFv, G, CS, p_atm, pbce, eta)
subroutine, public pressureforce_mont_bouss (h, tv, PFu, PFv, G, CS, p_atm, pbce, eta)
subroutine, public set_pbce_bouss (e, tv, G, g_Earth, Rho0, GFS_scale, pbce, rho_star)
subroutine, public set_pbce_nonbouss (p, tv, G, g_Earth, GFS_scale, pbce, alpha_star)
subroutine, public pressureforce_mont_init (Time, G, param_file, diag, CS, tides_CSp)
subroutine, public pressureforce_mont_end (CS)
Detailed Description
Definition at line 1 of file MOM_PressureForce_Montgomery.F90.
Member Function/Subroutine Documentation
subroutine, public mom_pressureforce_mont::pressureforce_mont_bouss (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_mont_cs), pointer CS, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 371 of file MOM_PressureForce_Montgomery.F90.
References mom_tidal_forcing::calc_tidal_forcing(), mom_error_handler::mom_error(), mom_eos::query_compressible(), and set_pbce_bouss().
Referenced by mom_pressureforce::pressureforce().
subroutine, public mom_pressureforce_mont::pressureforce_mont_end (type(pressureforce_mont_cs), pointer CS)
Definition at line 909 of file MOM_PressureForce_Montgomery.F90.
subroutine, public mom_pressureforce_mont::pressureforce_mont_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(pressureforce_mont_cs), pointer CS, type(tidal_forcing_cs), optional, pointer tides_CSp)
Definition at line 837 of file MOM_PressureForce_Montgomery.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_pressureforce::pressureforce_init().
subroutine, public mom_pressureforce_mont::pressureforce_mont_nonbouss (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_mont_cs), pointer CS, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 91 of file MOM_PressureForce_Montgomery.F90.
References mom_tidal_forcing::calc_tidal_forcing(), mom_eos::int_specific_vol_dp(), mom_error_handler::mom_error(), mom_eos::query_compressible(), and set_pbce_nonbouss().
Referenced by mom_pressureforce::pressureforce().
subroutine, public mom_pressureforce_mont::set_pbce_bouss (real, dimension(nimem_,njmem_,nk_interface_), intent(in) e, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, real, intent(in) g_Earth, real, intent(in) Rho0, real, intent(in) GFS_scale, real, dimension(nimem_,njmem_,nkmem_), intent(out) pbce, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional rho_star)
Definition at line 613 of file MOM_PressureForce_Montgomery.F90.
References mom_eos::calculate_density_derivs().
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss(), and pressureforce_mont_bouss().
subroutine, public mom_pressureforce_mont::set_pbce_nonbouss (real, dimension(nimem_,njmem_,nk_interface_), intent(in) p, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, real, intent(in) g_Earth, real, intent(in) GFS_scale, real, dimension(nimem_,njmem_,nkmem_), intent(out) pbce, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional alpha_star)
Definition at line 721 of file MOM_PressureForce_Montgomery.F90.
References mom_eos::calculate_density_derivs().
Referenced by mom_pressureforce_afv::pressureforce_afv_nonbouss(), and pressureforce_mont_nonbouss().
The documentation for this module was generated from the following file:
src/core/MOM_PressureForce_Montgomery.F90