MOM6: user_revise_forcing Module Reference
user_revise_forcing Module Reference
Data Types
type user_revise_forcing_cs
Public Member Functions
subroutine, public user_alter_forcing (state, fluxes, day, G, CS)
subroutine, public user_revise_forcing_init (param_file, CS)
Detailed Description
Definition at line 1 of file user_revise_forcing.F90.
Member Function/Subroutine Documentation
subroutine, public user_revise_forcing::user_alter_forcing (type(surface), intent(in) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(in) G, type(user_revise_forcing_cs), pointer CS)
Definition at line 51 of file user_revise_forcing.F90.
Referenced by mom_surface_forcing::convert_iob_to_fluxes(), and mom_surface_forcing::set_forcing().
subroutine, public user_revise_forcing::user_revise_forcing_init (type(param_file_type), intent(in) param_file, type(user_revise_forcing_cs), pointer CS)
Definition at line 70 of file user_revise_forcing.F90.
References mom_file_parser::log_version().
Referenced by mom_surface_forcing::surface_forcing_init().
The documentation for this module was generated from the following file:
src/user/user_revise_forcing.F90