MOM6: mom_eos Module Reference
mom_eos Module Reference
Data Types
interface calculate_density
interface calculate_tfreeze
type eos_type
Public Member Functions
subroutine, public calculate_density_derivs (T, S, pressure, drho_dT, drho_dS, start, npts, EOS)
subroutine, public calculate_compress (T, S, pressure, rho, drho_dp, start, npts, EOS)
subroutine, public calculate_2_densities (T, S, pressure1, pressure2, rho1, rho2, start, npts, EOS)
subroutine, public int_specific_vol_dp (T, S, p_t, p_b, alpha_ref, G, EOS, dza, intp_dza, intx_dza, inty_dza, halo_size)
subroutine, public int_density_dz (T, S, z_t, z_b, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
logical function, public query_compressible (EOS)
subroutine, public select_eqn_of_state (param_file, EOS)
subroutine, public deselect_eqn_of_state (EOS)
subroutine, public int_density_dz_generic_plm (T_t, T_b, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa, useMassWghtInterp)
subroutine, public int_density_dz_generic_ppm (T, T_t, T_b, S, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine, public int_density_dz_generic_plm_analytic (T_t, T_b, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
Public Attributes
integer, parameter eos_linear = 1
Private Member Functions
subroutine calculate_density_scalar (T, S, pressure, rho, EOS)
subroutine calculate_density_array (T, S, pressure, rho, start, npts, EOS)
subroutine calculate_tfreeze_scalar (S, pressure, T_fr, EOS)
subroutine calculate_tfreeze_array (S, pressure, T_fr, start, npts, EOS)
subroutine int_density_dz_generic (T, S, z_t, z_b, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine int_density_dz_generic_cell (T_t_arg, T_b_arg, S_t_arg, S_b_arg, z_t_arg, z_b_arg, depth, rho_ref, rho_0, G_e, G, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine compute_integral_bilinear (x, y, f, integral)
subroutine compute_integral_quadratic (x, y, f, integral)
subroutine evaluate_shape_bilinear (xi, eta, phi, dphidxi, dphideta)
subroutine evaluate_shape_quadratic (xi, eta, phi, dphidxi, dphideta)
subroutine int_spec_vol_dp_generic (T, S, p_t, p_b, alpha_ref, G, EOS, dza, intp_dza, intx_dza, inty_dza, halo_size)
Private Attributes
integer, parameter eos_unesco = 2
integer, parameter eos_wright = 3
character *(10), parameter eos_linear_string = "LINEAR"
character *(10), parameter eos_unesco_string = "UNESCO"
character *(10), parameter eos_wright_string = "WRIGHT"
character *(10), parameter eos_default = EOS_WRIGHT_STRING
integer, parameter tfreeze_linear = 1
integer, parameter tfreeze_millero = 2
character *(10), parameter tfreeze_linear_string = "LINEAR"
character *(10), parameter tfreeze_millero_string = "MILLERO_78"
character *(10), parameter tfreeze_default = TFREEZE_LINEAR_STRING
Detailed Description
Definition at line 1 of file MOM_EOS.F90.
Member Function/Subroutine Documentation
subroutine, public mom_eos::calculate_2_densities (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, intent(in) pressure1, real, intent(in) pressure2, real, dimension(:), intent(out) rho1, real, dimension(:), intent(out) rho2, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Definition at line 310 of file MOM_EOS.F90.
References mom_eos_linear::calculate_2_densities_linear(), mom_eos_unesco::calculate_2_densities_unesco(), mom_eos_wright::calculate_2_densities_wright(), and mom_error_handler::mom_error().
subroutine, public mom_eos::calculate_compress (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Definition at line 265 of file MOM_EOS.F90.
References mom_eos_linear::calculate_compress_linear(), mom_eos_unesco::calculate_compress_unesco(), mom_eos_wright::calculate_compress_wright(), and mom_error_handler::mom_error().
subroutine mom_eos::calculate_density_array (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS) private
Definition at line 130 of file MOM_EOS.F90.
References mom_eos_linear::calculate_density_linear::calculate_density_array_linear(), mom_eos_unesco::calculate_density_unesco::calculate_density_array_unesco(), mom_eos_wright::calculate_density_wright::calculate_density_array_wright(), and mom_error_handler::mom_error().
subroutine, public mom_eos::calculate_density_derivs (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT, real, dimension(:), intent(out) drho_dS, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Definition at line 227 of file MOM_EOS.F90.
References mom_eos_linear::calculate_density_derivs_linear(), mom_eos_unesco::calculate_density_derivs_unesco(), mom_eos_wright::calculate_density_derivs_wright(), and mom_error_handler::mom_error().
Referenced by benchmark_initialization::benchmark_init_temperature_salinity(), benchmark_initialization::benchmark_initialize_thickness(), mom_bulk_mixed_layer::bulkmixedlayer(), mom_kappa_shear::calculate_kappa_shear(), mom_forcing_type::calculatebuoyancyflux1d(), midas_vertmap::determine_temperature(), dome_initialization::dome_set_open_bdry_conds(), mom_set_diffusivity::double_diffusion(), mom_entrain_diffusive::entrainment_diffusive(), mom_set_diffusivity::find_n2(), mom_int_tide_input::find_n2_bottom(), mom_geothermal::geothermal(), mom_initialization::initialize_temp_salt_fit(), mom_initialization::set_open_bdry_conds(), mom_pressureforce_mont::set_pbce_bouss(), mom_pressureforce_mont::set_pbce_nonbouss(), mom_set_visc::set_viscous_bbl(), mom_set_visc::set_viscous_ml(), mom_thickness_diffuse::thickness_diffuse_full(), and mom_wave_speed::wave_speed().
subroutine mom_eos::calculate_density_scalar (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho, type(eos_type), pointer EOS) private
Definition at line 96 of file MOM_EOS.F90.
References mom_eos_linear::calculate_density_linear::calculate_density_scalar_linear(), mom_eos_unesco::calculate_density_unesco::calculate_density_scalar_unesco(), mom_eos_wright::calculate_density_wright::calculate_density_scalar_wright(), and mom_error_handler::mom_error().
subroutine mom_eos::calculate_tfreeze_array (real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) T_fr, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS) private
Definition at line 194 of file MOM_EOS.F90.
References mom_error_handler::mom_error().
subroutine mom_eos::calculate_tfreeze_scalar (real, intent(in) S, real, intent(in) pressure, real, intent(out) T_fr, type(eos_type), pointer EOS) private
Definition at line 164 of file MOM_EOS.F90.
References mom_error_handler::mom_error().
subroutine mom_eos::compute_integral_bilinear (real, dimension(4), intent(in) x, real, dimension(4), intent(in) y, real, dimension(4), intent(in) f, real, intent(out) integral) private
Definition at line 1582 of file MOM_EOS.F90.
References evaluate_shape_bilinear().
Referenced by int_density_dz_generic_plm_analytic().
subroutine mom_eos::compute_integral_quadratic (real, dimension(4), intent(in) x, real, dimension(4), intent(in) y, real, dimension(9), intent(in) f, real, intent(out) integral) private
Definition at line 1648 of file MOM_EOS.F90.
References evaluate_shape_bilinear(), and evaluate_shape_quadratic().
Referenced by int_density_dz_generic_ppm().
subroutine, public mom_eos::deselect_eqn_of_state (type(eos_type), pointer EOS)
Definition at line 582 of file MOM_EOS.F90.
subroutine mom_eos::evaluate_shape_bilinear (real, intent(in) xi, real, intent(in) eta, real, dimension(4), intent(out) phi, real, dimension(4), intent(out) dphidxi, real, dimension(4), intent(out) dphideta) private
Definition at line 1733 of file MOM_EOS.F90.
Referenced by compute_integral_bilinear(), and compute_integral_quadratic().
subroutine mom_eos::evaluate_shape_quadratic (real, intent(in) xi, real, intent(in) eta, real, dimension(9), intent(out) phi, real, dimension(9), intent(out) dphidxi, real, dimension(9), intent(out) dphideta) private
Definition at line 1771 of file MOM_EOS.F90.
Referenced by compute_integral_quadratic().
subroutine, public mom_eos::int_density_dz (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa)
Definition at line 411 of file MOM_EOS.F90.
References int_density_dz_generic(), mom_eos_linear::int_density_dz_linear(), mom_eos_wright::int_density_dz_wright(), and mom_error_handler::mom_error().
Referenced by mom_diagnostics::calculate_vertical_integrals(), and mom_pressureforce_afv::pressureforce_afv_bouss().
subroutine mom_eos::int_density_dz_generic (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa) private
Definition at line 594 of file MOM_EOS.F90.
Referenced by int_density_dz().
subroutine mom_eos::int_density_dz_generic_cell (real, dimension(2), intent(in) T_t_arg, real, dimension(2), intent(in) T_b_arg, real, dimension(2), intent(in) S_t_arg, real, dimension(2), intent(in) S_b_arg, real, dimension(2), intent(inout) z_t_arg, real, dimension(2), intent(inout) z_b_arg, real, dimension(2), intent(in) depth, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(2), intent(out) dpa, real, dimension(2), intent(out) intz_dpa, real, intent(out) intx_dpa, real, intent(out) inty_dpa) private
Definition at line 715 of file MOM_EOS.F90.
subroutine, public mom_eos::int_density_dz_generic_plm (real, dimension(nimem_,njmem_), intent(in) T_t, real, dimension(nimem_,njmem_), intent(in) T_b, real, dimension(nimem_,njmem_), intent(in) S_t, real, dimension(nimem_,njmem_), intent(in) S_b, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa, logical, intent(in), optional useMassWghtInterp)
Definition at line 921 of file MOM_EOS.F90.
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
subroutine, public mom_eos::int_density_dz_generic_plm_analytic (real, dimension(nimem_,njmem_), intent(in) T_t, real, dimension(nimem_,njmem_), intent(in) T_b, real, dimension(nimem_,njmem_), intent(in) S_t, real, dimension(nimem_,njmem_), intent(in) S_b, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa)
Definition at line 1421 of file MOM_EOS.F90.
References compute_integral_bilinear().
subroutine, public mom_eos::int_density_dz_generic_ppm (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) T_t, real, dimension(nimem_,njmem_), intent(in) T_b, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) S_t, real, dimension(nimem_,njmem_), intent(in) S_b, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa)
Definition at line 1187 of file MOM_EOS.F90.
References compute_integral_quadratic().
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
subroutine mom_eos::int_spec_vol_dp_generic (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) p_t, real, dimension(nimem_,njmem_), intent(in) p_b, real, intent(in) alpha_ref, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dza, real, dimension(nimem_,njmem_), intent(out), optional intp_dza, real, dimension(nimemb_,njmem_), intent(out), optional intx_dza, real, dimension(nimem_,njmemb_), intent(out), optional inty_dza, integer, intent(in), optional halo_size) private
Definition at line 1828 of file MOM_EOS.F90.
Referenced by int_specific_vol_dp().
subroutine, public mom_eos::int_specific_vol_dp (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) p_t, real, dimension(nimem_,njmem_), intent(in) p_b, real, intent(in) alpha_ref, type(ocean_grid_type), intent(in) G, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(out) dza, real, dimension(nimem_,njmem_), intent(out), optional intp_dza, real, dimension(nimemb_,njmem_), intent(out), optional intx_dza, real, dimension(nimem_,njmemb_), intent(out), optional inty_dza, integer, intent(in), optional halo_size)
Definition at line 348 of file MOM_EOS.F90.
References int_spec_vol_dp_generic(), mom_eos_linear::int_spec_vol_dp_linear(), mom_eos_wright::int_spec_vol_dp_wright(), and mom_error_handler::mom_error().
Referenced by mom_initialization::convert_thickness(), mom_interface_heights::find_eta_2d(), mom_interface_heights::find_eta_3d(), mom_pressureforce_afv::pressureforce_afv_nonbouss(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
logical function, public mom_eos::query_compressible (type(eos_type), pointer EOS)
Definition at line 473 of file MOM_EOS.F90.
References mom_error_handler::mom_error().
Referenced by mom_pressureforce_mont::pressureforce_mont_bouss(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
subroutine, public mom_eos::select_eqn_of_state (type(param_file_type), intent(in) param_file, type(eos_type), pointer EOS)
Definition at line 487 of file MOM_EOS.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_string_functions::uppercase().
Referenced by mom::initialize_mom().
Member Data Documentation
character*(10), parameter mom_eos::eos_default = EOS_WRIGHT_STRING private
Definition at line 86 of file MOM_EOS.F90.
integer, parameter mom_eos::eos_linear = 1
Definition at line 79 of file MOM_EOS.F90.
character*(10), parameter mom_eos::eos_linear_string = "LINEAR" private
Definition at line 83 of file MOM_EOS.F90.
integer, parameter mom_eos::eos_unesco = 2 private
Definition at line 80 of file MOM_EOS.F90.
character*(10), parameter mom_eos::eos_unesco_string = "UNESCO" private
Definition at line 84 of file MOM_EOS.F90.
integer, parameter mom_eos::eos_wright = 3 private
Definition at line 81 of file MOM_EOS.F90.
character*(10), parameter mom_eos::eos_wright_string = "WRIGHT" private
Definition at line 85 of file MOM_EOS.F90.
character*(10), parameter mom_eos::tfreeze_default = TFREEZE_LINEAR_STRING private
Definition at line 92 of file MOM_EOS.F90.
integer, parameter mom_eos::tfreeze_linear = 1 private
Definition at line 88 of file MOM_EOS.F90.
character*(10), parameter mom_eos::tfreeze_linear_string = "LINEAR" private
Definition at line 90 of file MOM_EOS.F90.
integer, parameter mom_eos::tfreeze_millero = 2 private
Definition at line 89 of file MOM_EOS.F90.
character*(10), parameter mom_eos::tfreeze_millero_string = "MILLERO_78" private
Definition at line 91 of file MOM_EOS.F90.
The documentation for this module was generated from the following file:
src/equation_of_state/MOM_EOS.F90