MOM6: mom_pointaccel Module Reference
mom_pointaccel Module Reference
Data Types
type pointaccel_cs
Public Member Functions
subroutine, public write_u_accel (I, j, um, hin, ADp, CDp, dt, G, CS, maxvel, minvel, str, a, hv)
subroutine, public write_v_accel (i, J, vm, hin, ADp, CDp, dt, G, CS, maxvel, minvel, str, a, hv)
subroutine, public pointaccel_init (MIS, Time, G, param_file, diag, dirs, CS)
Detailed Description
Definition at line 1 of file MOM_PointAccel.F90.
Member Function/Subroutine Documentation
subroutine, public mom_pointaccel::pointaccel_init (type(ocean_internal_state), intent(in), target MIS, type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(directories), intent(in) dirs, type(pointaccel_cs), pointer CS)
Definition at line 759 of file MOM_PointAccel.F90.
References mom_file_parser::log_version().
Referenced by mom_vert_friction::vertvisc_init().
subroutine, public mom_pointaccel::write_u_accel (integer, intent(in) I, integer, intent(in) j, real, dimension(nimemb_,njmem_,nkmem_), intent(in) um, real, dimension(nimem_,njmem_,nkmem_), intent(in) hin, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(pointaccel_cs), pointer CS, real, intent(in) maxvel, real, intent(in) minvel, real, intent(in), optional str, real, dimension(nimemb_,nkmem_), intent(in), optional a, real, dimension(nimemb_,nkmem_), intent(in), optional hv)
Definition at line 94 of file MOM_PointAccel.F90.
References mom_error_handler::mom_error().
Referenced by mom_vert_friction::vertvisc_limit_vel().
subroutine, public mom_pointaccel::write_v_accel (integer, intent(in) i, integer, intent(in) J, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vm, real, dimension(nimem_,njmem_,nkmem_), intent(in) hin, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(pointaccel_cs), pointer CS, real, intent(in) maxvel, real, intent(in) minvel, real, intent(in), optional str, real, dimension(nimem_,nkmem_), intent(in), optional a, real, dimension(nimem_,nkmem_), intent(in), optional hv)
Definition at line 427 of file MOM_PointAccel.F90.
References mom_error_handler::mom_error().
Referenced by mom_vert_friction::vertvisc_limit_vel().
The documentation for this module was generated from the following file:
src/diagnostics/MOM_PointAccel.F90