MOM6: mom_tracer_hor_diff Module Reference
mom_tracer_hor_diff Module Reference
Data Types
type p2d
type p2di
type tracer_hor_diff_cs
Public Member Functions
subroutine, public tracer_hordiff (h, dt, MEKE, VarMix, G, CS, Reg, tv)
subroutine, public tracer_hor_diff_init (Time, G, param_file, diag, CS)
subroutine, public tracer_hor_diff_end (CS)
Private Member Functions
subroutine tracer_epipycnal_ml_diff (h, dt, Tr, ntr, khdt_epi_x, khdt_epi_y, G, CS, tv, num_itts)
Private Attributes
integer id_clock_diffuse
integer id_clock_epimix
integer id_clock_pass
integer id_clock_sync
Detailed Description
Definition at line 1 of file MOM_tracer_hor_diff.F90.
Member Function/Subroutine Documentation
subroutine mom_tracer_hor_diff::tracer_epipycnal_ml_diff (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, intent(in) dt, type(tracer_type), dimension(:), intent(inout) Tr, integer, intent(in) ntr, real, dimension(nimemb_,njmem_), intent(in) khdt_epi_x, real, dimension(nimem_,njmemb_), intent(in) khdt_epi_y, type(ocean_grid_type), intent(inout) G, type(tracer_hor_diff_cs), intent(in) CS, type(thermo_var_ptrs), intent(in) tv, integer, intent(in) num_itts) private
Definition at line 392 of file MOM_tracer_hor_diff.F90.
Referenced by tracer_hordiff().
subroutine, public mom_tracer_hor_diff::tracer_hor_diff_end (type(tracer_hor_diff_cs), pointer CS)
Definition at line 1287 of file MOM_tracer_hor_diff.F90.
Referenced by mom::mom_end().
subroutine, public mom_tracer_hor_diff::tracer_hor_diff_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(tracer_hor_diff_cs), pointer CS)
Definition at line 1205 of file MOM_tracer_hor_diff.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
subroutine, public mom_tracer_hor_diff::tracer_hordiff (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, intent(in) dt, type(meke_type), pointer MEKE, type(varmix_cs), pointer VarMix, type(ocean_grid_type), intent(inout) G, type(tracer_hor_diff_cs), pointer CS, type(tracer_registry_type), pointer Reg, type(thermo_var_ptrs), intent(in) tv)
Definition at line 106 of file MOM_tracer_hor_diff.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_tracer_registry::mom_tracer_chksum(), and tracer_epipycnal_ml_diff().
Referenced by mom::step_mom().
Member Data Documentation
integer mom_tracer_hor_diff::id_clock_diffuse private
Definition at line 102 of file MOM_tracer_hor_diff.F90.
integer mom_tracer_hor_diff::id_clock_epimix private
Definition at line 102 of file MOM_tracer_hor_diff.F90.
integer mom_tracer_hor_diff::id_clock_pass private
Definition at line 102 of file MOM_tracer_hor_diff.F90.
integer mom_tracer_hor_diff::id_clock_sync private
Definition at line 102 of file MOM_tracer_hor_diff.F90.
The documentation for this module was generated from the following file:
src/tracer/MOM_tracer_hor_diff.F90