MOM6: ocean_model_mod Module Reference
ocean_model_mod Module Reference
Data Types
interface ocean_model_data_get
type ocean_public_type
type ocean_state_type
Public Member Functions
subroutine, public ocean_model_init (Ocean_sfc, OS, Time_init, Time_in)
subroutine, public update_ocean_model (Ice_ocean_boundary, OS, Ocean_sfc, time_start_update, Ocean_coupling_time_step)
subroutine, public ocean_model_restart (OS, timestamp)
subroutine, public ocean_model_end (Ocean_sfc, Ocean_state, Time)
subroutine, public ocean_model_save_restart (OS, Time, directory, filename_suffix)
subroutine, public ocean_model_init_sfc (OS, Ocean_sfc)
subroutine, public ocean_model_flux_init (OS)
subroutine, public ocean_stock_pe (OS, index, value, time_index)
subroutine ocean_model_data2d_get (OS, Ocean, name, array2D, isc, jsc)
subroutine ocean_model_data1d_get (OS, Ocean, name, value)
subroutine, public ocean_public_type_chksum (id, timestep, ocn)
Private Member Functions
subroutine initialize_ocean_public_type (input_domain, Ocean_sfc, maskmap)
subroutine convert_state_to_ocean_type (state, Ocean_sfc, G, patm, press_to_z)
Detailed Description
Definition at line 1 of file ocean_model_MOM.F90.
Member Function/Subroutine Documentation
subroutine ocean_model_mod::convert_state_to_ocean_type (type(surface), intent(inout) state, type(ocean_public_type), intent(inout), target Ocean_sfc, type(ocean_grid_type), intent(inout) G, real, dimension(:,:), intent(in), optional patm, real, intent(in), optional press_to_z) private
Definition at line 516 of file ocean_model_MOM.F90.
References mom_error_handler::mom_error().
Referenced by ocean_model_init_sfc(), and update_ocean_model().
subroutine ocean_model_mod::initialize_ocean_public_type (type(domain2d), intent(in) input_domain, type(ocean_public_type), intent(inout) Ocean_sfc, logical, dimension(:,:), intent(in), optional maskmap) private
Definition at line 479 of file ocean_model_MOM.F90.
Referenced by ocean_model_init().
subroutine ocean_model_mod::ocean_model_data1d_get (type(ocean_state_type), pointer OS, type(ocean_public_type), intent(in) Ocean, character(len=*), intent(in) name, real, intent(out) value)
Definition at line 780 of file ocean_model_MOM.F90.
References mom_error_handler::mom_error().
subroutine ocean_model_mod::ocean_model_data2d_get (type(ocean_state_type), pointer OS, type(ocean_public_type), intent(in) Ocean, character(len=*), intent(in) name, real, dimension(isc:,jsc:), intent(out) array2D, integer, intent(in) isc, integer, intent(in) jsc)
Definition at line 732 of file ocean_model_MOM.F90.
References mom_error_handler::mom_error().
subroutine, public ocean_model_mod::ocean_model_end (type(ocean_public_type), intent(inout) Ocean_sfc, type(ocean_state_type), pointer Ocean_state, type(time_type), intent(in) Time)
Definition at line 433 of file ocean_model_MOM.F90.
References mom::mom_end(), and ocean_model_save_restart().
subroutine, public ocean_model_mod::ocean_model_flux_init (type(ocean_state_type), pointer OS)
Definition at line 622 of file ocean_model_MOM.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_file_parser::close_param_file(), mom_get_input::get_mom_input(), and mom_error_handler::mom_error().
subroutine, public ocean_model_mod::ocean_model_init (type(ocean_public_type), intent(inout), target Ocean_sfc, type(ocean_state_type), pointer OS, type(time_type), intent(in) Time_init, type(time_type), intent(in) Time_in)
Definition at line 182 of file ocean_model_MOM.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_file_parser::close_param_file(), mom_diag_mediator::diag_mediator_close_registration(), mom::initialize_mom(), initialize_ocean_public_type(), mom_error_handler::is_root_pe(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_sum_output::mom_sum_output_init(), mom_surface_forcing::surface_forcing_init(), mom_string_functions::uppercase(), and mom_sum_output::write_energy().
subroutine, public ocean_model_mod::ocean_model_init_sfc (type(ocean_state_type), pointer OS, type(ocean_public_type), intent(inout) Ocean_sfc)
Definition at line 591 of file ocean_model_MOM.F90.
References mom::calculate_surface_state(), and convert_state_to_ocean_type().
subroutine, public ocean_model_mod::ocean_model_restart (type(ocean_state_type), pointer OS, character(len=*), intent(in), optional timestamp)
Definition at line 406 of file ocean_model_MOM.F90.
References mom_surface_forcing::forcing_save_restart(), and mom_restart::save_restart().
subroutine, public ocean_model_mod::ocean_model_save_restart (type(ocean_state_type), pointer OS, type(time_type), intent(in) Time, character(len=*), intent(in), optional directory, character(len=*), intent(in), optional filename_suffix)
Definition at line 452 of file ocean_model_MOM.F90.
References mom_surface_forcing::forcing_save_restart(), and mom_restart::save_restart().
Referenced by ocean_model_end().
subroutine, public ocean_model_mod::ocean_public_type_chksum (character(len=*), intent(in) id, integer, intent(in) timestep, type(ocean_public_type), intent(in) ocn)
Definition at line 799 of file ocean_model_MOM.F90.
subroutine, public ocean_model_mod::ocean_stock_pe (type(ocean_state_type), pointer OS, integer, intent(in) index, real, intent(out) value, integer, intent(in), optional time_index)
Definition at line 675 of file ocean_model_MOM.F90.
subroutine, public ocean_model_mod::update_ocean_model (type(ice_ocean_boundary_type), intent(inout) Ice_ocean_boundary, type(ocean_state_type), pointer OS, type(ocean_public_type), intent(inout) Ocean_sfc, type(time_type), intent(in) time_start_update, type(time_type), intent(in) Ocean_coupling_time_step)
Definition at line 308 of file ocean_model_MOM.F90.
References mom_sum_output::accumulate_net_input(), mom_surface_forcing::average_forcing(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_surface_forcing::convert_iob_to_fluxes(), convert_state_to_ocean_type(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom_error_handler::mom_error(), mom::step_mom(), and mom_sum_output::write_energy().
The documentation for this module was generated from the following file:
config_src/coupled_driver/ocean_model_MOM.F90