MOM6: adjustment_initialization Module Reference
adjustment_initialization Module Reference
Public Member Functions
subroutine, public adjustment_initialize_thickness (h, G, param_file)
subroutine, public adjustment_initialize_temperature_salinity (T, S, h, G, param_file, eqn_of_state)
Private Attributes
character(len=40) mod = "adjustment_initialization"
Detailed Description
Definition at line 1 of file adjustment_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public adjustment_initialization::adjustment_initialize_temperature_salinity (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Definition at line 206 of file adjustment_initialization.F90.
References regrid_consts::coordinatemode(), and mom_error_handler::mom_error().
Referenced by mom_initialization::mom_initialize().
subroutine, public adjustment_initialization::adjustment_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 62 of file adjustment_initialization.F90.
References regrid_consts::coordinatemode(), mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize().
Member Data Documentation
character(len=40) adjustment_initialization::mod = "adjustment_initialization" private
Definition at line 44 of file adjustment_initialization.F90.
The documentation for this module was generated from the following file:
src/user/adjustment_initialization.F90