MOM6: mom_obsolete_params Module Reference
mom_obsolete_params Module Reference
Public Member Functions
subroutine, public find_obsolete_params (param_file)
Private Member Functions
subroutine test_obsolete_logical (param_file, varname, warning_val)
subroutine test_obsolete_char (param_file, varname)
subroutine test_obsolete_real (param_file, varname, warning_val)
subroutine test_obsolete_int (param_file, varname, warning_val)
Detailed Description
Definition at line 1 of file MOM_obsolete_params.F90.
Member Function/Subroutine Documentation
subroutine, public mom_obsolete_params::find_obsolete_params (type(param_file_type), intent(in) param_file)
Definition at line 43 of file MOM_obsolete_params.F90.
References mom_error_handler::is_root_pe(), mom_file_parser::log_version(), mom_error_handler::mom_error(), test_obsolete_char(), test_obsolete_int(), test_obsolete_logical(), and test_obsolete_real().
Referenced by mom::initialize_mom().
subroutine mom_obsolete_params::test_obsolete_char (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname) private
Definition at line 234 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
subroutine mom_obsolete_params::test_obsolete_int (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, integer, intent(in), optional warning_val) private
Definition at line 268 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
subroutine mom_obsolete_params::test_obsolete_logical (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, logical, intent(in), optional warning_val) private
Definition at line 197 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
subroutine mom_obsolete_params::test_obsolete_real (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, real, intent(in), optional warning_val) private
Definition at line 247 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
The documentation for this module was generated from the following file:
src/diagnostics/MOM_obsolete_params.F90