MOM6: mom_grid Module Reference
mom_grid Module Reference
Data Types
type ocean_grid_type
Public Member Functions
subroutine, public mom_grid_init (G, param_file)
logical function, public ispointincell (G, i, j, x, y)
subroutine, public set_first_direction (G, y_first)
character(len=48) function, public get_thickness_units (G)
character(len=48) function, public get_flux_units (G)
character(len=48) function, public get_tr_flux_units (G, tr_units, tr_vol_conc_units, tr_mass_conc_units)
subroutine, public mom_grid_end (G)
Private Member Functions
subroutine allocate_metrics (G)
Detailed Description
Definition at line 1 of file MOM_grid.F90.
Member Function/Subroutine Documentation
subroutine mom_grid::allocate_metrics (type(ocean_grid_type), intent(inout) G) private
Definition at line 418 of file MOM_grid.F90.
Referenced by mom_grid_init().
character(len=48) function, public mom_grid::get_flux_units (type(ocean_grid_type), intent(in) G)
Definition at line 344 of file MOM_grid.F90.
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2(), mom::register_diags(), mom_dynamics_legacy_split::register_restarts_dyn_legacy_split(), mom_dynamics_split_rk2::register_restarts_dyn_split_rk2(), mom_dynamics_unsplit::register_restarts_dyn_unsplit(), mom_dynamics_unsplit_rk2::register_restarts_dyn_unsplit_rk2(), and mom::set_restart_fields().
character(len=48) function, public mom_grid::get_thickness_units (type(ocean_grid_type), intent(in) G)
Definition at line 327 of file MOM_grid.F90.
Referenced by mom::register_diags(), mom_dynamics_legacy_split::register_restarts_dyn_legacy_split(), mom_dynamics_split_rk2::register_restarts_dyn_split_rk2(), mom_dynamics_unsplit::register_restarts_dyn_unsplit(), mom_dynamics_unsplit_rk2::register_restarts_dyn_unsplit_rk2(), and mom::set_restart_fields().
character(len=48) function, public mom_grid::get_tr_flux_units (type(ocean_grid_type), intent(in) G, character(len=*), intent(in), optional tr_units, character(len=*), intent(in), optional tr_vol_conc_units, character(len=*), intent(in), optional tr_mass_conc_units)
Definition at line 361 of file MOM_grid.F90.
References mom_error_handler::mom_error().
Referenced by mom::register_diags().
logical function, public mom_grid::ispointincell (type(ocean_grid_type), intent(in) G, integer, intent(in) i, integer, intent(in) j, real, intent(in) x, real, intent(in) y)
Definition at line 303 of file MOM_grid.F90.
subroutine, public mom_grid::mom_grid_end (type(ocean_grid_type), intent(inout) G)
Definition at line 478 of file MOM_grid.F90.
References mom_verticalgrid::verticalgridend().
subroutine, public mom_grid::mom_grid_init (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file)
Definition at line 177 of file MOM_grid.F90.
References allocate_metrics(), mom_domains::get_domain_extent(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_verticalgrid::verticalgridinit().
Referenced by mom::initialize_mom(), and mom_main().
subroutine, public mom_grid::set_first_direction (type(ocean_grid_type), intent(inout) G, integer, intent(in) y_first)
Definition at line 320 of file MOM_grid.F90.
The documentation for this module was generated from the following file:
src/core/MOM_grid.F90