MOM6: phillips_initialization Module Reference
phillips_initialization Module Reference
Public Member Functions
subroutine, public phillips_initialize_thickness (h, G, param_file)
subroutine, public phillips_initialize_velocity (u, v, G, param_file)
subroutine, public phillips_initialize_sponges (G, use_temperature, tv, param_file, CSp, h)
Private Member Functions
real function sech (x)
Detailed Description
Definition at line 1 of file Phillips_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public phillips_initialization::phillips_initialize_sponges (type(ocean_grid_type), intent(in) G, logical, intent(in) use_temperature, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CSp, real, dimension(nimem_,njmem_, nkmem_), intent(in) h)
Definition at line 232 of file Phillips_initialization.F90.
References mom_sponge::initialize_sponge(), and mom_file_parser::log_version().
Referenced by mom_initialization::mom_initialize().
subroutine, public phillips_initialization::phillips_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 107 of file Phillips_initialization.F90.
References mom_file_parser::log_version().
Referenced by mom_initialization::mom_initialize().
subroutine, public phillips_initialization::phillips_initialize_velocity (real, dimension(nimemb_,njmem_, nkmem_), intent(out) u, real, dimension(nimem_,njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 177 of file Phillips_initialization.F90.
References mom_file_parser::log_version(), and sech().
Referenced by mom_initialization::mom_initialize().
real function phillips_initialization::sech (real, intent(in) x) private
Definition at line 300 of file Phillips_initialization.F90.
Referenced by phillips_initialize_velocity().
The documentation for this module was generated from the following file:
src/user/Phillips_initialization.F90