MOM6: mom_eos_unesco Module Reference
mom_eos_unesco Module Reference
Data Types
interface calculate_density_unesco
Public Member Functions
subroutine, public calculate_density_scalar_unesco (T, S, pressure, rho)
subroutine, public calculate_density_array_unesco (T, S, pressure, rho, start, npts)
subroutine, public calculate_density_derivs_unesco (T, S, pressure, drho_dT, drho_dS, start, npts)
subroutine, public calculate_compress_unesco (T, S, pressure, rho, drho_dp, start, npts)
subroutine, public calculate_2_densities_unesco (T, S, pressure1, pressure2, rho1, rho2, start, npts)
Private Attributes
real, parameter r00 = 999.842594
real, parameter r10 = 6.793952e-2
real, parameter r20 = -9.095290e-3
real, parameter r30 = 1.001685e-4
real, parameter r40 = -1.120083e-6
real, parameter r50 = 6.536332e-9
real, parameter r01 = 0.824493
real, parameter r11 = -4.0899e-3
real, parameter r21 = 7.6438e-5
real, parameter r31 = -8.2467e-7
real, parameter r41 = 5.3875e-9
real, parameter r032 = -5.72466e-3
real, parameter r132 = 1.0227e-4
real, parameter r232 = -1.6546e-6
real, parameter r02 = 4.8314e-4
real, parameter s00 = 1.965933e4
real, parameter s10 = 1.444304e2
real, parameter s20 = -1.706103
real, parameter s30 = 9.648704e-3
real, parameter s40 = -4.190253e-5
real, parameter s01 = 52.84855
real, parameter s11 = -3.101089e-1
real, parameter s21 = 6.283263e-3
real, parameter s31 = -5.084188e-5
real, parameter s032 = 3.886640e-1
real, parameter s132 = 9.085835e-3
real, parameter s232 = -4.619924e-4
real, parameter sp00 = 3.186519
real, parameter sp10 = 2.212276e-2
real, parameter sp20 = -2.984642e-4
real, parameter sp30 = 1.956415e-6
real, parameter sp01 = 6.704388e-3
real, parameter sp11 = -1.847318e-4
real, parameter sp21 = 2.059331e-7
real, parameter sp032 = 1.480266e-4
real, parameter sp000 = 2.102898e-4
real, parameter sp010 = -1.202016e-5
real, parameter sp020 = 1.394680e-7
real, parameter sp001 = -2.040237e-6
real, parameter sp011 = 6.128773e-8
real, parameter sp021 = 6.207323e-10
Detailed Description
Definition at line 1 of file MOM_EOS_UNESCO.F90.
Member Function/Subroutine Documentation
subroutine, public mom_eos_unesco::calculate_2_densities_unesco (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, intent(in) pressure1, real, intent(in) pressure2, real, dimension(:), intent(out) rho1, real, dimension(:), intent(out) rho2, integer, intent(in) start, integer, intent(in) npts)
Definition at line 258 of file MOM_EOS_UNESCO.F90.
Referenced by mom_eos::calculate_2_densities().
subroutine, public mom_eos_unesco::calculate_compress_unesco (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts)
Definition at line 203 of file MOM_EOS_UNESCO.F90.
Referenced by mom_eos::calculate_compress().
subroutine, public mom_eos_unesco::calculate_density_array_unesco (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts)
Definition at line 91 of file MOM_EOS_UNESCO.F90.
subroutine, public mom_eos_unesco::calculate_density_derivs_unesco (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT, real, dimension(:), intent(out) drho_dS, integer, intent(in) start, integer, intent(in) npts)
Definition at line 137 of file MOM_EOS_UNESCO.F90.
Referenced by mom_eos::calculate_density_derivs().
subroutine, public mom_eos_unesco::calculate_density_scalar_unesco (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho)
Definition at line 61 of file MOM_EOS_UNESCO.F90.
References mom_eos_unesco::calculate_density_unesco::calculate_density_array_unesco().
Member Data Documentation
real, parameter mom_eos_unesco::r00 = 999.842594 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r01 = 0.824493 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r02 = 4.8314e-4 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r032 = -5.72466e-3 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r10 = 6.793952e-2 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r11 = -4.0899e-3 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r132 = 1.0227e-4 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r20 = -9.095290e-3 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r21 = 7.6438e-5 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r232 = -1.6546e-6 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r30 = 1.001685e-4 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r31 = -8.2467e-7 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r40 = -1.120083e-6 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r41 = 5.3875e-9 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::r50 = 6.536332e-9 private
Definition at line 41 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s00 = 1.965933e4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s01 = 52.84855 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s032 = 3.886640e-1 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s10 = 1.444304e2 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s11 = -3.101089e-1 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s132 = 9.085835e-3 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s20 = -1.706103 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s21 = 6.283263e-3 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s232 = -4.619924e-4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s30 = 9.648704e-3 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s31 = -5.084188e-5 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::s40 = -4.190253e-5 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp00 = 3.186519 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp000 = 2.102898e-4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp001 = -2.040237e-6 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp01 = 6.704388e-3 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp010 = -1.202016e-5 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp011 = 6.128773e-8 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp020 = 1.394680e-7 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp021 = 6.207323e-10 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp032 = 1.480266e-4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp10 = 2.212276e-2 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp11 = -1.847318e-4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp20 = -2.984642e-4 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp21 = 2.059331e-7 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
real, parameter mom_eos_unesco::sp30 = 1.956415e-6 private
Definition at line 50 of file MOM_EOS_UNESCO.F90.
The documentation for this module was generated from the following file:
src/equation_of_state/MOM_EOS_UNESCO.F90