MOM6: midas_vertmap Module Reference
midas_vertmap Module Reference
Data Types
interface fill_boundaries
Public Member Functions
real function, dimension(size(tr_in,
1), size(tr_in, 2), nlay),
public tracer_z_init (tr_in, z_edges, e, nkml, nkbl, land_fill, wet, nlay, nlevs, debug, i_debug, j_debug)
subroutine, public determine_temperature (temp, salt, R, p_ref, niter, land_fill, h, k_start, eos)
real function, dimension(size(a,
1), size(a, 2)), public fill_miss_2d (a, good, fill, prev, cyclic_x, tripolar_n, smooth)
real function, dimension(size(rho,
1), size(rho, 2), size(rb,
1)), public find_interfaces (rho, zin, Rb, depth, nlevs, nkml, nkbl, hml, debug)
subroutine, public meshgrid (x, y, x_T, y_T)
Private Member Functions
integer function, dimension(size(a,
1), size(x, 1)) bisect_fast (a, x, lo, hi)
subroutine find_overlap (e, Z_top, Z_bot, k_max, k_start, k_top, k_bot, wt, z1, z2)
real function find_limited_slope (val, e, k)
subroutine smooth_heights (zi, fill, bad, sor, niter, cyclic_x, tripolar_n)
integer function, dimension(0:size(m,
1)+1, 0:size(m, 2)+1) fill_boundaries_int (m, cyclic_x, tripolar_n)
real function, dimension(0:size(m,
1)+1, 0:size(m, 2)+1) fill_boundaries_real (m, cyclic_x, tripolar_n)
Private Attributes
real, parameter epsln =1.e-10
Detailed Description
Definition at line 1 of file midas_vertmap.F90.
Member Function/Subroutine Documentation
integer function, dimension(size(a,1),size(x,1)) midas_vertmap::bisect_fast (real, dimension(:,:), intent(in) a, real, dimension(:), intent(in) x, integer, dimension(size(a,1)), intent(in), optional lo, integer, dimension(size(a,1)), intent(in), optional hi) private
Definition at line 399 of file midas_vertmap.F90.
Referenced by find_interfaces().
subroutine, public midas_vertmap::determine_temperature (real, dimension(:,:,:), intent(inout) temp, real, dimension(:,:,:), intent(inout) salt, real, dimension(size(temp,3)), intent(in) R, real, intent(in) p_ref, integer, intent(in) niter, real, intent(in) land_fill, real, dimension(:,:,:), intent(in) h, integer, intent(in) k_start, type(eos_type), intent(in), pointer eos)
Definition at line 488 of file midas_vertmap.F90.
References mom_diabatic_driver::adjust_salt(), and mom_eos::calculate_density_derivs().
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().
integer function, dimension(0:size(m,1)+1,0:size(m,2)+1) midas_vertmap::fill_boundaries_int (integer, dimension(:,:), intent(in) m, logical, intent(in) cyclic_x, logical, intent(in) tripolar_n) private
Definition at line 1124 of file midas_vertmap.F90.
References midas_vertmap::fill_boundaries::fill_boundaries_real().
real function, dimension(0:size(m,1)+1,0:size(m,2)+1) midas_vertmap::fill_boundaries_real (real, dimension(:,:), intent(in) m, logical, intent(in) cyclic_x, logical, intent(in) tripolar_n) private
Definition at line 1144 of file midas_vertmap.F90.
real function, dimension(size(a,1),size(a,2)), public midas_vertmap::fill_miss_2d (real, dimension(:,:), intent(in) a, integer, dimension(size(a,1),size(a,2)), intent(in) good, integer, dimension(size(a,1),size(a,2)), intent(in) fill, real, dimension(size(a,1),size(a,2)), intent(in), optional prev, logical, intent(in), optional cyclic_x, logical, intent(in), optional tripolar_n, logical, intent(in), optional smooth)
Definition at line 601 of file midas_vertmap.F90.
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().
real function, dimension(size(rho,1),size(rho,2),size(rb,1)), public midas_vertmap::find_interfaces (real, dimension(:,:,:), intent(in) rho, real, dimension(size(rho,3)), intent(in) zin, real, dimension(:), intent(in) Rb, real, dimension(size(rho,1),size(rho,2)), intent(in) depth, real, dimension(size(rho,1),size(rho,2)), intent(in), optional nlevs, integer, intent(in), optional nkml, integer, intent(in), optional nkbl, real, intent(in), optional hml, logical, intent(in), optional debug)
Definition at line 890 of file midas_vertmap.F90.
References bisect_fast().
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().
real function midas_vertmap::find_limited_slope (real, dimension(:), intent(in) val, real, dimension(:), intent(in) e, integer, intent(in) k) private
Definition at line 844 of file midas_vertmap.F90.
subroutine midas_vertmap::find_overlap (real, dimension(:), intent(in) e, real, intent(in) Z_top, real, intent(in) Z_bot, integer, intent(in) k_max, integer, intent(in) k_start, integer, intent(out) k_top, integer, intent(out) k_bot, real, dimension(:), intent(out) wt, real, dimension(:), intent(out) z1, real, dimension(:), intent(out) z2) private
Definition at line 773 of file midas_vertmap.F90.
subroutine, public midas_vertmap::meshgrid (real, dimension(:), intent(in) x, real, dimension(:), intent(in) y, real, dimension(size(x,1),size(y,1)), intent(inout) x_T, real, dimension(size(x,1),size(y,1)), intent(inout) y_T)
Definition at line 1027 of file midas_vertmap.F90.
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().
subroutine midas_vertmap::smooth_heights (real, dimension(:,:), intent(inout) zi, integer, dimension(size(zi,1),size(zi,2)), intent(in) fill, integer, dimension(size(zi,1),size(zi,2)), intent(in) bad, real, intent(in) sor, integer, intent(in) niter, logical, intent(in) cyclic_x, logical, intent(in) tripolar_n) private
Definition at line 1051 of file midas_vertmap.F90.
real function, dimension(size(tr_in,1),size(tr_in,2),nlay), public midas_vertmap::tracer_z_init (real, dimension(:,:,:), intent(in) tr_in, real, dimension(size(tr_in,3)+1), intent(in) z_edges, real, dimension(size(tr_in,1),size(tr_in,2),nlay+1), intent(in) e, integer, intent(in) nkml, integer, intent(in) nkbl, real, intent(in) land_fill, real, dimension(size(tr_in,1),size(tr_in,2)), intent(in) wet, integer, intent(in) nlay, real, dimension(size(tr_in,1),size(tr_in,2)), intent(in), optional nlevs, logical, intent(in), optional debug, integer, intent(in), optional i_debug, integer, intent(in), optional j_debug)
Definition at line 213 of file midas_vertmap.F90.
References mom_diag_to_z::find_limited_slope(), and mom_diag_to_z::find_overlap().
Referenced by mom_ocmip2_cfc::init_tracer_cfc(), ideal_age_example::initialize_ideal_age_tracer(), oil_tracer::initialize_oil_tracer(), mom_initialization::mom_temp_salt_initialize_from_z(), and mom_tracer_z_init::tracer_z_init().
Member Data Documentation
real, parameter midas_vertmap::epsln =1.e-10 private
Definition at line 63 of file midas_vertmap.F90.
The documentation for this module was generated from the following file:
src/initialization/midas_vertmap.F90