MOM6: mom_get_input Module Reference
mom_get_input Module Reference
Data Types
type directories
Public Member Functions
subroutine, public get_mom_input (param_file, dirs, check_params)
Detailed Description
Definition at line 1 of file MOM_get_input.F90.
Member Function/Subroutine Documentation
subroutine, public mom_get_input::get_mom_input (type(param_file_type), intent(out), optional param_file, type(directories), intent(out), optional dirs, logical, intent(in), optional check_params)
Definition at line 54 of file MOM_get_input.F90.
References mom_error_handler::mom_error(), mom_file_parser::open_param_file(), and mom_io::slasher().
Referenced by mom_ice_shelf::initialize_ice_shelf(), mom::initialize_mom(), ocean_model_mod::ocean_model_flux_init(), shelf_main(), and mom_surface_forcing::surface_forcing_init().
The documentation for this module was generated from the following file:
src/framework/MOM_get_input.F90