MOM6: atmos_ocean_fluxes_mod Module Reference
atmos_ocean_fluxes_mod Module Reference
Public Member Functions
integer function, public aof_set_coupler_flux (name, flux_type, implementation, atm_tr_index, param, flag, ice_restart_file, ocean_restart_file, units, caller)
integer function, public aof_set_coupler_flux (name, flux_type, implementation, atm_tr_index, param, flag, ice_restart_file, ocean_restart_file, units, caller)
Detailed Description
Definition at line 1 of file atmos_ocean_fluxes.F90.
Member Function/Subroutine Documentation
integer function, public atmos_ocean_fluxes_mod::aof_set_coupler_flux (character(len=*), intent(in) name, character(len=*), intent(in) flux_type, character(len=*), intent(in) implementation, integer, intent(in), optional atm_tr_index, real, dimension(:), intent(in), optional param, logical, dimension(:), intent(in), optional flag, character(len=*), intent(in), optional ice_restart_file, character(len=*), intent(in), optional ocean_restart_file, character(len=*), intent(in), optional units, character(len=*), intent(in), optional caller)
Definition at line 17 of file atmos_ocean_fluxes.F90.
Referenced by ocean_model_mod::ocean_model_flux_init(), advection_test_tracer::register_advection_test_tracer(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), and user_tracer_example::user_register_tracer_example().
integer function, public atmos_ocean_fluxes_mod::aof_set_coupler_flux (character(len=*), intent(in) name, character(len=*), intent(in) flux_type, character(len=*), intent(in) implementation, integer, intent(in), optional atm_tr_index, real, dimension(:), intent(in), optional param, logical, dimension(:), intent(in), optional flag, character(len=*), intent(in), optional ice_restart_file, character(len=*), intent(in), optional ocean_restart_file, character(len=*), intent(in), optional units, character(len=*), intent(in), optional caller)
Definition at line 17 of file atmos_ocean_fluxes.F90.
The documentation for this module was generated from the following file:
config_src/ice_solo_driver/atmos_ocean_fluxes.F90