MOM6: dome2d_initialization Module Reference
dome2d_initialization Module Reference
Public Member Functions
subroutine, public dome2d_initialize_topography (D, G, param_file, max_depth)
subroutine, public dome2d_initialize_thickness (h, G, param_file)
subroutine, public dome2d_initialize_temperature_salinity (T, S, h, G, param_file, eqn_of_state)
Private Attributes
real, parameter dome2d_width_bay = 0.1
real, parameter dome2d_width_bottom = 0.3
real, parameter dome2d_depth_bay = 0.2
character(len=40) mod = "DOEM2D_initialization"
Detailed Description
Definition at line 1 of file DOME2d_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public dome2d_initialization::dome2d_initialize_temperature_salinity (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Definition at line 231 of file DOME2d_initialization.F90.
References regrid_consts::coordinatemode(), and mom_error_handler::mom_error().
Referenced by mom_initialization::mom_initialize().
subroutine, public dome2d_initialization::dome2d_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 111 of file DOME2d_initialization.F90.
References regrid_consts::coordinatemode(), mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize().
subroutine, public dome2d_initialization::dome2d_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Definition at line 70 of file DOME2d_initialization.F90.
Referenced by mom_initialization::mom_initialize_topography().
Member Data Documentation
real, parameter dome2d_initialization::dome2d_depth_bay = 0.2 private
Definition at line 51 of file DOME2d_initialization.F90.
real, parameter dome2d_initialization::dome2d_width_bay = 0.1 private
Definition at line 49 of file DOME2d_initialization.F90.
real, parameter dome2d_initialization::dome2d_width_bottom = 0.3 private
Definition at line 50 of file DOME2d_initialization.F90.
character(len=40) dome2d_initialization::mod = "DOEM2D_initialization" private
Definition at line 53 of file DOME2d_initialization.F90.
The documentation for this module was generated from the following file:
src/user/DOME2d_initialization.F90