MOM6: mom_io Module Reference
mom_io Module Reference
Data Types
interface file_exists
interface mom_read_data
type vardesc
Public Member Functions
subroutine, public create_file (unit, filename, vars, novars, G, fields, threading, timeunit)
subroutine, public reopen_file (unit, filename, vars, novars, G, fields, threading, timeunit)
subroutine, public read_axis_data (filename, axis_name, var)
integer function, public num_timelevels (filename, varname, min_dims)
character(len=len(dir))
function, public slasher (dir)
subroutine, public mom_io_init (param_file)
Private Member Functions
logical function mom_file_exists (file_name, MOM_Domain)
subroutine mom_read_data_1d (filename, fieldname, data)
subroutine mom_read_data_2d (filename, fieldname, data, MOM_Domain, timelevel, position)
subroutine mom_read_data_3d (filename, fieldname, data, MOM_Domain, timelevel, position)
Detailed Description
Definition at line 1 of file MOM_io.F90.
Member Function/Subroutine Documentation
subroutine, public mom_io::create_file (integer, intent(out) unit, character(len=*), intent(in) filename, type(vardesc), dimension(:), intent(in) vars, integer, intent(in) novars, type(ocean_grid_type), intent(in) G, type(fieldtype), dimension(:), intent(inout) fields, integer, intent(in), optional threading, real, intent(in), optional timeunit)
Definition at line 115 of file MOM_io.F90.
References mom_error_handler::mom_error().
Referenced by mom_ale::ale_writecoordinatefile(), reopen_file(), mom_restart::save_restart(), mom_sum_output::write_energy(), mom_initialization::write_ocean_geometry_file(), and mom_initialization::write_vertgrid_file().
logical function mom_io::mom_file_exists (character(len=*), intent(in) file_name, type(mom_domain_type), intent(in) MOM_Domain) private
Definition at line 585 of file MOM_io.F90.
References mom_io::file_exists::file_exist(), and mom_io::file_exists::mom_file_exists().
subroutine, public mom_io::mom_io_init (type(param_file_type), intent(in) param_file)
Definition at line 641 of file MOM_io.F90.
References mom_file_parser::log_version().
Referenced by mom::initialize_mom(), and mom_main().
subroutine mom_io::mom_read_data_1d (character(len=*), intent(in) filename, character(len=*), intent(in) fieldname, real, dimension(:), intent(inout) data) private
Definition at line 598 of file MOM_io.F90.
subroutine mom_io::mom_read_data_2d (character(len=*), intent(in) filename, character(len=*), intent(in) fieldname, real, dimension(:,:), intent(inout) data, type(mom_domain_type), intent(in) MOM_Domain, integer, intent(in), optional timelevel, integer, intent(in), optional position) private
Definition at line 609 of file MOM_io.F90.
subroutine mom_io::mom_read_data_3d (character(len=*), intent(in) filename, character(len=*), intent(in) fieldname, real, dimension(:,:,:), intent(inout) data, type(mom_domain_type), intent(in) MOM_Domain, integer, intent(in), optional timelevel, integer, intent(in), optional position) private
Definition at line 625 of file MOM_io.F90.
integer function, public mom_io::num_timelevels (character(len=*), intent(in) filename, character(len=*), intent(in) varname, integer, intent(in), optional min_dims)
Definition at line 445 of file MOM_io.F90.
References mom_string_functions::lowercase(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::surface_forcing_init().
subroutine, public mom_io::read_axis_data (character(len=*), intent(in) filename, character(len=*), intent(in) axis_name, real, dimension(:), intent(out) var)
Definition at line 408 of file MOM_io.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialization::set_coord_from_file().
subroutine, public mom_io::reopen_file (integer, intent(out) unit, character(len=*), intent(in) filename, type(vardesc), dimension(:), intent(in) vars, integer, intent(in) novars, type(ocean_grid_type), intent(in) G, type(fieldtype), dimension(:), intent(inout) fields, integer, intent(in), optional threading, real, intent(in), optional timeunit)
Definition at line 337 of file MOM_io.F90.
References create_file(), and mom_error_handler::mom_error().
Referenced by mom_sum_output::write_energy().
character(len=len(dir)) function, public mom_io::slasher (character(len=*), intent(in) dir)
Definition at line 568 of file MOM_io.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialization::depress_surface(), mom_geothermal::geothermal_init(), mom_get_input::get_mom_input(), mom_initialization::initialize_sponges_file(), mom_initialization::initialize_temp_salt_from_file(), mom_initialization::initialize_temp_salt_from_profile(), mom_initialization::initialize_thickness_from_file(), mom_initialization::initialize_topography_from_file(), mom_initialization::initialize_velocity_from_file(), mom_int_tide_input::int_tide_input_init(), meso_surface_forcing::meso_surface_forcing_init(), mom_diag_to_z::mom_diag_to_z_init(), mom_domains::mom_domains_init(), mom_initialization::mom_initialize(), mom_sum_output::mom_sum_output_init(), mom_initialization::mom_temp_salt_initialize_from_z(), mom_opacity::opacity_init(), advection_test_tracer::register_advection_test_tracer(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), mom_initialization::reset_face_lengths_file(), mom_initialization::reset_face_lengths_list(), mom_initialization::set_coord_from_file(), mom_initialization::set_coord_from_ts_profile(), mom_set_diffusivity::set_diffusivity_init(), mom_initialization::set_flather_bdry_conds(), mom_grid_initialize::set_grid_metrics_from_mosaic(), mom_string_functions::slasher(), mom_surface_forcing::surface_forcing_init(), and user_tracer_example::user_register_tracer_example().
The documentation for this module was generated from the following file:
src/framework/MOM_io.F90