MOM6: mom_grid_initialize Module Reference
mom_grid_initialize Module Reference
Data Types
type gps
Public Member Functions
subroutine, public set_grid_metrics (G, param_file)
subroutine, public initialize_masks (G, PF)
Public Attributes
real, parameter epsln = 1.0e-10
Private Member Functions
real function ds_di (x, y, GP)
real function ds_dj (x, y, GP)
real function dl (x1, x2, y1, y2)
real function find_root (fn, dy_df, GP, fnval, y1, ymin, ymax, ittmax)
real function dx_di (x, GP)
real function int_di_dx (x, GP)
real function dy_dj (y, GP)
real function int_dj_dy (y, GP)
subroutine set_grid_derived_metrics (G, param_file)
subroutine grid_metrics_chksum (parent, G)
subroutine set_grid_metrics_from_mosaic (G, param_file)
subroutine set_grid_metrics_cartesian (G, param_file)
subroutine set_grid_metrics_spherical (G, param_file)
subroutine set_grid_metrics_mercator (G, param_file)
subroutine extrapolate_metric (var, jh)
Detailed Description
Definition at line 1 of file MOM_grid_initialize.F90.
Member Function/Subroutine Documentation
real function mom_grid_initialize::dl (real, intent(in) x1, real, intent(in) x2, real, intent(in) y1, real, intent(in) y2) private
Definition at line 136 of file MOM_grid_initialize.F90.
Referenced by set_grid_metrics_mercator().
real function mom_grid_initialize::ds_di (real, intent(in) x, real, intent(in) y, type(gps), intent(in) GP) private
Definition at line 109 of file MOM_grid_initialize.F90.
References dx_di().
Referenced by set_grid_metrics_mercator().
real function mom_grid_initialize::ds_dj (real, intent(in) x, real, intent(in) y, type(gps), intent(in) GP) private
Definition at line 122 of file MOM_grid_initialize.F90.
References dy_dj().
Referenced by set_grid_metrics_mercator().
real function mom_grid_initialize::dx_di (real, intent(in) x, type(gps), intent(in) GP) private
Definition at line 256 of file MOM_grid_initialize.F90.
Referenced by ds_di(), and set_grid_metrics_mercator().
real function mom_grid_initialize::dy_dj (real, intent(in) y, type(gps), intent(in) GP) private
Definition at line 279 of file MOM_grid_initialize.F90.
Referenced by ds_dj(), and set_grid_metrics_mercator().
subroutine mom_grid_initialize::extrapolate_metric (real, dimension(:,:), intent(inout) var, integer, intent(in) jh) private
Definition at line 1371 of file MOM_grid_initialize.F90.
Referenced by set_grid_metrics_from_mosaic().
real function mom_grid_initialize::find_root (real, external fn, real, external dy_df, type(gps), intent(in) GP, real, intent(in) fnval, real, intent(in) y1, real, intent(in) ymin, real, intent(in) ymax, integer, intent(out) ittmax) private
Definition at line 160 of file MOM_grid_initialize.F90.
References mom_error_handler::mom_error().
Referenced by set_grid_metrics_mercator().
subroutine mom_grid_initialize::grid_metrics_chksum (character(len=*), intent(in) parent, type(ocean_grid_type), intent(in) G) private
Definition at line 505 of file MOM_grid_initialize.F90.
Referenced by set_grid_metrics().
subroutine, public mom_grid_initialize::initialize_masks (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) PF)
Definition at line 1400 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and mom_error_handler::mom_error().
Referenced by mom_initialization::mom_initialize().
real function mom_grid_initialize::int_di_dx (real, intent(in) x, type(gps), intent(in) GP) private
Definition at line 268 of file MOM_grid_initialize.F90.
Referenced by set_grid_metrics_mercator().
real function mom_grid_initialize::int_dj_dy (real, intent(in) y, type(gps), intent(in) GP) private
Definition at line 308 of file MOM_grid_initialize.F90.
Referenced by set_grid_metrics_mercator().
subroutine mom_grid_initialize::set_grid_derived_metrics (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 408 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and mom_error_handler::mom_error().
Referenced by set_grid_metrics().
subroutine, public mom_grid_initialize::set_grid_metrics (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file)
Definition at line 353 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), grid_metrics_chksum(), mom_file_parser::log_version(), mom_error_handler::mom_error(), set_grid_derived_metrics(), set_grid_metrics_cartesian(), set_grid_metrics_from_mosaic(), set_grid_metrics_mercator(), and set_grid_metrics_spherical().
Referenced by mom_initialization::mom_initialize(), and mom_main().
subroutine mom_grid_initialize::set_grid_metrics_cartesian (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 854 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by set_grid_metrics().
subroutine mom_grid_initialize::set_grid_metrics_from_mosaic (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 611 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), extrapolate_metric(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by set_grid_metrics().
subroutine mom_grid_initialize::set_grid_metrics_mercator (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 1126 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), dl(), ds_di(), ds_dj(), dx_di(), dy_dj(), find_root(), int_di_dx(), and int_dj_dy().
Referenced by set_grid_metrics().
subroutine mom_grid_initialize::set_grid_metrics_spherical (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file) private
Definition at line 981 of file MOM_grid_initialize.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and mom_error_handler::mom_error().
Referenced by set_grid_metrics().
Member Data Documentation
real, parameter mom_grid_initialize::epsln = 1.0e-10
Definition at line 104 of file MOM_grid_initialize.F90.
The documentation for this module was generated from the following file:
src/initialization/MOM_grid_initialize.F90