MOM6: mom_kappa_shear Module Reference
mom_kappa_shear Module Reference
Data Types
type kappa_shear_cs
Public Member Functions
subroutine, public calculate_kappa_shear (u_in, v_in, h, tv, p_surf, kappa_io, tke_io, kv_io, dt, G, CS, initialize_all)
logical function, public kappa_shear_init (Time, G, param_file, diag, CS)
logical function, public kappa_shear_is_used (param_file)
Public Attributes
character(len=40) mod = "MOM_kappa_shear"
Detailed Description
Definition at line 1 of file MOM_kappa_shear.F90.
Member Function/Subroutine Documentation
subroutine, public mom_kappa_shear::calculate_kappa_shear (real, dimension(nimem_,njmem_,nkmem_), intent(in) u_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) v_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(:,:), pointer p_surf, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) kappa_io, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) tke_io, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) kv_io, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(kappa_shear_cs), pointer CS, logical, intent(in), optional initialize_all)
Definition at line 118 of file MOM_kappa_shear.F90.
References mom_eos::calculate_density_derivs(), calculate_projected_state(), and find_kappa_tke().
Referenced by mom_set_diffusivity::set_diffusivity().
logical function, public mom_kappa_shear::kappa_shear_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(kappa_shear_cs), pointer CS)
Definition at line 1624 of file MOM_kappa_shear.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_set_diffusivity::set_diffusivity_init().
logical function, public mom_kappa_shear::kappa_shear_is_used (type(param_file_type), intent(in) param_file)
Definition at line 1766 of file MOM_kappa_shear.F90.
Referenced by mom_diabatic_driver::diabatic_driver_init(), mom_set_visc::set_visc_init(), and mom_set_visc::set_visc_register_restarts().
Member Data Documentation
character(len=40) mom_kappa_shear::mod = "MOM_kappa_shear"
Definition at line 111 of file MOM_kappa_shear.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_kappa_shear.F90