MOM6: mom_continuity_ppm Module Reference
mom_continuity_ppm Module Reference
Data Types
type continuity_ppm_cs
type loop_bounds_type
Public Member Functions
subroutine, public continuity_ppm (u, v, hin, h, uh, vh, dt, G, CS, uhbt, vhbt, OBC, visc_rem_u, visc_rem_v, u_cor, v_cor, uhbt_aux, vhbt_aux, u_cor_aux, v_cor_aux, BT_cont)
subroutine, public continuity_ppm_init (Time, G, param_file, diag, CS)
subroutine, public continuity_ppm_end (CS)
Private Member Functions
subroutine zonal_mass_flux (u, h_in, uh, dt, G, CS, LB, uhbt, OBC, visc_rem_u, u_cor, uhbt_aux, u_cor_aux, BT_cont)
subroutine zonal_flux_layer (u, h, hL, hR, uh, duhdu, visc_rem, dt, G, j, ish, ieh, do_i, vol_CFL)
subroutine zonal_face_thickness (u, h, hL, hR, h_u, dt, G, LB, vol_CFL, visc_rem_u)
subroutine zonal_flux_adjust (u, h_in, hL, hR, uhbt, uh_tot_0, duhdu_tot_0, du, du_max_CFL, du_min_CFL, dt, G, CS, visc_rem, j, ish, ieh, do_i_in, full_precision, uh_3d)
subroutine set_zonal_bt_cont (u, h_in, hL, hR, BT_cont, uh_tot_0, duhdu_tot_0, du_max_CFL, du_min_CFL, dt, G, CS, visc_rem, visc_rem_max, j, ish, ieh, do_i)
subroutine meridional_mass_flux (v, h_in, vh, dt, G, CS, LB, vhbt, OBC, visc_rem_v, v_cor, vhbt_aux, v_cor_aux, BT_cont)
subroutine merid_flux_layer (v, h, hL, hR, vh, dvhdv, visc_rem, dt, G, J, ish, ieh, do_i, vol_CFL)
subroutine merid_face_thickness (v, h, hL, hR, h_v, dt, G, LB, vol_CFL, visc_rem_v)
subroutine meridional_flux_adjust (v, h_in, hL, hR, vhbt, vh_tot_0, dvhdv_tot_0, dv, dv_max_CFL, dv_min_CFL, dt, G, CS, visc_rem, j, ish, ieh, do_i_in, full_precision, vh_3d)
subroutine set_merid_bt_cont (v, h_in, hL, hR, BT_cont, vh_tot_0, dvhdv_tot_0, dv_max_CFL, dv_min_CFL, dt, G, CS, visc_rem, visc_rem_max, j, ish, ieh, do_i)
subroutine ppm_reconstruction_x (h_in, h_l, h_r, G, LB, h_min, monotonic, simple_2nd)
subroutine ppm_reconstruction_y (h_in, h_l, h_r, G, LB, h_min, monotonic, simple_2nd)
subroutine ppm_limit_pos (h_in, h_L, h_R, h_min, iis, iie, jis, jie)
subroutine ppm_limit_cw84 (h_in, h_l, h_r, iis, iie, jis, jie)
real function ratio_max (a, b, maxrat)
Private Attributes
integer id_clock_update
integer id_clock_correct
Detailed Description
Definition at line 1 of file MOM_continuity_PPM.F90.
Member Function/Subroutine Documentation
subroutine, public mom_continuity_ppm::continuity_ppm (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) hin, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_,nkmem_), intent(out) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(out) vh, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, real, dimension(nimemb_,njmem_), intent(in), optional uhbt, real, dimension(nimem_,njmemb_), intent(in), optional vhbt, type(ocean_obc_type), optional, pointer OBC, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional visc_rem_u, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional visc_rem_v, real, dimension(nimemb_,njmem_,nkmem_), intent(out), optional u_cor, real, dimension(nimem_,njmemb_,nkmem_), intent(out), optional v_cor, real, dimension(nimemb_,njmem_), intent(in), optional uhbt_aux, real, dimension(nimem_,njmemb_), intent(in), optional vhbt_aux, real, dimension(nimemb_,njmem_,nkmem_), intent(out), optional u_cor_aux, real, dimension(nimem_,njmemb_,nkmem_), intent(out), optional v_cor_aux, type(bt_cont_type), optional, pointer BT_cont)
Definition at line 102 of file MOM_continuity_PPM.F90.
References meridional_mass_flux(), mom_error_handler::mom_error(), and zonal_mass_flux().
Referenced by mom_continuity::continuity().
subroutine, public mom_continuity_ppm::continuity_ppm_end (type(continuity_ppm_cs), pointer CS)
Definition at line 2147 of file MOM_continuity_PPM.F90.
Referenced by mom_continuity::continuity_end().
subroutine, public mom_continuity_ppm::continuity_ppm_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(continuity_ppm_cs), pointer CS)
Definition at line 2053 of file MOM_continuity_PPM.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_continuity::continuity_init().
subroutine mom_continuity_ppm::merid_face_thickness (real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) h_v, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(loop_bounds_type), intent(in) LB, logical, intent(in) vol_CFL, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional visc_rem_v) private
Definition at line 1386 of file MOM_continuity_PPM.F90.
Referenced by meridional_mass_flux().
subroutine mom_continuity_ppm::merid_flux_layer (real, dimension(nimem_), intent(in) v, real, dimension(nimem_,njmem_), intent(in) h, real, dimension(nimem_,njmem_), intent(in) hL, real, dimension(nimem_,njmem_), intent(in) hR, real, dimension(nimem_), intent(inout) vh, real, dimension(nimem_), intent(inout) dvhdv, real, dimension(nimem_), intent(in) visc_rem, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, integer, intent(in) J, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimem_), intent(in) do_i, logical, intent(in) vol_CFL) private
Definition at line 1325 of file MOM_continuity_PPM.F90.
Referenced by meridional_flux_adjust(), meridional_mass_flux(), and set_merid_bt_cont().
subroutine mom_continuity_ppm::meridional_flux_adjust (real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, real, dimension(nimem_), intent(in) vhbt, real, dimension(nimem_), intent(in) vh_tot_0, real, dimension(nimem_), intent(in) dvhdv_tot_0, real, dimension(nimem_), intent(out) dv, real, dimension(nimem_), intent(in) dv_max_CFL, real, dimension(nimem_), intent(in) dv_min_CFL, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, real, dimension(nimem_,nkmem_), intent(in) visc_rem, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimem_), intent(in) do_i_in, logical, intent(in), optional full_precision, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), optional vh_3d) private
Definition at line 1451 of file MOM_continuity_PPM.F90.
References merid_flux_layer().
Referenced by meridional_mass_flux(), and set_merid_bt_cont().
subroutine mom_continuity_ppm::meridional_mass_flux (real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimem_,njmemb_,nkmem_), intent(out) vh, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, type(loop_bounds_type), intent(in) LB, real, dimension(nimem_,njmemb_), intent(in), optional vhbt, type(ocean_obc_type), optional, pointer OBC, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional visc_rem_v, real, dimension(nimem_,njmemb_,nkmem_), intent(out), optional v_cor, real, dimension(nimem_,njmemb_), intent(in), optional vhbt_aux, real, dimension(nimem_,njmemb_,nkmem_), intent(out), optional v_cor_aux, type(bt_cont_type), optional, pointer BT_cont) private
Definition at line 1053 of file MOM_continuity_PPM.F90.
References merid_face_thickness(), merid_flux_layer(), meridional_flux_adjust(), ppm_reconstruction_y(), ratio_max(), and set_merid_bt_cont().
Referenced by continuity_ppm().
subroutine mom_continuity_ppm::ppm_limit_cw84 (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(inout) h_l, real, dimension(nimem_,njmem_), intent(inout) h_r, integer, intent(in) iis, integer, intent(in) iie, integer, intent(in) jis, integer, intent(in) jie) private
Definition at line 2007 of file MOM_continuity_PPM.F90.
Referenced by ppm_reconstruction_x(), and ppm_reconstruction_y().
subroutine mom_continuity_ppm::ppm_limit_pos (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(inout) h_L, real, dimension(nimem_,njmem_), intent(inout) h_R, real, intent(in) h_min, integer, intent(in) iis, integer, intent(in) iie, integer, intent(in) jis, integer, intent(in) jie) private
Definition at line 1964 of file MOM_continuity_PPM.F90.
Referenced by ppm_reconstruction_x(), mom_internal_tides::ppm_reconstruction_x(), mom_internal_tides::ppm_reconstruction_y(), and ppm_reconstruction_y().
subroutine mom_continuity_ppm::ppm_reconstruction_x (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(out) h_l, real, dimension(nimem_,njmem_), intent(out) h_r, type(ocean_grid_type), intent(in) G, type(loop_bounds_type), intent(in) LB, real, intent(in) h_min, logical, intent(in), optional monotonic, logical, intent(in), optional simple_2nd) private
Definition at line 1780 of file MOM_continuity_PPM.F90.
References mom_error_handler::mom_error(), ppm_limit_cw84(), and ppm_limit_pos().
Referenced by mom_internal_tides::propagate_x(), and zonal_mass_flux().
subroutine mom_continuity_ppm::ppm_reconstruction_y (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(out) h_l, real, dimension(nimem_,njmem_), intent(out) h_r, type(ocean_grid_type), intent(in) G, type(loop_bounds_type), intent(in) LB, real, intent(in) h_min, logical, intent(in), optional monotonic, logical, intent(in), optional simple_2nd) private
Definition at line 1873 of file MOM_continuity_PPM.F90.
References mom_error_handler::mom_error(), ppm_limit_cw84(), and ppm_limit_pos().
Referenced by meridional_mass_flux(), and mom_internal_tides::propagate_y().
real function mom_continuity_ppm::ratio_max (real, intent(in) a, real, intent(in) b, real, intent(in) maxrat) private
Definition at line 2042 of file MOM_continuity_PPM.F90.
Referenced by meridional_mass_flux(), and zonal_mass_flux().
subroutine mom_continuity_ppm::set_merid_bt_cont (real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, type(bt_cont_type), intent(inout) BT_cont, real, dimension(nimem_), intent(in) vh_tot_0, real, dimension(nimem_), intent(in) dvhdv_tot_0, real, dimension(nimem_), intent(in) dv_max_CFL, real, dimension(nimem_), intent(in) dv_min_CFL, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, real, dimension(nimem_,nkmem_), intent(in) visc_rem, real, dimension(nimem_), intent(in) visc_rem_max, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimem_), intent(in) do_i) private
Definition at line 1613 of file MOM_continuity_PPM.F90.
References merid_flux_layer(), and meridional_flux_adjust().
Referenced by meridional_mass_flux().
subroutine mom_continuity_ppm::set_zonal_bt_cont (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, type(bt_cont_type), intent(inout) BT_cont, real, dimension(nimemb_), intent(in) uh_tot_0, real, dimension(nimemb_), intent(in) duhdu_tot_0, real, dimension(nimemb_), intent(in) du_max_CFL, real, dimension(nimemb_), intent(in) du_min_CFL, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, real, dimension(nimemb_,nkmem_), intent(in) visc_rem, real, dimension(nimemb_), intent(in) visc_rem_max, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimemb_), intent(in) do_i) private
Definition at line 883 of file MOM_continuity_PPM.F90.
References zonal_flux_adjust(), and zonal_flux_layer().
Referenced by zonal_mass_flux().
subroutine mom_continuity_ppm::zonal_face_thickness (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) h_u, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(loop_bounds_type), intent(in) LB, logical, intent(in) vol_CFL, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional visc_rem_u) private
Definition at line 655 of file MOM_continuity_PPM.F90.
Referenced by zonal_mass_flux().
subroutine mom_continuity_ppm::zonal_flux_adjust (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) hL, real, dimension(nimem_,njmem_,nkmem_), intent(in) hR, real, dimension(nimemb_), intent(in) uhbt, real, dimension(nimemb_), intent(in) uh_tot_0, real, dimension(nimemb_), intent(in) duhdu_tot_0, real, dimension(nimemb_), intent(out) du, real, dimension(nimemb_), intent(in) du_max_CFL, real, dimension(nimemb_), intent(in) du_min_CFL, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, real, dimension(nimemb_,nkmem_), intent(in) visc_rem, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimemb_), intent(in) do_i_in, logical, intent(in), optional full_precision, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), optional uh_3d) private
Definition at line 719 of file MOM_continuity_PPM.F90.
References zonal_flux_layer().
Referenced by set_zonal_bt_cont(), and zonal_mass_flux().
subroutine mom_continuity_ppm::zonal_flux_layer (real, dimension(nimemb_), intent(in) u, real, dimension(nimem_), intent(in) h, real, dimension(nimem_), intent(in) hL, real, dimension(nimem_), intent(in) hR, real, dimension(nimemb_), intent(inout) uh, real, dimension(nimemb_), intent(inout) duhdu, real, dimension(nimemb_), intent(in) visc_rem, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, dimension(nimemb_), intent(in) do_i, logical, intent(in) vol_CFL) private
Definition at line 595 of file MOM_continuity_PPM.F90.
Referenced by set_zonal_bt_cont(), zonal_flux_adjust(), and zonal_mass_flux().
subroutine mom_continuity_ppm::zonal_mass_flux (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_in, real, dimension(nimemb_,njmem_,nkmem_), intent(out) uh, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_ppm_cs), pointer CS, type(loop_bounds_type), intent(in) LB, real, dimension(nimemb_,njmem_), intent(in), optional uhbt, type(ocean_obc_type), optional, pointer OBC, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional visc_rem_u, real, dimension(nimemb_,njmem_,nkmem_), intent(out), optional u_cor, real, dimension(nimemb_,njmem_), intent(in), optional uhbt_aux, real, dimension(nimemb_,njmem_,nkmem_), intent(out), optional u_cor_aux, type(bt_cont_type), optional, pointer BT_cont) private
Definition at line 317 of file MOM_continuity_PPM.F90.
References ppm_reconstruction_x(), ratio_max(), set_zonal_bt_cont(), zonal_face_thickness(), zonal_flux_adjust(), and zonal_flux_layer().
Referenced by continuity_ppm().
Member Data Documentation
integer mom_continuity_ppm::id_clock_correct private
Definition at line 60 of file MOM_continuity_PPM.F90.
integer mom_continuity_ppm::id_clock_update private
Definition at line 60 of file MOM_continuity_PPM.F90.
The documentation for this module was generated from the following file:
src/core/MOM_continuity_PPM.F90