MOM6: pqm_functions Module Reference
pqm_functions Module Reference
Public Member Functions
subroutine, public pqm_reconstruction (N, h, u, ppoly)
subroutine, public pqm_boundary_extrapolation (N, h, u, ppoly)
subroutine, public pqm_boundary_extrapolation_v1 (N, h, u, ppoly)
Private Member Functions
subroutine pqm_limiter (N, h, u, ppoly)
Detailed Description
Definition at line 1 of file PQM_functions.F90.
Member Function/Subroutine Documentation
subroutine, public pqm_functions::pqm_boundary_extrapolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 359 of file PQM_functions.F90.
subroutine, public pqm_functions::pqm_boundary_extrapolation_v1 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 517 of file PQM_functions.F90.
Referenced by mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine pqm_functions::pqm_limiter (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly) private
Definition at line 85 of file PQM_functions.F90.
References regrid_edge_values::bound_edge_values(), and regrid_edge_values::check_discontinuous_edge_values().
Referenced by pqm_reconstruction().
subroutine, public pqm_functions::pqm_reconstruction (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 25 of file PQM_functions.F90.
References pqm_limiter().
Referenced by mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
The documentation for this module was generated from the following file:
src/ALE/PQM_functions.F90