MOM6: mom_checksum_packages Module Reference
mom_checksum_packages Module Reference
Data Types
interface mom_state_chksum
type stats
Public Member Functions
subroutine, public mom_thermo_chksum (mesg, tv, G, haloshift)
subroutine, public mom_accel_chksum (mesg, CAu, CAv, PFu, PFv, diffu, diffv, G, pbce, u_accel_bt, v_accel_bt)
subroutine, public mom_state_stats (mesg, u, v, h, Temp, Salt, G, allowChange, permitDiminishing)
Private Member Functions
subroutine mom_state_chksum_5arg (mesg, u, v, h, uh, vh, G, haloshift)
subroutine mom_state_chksum_3arg (mesg, u, v, h, G, haloshift)
Detailed Description
Definition at line 1 of file MOM_checksum_packages.F90.
Member Function/Subroutine Documentation
subroutine, public mom_checksum_packages::mom_accel_chksum (character(len=*), intent(in) mesg, real, dimension(nimemb_,njmem_,nkmem_), intent(in) CAu, real, dimension(nimem_,njmemb_,nkmem_), intent(in) CAv, real, dimension(nimemb_,njmem_,nkmem_), intent(in) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(in) PFv, real, dimension(nimemb_,njmem_,nkmem_), intent(in) diffu, real, dimension(nimem_,njmemb_,nkmem_), intent(in) diffv, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional pbce, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional u_accel_bt, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional v_accel_bt)
Definition at line 140 of file MOM_checksum_packages.F90.
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine mom_checksum_packages::mom_state_chksum_3arg (character(len=*), intent(in) mesg, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 87 of file MOM_checksum_packages.F90.
subroutine mom_checksum_packages::mom_state_chksum_5arg (character(len=*), intent(in) mesg, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_,nkmem_), intent(in) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vh, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 54 of file MOM_checksum_packages.F90.
subroutine, public mom_checksum_packages::mom_state_stats (character(len=*), intent(in) mesg, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) Temp, real, dimension(nimem_,njmem_,nkmem_), intent(in) Salt, type(ocean_grid_type), intent(in) G, logical, intent(in), optional allowChange, logical, intent(in), optional permitDiminishing)
Definition at line 197 of file MOM_checksum_packages.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_mesg().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_checksum_packages::mom_thermo_chksum (character(len=*), intent(in) mesg, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift)
Definition at line 116 of file MOM_checksum_packages.F90.
Referenced by mom::step_mom().
The documentation for this module was generated from the following file:
src/core/MOM_checksum_packages.F90