MOM6: mom_forcing_type Module Reference
mom_forcing_type Module Reference
Data Types
type forcing
type optics_type
Public Member Functions
subroutine, public extractfluxes1d (G, fluxes, optics, nsw, j, dt, DepthBeforeScalingFluxes, useRiverHeatContent, useCalvingHeatContent, h, T, Net_H, Net_heat, Net_salt, Pen_SW_bnd, tv)
subroutine, public extractfluxes2d (G, fluxes, optics, nsw, dt, DepthBeforeScalingFluxes, useRiverHeatContent, useCalvingHeatContent, h, T, Net_H, Net_heat, Net_salt, Pen_SW_bnd, tv)
subroutine, public calculatebuoyancyflux1d (G, fluxes, optics, h, Temp, Salt, tv, j, buoyancyFlux, netHeatMinusSW, netSalt)
subroutine, public calculatebuoyancyflux2d (G, fluxes, optics, h, Temp, Salt, tv, buoyancyFlux, netHeatMinusSW, netSalt)
subroutine, public absorbremainingsw (G, h, eps, htot, opacity_band, nsw, j, dt, H_limit_fluxes, correctAbsorption, absorbAllSW, ksort, T, Ttot, Pen_SW_bnd)
subroutine, public mom_forcing_chksum (mesg, fluxes, G, haloshift)
subroutine, public forcing_singlepointprint (fluxes, G, i, j, mesg)
Private Member Functions
subroutine sumswoverbands (G, h, eps, htot, opacity_band, nsw, j, dt, H_limit_fluxes, correctAbsorption, absorbAllSW, ksort, iPen_SW_bnd, netPen)
Private Attributes
integer num_msg = 0
integer max_msg = 2
Detailed Description
Definition at line 1 of file MOM_forcing_type.F90.
Member Function/Subroutine Documentation
subroutine, public mom_forcing_type::absorbremainingsw (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,nkmem_), intent(in) h, real, dimension(nimem_,nkmem_), intent(in) eps, real, dimension(nimem_), intent(in) htot, real, dimension(:,:,:), intent(in) opacity_band, integer, intent(in) nsw, integer, intent(in) j, real, intent(in) dt, real, intent(in) H_limit_fluxes, logical, intent(in) correctAbsorption, logical, intent(in) absorbAllSW, integer, dimension(nimem_,nkmem_), intent(in) ksort, real, dimension(nimem_,nkmem_), intent(inout) T, real, dimension(nimem_), intent(inout) Ttot, real, dimension(:,:), intent(inout) Pen_SW_bnd)
Definition at line 473 of file MOM_forcing_type.F90.
Referenced by mom_diabatic_driver::applyboundaryfluxes(), and mom_bulk_mixed_layer::bulkmixedlayer().
subroutine, public mom_forcing_type::calculatebuoyancyflux1d (type(ocean_grid_type), intent(in) G, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) Temp, real, dimension(nimem_,njmem_,nkmem_), intent(in) Salt, type(thermo_var_ptrs), intent(inout) tv, integer, intent(in) j, real, dimension(nimem_,nk_interface_), intent(inout) buoyancyFlux, real, dimension(nimem_), intent(inout) netHeatMinusSW, real, dimension(nimem_), intent(inout) netSalt)
Definition at line 362 of file MOM_forcing_type.F90.
References mom_eos::calculate_density_derivs(), extractfluxes1d(), and sumswoverbands().
Referenced by calculatebuoyancyflux2d().
subroutine, public mom_forcing_type::calculatebuoyancyflux2d (type(ocean_grid_type), intent(in) G, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) Temp, real, dimension(nimem_,njmem_,nkmem_), intent(in) Salt, type(thermo_var_ptrs), intent(inout) tv, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) buoyancyFlux, real, dimension(nimem_,njmem_), intent(inout), optional netHeatMinusSW, real, dimension(nimem_,njmem_), intent(inout), optional netSalt)
Definition at line 442 of file MOM_forcing_type.F90.
References calculatebuoyancyflux1d().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_forcing_type::extractfluxes1d (type(ocean_grid_type), intent(in) G, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, integer, intent(in) nsw, integer, intent(in) j, real, intent(in) dt, real, intent(in) DepthBeforeScalingFluxes, logical, intent(in) useRiverHeatContent, logical, intent(in) useCalvingHeatContent, real, dimension(nimem_,nkmem_), intent(in) h, real, dimension(nimem_,nkmem_), intent(in) T, real, dimension(nimem_), intent(out) Net_H, real, dimension(nimem_), intent(out) Net_heat, real, dimension(nimem_), intent(out) Net_salt, real, dimension(:,:), intent(out) Pen_SW_bnd, type(thermo_var_ptrs), intent(inout) tv)
Definition at line 142 of file MOM_forcing_type.F90.
References mom_error_handler::mom_error().
Referenced by mom_diabatic_driver::applyboundaryfluxes(), mom_bulk_mixed_layer::bulkmixedlayer(), calculatebuoyancyflux1d(), and extractfluxes2d().
subroutine, public mom_forcing_type::extractfluxes2d (type(ocean_grid_type), intent(in) G, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, integer, intent(in) nsw, real, intent(in) dt, real, intent(in) DepthBeforeScalingFluxes, logical, intent(in) useRiverHeatContent, logical, intent(in) useCalvingHeatContent, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(out) Net_H, real, dimension(nimem_,njmem_), intent(out) Net_heat, real, dimension(nimem_,njmem_), intent(out) Net_salt, real, dimension(:,:,:), intent(out) Pen_SW_bnd, type(thermo_var_ptrs), intent(inout) tv)
Definition at line 311 of file MOM_forcing_type.F90.
References extractfluxes1d().
subroutine, public mom_forcing_type::forcing_singlepointprint (type(forcing), intent(in) fluxes, type(ocean_grid_type), intent(in) G, integer, intent(in) i, integer, intent(in) j, character(len=*), intent(in) mesg)
Definition at line 887 of file MOM_forcing_type.F90.
References locmsg().
Referenced by mom_diabatic_driver::applyboundaryfluxes().
subroutine, public mom_forcing_type::mom_forcing_chksum (character(len=*), intent(in) mesg, type(forcing), intent(in) fluxes, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift)
Definition at line 816 of file MOM_forcing_type.F90.
Referenced by mom_diabatic_driver::diabatic().
subroutine mom_forcing_type::sumswoverbands (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,nkmem_), intent(in) h, real, dimension(nimem_,nkmem_), intent(in) eps, real, dimension(nimem_), intent(in) htot, real, dimension(:,:,:), intent(in) opacity_band, integer, intent(in) nsw, integer, intent(in) j, real, intent(in) dt, real, intent(in) H_limit_fluxes, logical, intent(in) correctAbsorption, logical, intent(in) absorbAllSW, integer, dimension(nimem_,nkmem_), intent(in) ksort, real, dimension(:,:), intent(in) iPen_SW_bnd, real, dimension(nimem_,nk_interface_), intent(inout) netPen) private
Definition at line 659 of file MOM_forcing_type.F90.
Referenced by calculatebuoyancyflux1d().
Member Data Documentation
integer mom_forcing_type::max_msg = 2 private
Definition at line 44 of file MOM_forcing_type.F90.
integer mom_forcing_type::num_msg = 0 private
Definition at line 44 of file MOM_forcing_type.F90.
The documentation for this module was generated from the following file:
src/core/MOM_forcing_type.F90