MOM6: mom_diffconvection Module Reference
mom_diffconvection Module Reference
Data Types
type diffconvection_cs
Public Member Functions
logical function, public diffconvection_init (paramFile, G, diag, Time, CS)
subroutine, public diffconvection_calculate (CS, G, h, Temp, Salt, EOS, Kd_int)
subroutine, public diffconvection_end (CS)
Public Attributes
logical, parameter verbose = .False.
Detailed Description
Definition at line 1 of file MOM_diffConvection.F90.
Member Function/Subroutine Documentation
subroutine, public mom_diffconvection::diffconvection_calculate (type(diffconvection_cs), pointer CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) Temp, real, dimension(nimem_,njmem_,nkmem_), intent(in) Salt, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) Kd_int)
Definition at line 98 of file MOM_diffConvection.F90.
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_diffconvection::diffconvection_end (type(diffconvection_cs), pointer CS)
Definition at line 153 of file MOM_diffConvection.F90.
Referenced by mom_diabatic_driver::diabatic_driver_end().
logical function, public mom_diffconvection::diffconvection_init (type(param_file_type), intent(in) paramFile, type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(in), target diag, type(time_type), intent(in) Time, type(diffconvection_cs), pointer CS)
Definition at line 41 of file MOM_diffConvection.F90.
References mom_file_parser::closeparameterblock(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_file_parser::openparameterblock(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
Member Data Documentation
logical, parameter mom_diffconvection::verbose = .False.
Definition at line 37 of file MOM_diffConvection.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_diffConvection.F90