MOM6: mom_geothermal Module Reference
mom_geothermal Module Reference
Data Types
type geothermal_cs
Public Member Functions
subroutine, public geothermal (h, tv, dt, ea, eb, G, CS)
subroutine, public geothermal_init (Time, G, param_file, diag, CS)
subroutine, public geothermal_end (CS)
Detailed Description
Definition at line 1 of file MOM_geothermal.F90.
Member Function/Subroutine Documentation
subroutine, public mom_geothermal::geothermal (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) eb, type(ocean_grid_type), intent(inout) G, type(geothermal_cs), pointer CS)
Definition at line 88 of file MOM_geothermal.F90.
References mom_eos::calculate_density_derivs(), and mom_error_handler::mom_error().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_geothermal::geothermal_end (type(geothermal_cs), pointer CS)
Definition at line 436 of file MOM_geothermal.F90.
subroutine, public mom_geothermal::geothermal_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(geothermal_cs), pointer CS)
Definition at line 355 of file MOM_geothermal.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_static_field(), and mom_io::slasher().
Referenced by mom_diabatic_driver::diabatic_driver_init().
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_geothermal.F90