MOM6: mom_ocmip2_co2calc_mod Module Reference
mom_ocmip2_co2calc_mod Module Reference
Data Types
type co2_dope_vector
Public Member Functions
subroutine, public mom_ocmip2_co2calc (dope_vec, mask, t_in, s_in, dic_in, pt_in, sit_in, ta_in, htotallo, htotalhi, htotal, co2star, alpha, pCO2surf, co3_ion)
Private Member Functions
real function drtsafe (k0, k1, k2, kb, k1p, k2p, k3p, ksi, kw, ks, kf, bt, dic, ft, pt, sit, st, ta, x1, x2, xacc)
subroutine ta_iter_1 (k0, k1, k2, kb, k1p, k2p, k3p, ksi, kw, ks, kf, bt, dic, ft, pt, sit, st, ta, x, fn, df)
Detailed Description
Definition at line 1 of file MOM_OCMIP2_CO2calc.F90.
Member Function/Subroutine Documentation
real function mom_ocmip2_co2calc_mod::drtsafe (real k0, real k1, real k2, real kb, real k1p, real k2p, real k3p, real ksi, real kw, real ks, real kf, real bt, real dic, real ft, real pt, real sit, real st, real ta, real x1, real x2, real xacc) private
Definition at line 402 of file MOM_OCMIP2_CO2calc.F90.
References mom_barotropic::swap(), and ta_iter_1().
Referenced by mom_ocmip2_co2calc().
subroutine, public mom_ocmip2_co2calc_mod::mom_ocmip2_co2calc (type(co2_dope_vector), intent(in) dope_vec, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) mask, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) t_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) s_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) dic_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) pt_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) sit_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) ta_in, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) htotallo, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(in) htotalhi, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(inout) htotal, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(out), optional co2star, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(out), optional alpha, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(out), optional pCO2surf, real, dimension(dope_vec%isd:dope_vec%ied,dope_vec%jsd:dope_vec%jed), intent(out), optional co3_ion)
Definition at line 118 of file MOM_OCMIP2_CO2calc.F90.
References drtsafe().
subroutine mom_ocmip2_co2calc_mod::ta_iter_1 (real k0, real k1, real k2, real kb, real k1p, real k2p, real k3p, real ksi, real kw, real ks, real kf, real bt, real dic, real ft, real pt, real sit, real st, real ta, real x, real fn, real df) private
Definition at line 500 of file MOM_OCMIP2_CO2calc.F90.
Referenced by drtsafe().
The documentation for this module was generated from the following file:
src/tracer/MOM_OCMIP2_CO2calc.F90