MOM6: plm_functions Module Reference
plm_functions Module Reference
Public Member Functions
subroutine, public plm_reconstruction (N, h, u, ppoly)
subroutine, public plm_boundary_extrapolation (N, h, u, ppoly)
Detailed Description
Definition at line 1 of file PLM_functions.F90.
Member Function/Subroutine Documentation
subroutine, public plm_functions::plm_boundary_extrapolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 165 of file PLM_functions.F90.
Referenced by mom_ale::pressure_gradient_plm(), mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine, public plm_functions::plm_reconstruction (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 24 of file PLM_functions.F90.
Referenced by mom_ale::pressure_gradient_plm(), mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
The documentation for this module was generated from the following file:
src/ALE/PLM_functions.F90