MOM6: advection_test_tracer Module Reference
advection_test_tracer Module Reference
Data Types
type advection_test_tracer_cs
type p3d
Public Member Functions
logical function, public register_advection_test_tracer (G, param_file, CS, diag, tr_Reg, restart_CS)
subroutine, public initialize_advection_test_tracer (restart, day, G, h, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public advection_test_tracer_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, CS)
subroutine, public advection_test_tracer_surface_state (state, h, G, CS)
subroutine, public advection_test_tracer_end (CS)
Private Attributes
integer, parameter ntr = 11
Detailed Description
Definition at line 1 of file advection_test_tracer.F90.
Member Function/Subroutine Documentation
subroutine, public advection_test_tracer::advection_test_tracer_column_physics (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(advection_test_tracer_cs), pointer CS)
Definition at line 354 of file advection_test_tracer.F90.
Referenced by mom_tracer_flow_control::call_tracer_column_fns().
subroutine, public advection_test_tracer::advection_test_tracer_end (type(advection_test_tracer_cs), pointer CS)
Definition at line 452 of file advection_test_tracer.F90.
Referenced by mom_tracer_flow_control::tracer_flow_control_end().
subroutine, public advection_test_tracer::advection_test_tracer_surface_state (type(surface), intent(inout) state, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(advection_test_tracer_cs), pointer CS)
Definition at line 424 of file advection_test_tracer.F90.
References coupler_util::set_coupler_values().
Referenced by mom_tracer_flow_control::call_tracer_surface_state().
subroutine, public advection_test_tracer::initialize_advection_test_tracer (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_obc_type), pointer OBC, type(advection_test_tracer_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 223 of file advection_test_tracer.F90.
References mom_tracer_registry::add_tracer_diagnostics(), mom_diag_mediator::register_diag_field(), and mom_diag_to_z::register_z_tracer().
Referenced by mom_tracer_flow_control::tracer_flow_control_init().
logical function, public advection_test_tracer::register_advection_test_tracer (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(advection_test_tracer_cs), pointer CS, type(diag_ctrl), intent(in), target diag, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Definition at line 127 of file advection_test_tracer.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_tracer_registry::register_tracer(), and mom_io::slasher().
Referenced by mom_tracer_flow_control::call_tracer_register().
Member Data Documentation
integer, parameter advection_test_tracer::ntr = 11 private
Definition at line 84 of file advection_test_tracer.F90.
The documentation for this module was generated from the following file:
src/tracer/advection_test_tracer.F90