MOM6: mom_diagnostics Module Reference
mom_diagnostics Module Reference
Data Types
type diagnostics_cs
Public Member Functions
subroutine, public calculate_diagnostic_fields (u, v, h, uh, vh, tv, ADp, CDp, dt, G, CS, eta_bt)
subroutine, public register_time_deriv (f_ptr, deriv_ptr, CS)
subroutine, public mom_diagnostics_init (MIS, ADp, CDp, Time, G, param_file, diag, CS)
subroutine, public mom_diagnostics_end (CS, ADp)
Private Member Functions
subroutine find_weights (Rlist, R_in, k, nz, wt, wt_p)
subroutine calculate_vertical_integrals (h, tv, G, CS)
subroutine calculate_energy_diagnostics (u, v, h, uh, vh, ADp, CDp, G, CS)
subroutine calculate_derivs (dt, G, CS)
subroutine set_dependent_diagnostics (MIS, ADp, CDp, G, CS)
Detailed Description
Definition at line 1 of file MOM_diagnostics.F90.
Member Function/Subroutine Documentation
subroutine mom_diagnostics::calculate_derivs (real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diagnostics_cs), pointer CS) private
Definition at line 739 of file MOM_diagnostics.F90.
Referenced by calculate_diagnostic_fields().
subroutine, public mom_diagnostics::calculate_diagnostic_fields (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_,nkmem_), intent(in) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vh, type(thermo_var_ptrs), intent(in) tv, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diagnostics_cs), pointer CS, real, dimension(nimem_,njmem_), intent(in), optional eta_bt)
Definition at line 132 of file MOM_diagnostics.F90.
References calculate_derivs(), calculate_energy_diagnostics(), calculate_vertical_integrals(), find_weights(), mom_error_handler::mom_error(), and mom_wave_speed::wave_speed().
Referenced by mom::step_mom().
subroutine mom_diagnostics::calculate_energy_diagnostics (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_,nkmem_), intent(in) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vh, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, type(ocean_grid_type), intent(inout) G, type(diagnostics_cs), pointer CS) private
Definition at line 517 of file MOM_diagnostics.F90.
Referenced by calculate_diagnostic_fields().
subroutine mom_diagnostics::calculate_vertical_integrals (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(inout) G, type(diagnostics_cs), pointer CS) private
Definition at line 423 of file MOM_diagnostics.F90.
References mom_eos::int_density_dz().
Referenced by calculate_diagnostic_fields().
subroutine mom_diagnostics::find_weights (real, dimension(:), intent(in) Rlist, real, intent(in) R_in, integer, intent(inout) k, integer, intent(in) nz, real, intent(out) wt, real, intent(out) wt_p) private
Definition at line 367 of file MOM_diagnostics.F90.
Referenced by calculate_diagnostic_fields().
subroutine, public mom_diagnostics::mom_diagnostics_end (type(diagnostics_cs), pointer CS, type(accel_diag_ptrs), intent(inout) ADp)
Definition at line 1009 of file MOM_diagnostics.F90.
subroutine, public mom_diagnostics::mom_diagnostics_init (type(ocean_internal_state), intent(in) MIS, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(diagnostics_cs), pointer CS)
Definition at line 763 of file MOM_diagnostics.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), register_time_deriv(), set_dependent_diagnostics(), and mom_wave_speed::wave_speed_init().
Referenced by mom::initialize_mom().
subroutine, public mom_diagnostics::register_time_deriv (real, dimension(:,:,:), target f_ptr, real, dimension(:,:,:), target deriv_ptr, type(diagnostics_cs), pointer CS)
Definition at line 707 of file MOM_diagnostics.F90.
References mom_error_handler::mom_error().
Referenced by mom_diagnostics_init(), and set_dependent_diagnostics().
subroutine mom_diagnostics::set_dependent_diagnostics (type(ocean_internal_state), intent(in) MIS, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, type(ocean_grid_type), intent(in) G, type(diagnostics_cs), pointer CS) private
Definition at line 946 of file MOM_diagnostics.F90.
References register_time_deriv().
Referenced by mom_diagnostics_init().
The documentation for this module was generated from the following file:
src/diagnostics/MOM_diagnostics.F90