MOM6: user_tracer_example Module Reference
user_tracer_example Module Reference
Data Types
type p3d
type user_tracer_example_cs
Public Member Functions
logical function, public user_register_tracer_example (G, param_file, CS, diag, tr_Reg, restart_CS)
subroutine, public user_initialize_tracer (restart, day, G, h, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public tracer_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, CS)
integer function, public user_tracer_stock (h, stocks, G, CS, names, units, stock_index)
subroutine, public user_tracer_surface_state (state, h, G, CS)
subroutine, public user_tracer_example_end (CS)
Private Attributes
integer, parameter ntr = 1
Detailed Description
Definition at line 1 of file tracer_example.F90.
Member Function/Subroutine Documentation
subroutine, public user_tracer_example::tracer_column_physics (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(user_tracer_example_cs), pointer CS)
Definition at line 375 of file tracer_example.F90.
Referenced by mom_tracer_flow_control::call_tracer_column_fns().
subroutine, public user_tracer_example::user_initialize_tracer (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_obc_type), pointer OBC, type(user_tracer_example_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 205 of file tracer_example.F90.
References mom_tracer_registry::add_tracer_diagnostics(), mom_tracer_registry::add_tracer_obc_values(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), mom_diag_to_z::register_z_tracer(), and mom_sponge::set_up_sponge_field().
Referenced by mom_tracer_flow_control::tracer_flow_control_init().
logical function, public user_tracer_example::user_register_tracer_example (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(user_tracer_example_cs), pointer CS, type(diag_ctrl), intent(in), target diag, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Definition at line 119 of file tracer_example.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_tracer_registry::register_tracer(), and mom_io::slasher().
Referenced by mom_tracer_flow_control::call_tracer_register().
subroutine, public user_tracer_example::user_tracer_example_end (type(user_tracer_example_cs), pointer CS)
Definition at line 585 of file tracer_example.F90.
Referenced by mom_tracer_flow_control::tracer_flow_control_end().
integer function, public user_tracer_example::user_tracer_stock (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(:), intent(out) stocks, type(ocean_grid_type), intent(in) G, type(user_tracer_example_cs), pointer CS, character(len=*), dimension(:), intent(out) names, character(len=*), dimension(:), intent(out) units, integer, intent(in), optional stock_index)
Definition at line 506 of file tracer_example.F90.
Referenced by mom_tracer_flow_control::call_tracer_stocks().
subroutine, public user_tracer_example::user_tracer_surface_state (type(surface), intent(inout) state, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(user_tracer_example_cs), pointer CS)
Definition at line 556 of file tracer_example.F90.
References coupler_util::set_coupler_values().
Referenced by mom_tracer_flow_control::call_tracer_surface_state().
Member Data Documentation
integer, parameter user_tracer_example::ntr = 1 private
Definition at line 79 of file tracer_example.F90.
The documentation for this module was generated from the following file:
src/tracer/tracer_example.F90