MOM6: mom_int_tide_input Module Reference
mom_int_tide_input Module Reference
Data Types
type int_tide_input_cs
type int_tide_input_type
Public Member Functions
subroutine, public set_int_tide_input (u, v, h, tv, fluxes, itide, dt, G, CS)
subroutine, public int_tide_input_init (Time, G, param_file, diag, CS, itide)
subroutine, public int_tide_input_end (CS)
Private Member Functions
subroutine find_n2_bottom (h, tv, T_f, S_f, h2, fluxes, G, N2_bot)
Detailed Description
Definition at line 1 of file MOM_internal_tide_input.F90.
Member Function/Subroutine Documentation
subroutine mom_int_tide_input::find_n2_bottom (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_,nkmem_), intent(in) T_f, real, dimension(nimem_,njmem_,nkmem_), intent(in) S_f, real, dimension(nimem_,njmem_), intent(in) h2, type(forcing), intent(in) fluxes, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(out) N2_bot) private
Definition at line 163 of file MOM_internal_tide_input.F90.
References mom_eos::calculate_density_derivs().
Referenced by set_int_tide_input().
subroutine, public mom_int_tide_input::int_tide_input_end (type(int_tide_input_cs), pointer CS)
Definition at line 399 of file MOM_internal_tide_input.F90.
subroutine, public mom_int_tide_input::int_tide_input_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(int_tide_input_cs), pointer CS, type(int_tide_input_type), pointer itide)
Definition at line 266 of file MOM_internal_tide_input.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), and mom_io::slasher().
Referenced by mom_diabatic_driver::diabatic_driver_init().
subroutine, public mom_int_tide_input::set_int_tide_input (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(forcing), intent(in) fluxes, type(int_tide_input_type), intent(inout) itide, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(int_tide_input_cs), pointer CS)
Definition at line 92 of file MOM_internal_tide_input.F90.
References find_n2_bottom(), mom_error_handler::mom_error(), and mom_thickness_diffuse::vert_fill_ts().
Referenced by mom_diabatic_driver::diabatic().
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_internal_tide_input.F90