MOM6: mom_spatial_means Module Reference
mom_spatial_means Module Reference
Public Member Functions
subroutine, public global_i_mean (array, i_mean, G, mask)
subroutine, public global_j_mean (array, j_mean, G, mask)
Detailed Description
Definition at line 1 of file MOM_spatial_means.F90.
Member Function/Subroutine Documentation
subroutine, public mom_spatial_means::global_i_mean (real, dimension(nimem_,njmem_), intent(in) array, real, dimension(njmem_), intent(out) i_mean, type(ocean_grid_type), intent(inout) G, real, dimension(nimem_,njmem_), intent(in), optional mask)
Definition at line 38 of file MOM_spatial_means.F90.
References mom_coms::efp_list_sum_across_pes(), mom_coms::efp_to_real(), mom_error_handler::mom_error(), mom_coms::query_efp_overflow_error(), mom_coms::real_to_efp(), and mom_coms::reset_efp_overflow_error().
Referenced by mom_sponge::apply_sponge().
subroutine, public mom_spatial_means::global_j_mean (real, dimension(nimem_,njmem_), intent(in) array, real, dimension(nimem_), intent(out) j_mean, type(ocean_grid_type), intent(inout) G, real, dimension(nimem_,njmem_), intent(in), optional mask)
Definition at line 116 of file MOM_spatial_means.F90.
References mom_coms::efp_list_sum_across_pes(), mom_coms::efp_to_real(), mom_error_handler::mom_error(), mom_coms::query_efp_overflow_error(), mom_coms::real_to_efp(), and mom_coms::reset_efp_overflow_error().
The documentation for this module was generated from the following file:
src/framework/MOM_spatial_means.F90