MOM6: mom_dynamics_legacy_split Module Reference
mom_dynamics_legacy_split Module Reference
Data Types
type mom_dyn_legacy_split_cs
Public Member Functions
subroutine, public step_mom_dyn_legacy_split (u, v, h, tv, visc, Time_local, dt, fluxes, p_surf_begin, p_surf_end, dt_since_flux, dt_therm, uh, vh, uhtr, vhtr, eta_av, G, CS, calc_dtbt, VarMix, MEKE)
subroutine, public adjustments_dyn_legacy_split (u, v, h, dt, G, CS)
subroutine, public register_restarts_dyn_legacy_split (G, param_file, CS, restart_CS, uh, vh)
subroutine, public initialize_dyn_legacy_split (u, v, h, uh, vh, eta, Time, G, param_file, diag, CS, restart_CS, dt, Accel_diag, Cont_diag, MIS, VarMix, MEKE, OBC, ALE_CSp, visc, dirs, ntrunc)
subroutine, public end_dyn_legacy_split (CS)
Public Attributes
integer id_clock_cor
Private Attributes
integer id_clock_pres
integer id_clock_vertvisc
integer id_clock_horvisc
integer id_clock_mom_update
integer id_clock_continuity
integer id_clock_thick_diff
integer id_clock_btstep
integer id_clock_btcalc
integer id_clock_btforce
integer id_clock_pass
integer id_clock_pass_init
Detailed Description
Definition at line 1 of file MOM_dynamics_legacy_split.F90.
Member Function/Subroutine Documentation
subroutine, public mom_dynamics_legacy_split::adjustments_dyn_legacy_split (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(mom_dyn_legacy_split_cs), pointer CS)
Definition at line 1043 of file MOM_dynamics_legacy_split.F90.
References mom_continuity::continuity().
Referenced by mom::step_mom().
subroutine, public mom_dynamics_legacy_split::end_dyn_legacy_split (type(mom_dyn_legacy_split_cs), pointer CS)
Definition at line 1483 of file MOM_dynamics_legacy_split.F90.
References mom_variables::dealloc_bt_cont_type().
Referenced by mom::mom_end().
subroutine, public mom_dynamics_legacy_split::initialize_dyn_legacy_split (real, dimension(nimemb_,njmem_,nkmem_), intent(inout) u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) v, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), target uh, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), target vh, real, dimension(nimem_,njmem_), intent(inout) eta, type(time_type), intent(in), target Time, type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(mom_dyn_legacy_split_cs), pointer CS, type(mom_restart_cs), pointer restart_CS, real, intent(in) dt, type(accel_diag_ptrs), intent(inout), target Accel_diag, type(cont_diag_ptrs), intent(inout), target Cont_diag, type(ocean_internal_state), intent(inout) MIS, type(varmix_cs), pointer VarMix, type(meke_type), pointer MEKE, type(ocean_obc_type), pointer OBC, type(ale_cs), pointer ALE_CSp, type(vertvisc_type), intent(inout) visc, type(directories), intent(in) dirs, integer, intent(inout), target ntrunc)
Definition at line 1193 of file MOM_dynamics_legacy_split.F90.
References mom_diabatic_driver::adiabatic(), mom_continuity::continuity(), mom_continuity::continuity_init(), mom_coriolisadv::coriolisadv_init(), mom_grid::get_flux_units(), mom_hor_visc::hor_visc_init(), mom_hor_visc::horizontal_viscosity(), mom_legacy_barotropic::legacy_barotropic_init(), mom_error_handler::mom_error(), mom_open_boundary::open_boundary_init(), mom_pressureforce::pressureforce_init(), mom_diag_mediator::register_diag_field(), mom_set_visc::set_visc_init(), mom_tidal_forcing::tidal_forcing_init(), and mom_vert_friction::vertvisc_init().
Referenced by mom::initialize_mom().
subroutine, public mom_dynamics_legacy_split::register_restarts_dyn_legacy_split (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(mom_dyn_legacy_split_cs), pointer CS, type(mom_restart_cs), pointer restart_CS, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), target uh, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), target vh)
Definition at line 1088 of file MOM_dynamics_legacy_split.F90.
References mom_diabatic_driver::adiabatic(), mom_grid::get_flux_units(), mom_grid::get_thickness_units(), mom_error_handler::mom_error(), and mom_legacy_barotropic::register_legacy_barotropic_restarts().
Referenced by mom::initialize_mom().
subroutine, public mom_dynamics_legacy_split::step_mom_dyn_legacy_split (real, dimension(nimemb_,njmem_,nkmem_), intent(inout), target u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), target v, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(in) tv, type(vertvisc_type), intent(inout) visc, type(time_type), intent(in) Time_local, real, intent(in) dt, type(forcing), intent(in) fluxes, real, dimension(:,:), pointer p_surf_begin, real, dimension(:,:), pointer p_surf_end, real, intent(in) dt_since_flux, real, intent(in) dt_therm, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), target uh, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), target vh, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) uhtr, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) vhtr, real, dimension(nimem_,njmem_), intent(out) eta_av, type(ocean_grid_type), intent(inout) G, type(mom_dyn_legacy_split_cs), pointer CS, logical, intent(in) calc_dtbt, type(varmix_cs), pointer VarMix, type(meke_type), pointer MEKE)
Definition at line 268 of file MOM_dynamics_legacy_split.F90.
References mom_continuity::continuity(), mom_coriolisadv::coradcalc(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom_hor_visc::horizontal_viscosity(), mom_legacy_barotropic::legacy_bt_mass_source(), mom_legacy_barotropic::legacy_btcalc(), mom_legacy_barotropic::legacy_btstep(), mom_legacy_barotropic::legacy_set_dtbt(), mom_checksum_packages::mom_accel_chksum(), mom_pressureforce::pressureforce(), mom_open_boundary::radiation_open_bdry_conds(), mom_set_visc::set_viscous_bbl(), mom_set_visc::set_viscous_ml(), mom_vert_friction::vertvisc(), mom_vert_friction::vertvisc_coef(), mom_vert_friction::vertvisc_limit_vel(), and mom_vert_friction::vertvisc_remnant().
Referenced by mom::step_mom().
Member Data Documentation
integer mom_dynamics_legacy_split::id_clock_btcalc private
Definition at line 261 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_btforce private
Definition at line 261 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_btstep private
Definition at line 261 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_continuity private
Definition at line 260 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_cor
Definition at line 258 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_horvisc private
Definition at line 259 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_mom_update private
Definition at line 259 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_pass private
Definition at line 262 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_pass_init private
Definition at line 262 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_pres private
Definition at line 258 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_thick_diff private
Definition at line 260 of file MOM_dynamics_legacy_split.F90.
integer mom_dynamics_legacy_split::id_clock_vertvisc private
Definition at line 258 of file MOM_dynamics_legacy_split.F90.
The documentation for this module was generated from the following file:
src/core/MOM_dynamics_legacy_split.F90