MOM6: mom_verticalgrid Module Reference
mom_verticalgrid Module Reference
Data Types
type verticalgrid_type
Public Member Functions
subroutine, public verticalgridinit (param_file, GV)
subroutine, public setverticalgridaxes (Rlay, GV)
subroutine, public verticalgridend (GV)
Detailed Description
Definition at line 1 of file MOM_verticalGrid.F90.
Member Function/Subroutine Documentation
subroutine, public mom_verticalgrid::setverticalgridaxes (real, dimension(gv%ke), intent(in) Rlay, type(verticalgrid_type), pointer GV)
Definition at line 153 of file MOM_verticalGrid.F90.
Referenced by mom_initialization::mom_initialize().
subroutine, public mom_verticalgrid::verticalgridend (type(verticalgrid_type), pointer GV)
Definition at line 172 of file MOM_verticalGrid.F90.
Referenced by mom_grid::mom_grid_end().
subroutine, public mom_verticalgrid::verticalgridinit (type(param_file_type), intent(in) param_file, type(verticalgrid_type), pointer GV)
Definition at line 80 of file MOM_verticalGrid.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_grid::mom_grid_init().
The documentation for this module was generated from the following file:
src/core/MOM_verticalGrid.F90