MOM6: mom_write_cputime Module Reference
mom_write_cputime Module Reference
Data Types
type write_cputime_cs
Public Member Functions
subroutine, public write_cputime_start_clock (CS)
subroutine, public mom_write_cputime_init (param_file, directory, Input_start_time, CS)
subroutine, public write_cputime (day, n, nmax, CS)
Private Attributes
integer clocks_per_sec = 1000
integer max_ticks = 1000
Detailed Description
Definition at line 1 of file MOM_write_cputime.F90.
Member Function/Subroutine Documentation
subroutine, public mom_write_cputime::mom_write_cputime_init (type(param_file_type), intent(in) param_file, character(len=*), intent(in) directory, type(time_type), intent(in) Input_start_time, type(write_cputime_cs), pointer CS)
Definition at line 80 of file MOM_write_cputime.F90.
References mom_file_parser::log_version().
Referenced by mom_main(), and shelf_main().
subroutine, public mom_write_cputime::write_cputime (type(time_type), intent(inout) day, integer, intent(in) n, integer, intent(inout) nmax, type(write_cputime_cs), pointer CS)
Definition at line 123 of file MOM_write_cputime.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by mom_main(), and shelf_main().
subroutine, public mom_write_cputime::write_cputime_start_clock (type(write_cputime_cs), pointer CS)
Definition at line 69 of file MOM_write_cputime.F90.
Referenced by mom_main(), and shelf_main().
Member Data Documentation
integer mom_write_cputime::clocks_per_sec = 1000 private
Definition at line 46 of file MOM_write_cputime.F90.
integer mom_write_cputime::max_ticks = 1000 private
Definition at line 47 of file MOM_write_cputime.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_write_cputime.F90