MOM6: mom_domains Module Reference
mom_domains Module Reference
Data Types
interface clone_mom_domain
interface fill_symmetric_edges
type mom_domain_type
interface pass_var
interface pass_var_complete
interface pass_var_start
interface pass_vector
interface pass_vector_complete
interface pass_vector_start
Public Member Functions
subroutine, public mom_domains_init (MOM_dom, param_file, symmetric, static_memory, NIHALO, NJHALO, NIGLOBAL, NJGLOBAL, NIPROC, NJPROC, min_halo, domain_name, include_name)
subroutine, public get_domain_extent (Domain, isc, iec, jsc, jec, isd, ied, jsd, jed, isg, ieg, jsg, jeg, idg_offset, jdg_offset, symmetric, local_indexing)
Public Attributes
integer, parameter, public to_all = To_East + To_West + To_North + To_South
Private Member Functions
subroutine pass_var_3d (array, MOM_dom, sideflag, complete, position)
subroutine pass_var_2d (array, MOM_dom, sideflag, complete, position)
integer function pass_var_start_2d (array, MOM_dom, sideflag, position, complete)
integer function pass_var_start_3d (array, MOM_dom, sideflag, position, complete)
subroutine pass_var_complete_2d (id_update, array, MOM_dom, sideflag, position)
subroutine pass_var_complete_3d (id_update, array, MOM_dom, sideflag, position)
subroutine pass_vector_2d (u_cmpt, v_cmpt, MOM_dom, direction, stagger, complete)
subroutine fill_vector_symmetric_edges_2d (u_cmpt, v_cmpt, MOM_dom, stagger, scalar)
subroutine pass_vector_3d (u_cmpt, v_cmpt, MOM_dom, direction, stagger, complete)
integer function pass_vector_start_2d (u_cmpt, v_cmpt, MOM_dom, direction, stagger, complete)
integer function pass_vector_start_3d (u_cmpt, v_cmpt, MOM_dom, direction, stagger, complete)
subroutine pass_vector_complete_2d (id_update, u_cmpt, v_cmpt, MOM_dom, direction, stagger)
subroutine pass_vector_complete_3d (id_update, u_cmpt, v_cmpt, MOM_dom, direction, stagger)
subroutine clone_md_to_md (MD_in, MOM_dom, min_halo, halo_size, symmetric, domain_name)
subroutine clone_md_to_d2d (MD_in, mpp_domain, min_halo, halo_size, symmetric, domain_name)
Detailed Description
Definition at line 1 of file MOM_domains.F90.
Member Function/Subroutine Documentation
subroutine mom_domains::clone_md_to_d2d (type(mom_domain_type), intent(in) MD_in, type(domain2d), intent(inout) mpp_domain, integer, dimension(2), intent(inout), optional min_halo, integer, intent(in), optional halo_size, logical, intent(in), optional symmetric, character(len=*), intent(in), optional domain_name) private
Definition at line 1087 of file MOM_domains.F90.
References mom_error_handler::mom_error().
subroutine mom_domains::clone_md_to_md (type(mom_domain_type), intent(in) MD_in, type(mom_domain_type), pointer MOM_dom, integer, dimension(2), intent(inout), optional min_halo, integer, intent(in), optional halo_size, logical, intent(in), optional symmetric, character(len=*), intent(in), optional domain_name) private
Definition at line 1007 of file MOM_domains.F90.
References mom_error_handler::mom_error().
subroutine mom_domains::fill_vector_symmetric_edges_2d (real, dimension(:,:), intent(inout) u_cmpt, real, dimension(:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional stagger, logical, intent(in), optional scalar) private
Definition at line 347 of file MOM_domains.F90.
subroutine, public mom_domains::get_domain_extent (type(mom_domain_type), intent(in) Domain, integer, intent(out) isc, integer, intent(out) iec, integer, intent(out) jsc, integer, intent(out) jec, integer, intent(out) isd, integer, intent(out) ied, integer, intent(out) jsd, integer, intent(out) jed, integer, intent(out) isg, integer, intent(out) ieg, integer, intent(out) jsg, integer, intent(out) jeg, integer, intent(out) idg_offset, integer, intent(out) jdg_offset, logical, intent(out) symmetric, logical, intent(in), optional local_indexing)
Definition at line 1150 of file MOM_domains.F90.
Referenced by mom_grid::mom_grid_init().
subroutine, public mom_domains::mom_domains_init (type(mom_domain_type), pointer MOM_dom, type(param_file_type), intent(in) param_file, logical, intent(in), optional symmetric, logical, intent(in), optional static_memory, integer, intent(in), optional NIHALO, integer, intent(in), optional NJHALO, integer, intent(in), optional NIGLOBAL, integer, intent(in), optional NJGLOBAL, integer, intent(in), optional NIPROC, integer, intent(in), optional NJPROC, integer, dimension(2), intent(inout), optional min_halo, character(len=*), intent(in), optional domain_name, character(len=*), intent(in), optional include_name)
Definition at line 636 of file MOM_domains.F90.
References mom_io::file_exists::file_exist(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_io::slasher().
Referenced by mom::initialize_mom(), and mom_main().
subroutine mom_domains::pass_var_2d (real, dimension(:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, logical, intent(in), optional complete, integer, intent(in), optional position) private
Definition at line 148 of file MOM_domains.F90.
subroutine mom_domains::pass_var_3d (real, dimension(:,:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, logical, intent(in), optional complete, integer, intent(in), optional position) private
Definition at line 114 of file MOM_domains.F90.
subroutine mom_domains::pass_var_complete_2d (integer, intent(in) id_update, real, dimension(:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, integer, intent(in), optional position) private
Definition at line 246 of file MOM_domains.F90.
subroutine mom_domains::pass_var_complete_3d (integer, intent(in) id_update, real, dimension(:,:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, integer, intent(in), optional position) private
Definition at line 274 of file MOM_domains.F90.
integer function mom_domains::pass_var_start_2d (real, dimension(:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, integer, intent(in), optional position, logical, intent(in), optional complete) private
Definition at line 182 of file MOM_domains.F90.
References mom_domains::pass_var_start::pass_var_start_2d().
integer function mom_domains::pass_var_start_3d (real, dimension(:,:,:), intent(inout) array, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional sideflag, integer, intent(in), optional position, logical, intent(in), optional complete) private
Definition at line 214 of file MOM_domains.F90.
References mom_domains::pass_var_start::pass_var_start_3d().
subroutine mom_domains::pass_vector_2d (real, dimension(:,:), intent(inout) u_cmpt, real, dimension(:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger, logical, intent(in), optional complete) private
Definition at line 303 of file MOM_domains.F90.
subroutine mom_domains::pass_vector_3d (real, dimension(:,:,:), intent(inout) u_cmpt, real, dimension(:,:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger, logical, intent(in), optional complete) private
Definition at line 422 of file MOM_domains.F90.
subroutine mom_domains::pass_vector_complete_2d (integer, intent(in) id_update, real, dimension(:,:), intent(inout) u_cmpt, real, dimension(:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 554 of file MOM_domains.F90.
subroutine mom_domains::pass_vector_complete_3d (integer, intent(in) id_update, real, dimension(:,:,:), intent(inout) u_cmpt, real, dimension(:,:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 595 of file MOM_domains.F90.
integer function mom_domains::pass_vector_start_2d (real, dimension(:,:), intent(inout) u_cmpt, real, dimension(:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger, logical, intent(in), optional complete) private
Definition at line 466 of file MOM_domains.F90.
References mom_domains::pass_vector_start::pass_vector_start_2d().
integer function mom_domains::pass_vector_start_3d (real, dimension(:,:,:), intent(inout) u_cmpt, real, dimension(:,:,:), intent(inout) v_cmpt, type(mom_domain_type), intent(inout) MOM_dom, integer, intent(in), optional direction, integer, intent(in), optional stagger, logical, intent(in), optional complete) private
Definition at line 510 of file MOM_domains.F90.
References mom_domains::pass_vector_start::pass_vector_start_3d().
Member Data Documentation
integer, parameter, public mom_domains::to_all = To_East + To_West + To_North + To_South
Definition at line 110 of file MOM_domains.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_domains.F90