MOM6: mom_meke Module Reference
mom_meke Module Reference
Data Types
type meke_cs
Public Member Functions
subroutine, public step_forward_meke (MEKE, h, visc, dt, G, CS)
subroutine, public meke_init (Time, G, param_file, diag, CS, MEKE)
subroutine, public meke_alloc_register_restart (G, param_file, MEKE, restart_CS)
subroutine, public meke_end (MEKE, CS)
Public Attributes
integer id_clock_pass
Detailed Description
Definition at line 1 of file MOM_MEKE.F90.
Member Function/Subroutine Documentation
subroutine, public mom_meke::meke_alloc_register_restart (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(meke_type), pointer MEKE, type(mom_restart_cs), pointer restart_CS)
Definition at line 468 of file MOM_MEKE.F90.
References mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by mom::initialize_mom().
subroutine, public mom_meke::meke_end (type(meke_type), pointer MEKE, type(meke_cs), pointer CS)
Definition at line 515 of file MOM_MEKE.F90.
subroutine, public mom_meke::meke_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(meke_cs), pointer CS, type(meke_type), pointer MEKE)
Definition at line 332 of file MOM_MEKE.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_diag_mediator::register_diag_field().
Referenced by mom::initialize_mom().
subroutine, public mom_meke::step_forward_meke (type(meke_type), pointer MEKE, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(meke_cs), pointer CS)
Definition at line 80 of file MOM_MEKE.F90.
References mom_error_handler::mom_error().
Referenced by mom::step_mom().
Member Data Documentation
integer mom_meke::id_clock_pass
Definition at line 76 of file MOM_MEKE.F90.
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_MEKE.F90