MOM6: mom_document Module Reference
mom_document Module Reference
Data Types
interface doc_param
type doc_type
type link_msg
Public Member Functions
subroutine, public doc_openblock (doc, blockName, desc)
subroutine, public doc_closeblock (doc, blockName)
subroutine, public doc_module (doc, modname, desc)
subroutine, public doc_subroutine (doc, modname, subname, desc)
subroutine, public doc_function (doc, modname, fnname, desc)
subroutine, public doc_init (docFileBase, doc, minimal, complete)
subroutine, public doc_end (doc)
Private Member Functions
subroutine doc_param_none (doc, varname, desc, units)
subroutine doc_param_logical (doc, varname, desc, units, val, default)
subroutine doc_param_logical_array (doc, varname, desc, units, vals, default)
subroutine doc_param_int (doc, varname, desc, units, val, default)
subroutine doc_param_int_array (doc, varname, desc, units, vals, default)
subroutine doc_param_real (doc, varname, desc, units, val, default)
subroutine doc_param_real_array (doc, varname, desc, units, vals, default)
subroutine doc_param_char (doc, varname, desc, units, val, default)
subroutine doc_param_time (doc, varname, desc, units, val, default)
subroutine writemessageanddesc (doc, vmesg, desc, valueWasDefault, indent)
character(len=32) function real_string (val)
character(len=1320) function real_array_string (vals, sep)
logical function testformattedfloatisreal (str, val)
character(len=24) function int_string (val)
character(len=24) function logical_string (val)
character(len=mlen) function define_string (doc, varName, valString, units)
character(len=mlen) function undef_string (doc, varName, units)
subroutine open_doc_file (doc)
integer function find_unused_unit_number ()
logical function mesghasbeendocumented (doc, varName, mesg)
Private Attributes
integer, parameter mlen = 1240
character(len=4), parameter string_true = 'True'
character(len=5), parameter string_false = 'False'
Detailed Description
Definition at line 1 of file MOM_document.F90.
Member Function/Subroutine Documentation
character(len=mlen) function mom_document::define_string (type(doc_type), pointer doc, character(len=*), intent(in) varName, character(len=*), intent(in) valString, character(len=*), intent(in) units) private
Definition at line 564 of file MOM_document.F90.
Referenced by doc_param_char(), doc_param_int(), doc_param_int_array(), doc_param_logical(), doc_param_logical_array(), doc_param_real(), and doc_param_real_array().
subroutine, public mom_document::doc_closeblock (type(doc_type), pointer doc, character(len=*), intent(in) blockName)
Definition at line 344 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), open_doc_file(), and writemessageanddesc().
Referenced by mom_file_parser::closeparameterblock().
subroutine, public mom_document::doc_end (type(doc_type), pointer doc)
Definition at line 713 of file MOM_document.F90.
Referenced by mom_file_parser::close_param_file().
subroutine, public mom_document::doc_function (type(doc_type), pointer doc, character(len=*), intent(in) modname, character(len=*), intent(in) fnname, character(len=*), intent(in) desc)
Definition at line 626 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), and open_doc_file().
subroutine, public mom_document::doc_init (character(len=*), intent(in) docFileBase, type(doc_type), pointer doc, logical, intent(in), optional minimal, logical, intent(in), optional complete)
Definition at line 637 of file MOM_document.F90.
Referenced by mom_file_parser::open_param_file().
subroutine, public mom_document::doc_module (type(doc_type), pointer doc, character(len=*), intent(in) modname, character(len=*), intent(in) desc)
Definition at line 601 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), open_doc_file(), and writemessageanddesc().
Referenced by mom_file_parser::log_version().
subroutine, public mom_document::doc_openblock (type(doc_type), pointer doc, character(len=*), intent(in) blockName, character(len=*), intent(in), optional desc)
Definition at line 321 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), open_doc_file(), and writemessageanddesc().
Referenced by mom_file_parser::openparameterblock().
subroutine mom_document::doc_param_char (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, character(len=*), intent(in) val, character(len=*), intent(in), optional default) private
Definition at line 294 of file MOM_document.F90.
References define_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine mom_document::doc_param_int (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, integer, intent(in) val, integer, intent(in), optional default) private
Definition at line 171 of file MOM_document.F90.
References define_string(), int_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine mom_document::doc_param_int_array (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, integer, dimension(:), intent(in) vals, integer, intent(in), optional default) private
Definition at line 199 of file MOM_document.F90.
References define_string(), int_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine mom_document::doc_param_logical (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, logical, intent(in) val, logical, intent(in), optional default) private
Definition at line 95 of file MOM_document.F90.
References define_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), undef_string(), and writemessageanddesc().
subroutine mom_document::doc_param_logical_array (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, logical, dimension(:), intent(in) vals, logical, intent(in), optional default) private
Definition at line 129 of file MOM_document.F90.
References define_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine mom_document::doc_param_none (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units) private
Definition at line 75 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine mom_document::doc_param_real (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, real, intent(in) val, real, intent(in), optional default) private
Definition at line 234 of file MOM_document.F90.
References define_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), real_string(), and writemessageanddesc().
subroutine mom_document::doc_param_real_array (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, real, dimension(:), intent(in) vals, real, intent(in), optional default) private
Definition at line 262 of file MOM_document.F90.
References define_string(), mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), real_array_string(), real_string(), and writemessageanddesc().
subroutine mom_document::doc_param_time (type(doc_type), pointer doc, character(len=*), intent(in) varname, character(len=*), intent(in) desc, character(len=*), intent(in) units, type(time_type), intent(in) val, type(time_type), intent(in), optional default) private
Definition at line 368 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), mesghasbeendocumented(), open_doc_file(), and writemessageanddesc().
subroutine, public mom_document::doc_subroutine (type(doc_type), pointer doc, character(len=*), intent(in) modname, character(len=*), intent(in) subname, character(len=*), intent(in) desc)
Definition at line 617 of file MOM_document.F90.
References mom_error_handler::is_root_pe(), and open_doc_file().
integer function mom_document::find_unused_unit_number () private
Definition at line 700 of file MOM_document.F90.
References mom_error_handler::mom_error().
Referenced by open_doc_file().
character(len=24) function mom_document::int_string (integer, intent(in) val) private
Definition at line 548 of file MOM_document.F90.
Referenced by doc_param_int(), doc_param_int_array(), and real_array_string().
character(len=24) function mom_document::logical_string (logical, intent(in) val) private
Definition at line 556 of file MOM_document.F90.
logical function mom_document::mesghasbeendocumented (type(doc_type), pointer doc, character(len=*), intent(in) varName, character(len=*), intent(in) mesg) private
Definition at line 739 of file MOM_document.F90.
References mom_error_handler::mom_error().
Referenced by doc_param_char(), doc_param_int(), doc_param_int_array(), doc_param_logical(), doc_param_logical_array(), doc_param_none(), doc_param_real(), doc_param_real_array(), and doc_param_time().
subroutine mom_document::open_doc_file (type(doc_type), pointer doc) private
Definition at line 653 of file MOM_document.F90.
References find_unused_unit_number(), mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by doc_closeblock(), doc_function(), doc_module(), doc_openblock(), doc_param_char(), doc_param_int(), doc_param_int_array(), doc_param_logical(), doc_param_logical_array(), doc_param_none(), doc_param_real(), doc_param_real_array(), doc_param_time(), and doc_subroutine().
character(len=1320) function mom_document::real_array_string (real, dimension(:), intent(in) vals, character(len=*), optional sep) private
Definition at line 494 of file MOM_document.F90.
References int_string(), and real_string().
Referenced by doc_param_real_array().
character(len=32) function mom_document::real_string (real, intent(in) val) private
Definition at line 448 of file MOM_document.F90.
References testformattedfloatisreal().
Referenced by doc_param_real(), doc_param_real_array(), and real_array_string().
logical function mom_document::testformattedfloatisreal (character(len=*), intent(in) str, real, intent(in) val) private
Definition at line 533 of file MOM_document.F90.
Referenced by real_string().
character(len=mlen) function mom_document::undef_string (type(doc_type), pointer doc, character(len=*), intent(in) varName, character(len=*), intent(in) units) private
Definition at line 581 of file MOM_document.F90.
Referenced by doc_param_logical().
subroutine mom_document::writemessageanddesc (type(doc_type), intent(in) doc, character(len=*), intent(in) vmesg, character(len=*), intent(in) desc, logical, intent(in), optional valueWasDefault, integer, intent(in), optional indent) private
Definition at line 394 of file MOM_document.F90.
Referenced by doc_closeblock(), doc_module(), doc_openblock(), doc_param_char(), doc_param_int(), doc_param_int_array(), doc_param_logical(), doc_param_logical_array(), doc_param_none(), doc_param_real(), doc_param_real_array(), and doc_param_time().
Member Data Documentation
integer, parameter mom_document::mlen = 1240 private
Definition at line 46 of file MOM_document.F90.
character(len=5), parameter mom_document::string_false = 'False' private
Definition at line 69 of file MOM_document.F90.
character(len=4), parameter mom_document::string_true = 'True' private
Definition at line 68 of file MOM_document.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_document.F90