MOM6: mom_ale Module Reference
mom_ale Module Reference
Data Types
type ale_cs
Public Member Functions
subroutine, public initialize_ale (param_file, G, CS)
subroutine, public adjustgridforintegrity (CS, G, h)
subroutine, public end_ale (CS)
subroutine, public ale_main (G, h, u, v, tv, CS)
subroutine, public pressure_gradient_plm (CS, S_t, S_b, T_t, T_b, G, tv, h)
subroutine, public pressure_gradient_ppm (CS, S_t, S_b, T_t, T_b, G, tv, h)
logical function, public usepressurereconstruction (CS)
integer function, public pressurereconstructionscheme (CS)
subroutine, public ale_initregridding (G, param_file, mod, regridCS, dz)
real function, dimension(cs%nk+1),
public ale_getcoordinate (CS)
character(len=20) function, public ale_getcoordinateunits (CS)
subroutine, public ale_updateverticalgridtype (CS, GV)
subroutine, public ale_writecoordinatefile (CS, G, directory)
Public Attributes
integer, parameter interpolation_p1m_h2 = 0
Private Member Functions
subroutine ale_memory_allocation (G, CS)
subroutine ale_memory_deallocation (CS)
Private Attributes
integer, parameter interpolation_p1m_h4 = 1
integer, parameter interpolation_p1m_ih4 = 2
integer, parameter interpolation_plm = 3
integer, parameter interpolation_ppm_h4 = 4
integer, parameter interpolation_ppm_ih4 = 5
integer, parameter interpolation_p3m_ih4ih3 = 6
integer, parameter interpolation_p3m_ih6ih5 = 7
integer, parameter interpolation_pqm_ih4ih3 = 8
integer, parameter interpolation_pqm_ih6ih5 = 9
Detailed Description
Definition at line 1 of file MOM_ALE.F90.
Member Function/Subroutine Documentation
subroutine, public mom_ale::adjustgridforintegrity (type(ale_cs), pointer CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h)
Definition at line 221 of file MOM_ALE.F90.
References mom_regridding::check_grid_integrity().
Referenced by mom::initialize_mom().
real function, dimension(cs%nk+1), public mom_ale::ale_getcoordinate (type(ale_cs), pointer CS)
Definition at line 636 of file MOM_ALE.F90.
References mom_regridding::getcoordinateinterfaces().
character(len=20) function, public mom_ale::ale_getcoordinateunits (type(ale_cs), pointer CS)
Definition at line 647 of file MOM_ALE.F90.
References mom_regridding::getcoordinateunits().
subroutine, public mom_ale::ale_initregridding (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, character(len=*), intent(in) mod, type(regridding_cs), intent(out) regridCS, real, dimension(:), intent(out) dz)
Definition at line 516 of file MOM_ALE.F90.
References regrid_consts::coordinatemode(), mom_string_functions::extractword(), mom_regridding::initialize_regridding(), mom_error_handler::mom_error(), mom_regridding::setcoordinateresolution(), mom_regridding::setregriddingboundaryextrapolation(), mom_regridding::setregriddingminimumthickness(), and mom_regridding::uniformresolution().
Referenced by initialize_ale(), and mom_initialization::mom_temp_salt_initialize_from_z().
subroutine, public mom_ale::ale_main (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_, nkmem_), intent(inout) u, real, dimension(nimem_,njmemb_, nkmem_), intent(inout) v, type(thermo_var_ptrs), intent(inout) tv, type(ale_cs), intent(inout) CS)
Definition at line 262 of file MOM_ALE.F90.
References mom_regridding::regridding_main(), and mom_remapping::remapping_main().
Referenced by mom::initialize_mom(), and mom::step_mom().
subroutine mom_ale::ale_memory_allocation (type(ocean_grid_type), intent(in) G, type(ale_cs), intent(inout) CS) private
Definition at line 440 of file MOM_ALE.F90.
References regrid_ppoly_class::ppoly_init(), regrid_edge_values::tridiagedgeworkallocate(), and regrid_edge_slopes::tridiagslopeworkallocate().
Referenced by initialize_ale().
subroutine mom_ale::ale_memory_deallocation (type(ale_cs), intent(inout) CS) private
Definition at line 478 of file MOM_ALE.F90.
References regrid_ppoly_class::ppoly_destroy(), regrid_edge_values::tridiagedgeworkdeallocate(), and regrid_edge_slopes::tridiagslopeworkdeallocate().
Referenced by end_ale().
subroutine, public mom_ale::ale_updateverticalgridtype (type(ale_cs), pointer CS, type(verticalgrid_type), pointer GV)
Definition at line 658 of file MOM_ALE.F90.
References mom_regridding::getcoordinateinterfaces(), mom_regridding::getcoordinateshortname(), and mom_regridding::getcoordinateunits().
Referenced by mom::initialize_mom().
subroutine, public mom_ale::ale_writecoordinatefile (type(ale_cs), pointer CS, type(ocean_grid_type), intent(inout) G, character(len=*), intent(in) directory)
Definition at line 678 of file MOM_ALE.F90.
References mom_io::create_file(), mom_regridding::getcoordinateresolution(), and mom_regridding::getcoordinateunits().
Referenced by mom::initialize_mom().
subroutine, public mom_ale::end_ale (type(ale_cs), pointer CS)
Definition at line 242 of file MOM_ALE.F90.
References ale_memory_deallocation(), mom_regridding::end_regridding(), and mom_remapping::end_remapping().
Referenced by mom::mom_end().
subroutine, public mom_ale::initialize_ale (type(param_file_type), intent(in) param_file, type(ocean_grid_type), intent(in) G, type(ale_cs), pointer CS)
Definition at line 144 of file MOM_ALE.F90.
References ale_initregridding(), ale_memory_allocation(), mom_remapping::initialize_remapping(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
subroutine, public mom_ale::pressure_gradient_plm (type(ale_cs), intent(inout) CS, real, dimension(nimem_,njmem_,nkmem_), intent(inout) S_t, real, dimension(nimem_,njmem_,nkmem_), intent(inout) S_b, real, dimension(nimem_,njmem_,nkmem_), intent(inout) T_t, real, dimension(nimem_,njmem_,nkmem_), intent(inout) T_b, type(ocean_grid_type), intent(in) G, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_,nkmem_), intent(in) h)
Definition at line 304 of file MOM_ALE.F90.
References plm_functions::plm_boundary_extrapolation(), and plm_functions::plm_reconstruction().
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
subroutine, public mom_ale::pressure_gradient_ppm (type(ale_cs), intent(inout) CS, real, dimension(nimem_,njmem_,nkmem_), intent(inout) S_t, real, dimension(nimem_,njmem_,nkmem_), intent(inout) S_b, real, dimension(nimem_,njmem_,nkmem_), intent(inout) T_t, real, dimension(nimem_,njmem_,nkmem_), intent(inout) T_b, type(ocean_grid_type), intent(in) G, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_,nkmem_), intent(in) h)
Definition at line 371 of file MOM_ALE.F90.
References regrid_edge_values::edge_values_implicit_h4(), ppm_functions::ppm_boundary_extrapolation(), and ppm_functions::ppm_reconstruction().
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
integer function, public mom_ale::pressurereconstructionscheme (type(ale_cs), pointer CS)
Definition at line 507 of file MOM_ALE.F90.
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
logical function, public mom_ale::usepressurereconstruction (type(ale_cs), pointer CS)
Definition at line 498 of file MOM_ALE.F90.
Referenced by mom_pressureforce_afv::pressureforce_afv_bouss().
Member Data Documentation
integer, parameter mom_ale::interpolation_p1m_h2 = 0
Definition at line 125 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_p1m_h4 = 1 private
Definition at line 126 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_p1m_ih4 = 2 private
Definition at line 127 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_p3m_ih4ih3 = 6 private
Definition at line 131 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_p3m_ih6ih5 = 7 private
Definition at line 132 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_plm = 3 private
Definition at line 128 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_ppm_h4 = 4 private
Definition at line 129 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_ppm_ih4 = 5 private
Definition at line 130 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_pqm_ih4ih3 = 8 private
Definition at line 133 of file MOM_ALE.F90.
integer, parameter mom_ale::interpolation_pqm_ih6ih5 = 9 private
Definition at line 134 of file MOM_ALE.F90.
The documentation for this module was generated from the following file:
src/ALE/MOM_ALE.F90