MOM6: mom_set_diffusivity Module Reference
mom_set_diffusivity Module Reference
Data Types
type diffusivity_diags
type set_diffusivity_cs
Public Member Functions
subroutine, public set_diffusivity (u, v, h, u_h, v_h, tv, fluxes, optics, visc, dt, G, CS, Kd, Kd_int)
subroutine, public set_bbl_diffusivity (u, v, h, fluxes, visc, G, CS)
subroutine, public set_diffusivity_init (Time, G, param_file, diag, CS, diag_to_Z_CSp)
subroutine, public set_diffusivity_end (CS)
Private Member Functions
subroutine find_tke_to_kd (h, tv, dRho_int, N2_lay, j, dt, G, CS, TKE_to_Kd, maxTKE, kb)
subroutine find_n2 (h, tv, T_f, S_f, fluxes, j, G, CS, dRho_int, N2_lay, N2_int, N2_bot)
subroutine double_diffusion (tv, h, T_f, S_f, j, G, CS, Kd_T_dd, Kd_S_dd)
subroutine add_drag_diffusivity (h, u, v, tv, fluxes, visc, j, TKE_to_Kd, maxTKE, kb, G, CS, Kd, Kd_int)
subroutine add_mlrad_diffusivity (h, fluxes, j, G, CS, Kd, TKE_to_Kd, Kd_int)
subroutine add_int_tide_diffusivity (h, N2_bot, j, TKE_to_Kd, max_TKE, G, CS, dd, N2_lay, Kd, Kd_int)
subroutine set_density_ratios (h, tv, kb, G, CS, j, ds_dsp1, rho_0)
Private Attributes
character *(20), parameter stlaurent_profile_string = "STLAURENT_02"
character *(20), parameter polzin_profile_string = "POLZIN_09"
integer, parameter stlaurent_02 = 1
integer, parameter polzin_09 = 2
integer id_clock_kappashear
Detailed Description
Definition at line 1 of file MOM_set_diffusivity.F90.
Member Function/Subroutine Documentation
subroutine mom_set_diffusivity::add_drag_diffusivity (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, type(thermo_var_ptrs), intent(in) tv, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(in) visc, integer, intent(in) j, real, dimension(nimem_,nkmem_), intent(in) TKE_to_Kd, real, dimension(nimem_,nkmem_), intent(in) maxTKE, integer, dimension(nimem_), intent(in) kb, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(inout) Kd, real, dimension(nimem_,njmem_,nk_interface_), intent(inout), optional Kd_int) private
Definition at line 1249 of file MOM_set_diffusivity.F90.
Referenced by set_diffusivity().
subroutine mom_set_diffusivity::add_int_tide_diffusivity (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_), intent(in) N2_bot, integer, intent(in) j, real, dimension(nimem_,nkmem_), intent(in) TKE_to_Kd, real, dimension(nimem_,nkmem_), intent(in) max_TKE, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, type(diffusivity_diags), intent(inout) dd, real, dimension(nimem_,nkmem_), intent(in) N2_lay, real, dimension(nimem_,njmem_,nkmem_), intent(inout) Kd, real, dimension(nimem_,njmem_,nk_interface_), intent(inout), optional Kd_int) private
Definition at line 1571 of file MOM_set_diffusivity.F90.
Referenced by set_diffusivity().
subroutine mom_set_diffusivity::add_mlrad_diffusivity (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(forcing), intent(in) fluxes, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(inout) Kd, real, dimension(nimem_,nkmem_), intent(in) TKE_to_Kd, real, dimension(nimem_,njmem_,nk_interface_), intent(inout), optional Kd_int) private
Definition at line 1459 of file MOM_set_diffusivity.F90.
Referenced by set_diffusivity().
subroutine mom_set_diffusivity::double_diffusion (type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) T_f, real, dimension(nimem_,njmem_,nkmem_), intent(in) S_f, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,nk_interface_), intent(out) Kd_T_dd, real, dimension(nimem_,nk_interface_), intent(out) Kd_S_dd) private
Definition at line 1156 of file MOM_set_diffusivity.F90.
References mom_eos::calculate_density_derivs().
Referenced by set_diffusivity().
subroutine mom_set_diffusivity::find_n2 (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_,nkmem_), intent(in) T_f, real, dimension(nimem_,njmem_,nkmem_), intent(in) S_f, type(forcing), intent(in) fluxes, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,nk_interface_), intent(out) dRho_int, real, dimension(nimem_,nkmem_), intent(out) N2_lay, real, dimension(nimem_,nk_interface_), intent(out) N2_int, real, dimension(nimem_), intent(out) N2_bot) private
Definition at line 1007 of file MOM_set_diffusivity.F90.
References mom_eos::calculate_density_derivs().
Referenced by set_diffusivity().
subroutine mom_set_diffusivity::find_tke_to_kd (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,nk_interface_), intent(in) dRho_int, real, dimension(nimem_,nkmem_), intent(in) N2_lay, integer, intent(in) j, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,nkmem_), intent(out) TKE_to_Kd, real, dimension(nimem_,nkmem_), intent(out) maxTKE, integer, dimension(nimem_), intent(out) kb) private
Definition at line 833 of file MOM_set_diffusivity.F90.
References set_density_ratios().
Referenced by set_diffusivity().
subroutine, public mom_set_diffusivity::set_bbl_diffusivity (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(inout) visc, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS)
Definition at line 1868 of file MOM_set_diffusivity.F90.
References mom_error_handler::mom_error().
Referenced by mom_diabatic_driver::diabatic().
subroutine mom_set_diffusivity::set_density_ratios (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, integer, dimension(nimem_), intent(in) kb, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, integer, intent(in) j, real, dimension(nimem_,nkmem_), intent(out) ds_dsp1, real, dimension(nimem_,nkmem_), intent(in), optional rho_0) private
Definition at line 1989 of file MOM_set_diffusivity.F90.
Referenced by find_tke_to_kd().
subroutine, public mom_set_diffusivity::set_diffusivity (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) u_h, real, dimension(nimem_,njmem_,nkmem_), intent(in) v_h, type(thermo_var_ptrs), intent(inout) tv, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, type(vertvisc_type), intent(inout) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(set_diffusivity_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(out) Kd, real, dimension(nimem_,njmem_,nk_interface_), intent(out), optional Kd_int)
Definition at line 326 of file MOM_set_diffusivity.F90.
References add_drag_diffusivity(), add_int_tide_diffusivity(), add_mlrad_diffusivity(), mom_diag_to_z::calc_zint_diags(), mom_kappa_shear::calculate_kappa_shear(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::calltree_showquery(), mom_error_handler::calltree_waypoint(), double_diffusion(), find_n2(), find_tke_to_kd(), mom_intrinsic_functions::invcosh(), mom_error_handler::mom_error(), user_change_diffusivity::user_change_diff(), and mom_thickness_diffuse::vert_fill_ts().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_set_diffusivity::set_diffusivity_end (type(set_diffusivity_cs), pointer CS)
Definition at line 2660 of file MOM_set_diffusivity.F90.
References user_change_diffusivity::user_change_diff_end().
Referenced by mom_diabatic_driver::diabatic_driver_end().
subroutine, public mom_set_diffusivity::set_diffusivity_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(set_diffusivity_cs), pointer CS, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 2096 of file MOM_set_diffusivity.F90.
References mom_kappa_shear::kappa_shear_init(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), mom_diag_to_z::register_zint_diag(), mom_io::slasher(), mom_string_functions::uppercase(), and user_change_diffusivity::user_change_diff_init().
Referenced by mom_diabatic_driver::diabatic_driver_init().
Member Data Documentation
integer mom_set_diffusivity::id_clock_kappashear private
Definition at line 322 of file MOM_set_diffusivity.F90.
integer, parameter mom_set_diffusivity::polzin_09 = 2 private
Definition at line 319 of file MOM_set_diffusivity.F90.
character*(20), parameter mom_set_diffusivity::polzin_profile_string = "POLZIN_09" private
Definition at line 317 of file MOM_set_diffusivity.F90.
integer, parameter mom_set_diffusivity::stlaurent_02 = 1 private
Definition at line 318 of file MOM_set_diffusivity.F90.
character*(20), parameter mom_set_diffusivity::stlaurent_profile_string = "STLAURENT_02" private
Definition at line 316 of file MOM_set_diffusivity.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_set_diffusivity.F90