MOM6: regrid_solvers Module Reference
regrid_solvers Module Reference
Public Member Functions
subroutine, public solve_linear_system (A, B, X, system_size)
subroutine, public solve_tridiagonal_system (Al, Ad, Au, B, X, system_size)
Detailed Description
Definition at line 1 of file regrid_solvers.F90.
Member Function/Subroutine Documentation
subroutine, public regrid_solvers::solve_linear_system (real, dimension(:,:), intent(inout) A, real, dimension(:), intent(inout) B, real, dimension(:), intent(inout) X, integer system_size)
Definition at line 29 of file regrid_solvers.F90.
References mom_error_handler::mom_error().
Referenced by regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), and regrid_edge_values::edge_values_implicit_h6().
subroutine, public regrid_solvers::solve_tridiagonal_system (real, dimension(:), intent(inout) Al, real, dimension(:), intent(inout) Ad, real, dimension(:), intent(inout) Au, real, dimension(:), intent(inout) B, real, dimension(:), intent(inout) X, integer, intent(in) system_size)
Definition at line 130 of file regrid_solvers.F90.
Referenced by regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_implicit_h4(), and regrid_edge_values::edge_values_implicit_h6().
The documentation for this module was generated from the following file:
src/ALE/regrid_solvers.F90