MOM6: mom_controlled_forcing Module Reference
mom_controlled_forcing Module Reference
Data Types
type ctrl_forcing_cs
Public Member Functions
subroutine, public apply_ctrl_forcing (SST_anom, SSS_anom, SSS_mean, virt_heat, virt_precip, day_start, dt, G, CS)
subroutine, public register_ctrl_forcing_restarts (G, param_file, CS, restart_CS)
subroutine, public controlled_forcing_init (Time, G, param_file, diag, CS)
subroutine, public controlled_forcing_end (CS)
Private Member Functions
integer function periodic_int (rval, num_period)
real function periodic_real (rval, num_period)
Detailed Description
Definition at line 1 of file MOM_controlled_forcing.F90.
Member Function/Subroutine Documentation
subroutine, public mom_controlled_forcing::apply_ctrl_forcing (real, dimension(nimem_,njmem_), intent(in) SST_anom, real, dimension(nimem_,njmem_), intent(in) SSS_anom, real, dimension(nimem_,njmem_), intent(in) SSS_mean, real, dimension(nimem_,njmem_), intent(inout) virt_heat, real, dimension(nimem_,njmem_), intent(inout) virt_precip, type(time_type), intent(in) day_start, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(ctrl_forcing_cs), pointer CS)
Definition at line 114 of file MOM_controlled_forcing.F90.
References mom_error_handler::mom_error(), periodic_int(), and periodic_real().
subroutine, public mom_controlled_forcing::controlled_forcing_end (type(ctrl_forcing_cs), pointer CS)
Definition at line 594 of file MOM_controlled_forcing.F90.
subroutine, public mom_controlled_forcing::controlled_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(ctrl_forcing_cs), pointer CS)
Definition at line 512 of file MOM_controlled_forcing.F90.
References mom_file_parser::log_version().
integer function mom_controlled_forcing::periodic_int (real, intent(in) rval, integer, intent(in) num_period) private
Definition at line 407 of file MOM_controlled_forcing.F90.
Referenced by apply_ctrl_forcing().
real function mom_controlled_forcing::periodic_real (real, intent(in) rval, integer, intent(in) num_period) private
Definition at line 421 of file MOM_controlled_forcing.F90.
Referenced by apply_ctrl_forcing().
subroutine, public mom_controlled_forcing::register_ctrl_forcing_restarts (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(ctrl_forcing_cs), pointer CS, type(mom_restart_cs), pointer restart_CS)
Definition at line 437 of file MOM_controlled_forcing.F90.
References mom_error_handler::mom_error().
The documentation for this module was generated from the following file:
src/user/MOM_controlled_forcing.F90