MOM6: mom_tracer_registry Module Reference
mom_tracer_registry Module Reference
Data Types
type tracer_registry_type
type tracer_type
Public Member Functions
subroutine, public register_tracer (tr1, name, param_file, Reg, ad_x, ad_y, df_x, df_y, OBC_inflow, OBC_in_u, OBC_in_v, ad_2d_x, ad_2d_y, df_2d_x, df_2d_y)
subroutine, public add_tracer_obc_values (name, Reg, OBC_inflow, OBC_in_u, OBC_in_v)
subroutine, public add_tracer_diagnostics (name, Reg, ad_x, ad_y, df_x, df_y, ad_2d_x, ad_2d_y, df_2d_x, df_2d_y)
subroutine, public tracer_vertdiff (h_old, ea, eb, dt, tr, G, sfc_flux, btm_flux, btm_reservoir, sink_rate)
subroutine, public mom_tracer_chksum (mesg, Tr, ntr, G)
subroutine, public tracer_registry_init (param_file, Reg)
subroutine, public tracer_registry_end (Reg)
Detailed Description
Definition at line 1 of file MOM_tracer_registry.F90.
Member Function/Subroutine Documentation
subroutine, public mom_tracer_registry::add_tracer_diagnostics (character(len=*), intent(in) name, type(tracer_registry_type), pointer Reg, real, dimension(:,:,:), optional, pointer ad_x, real, dimension(:,:,:), optional, pointer ad_y, real, dimension(:,:,:), optional, pointer df_x, real, dimension(:,:,:), optional, pointer df_y, real, dimension(:,:), optional, pointer ad_2d_x, real, dimension(:,:), optional, pointer ad_2d_y, real, dimension(:,:), optional, pointer df_2d_x, real, dimension(:,:), optional, pointer df_2d_y)
Definition at line 189 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error().
Referenced by advection_test_tracer::initialize_advection_test_tracer(), dome_tracer::initialize_dome_tracer(), ideal_age_example::initialize_ideal_age_tracer(), mom::initialize_mom(), mom_ocmip2_cfc::initialize_ocmip2_cfc(), oil_tracer::initialize_oil_tracer(), and user_tracer_example::user_initialize_tracer().
subroutine, public mom_tracer_registry::add_tracer_obc_values (character(len=*), intent(in) name, type(tracer_registry_type), pointer Reg, real, intent(in), optional OBC_inflow, real, dimension(:,:,:), optional, pointer OBC_in_u, real, dimension(:,:,:), optional, pointer OBC_in_v)
Definition at line 153 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error().
Referenced by dome_initialization::dome_set_open_bdry_conds(), dome_tracer::initialize_dome_tracer(), mom_initialization::set_flather_bdry_conds(), mom_initialization::set_open_bdry_conds(), and user_tracer_example::user_initialize_tracer().
subroutine, public mom_tracer_registry::mom_tracer_chksum (character(len=*), intent(in) mesg, type(tracer_type), dimension(:), intent(in) Tr, integer, intent(in) ntr, type(ocean_grid_type), intent(in) G)
Definition at line 401 of file MOM_tracer_registry.F90.
Referenced by mom_tracer_hor_diff::tracer_hordiff().
subroutine, public mom_tracer_registry::register_tracer (real, dimension(nimem_,njmem_,nkmem_), target tr1, character(len=*), intent(in) name, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer Reg, real, dimension(:,:,:), optional, pointer ad_x, real, dimension(:,:,:), optional, pointer ad_y, real, dimension(:,:,:), optional, pointer df_x, real, dimension(:,:,:), optional, pointer df_y, real, intent(in), optional OBC_inflow, real, dimension(:,:,:), optional, pointer OBC_in_u, real, dimension(:,:,:), optional, pointer OBC_in_v, real, dimension(:,:), optional, pointer ad_2d_x, real, dimension(:,:), optional, pointer ad_2d_y, real, dimension(:,:), optional, pointer df_2d_x, real, dimension(:,:), optional, pointer df_2d_y)
Definition at line 77 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error(), and tracer_registry_init().
Referenced by mom::initialize_mom(), advection_test_tracer::register_advection_test_tracer(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), and user_tracer_example::user_register_tracer_example().
subroutine, public mom_tracer_registry::tracer_registry_end (type(tracer_registry_type), pointer Reg)
Definition at line 447 of file MOM_tracer_registry.F90.
Referenced by mom::mom_end().
subroutine, public mom_tracer_registry::tracer_registry_init (type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer Reg)
Definition at line 420 of file MOM_tracer_registry.F90.
References mom_error_handler::is_root_pe(), mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom(), and register_tracer().
subroutine, public mom_tracer_registry::tracer_vertdiff (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) tr, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(in), optional sfc_flux, real, dimension(nimem_,njmem_), intent(in), optional btm_flux, real, dimension(nimem_,njmem_), intent(inout), optional btm_reservoir, real, intent(in), optional sink_rate)
Definition at line 239 of file MOM_tracer_registry.F90.
Referenced by dome_tracer::dome_tracer_column_physics(), ideal_age_example::ideal_age_tracer_column_physics(), mom_ocmip2_cfc::ocmip2_cfc_column_physics(), and oil_tracer::oil_tracer_column_physics().
The documentation for this module was generated from the following file:
src/tracer/MOM_tracer_registry.F90