MOM6: benchmark_initialization Module Reference
benchmark_initialization Module Reference
Public Member Functions
subroutine, public benchmark_initialize_topography (D, G, param_file, max_depth)
subroutine, public benchmark_initialize_thickness (h, G, param_file, eqn_of_state, P_ref)
subroutine, public benchmark_init_temperature_salinity (T, S, G, param_file, eqn_of_state, P_Ref)
Detailed Description
Definition at line 1 of file benchmark_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public benchmark_initialization::benchmark_init_temperature_salinity (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_Ref)
Definition at line 215 of file benchmark_initialization.F90.
References mom_eos::calculate_density_derivs().
Referenced by mom_initialization::mom_initialize().
subroutine, public benchmark_initialization::benchmark_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, real, intent(in) P_ref)
Definition at line 96 of file benchmark_initialization.F90.
References mom_eos::calculate_density_derivs(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize().
subroutine, public benchmark_initialization::benchmark_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Definition at line 48 of file benchmark_initialization.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_initialize_topography().
The documentation for this module was generated from the following file:
src/user/benchmark_initialization.F90