MOM6: mom_variables Module Reference
mom_variables Module Reference
Data Types
type accel_diag_ptrs
type bt_cont_type
type cont_diag_ptrs
type ocean_internal_state
type ocean_obc_type
type optics_type
type p2d
type p3d
type surface
type thermo_var_ptrs
type vertvisc_type
Public Member Functions
subroutine, public alloc_bt_cont_type (BT_cont, G, alloc_faces)
subroutine, public dealloc_bt_cont_type (BT_cont)
subroutine, public mom_thermovar_chksum (mesg, tv, G)
Public Attributes
integer, parameter, public obc_none = 0
integer, parameter, public obc_simple = 1
integer, parameter, public obc_wall = 2
integer, parameter, public obc_flather_e = 4
integer, parameter, public obc_flather_w = 5
integer, parameter, public obc_flather_n = 6
integer, parameter, public obc_flather_s = 7
Detailed Description
Definition at line 1 of file MOM_variables.F90.
Member Function/Subroutine Documentation
subroutine, public mom_variables::alloc_bt_cont_type (type(bt_cont_type), pointer BT_cont, type(ocean_grid_type), intent(in) G, logical, intent(in), optional alloc_faces)
Definition at line 341 of file MOM_variables.F90.
References mom_error_handler::mom_error().
Referenced by mom_barotropic::barotropic_init(), and mom_legacy_barotropic::legacy_barotropic_init().
subroutine, public mom_variables::dealloc_bt_cont_type (type(bt_cont_type), pointer BT_cont)
Definition at line 375 of file MOM_variables.F90.
Referenced by mom_dynamics_legacy_split::end_dyn_legacy_split(), and mom_dynamics_split_rk2::end_dyn_split_rk2().
subroutine, public mom_variables::mom_thermovar_chksum (character(len=*), intent(in) mesg, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G)
Definition at line 395 of file MOM_variables.F90.
Referenced by mom_diabatic_driver::diabatic().
Member Data Documentation
integer, parameter, public mom_variables::obc_flather_e = 4
Definition at line 238 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_flather_n = 6
Definition at line 239 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_flather_s = 7
Definition at line 239 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_flather_w = 5
Definition at line 238 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_none = 0
Definition at line 237 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_simple = 1
Definition at line 237 of file MOM_variables.F90.
integer, parameter, public mom_variables::obc_wall = 2
Definition at line 237 of file MOM_variables.F90.
The documentation for this module was generated from the following file:
src/core/MOM_variables.F90