MOM6: regrid_edge_slopes Module Reference
regrid_edge_slopes Module Reference
Data Types
type edgeslopearrays
Public Member Functions
subroutine, public edge_slopes_implicit_h3 (N, h, u, work, edge_slopes)
subroutine, public edge_slopes_implicit_h5 (N, h, u, work, edge_slopes)
subroutine, public tridiagslopeworkallocate (N, work)
subroutine, public tridiagslopeworkdeallocate (work)
Detailed Description
Definition at line 1 of file regrid_edge_slopes.F90.
Member Function/Subroutine Documentation
subroutine, public regrid_edge_slopes::edge_slopes_implicit_h3 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(edgeslopearrays), intent(inout) work, real, dimension(:,:), intent(inout) edge_slopes)
Definition at line 45 of file regrid_edge_slopes.F90.
References polynomial_functions::evaluation_polynomial(), regrid_solvers::solve_linear_system(), and regrid_solvers::solve_tridiagonal_system().
Referenced by mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine, public regrid_edge_slopes::edge_slopes_implicit_h5 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(edgeslopearrays), intent(inout) work, real, dimension(:,:), intent(inout) edge_slopes)
Definition at line 190 of file regrid_edge_slopes.F90.
References polynomial_functions::evaluation_polynomial(), regrid_solvers::solve_linear_system(), and regrid_solvers::solve_tridiagonal_system().
Referenced by mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine, public regrid_edge_slopes::tridiagslopeworkallocate (integer, intent(in) N, type(edgeslopearrays), intent(inout) work)
Definition at line 660 of file regrid_edge_slopes.F90.
Referenced by mom_ale::ale_memory_allocation(), mom_regridding::allocate_regridding(), and mom_remapping::allocate_remapping().
subroutine, public regrid_edge_slopes::tridiagslopeworkdeallocate (type(edgeslopearrays), intent(inout) work)
Definition at line 682 of file regrid_edge_slopes.F90.
Referenced by mom_ale::ale_memory_deallocation(), mom_remapping::end_remapping(), and mom_regridding::regridding_memory_deallocation().
The documentation for this module was generated from the following file:
src/ALE/regrid_edge_slopes.F90