MOM6: mom_interface_heights Module Reference
mom_interface_heights Module Reference
Data Types
interface find_eta
Private Member Functions
subroutine find_eta_3d (h, tv, G_Earth, G, eta, eta_bt, halo_size)
subroutine find_eta_2d (h, tv, G_Earth, G, eta, eta_bt, halo_size)
Detailed Description
Definition at line 1 of file MOM_interface_heights.F90.
Member Function/Subroutine Documentation
subroutine mom_interface_heights::find_eta_2d (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, intent(in) G_Earth, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(out) eta, real, dimension(nimem_,njmem_), intent(in), optional eta_bt, integer, intent(in), optional halo_size) private
Definition at line 164 of file MOM_interface_heights.F90.
References mom_eos::int_specific_vol_dp().
subroutine mom_interface_heights::find_eta_3d (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, intent(in) G_Earth, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nk_interface_), intent(out) eta, real, dimension(nimem_,njmem_), intent(in), optional eta_bt, integer, intent(in), optional halo_size) private
Definition at line 67 of file MOM_interface_heights.F90.
References mom_eos::int_specific_vol_dp(), and mom_error_handler::mom_error().
The documentation for this module was generated from the following file:
src/core/MOM_interface_heights.F90