MOM6: mom_pressureforce Module Reference
mom_pressureforce Module Reference
Data Types
type pressureforce_cs
Public Member Functions
subroutine, public pressureforce (h, tv, PFu, PFv, G, CS, ALE_CSp, p_atm, pbce, eta)
subroutine, public pressureforce_init (Time, G, param_file, diag, CS, tides_CSp)
subroutine, public pressureforce_end (CS)
Detailed Description
Definition at line 1 of file MOM_PressureForce.F90.
Member Function/Subroutine Documentation
subroutine, public mom_pressureforce::pressureforce (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_cs), pointer CS, type(ale_cs), pointer ALE_CSp, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 79 of file MOM_PressureForce.F90.
References mom_pressureforce_afv::pressureforce_afv_bouss(), mom_pressureforce_afv::pressureforce_afv_nonbouss(), mom_pressureforce_mont::pressureforce_mont_bouss(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_pressureforce::pressureforce_end (type(pressureforce_cs), pointer CS)
Definition at line 162 of file MOM_PressureForce.F90.
subroutine, public mom_pressureforce::pressureforce_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(pressureforce_cs), pointer CS, type(tidal_forcing_cs), optional, pointer tides_CSp)
Definition at line 116 of file MOM_PressureForce.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_pressureforce_afv::pressureforce_afv_init(), and mom_pressureforce_mont::pressureforce_mont_init().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
The documentation for this module was generated from the following file:
src/core/MOM_PressureForce.F90