MOM6: mom_restart Module Reference
mom_restart Module Reference
Data Types
type field_restart
type mom_restart_cs
type p0d
type p1d
type p2d
type p3d
interface query_initialized
interface register_restart_field
Public Member Functions
subroutine, public save_restart (directory, time, G, CS, time_stamped, filename)
subroutine, public restore_state (filename, directory, day, G, CS)
subroutine, public restart_init (param_file, CS, restart_root)
subroutine, public restart_init_end (CS)
subroutine, public restart_end (CS)
Private Member Functions
subroutine register_restart_field_ptr3d (f_ptr, var_desc, mandatory, CS)
subroutine register_restart_field_ptr2d (f_ptr, var_desc, mandatory, CS)
subroutine register_restart_field_ptr1d (f_ptr, var_desc, mandatory, CS)
subroutine register_restart_field_ptr0d (f_ptr, var_desc, mandatory, CS)
logical function query_initialized_name (name, CS)
logical function query_initialized_0d (f_ptr, CS)
logical function query_initialized_1d (f_ptr, CS)
logical function query_initialized_2d (f_ptr, CS)
logical function query_initialized_3d (f_ptr, CS)
logical function query_initialized_0d_name (f_ptr, name, CS)
logical function query_initialized_1d_name (f_ptr, name, CS)
logical function query_initialized_2d_name (f_ptr, name, CS)
logical function query_initialized_3d_name (f_ptr, name, CS)
subroutine restart_error (CS)
Detailed Description
Definition at line 1 of file MOM_restart.F90.
Member Function/Subroutine Documentation
logical function mom_restart::query_initialized_0d (real, target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 330 of file MOM_restart.F90.
References mom_error_handler::mom_error(), and restart_error().
logical function mom_restart::query_initialized_0d_name (real, target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 446 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_restart::query_initialized::query_initialized_name(), and restart_error().
logical function mom_restart::query_initialized_1d (real, dimension(:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 359 of file MOM_restart.F90.
References mom_error_handler::mom_error(), and restart_error().
logical function mom_restart::query_initialized_1d_name (real, dimension(:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 483 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_restart::query_initialized::query_initialized_name(), and restart_error().
logical function mom_restart::query_initialized_2d (real, dimension(:,:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 388 of file MOM_restart.F90.
References mom_error_handler::mom_error(), and restart_error().
logical function mom_restart::query_initialized_2d_name (real, dimension(:,:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 520 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_restart::query_initialized::query_initialized_name(), and restart_error().
logical function mom_restart::query_initialized_3d (real, dimension(:,:,:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 417 of file MOM_restart.F90.
References mom_error_handler::mom_error(), and restart_error().
logical function mom_restart::query_initialized_3d_name (real, dimension(:,:,:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 557 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_restart::query_initialized::query_initialized_name(), and restart_error().
logical function mom_restart::query_initialized_name (character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 294 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and restart_error().
subroutine mom_restart::register_restart_field_ptr0d (real, target f_ptr, type(vardesc), intent(in) var_desc, logical, intent(in) mandatory, type(mom_restart_cs), pointer CS) private
Definition at line 258 of file MOM_restart.F90.
References mom_error_handler::mom_error().
subroutine mom_restart::register_restart_field_ptr1d (real, dimension(:), target f_ptr, type(vardesc), intent(in) var_desc, logical, intent(in) mandatory, type(mom_restart_cs), pointer CS) private
Definition at line 222 of file MOM_restart.F90.
References mom_error_handler::mom_error().
subroutine mom_restart::register_restart_field_ptr2d (real, dimension(:,:), target f_ptr, type(vardesc), intent(in) var_desc, logical, intent(in) mandatory, type(mom_restart_cs), pointer CS) private
Definition at line 186 of file MOM_restart.F90.
References mom_error_handler::mom_error().
subroutine mom_restart::register_restart_field_ptr3d (real, dimension(:,:,:), target f_ptr, type(vardesc), intent(in) var_desc, logical, intent(in) mandatory, type(mom_restart_cs), pointer CS) private
Definition at line 151 of file MOM_restart.F90.
References mom_error_handler::mom_error().
subroutine, public mom_restart::restart_end (type(mom_restart_cs), pointer CS)
Definition at line 1137 of file MOM_restart.F90.
Referenced by restart_init_end().
subroutine mom_restart::restart_error (type(mom_restart_cs), pointer CS) private
Definition at line 1149 of file MOM_restart.F90.
References mom_error_handler::mom_error().
Referenced by query_initialized_0d(), query_initialized_0d_name(), query_initialized_1d(), query_initialized_1d_name(), query_initialized_2d(), query_initialized_2d_name(), query_initialized_3d(), query_initialized_3d_name(), query_initialized_name(), restore_state(), and save_restart().
subroutine, public mom_restart::restart_init (type(param_file_type), intent(in) param_file, type(mom_restart_cs), pointer CS, character(len=*), intent(in), optional restart_root)
Definition at line 1076 of file MOM_restart.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom(), and mom_surface_forcing::surface_forcing_init().
subroutine, public mom_restart::restart_init_end (type(mom_restart_cs), pointer CS)
Definition at line 1128 of file MOM_restart.F90.
References restart_end().
Referenced by mom_surface_forcing::surface_forcing_init().
subroutine, public mom_restart::restore_state (character(len=*), intent(in) filename, character(len=*), intent(in) directory, type(time_type), intent(out) day, type(ocean_grid_type), intent(in) G, type(mom_restart_cs), pointer CS)
Definition at line 748 of file MOM_restart.F90.
References mom_error_handler::is_root_pe(), mom_string_functions::lowercase(), mom_error_handler::mom_error(), and restart_error().
Referenced by mom_initialization::mom_initialize(), and mom_surface_forcing::surface_forcing_init().
subroutine, public mom_restart::save_restart (character(len=*), intent(in) directory, type(time_type), intent(in) time, type(ocean_grid_type), intent(inout) G, type(mom_restart_cs), pointer CS, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename)
Definition at line 594 of file MOM_restart.F90.
References mom_io::create_file(), mom_error_handler::mom_error(), and restart_error().
Referenced by mom_surface_forcing::forcing_save_restart(), mom::initialize_mom(), mom_main(), ocean_model_mod::ocean_model_restart(), ocean_model_mod::ocean_model_save_restart(), and shelf_main().
The documentation for this module was generated from the following file:
src/framework/MOM_restart.F90