MOM6: mom_string_functions Module Reference
mom_string_functions Module Reference
Public Member Functions
character(len=len(input_string))
function, public lowercase (input_string)
character(len=len(input_string))
function, public uppercase (input_string)
character(len=19) function, public left_int (i)
character(len=1320) function,
public left_ints (i)
character(len=32) function, public left_real (val)
character(len=1320) function,
public left_reals (r, sep)
character(len=120) function, public extractword (string, n)
logical function, public stringfunctionsunittests ()
character(len=len(dir)+2)
function, public slasher (dir)
Private Member Functions
logical function isformattedfloatequalto (str, val)
Detailed Description
Definition at line 1 of file MOM_string_functions.F90.
Member Function/Subroutine Documentation
character(len=120) function, public mom_string_functions::extractword (character(len=*), intent(in) string, integer, intent(in) n)
Definition at line 209 of file MOM_string_functions.F90.
Referenced by mom_ale::ale_initregridding(), and stringfunctionsunittests().
logical function mom_string_functions::isformattedfloatequalto (character(len=*), intent(in) str, real, intent(in) val) private
Definition at line 194 of file MOM_string_functions.F90.
Referenced by left_real().
character(len=19) function, public mom_string_functions::left_int (integer, intent(in) i)
Definition at line 78 of file MOM_string_functions.F90.
Referenced by left_ints(), left_reals(), mom_file_parser::log_param_int(), and stringfunctionsunittests().
character(len=1320) function, public mom_string_functions::left_ints (integer, dimension(:), intent(in) i)
Definition at line 90 of file MOM_string_functions.F90.
References left_int().
Referenced by mom_file_parser::log_param_int_array(), and stringfunctionsunittests().
character(len=32) function, public mom_string_functions::left_real (real, intent(in) val)
Definition at line 108 of file MOM_string_functions.F90.
References isformattedfloatequalto().
Referenced by left_reals(), mom_file_parser::log_param_real(), and stringfunctionsunittests().
character(len=1320) function, public mom_string_functions::left_reals (real, dimension(:), intent(in) r, character(len=*), optional sep)
Definition at line 154 of file MOM_string_functions.F90.
References left_int(), and left_real().
Referenced by mom_file_parser::log_param_real_array(), and stringfunctionsunittests().
character(len=len(input_string)) function, public mom_string_functions::lowercase (character(len=*), intent(in) input_string)
Definition at line 43 of file MOM_string_functions.F90.
Referenced by mom_io::num_timelevels(), mom_restart::restore_state(), and mom_diag_mediator::set_axes_info().
character(len=len(dir)+2) function, public mom_string_functions::slasher (character(len=*), intent(in) dir)
Definition at line 276 of file MOM_string_functions.F90.
References mom_io::slasher().
logical function, public mom_string_functions::stringfunctionsunittests ()
Definition at line 248 of file MOM_string_functions.F90.
References extractword(), left_int(), left_ints(), left_real(), left_reals(), and localtest().
Referenced by localtest(), and mom::unittests().
character(len=len(input_string)) function, public mom_string_functions::uppercase (character(len=*), intent(in) input_string)
Definition at line 61 of file MOM_string_functions.F90.
Referenced by mom_continuity::continuity_init(), regrid_consts::coordinatemode(), mom_coriolisadv::coriolisadv_init(), mom_regridding::initialize_regridding(), ocean_model_mod::ocean_model_init(), mom_opacity::opacity_init(), mom_initialization::read_face_length_list(), mom_initialization::reset_face_lengths_list(), mom_eos::select_eqn_of_state(), mom_set_diffusivity::set_diffusivity_init(), mom_remapping::setreconstructiontype(), mom_surface_forcing::surface_forcing_init(), and mom_surface_forcing::wind_forcing_from_file().
The documentation for this module was generated from the following file:
src/framework/MOM_string_functions.F90