MOM6: mom_opacity Module Reference
mom_opacity Module Reference
Data Types
type opacity_cs
Public Member Functions
subroutine, public set_opacity (optics, fluxes, G, CS)
real function, public opacity_morel (chl_data)
real function, public opacity_manizza (chl_data)
subroutine, public opacity_init (Time, G, param_file, diag, tracer_flow, CS, optics)
subroutine, public opacity_end (CS, optics)
Public Attributes
integer, parameter no_scheme = 0
Private Member Functions
subroutine opacity_from_chl (optics, fluxes, G, CS, chl_in)
real function sw_pen_frac_morel (chl_data)
Private Attributes
integer, parameter manizza_05 = 1
integer, parameter morel_88 = 2
character *(10), parameter manizza_05_string = "MANIZZA_05"
character *(10), parameter morel_88_string = "MOREL_88"
Detailed Description
Definition at line 1 of file MOM_opacity.F90.
Member Function/Subroutine Documentation
subroutine, public mom_opacity::opacity_end (type(opacity_cs), pointer CS, type(optics_type), optional, pointer optics)
Definition at line 579 of file MOM_opacity.F90.
Referenced by mom_diabatic_driver::diabatic_driver_end().
subroutine mom_opacity::opacity_from_chl (type(optics_type), intent(inout) optics, type(forcing), intent(in) fluxes, type(ocean_grid_type), intent(in) G, type(opacity_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional chl_in) private
Definition at line 209 of file MOM_opacity.F90.
References mom_error_handler::mom_error(), opacity_morel(), and sw_pen_frac_morel().
Referenced by set_opacity().
subroutine, public mom_opacity::opacity_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(tracer_flow_control_cs), intent(in), target tracer_flow, type(opacity_cs), pointer CS, type(optics_type), pointer optics)
Definition at line 423 of file MOM_opacity.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), mom_diag_mediator::register_diag_field(), mom_io::slasher(), and mom_string_functions::uppercase().
Referenced by mom_diabatic_driver::diabatic_driver_init().
real function, public mom_opacity::opacity_manizza (real, intent(in) chl_data)
Definition at line 413 of file MOM_opacity.F90.
real function, public mom_opacity::opacity_morel (real, intent(in) chl_data)
Definition at line 377 of file MOM_opacity.F90.
Referenced by opacity_from_chl().
subroutine, public mom_opacity::set_opacity (type(optics_type), intent(inout) optics, type(forcing), intent(in) fluxes, type(ocean_grid_type), intent(in) G, type(opacity_cs), pointer CS)
Definition at line 114 of file MOM_opacity.F90.
References mom_tracer_flow_control::get_chl_from_model(), mom_error_handler::mom_error(), opacity_from_chl(), and mom_diag_mediator::query_averaging_enabled().
Referenced by mom_diabatic_driver::diabatic().
real function mom_opacity::sw_pen_frac_morel (real, intent(in) chl_data) private
Definition at line 395 of file MOM_opacity.F90.
Referenced by opacity_from_chl().
Member Data Documentation
integer, parameter mom_opacity::manizza_05 = 1 private
Definition at line 107 of file MOM_opacity.F90.
character*(10), parameter mom_opacity::manizza_05_string = "MANIZZA_05" private
Definition at line 109 of file MOM_opacity.F90.
integer, parameter mom_opacity::morel_88 = 2 private
Definition at line 107 of file MOM_opacity.F90.
character*(10), parameter mom_opacity::morel_88_string = "MOREL_88" private
Definition at line 110 of file MOM_opacity.F90.
integer, parameter mom_opacity::no_scheme = 0
Definition at line 107 of file MOM_opacity.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_opacity.F90