MOM6: mom_file_parser Module Reference
mom_file_parser Module Reference
Data Types
type file_data_type
interface get_param
type link_parameter
interface log_param
type param_file_type
type parameter_block
interface read_param
Public Member Functions
subroutine, public open_param_file (filename, CS, checkable, component)
subroutine, public close_param_file (CS, quiet_close, component)
subroutine, public log_version (CS, modulename, version, desc)
subroutine, public clearparameterblock (CS)
subroutine, public openparameterblock (CS, blockName, desc)
subroutine, public closeparameterblock (CS)
Public Attributes
integer, parameter, public max_param_files = 5
Private Member Functions
subroutine populate_param_data (iounit, filename, param_data)
logical function openmultilinecomment (string)
logical function closemultilinecomment (string)
integer function lastnoncommentindex (string)
integer function lastnoncommentnonblank (string)
character(len=len(string)) function replacetabs (string)
character(len=len(string)) function removecomments (string)
character(len=len(string)+16)
function simplifywhitespace (string)
subroutine read_param_int (CS, varname, value, fail_if_missing)
subroutine read_param_int_array (CS, varname, value, fail_if_missing)
subroutine read_param_real (CS, varname, value, fail_if_missing)
subroutine read_param_real_array (CS, varname, value, fail_if_missing)
subroutine read_param_char (CS, varname, value, fail_if_missing)
subroutine read_param_char_array (CS, varname, value, fail_if_missing)
subroutine read_param_logical (CS, varname, value, fail_if_missing)
subroutine read_param_time (CS, varname, value, timeunit, fail_if_missing)
subroutine get_variable_line (CS, varname, found, defined, value_string, paramIsLogical)
subroutine flag_line_as_read (line_used, count)
logical function overridewarninghasbeenissued (chain, varName)
subroutine log_param_int (CS, modulename, varname, value, desc, units, default)
subroutine log_param_int_array (CS, modulename, varname, value, desc, units, default)
subroutine log_param_real (CS, modulename, varname, value, desc, units, default)
subroutine log_param_real_array (CS, modulename, varname, value, desc, units, default)
subroutine log_param_logical (CS, modulename, varname, value, desc, units, default)
subroutine log_param_char (CS, modulename, varname, value, desc, units, default)
subroutine log_param_time (CS, modulename, varname, value, desc, units, default, timeunit)
subroutine get_param_int (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_int_array (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_real (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_real_array (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_char (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_char_array (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_logical (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, static_value)
subroutine get_param_time (CS, modulename, varname, value, desc, units, default, fail_if_missing, do_not_read, do_not_log, timeunit, static_value)
character(len=len(oldblockname)+40)
function pushblocklevel (oldblockName, newBlockName)
character(len=len(oldblockname)+40)
function popblocklevel (oldblockName)
Private Attributes
integer, parameter input_str_length = 120
integer, parameter filename_length = 200
logical all_pes_read = .false.
logical, parameter report_unused_default = .false.
logical, parameter unused_params_fatal_default = .false.
logical, parameter log_to_stdout_default = .false.
logical, parameter complete_doc_default = .true.
logical, parameter minimal_doc_default = .true.
Detailed Description
Definition at line 1 of file MOM_file_parser.F90.
Member Function/Subroutine Documentation
subroutine, public mom_file_parser::clearparameterblock (type(param_file_type), intent(in) CS)
Definition at line 1638 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
subroutine, public mom_file_parser::close_param_file (type(param_file_type), intent(inout) CS, logical, intent(in), optional quiet_close, character(len=*), intent(in), optional component)
Definition at line 253 of file MOM_file_parser.F90.
References mom_document::doc_end(), mom_error_handler::is_root_pe(), log_version(), mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by mom_main(), ocean_model_mod::ocean_model_flux_init(), ocean_model_mod::ocean_model_init(), and shelf_main().
logical function mom_file_parser::closemultilinecomment (character(len=*), intent(in) string) private
Definition at line 458 of file MOM_file_parser.F90.
Referenced by populate_param_data().
subroutine, public mom_file_parser::closeparameterblock (type(param_file_type), intent(in) CS)
Definition at line 1667 of file MOM_file_parser.F90.
References mom_document::doc_closeblock(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and popblocklevel().
Referenced by mom_diffconvection::diffconvection_init(), and mom_kpp::kpp_init().
subroutine mom_file_parser::flag_line_as_read (logical, dimension(:), pointer line_used, integer, intent(in) count) private
Definition at line 1116 of file MOM_file_parser.F90.
Referenced by get_variable_line().
subroutine mom_file_parser::get_param_char (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, character(len=*), intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, character(len=*), intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, character(len=*), intent(in), optional static_value) private
Definition at line 1504 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_char(), and mom_file_parser::read_param::read_param_char().
subroutine mom_file_parser::get_param_char_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, character(len=*), dimension(:), intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, character(len=*), intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, character(len=*), intent(in), optional static_value) private
Definition at line 1534 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_char(), and mom_file_parser::read_param::read_param_char_array().
subroutine mom_file_parser::get_param_int (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, integer, intent(in), optional static_value) private
Definition at line 1384 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_int(), and mom_file_parser::read_param::read_param_int().
subroutine mom_file_parser::get_param_int_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, dimension(:), intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, integer, intent(in), optional static_value) private
Definition at line 1414 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_int_array(), and mom_file_parser::read_param::read_param_int_array().
subroutine mom_file_parser::get_param_logical (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, logical, intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, logical, intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, logical, intent(in), optional static_value) private
Definition at line 1574 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_logical(), and mom_file_parser::read_param::read_param_logical().
subroutine mom_file_parser::get_param_real (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, real, intent(in), optional static_value) private
Definition at line 1444 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_real(), and mom_file_parser::read_param::read_param_real().
subroutine mom_file_parser::get_param_real_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, dimension(:), intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, real, intent(in), optional static_value) private
Definition at line 1474 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_real_array(), and mom_file_parser::read_param::read_param_real_array().
subroutine mom_file_parser::get_param_time (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, type(time_type), intent(inout) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, type(time_type), intent(in), optional default, logical, intent(in), optional fail_if_missing, logical, intent(in), optional do_not_read, logical, intent(in), optional do_not_log, real, intent(in), optional timeunit, type(time_type), intent(in), optional static_value) private
Definition at line 1604 of file MOM_file_parser.F90.
References mom_file_parser::log_param::log_param_time(), and mom_file_parser::read_param::read_param_time().
subroutine mom_file_parser::get_variable_line (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, logical, intent(out) found, logical, intent(out) defined, character(len=*), dimension(:), intent(out) value_string, logical, intent(in), optional paramIsLogical) private
Definition at line 792 of file MOM_file_parser.F90.
References defined, flag_line_as_read(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), overridewarninghasbeenissued(), popblocklevel(), and pushblocklevel().
Referenced by read_param_char(), read_param_char_array(), read_param_int(), read_param_int_array(), read_param_logical(), read_param_real(), read_param_real_array(), and read_param_time().
integer function mom_file_parser::lastnoncommentindex (character(len=*), intent(in) string) private
Definition at line 466 of file MOM_file_parser.F90.
Referenced by lastnoncommentnonblank(), and openmultilinecomment().
integer function mom_file_parser::lastnoncommentnonblank (character(len=*), intent(in) string) private
Definition at line 479 of file MOM_file_parser.F90.
References lastnoncommentindex().
Referenced by populate_param_data(), and removecomments().
subroutine mom_file_parser::log_param_char (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, character(len=*), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, character(len=*), intent(in), optional default) private
Definition at line 1296 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe().
subroutine mom_file_parser::log_param_int (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default) private
Definition at line 1165 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_string_functions::left_int().
subroutine mom_file_parser::log_param_int_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, dimension(:), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default) private
Definition at line 1189 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_string_functions::left_ints().
subroutine mom_file_parser::log_param_logical (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, logical, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, logical, intent(in), optional default) private
Definition at line 1268 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe().
subroutine mom_file_parser::log_param_real (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default) private
Definition at line 1214 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_string_functions::left_real().
subroutine mom_file_parser::log_param_real_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, dimension(:), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default) private
Definition at line 1239 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_string_functions::left_reals().
subroutine mom_file_parser::log_param_time (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, type(time_type), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, type(time_type), intent(in), optional default, real, intent(in), optional timeunit) private
Definition at line 1321 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe().
subroutine, public mom_file_parser::log_version (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) version, character(len=*), intent(in), optional desc)
Definition at line 1146 of file MOM_file_parser.F90.
References mom_document::doc_module(), and mom_error_handler::is_root_pe().
Referenced by mom_diabatic_driver::adiabatic_driver_init(), mom_barotropic::barotropic_init(), benchmark_init_topog_local(), benchmark_initialization::benchmark_initialize_topography(), mom_bulk_mixed_layer::bulkmixedlayer_init(), mom_tracer_flow_control::call_tracer_register(), circle_obcs_initialization::circle_obcs_initialize_thickness(), close_param_file(), mom_continuity::continuity_init(), mom_continuity_ppm::continuity_ppm_init(), mom_controlled_forcing::controlled_forcing_init(), mom_coriolisadv::coriolisadv_init(), mom_diabatic_driver::diabatic_driver_init(), mom_diffconvection::diffconvection_init(), dome_initialization::dome_initialize_topography(), mom_entrain_diffusive::entrain_diffusive_init(), mom_obsolete_params::find_obsolete_params(), mom_geothermal::geothermal_init(), mom_hor_visc::hor_visc_init(), mom_ice_shelf::initialize_ice_shelf(), mom::initialize_mom(), mom_sponge::initialize_sponge(), mom_int_tide_input::int_tide_input_init(), mom_internal_tides::internal_tides_init(), mom_kappa_shear::kappa_shear_init(), mom_kpp::kpp_init(), mom_legacy_barotropic::legacy_barotropic_init(), mom_meke::meke_init(), meso_surface_forcing::meso_surface_forcing_init(), mom_mixed_layer_restrat::mixedlayer_restrat_init(), mom_checksums::mom_checksums_init(), mom_diag_to_z::mom_diag_to_z_init(), mom_diagnostics::mom_diagnostics_init(), mom_domains::mom_domains_init(), mom_grid::mom_grid_init(), mom_initialization::mom_initialize(), mom_io::mom_io_init(), mom_main(), mom_sum_output::mom_sum_output_init(), mom_initialization::mom_temp_salt_initialize_from_z(), mom_write_cputime::mom_write_cputime_init(), ocean_model_mod::ocean_model_init(), mom_opacity::opacity_init(), mom_open_boundary::open_boundary_init(), phillips_initialization::phillips_initialize_sponges(), phillips_initialization::phillips_initialize_thickness(), phillips_initialization::phillips_initialize_velocity(), mom_pointaccel::pointaccel_init(), mom_pressureforce_afv::pressureforce_afv_init(), mom_pressureforce::pressureforce_init(), mom_pressureforce_mont::pressureforce_mont_init(), advection_test_tracer::register_advection_test_tracer(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), mom_regularize_layers::regularize_layers_init(), mom_restart::restart_init(), mom_eos::select_eqn_of_state(), mom_diag_mediator::set_axes_info(), mom_set_diffusivity::set_diffusivity_init(), mom_grid_initialize::set_grid_metrics(), mom_set_visc::set_visc_init(), shelf_main(), mom_surface_forcing::surface_forcing_init(), mom_thickness_diffuse::thickness_diffuse_init(), mom_tidal_forcing::tidal_forcing_init(), mom_tracer_advect::tracer_advect_init(), mom_tracer_hor_diff::tracer_hor_diff_init(), mom_tracer_registry::tracer_registry_init(), user_change_diffusivity::user_change_diff_init(), user_tracer_example::user_register_tracer_example(), user_revise_forcing::user_revise_forcing_init(), user_surface_forcing::user_surface_forcing_init(), mom_lateral_mixing_coeffs::varmix_init(), mom_verticalgrid::verticalgridinit(), mom_vert_friction::vertvisc_init(), mom_wave_speed::wave_speed_init(), and user_initialization::write_user_log().
subroutine, public mom_file_parser::open_param_file (character(len=*), intent(in) filename, type(param_file_type), intent(inout) CS, logical, intent(in), optional checkable, character(len=*), intent(in), optional component)
Definition at line 142 of file MOM_file_parser.F90.
References mom_document::doc_init(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), number(), and populate_param_data().
Referenced by mom_get_input::get_mom_input(), and mom_main().
logical function mom_file_parser::openmultilinecomment (character(len=*), intent(in) string) private
Definition at line 443 of file MOM_file_parser.F90.
References lastnoncommentindex().
Referenced by populate_param_data().
subroutine, public mom_file_parser::openparameterblock (type(param_file_type), intent(in) CS, character(len=*), intent(in) blockName, character(len=*), intent(in), optional desc)
Definition at line 1651 of file MOM_file_parser.F90.
References mom_document::doc_openblock(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), and pushblocklevel().
Referenced by mom_diffconvection::diffconvection_init(), and mom_kpp::kpp_init().
logical function mom_file_parser::overridewarninghasbeenissued (type(link_parameter), pointer chain, character(len=*), intent(in) varName) private
Definition at line 1122 of file MOM_file_parser.F90.
Referenced by get_variable_line().
character(len=len(oldblockname)+40) function mom_file_parser::popblocklevel (character(len=*), intent(in) oldblockName) private
Definition at line 1696 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by closeparameterblock(), and get_variable_line().
subroutine mom_file_parser::populate_param_data (integer, intent(in) iounit, character(len=*), intent(in) filename, type(file_data_type), intent(inout) param_data) private
Definition at line 348 of file MOM_file_parser.F90.
References closemultilinecomment(), mom_error_handler::is_root_pe(), lastnoncommentnonblank(), mom_error_handler::mom_error(), openmultilinecomment(), removecomments(), replacetabs(), and simplifywhitespace().
Referenced by open_param_file().
character(len=len(oldblockname)+40) function mom_file_parser::pushblocklevel (character(len=*), intent(in) oldblockName, character(len=*), intent(in) newBlockName) private
Definition at line 1685 of file MOM_file_parser.F90.
Referenced by get_variable_line(), and openparameterblock().
subroutine mom_file_parser::read_param_char (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, character(len=*), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 680 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_char_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, character(len=*), dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 703 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_int (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, integer, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 562 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_int_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, integer, dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 591 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_logical (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, logical, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 731 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_real (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, real, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 621 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_real_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, real, dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 650 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
subroutine mom_file_parser::read_param_time (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, type(time_type), intent(inout) value, real, intent(in), optional timeunit, logical, intent(in), optional fail_if_missing) private
Definition at line 754 of file MOM_file_parser.F90.
References defined, get_variable_line(), and mom_error_handler::mom_error().
character(len=len(string)) function mom_file_parser::removecomments (character(len=*), intent(in) string) private
Definition at line 500 of file MOM_file_parser.F90.
References lastnoncommentnonblank().
Referenced by populate_param_data().
character(len=len(string)) function mom_file_parser::replacetabs (character(len=*), intent(in) string) private
Definition at line 486 of file MOM_file_parser.F90.
Referenced by populate_param_data().
character(len=len(string)+16) function mom_file_parser::simplifywhitespace (character(len=*), intent(in) string) private
Definition at line 510 of file MOM_file_parser.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by populate_param_data().
Member Data Documentation
logical mom_file_parser::all_pes_read = .false. private
Definition at line 65 of file MOM_file_parser.F90.
logical, parameter mom_file_parser::complete_doc_default = .true. private
Definition at line 71 of file MOM_file_parser.F90.
integer, parameter mom_file_parser::filename_length = 200 private
Definition at line 61 of file MOM_file_parser.F90.
integer, parameter mom_file_parser::input_str_length = 120 private
Definition at line 60 of file MOM_file_parser.F90.
logical, parameter mom_file_parser::log_to_stdout_default = .false. private
Definition at line 70 of file MOM_file_parser.F90.
integer, parameter, public mom_file_parser::max_param_files = 5
Definition at line 59 of file MOM_file_parser.F90.
logical, parameter mom_file_parser::minimal_doc_default = .true. private
Definition at line 72 of file MOM_file_parser.F90.
logical, parameter mom_file_parser::report_unused_default = .false. private
Definition at line 68 of file MOM_file_parser.F90.
logical, parameter mom_file_parser::unused_params_fatal_default = .false. private
Definition at line 69 of file MOM_file_parser.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_file_parser.F90