MOM6: user_change_diffusivity Module Reference
user_change_diffusivity Module Reference
Data Types
type user_change_diff_cs
Public Member Functions
subroutine, public user_change_diff (h, tv, G, CS, Kd, Kd_int, T_f, S_f, Kd_int_add)
subroutine, public user_change_diff_init (Time, G, param_file, diag, CS)
subroutine, public user_change_diff_end (CS)
Private Member Functions
logical function range_ok (range)
real function val_weights (val, range)
Detailed Description
Definition at line 1 of file user_change_diffusivity.F90.
Member Function/Subroutine Documentation
logical function user_change_diffusivity::range_ok (real, dimension(4), intent(in) range) private
Definition at line 183 of file user_change_diffusivity.F90.
Referenced by user_change_diff(), and user_change_diff_init().
subroutine, public user_change_diffusivity::user_change_diff (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(user_change_diff_cs), pointer CS, real, dimension(nimem_,njmem_,nkmem_), intent(inout), optional Kd, real, dimension(nimem_,njmem_,nk_interface_), intent(inout), optional Kd_int, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional T_f, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional S_f, real, dimension(:,:,:), optional, pointer Kd_int_add)
Definition at line 73 of file user_change_diffusivity.F90.
References mom_error_handler::mom_error(), range_ok(), and val_weights().
Referenced by mom_set_diffusivity::set_diffusivity().
subroutine, public user_change_diffusivity::user_change_diff_end (type(user_change_diff_cs), pointer CS)
Definition at line 292 of file user_change_diffusivity.F90.
Referenced by mom_set_diffusivity::set_diffusivity_end().
subroutine, public user_change_diffusivity::user_change_diff_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(user_change_diff_cs), pointer CS)
Definition at line 223 of file user_change_diffusivity.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and range_ok().
Referenced by mom_set_diffusivity::set_diffusivity_init().
real function user_change_diffusivity::val_weights (real, intent(in) val, real, dimension(4), intent(in) range) private
Definition at line 194 of file user_change_diffusivity.F90.
Referenced by user_change_diff().
The documentation for this module was generated from the following file:
src/user/user_change_diffusivity.F90