MOM6: mom_open_boundary Module Reference
mom_open_boundary Module Reference
Data Types
type open_boundary_cs
Public Member Functions
subroutine, public radiation_open_bdry_conds (OBC, u_new, u_old, v_new, v_old, h_new, h_old, G, CS)
subroutine, public open_boundary_init (Time, G, param_file, diag, CS)
subroutine, public open_boundary_end (CS)
Public Attributes
integer id_clock_pass
Detailed Description
Definition at line 1 of file MOM_open_boundary.F90.
Member Function/Subroutine Documentation
subroutine, public mom_open_boundary::open_boundary_end (type(open_boundary_cs), pointer CS)
Definition at line 260 of file MOM_open_boundary.F90.
subroutine, public mom_open_boundary::open_boundary_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(open_boundary_cs), pointer CS)
Definition at line 192 of file MOM_open_boundary.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
subroutine, public mom_open_boundary::radiation_open_bdry_conds (type(ocean_obc_type), pointer OBC, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) u_new, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u_old, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) v_new, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v_old, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, type(ocean_grid_type), intent(inout) G, type(open_boundary_cs), pointer CS)
Definition at line 76 of file MOM_open_boundary.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), and mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
Member Data Documentation
integer mom_open_boundary::id_clock_pass
Definition at line 72 of file MOM_open_boundary.F90.
The documentation for this module was generated from the following file:
src/core/MOM_open_boundary.F90