MOM6: mom_eos_wright Module Reference
mom_eos_wright Module Reference
Data Types
interface calculate_density_wright
Public Member Functions
subroutine, public calculate_density_scalar_wright (T, S, pressure, rho)
subroutine, public calculate_density_array_wright (T, S, pressure, rho, start, npts)
subroutine, public calculate_density_derivs_wright (T, S, pressure, drho_dT, drho_dS, start, npts)
subroutine, public calculate_compress_wright (T, S, pressure, rho, drho_dp, start, npts)
subroutine, public calculate_2_densities_wright (T, S, pressure1, pressure2, rho1, rho2, start, npts)
subroutine, public int_density_dz_wright (T, S, z_t, z_b, rho_ref, rho_0, G_e, G, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine, public int_spec_vol_dp_wright (T, S, p_t, p_b, alpha_ref, G, dza, intp_dza, intx_dza, inty_dza, halo_size)
Private Attributes
real, parameter a0 = 7.057924e-4
real, parameter a1 = 3.480336e-7
real, parameter a2 = -1.112733e-7
real, parameter b0 = 5.790749e8
real, parameter b1 = 3.516535e6
real, parameter b2 = -4.002714e4
real, parameter b3 = 2.084372e2
real, parameter b4 = 5.944068e5
real, parameter b5 = -9.643486e3
real, parameter c0 = 1.704853e5
real, parameter c1 = 7.904722e2
real, parameter c2 = -7.984422
real, parameter c3 = 5.140652e-2
real, parameter c4 = -2.302158e2
real, parameter c5 = -3.079464
Detailed Description
Definition at line 1 of file MOM_EOS_Wright.F90.
Member Function/Subroutine Documentation
subroutine, public mom_eos_wright::calculate_2_densities_wright (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, intent(in) pressure1, real, intent(in) pressure2, real, dimension(:), intent(out) rho1, real, dimension(:), intent(out) rho2, integer, intent(in) start, integer, intent(in) npts)
Definition at line 193 of file MOM_EOS_Wright.F90.
Referenced by mom_eos::calculate_2_densities().
subroutine, public mom_eos_wright::calculate_compress_wright (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts)
Definition at line 158 of file MOM_EOS_Wright.F90.
Referenced by mom_eos::calculate_compress().
subroutine, public mom_eos_wright::calculate_density_array_wright (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts)
Definition at line 95 of file MOM_EOS_Wright.F90.
subroutine, public mom_eos_wright::calculate_density_derivs_wright (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT, real, dimension(:), intent(out) drho_dS, integer, intent(in) start, integer, intent(in) npts)
Definition at line 125 of file MOM_EOS_Wright.F90.
Referenced by mom_eos::calculate_density_derivs().
subroutine, public mom_eos_wright::calculate_density_scalar_wright (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho)
Definition at line 63 of file MOM_EOS_Wright.F90.
References mom_eos_wright::calculate_density_wright::calculate_density_array_wright().
subroutine, public mom_eos_wright::int_density_dz_wright (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa)
Definition at line 227 of file MOM_EOS_Wright.F90.
Referenced by mom_eos::int_density_dz().
subroutine, public mom_eos_wright::int_spec_vol_dp_wright (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) p_t, real, dimension(nimem_,njmem_), intent(in) p_b, real, intent(in) alpha_ref, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(out) dza, real, dimension(nimem_,njmem_), intent(out), optional intp_dza, real, dimension(nimemb_,njmem_), intent(out), optional intx_dza, real, dimension(nimem_,njmemb_), intent(out), optional inty_dza, integer, intent(in), optional halo_size)
Definition at line 353 of file MOM_EOS_Wright.F90.
Referenced by mom_eos::int_specific_vol_dp().
Member Data Documentation
real, parameter mom_eos_wright::a0 = 7.057924e-4 private
Definition at line 55 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::a1 = 3.480336e-7 private
Definition at line 55 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::a2 = -1.112733e-7 private
Definition at line 55 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b0 = 5.790749e8 private
Definition at line 56 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b1 = 3.516535e6 private
Definition at line 56 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b2 = -4.002714e4 private
Definition at line 56 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b3 = 2.084372e2 private
Definition at line 57 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b4 = 5.944068e5 private
Definition at line 57 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::b5 = -9.643486e3 private
Definition at line 57 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c0 = 1.704853e5 private
Definition at line 58 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c1 = 7.904722e2 private
Definition at line 58 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c2 = -7.984422 private
Definition at line 58 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c3 = 5.140652e-2 private
Definition at line 59 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c4 = -2.302158e2 private
Definition at line 59 of file MOM_EOS_Wright.F90.
real, parameter mom_eos_wright::c5 = -3.079464 private
Definition at line 59 of file MOM_EOS_Wright.F90.
The documentation for this module was generated from the following file:
src/equation_of_state/MOM_EOS_Wright.F90