MOM6: mom_remapping Module Reference
mom_remapping Module Reference
Data Types
type remapping_cs
Public Member Functions
subroutine, public remapping_main (CS, G, h, dxInterface, tv, u, v)
subroutine, public remapping_core (CS, n0, h0, u0, n1, dx, u1)
subroutine, public dzfromh1h2 (n1, h1, n2, h2, dx)
subroutine, public initialize_remapping (nk, remappingScheme, CS)
subroutine, public setreconstructiontype (string, CS)
subroutine, public rempaenableboundaryextrapolation (CS)
subroutine, public remapdisableboundaryextrapolation (CS)
subroutine, public end_remapping (CS)
logical function, public remappingunittests ()
Public Attributes
integer, parameter remapping_pcm = 0
character(len=256), public remappingschemesdoc = "PCM (1st-order accurate)\n"// "PLM (2nd-order accurate)\n"// "PPM_H4 (3rd-order accurate)\n"// "PPM_IH4 (3rd-order accurate)\n"// "PQM_IH4IH3 (4th-order accurate)\n"// "PQM_IH6IH5 (5th-order accurate)\n"
character(len=3), public remappingdefaultscheme = "PLM"
Private Member Functions
subroutine buildgridfromh (nz, h, x)
subroutine checkconsistantcoords (ns, xs, nf, xf, strict, msg)
logical function ispossumerrsignificant (n1, sum1, n2, sum2)
subroutine sumhtimesq (nz, h, q, sumHQ, sumErr)
logical function issignedsumerrsignificant (n1, maxTerm1, sum1, n2, maxTerm2, sum2)
subroutine remapbyprojection (n0, h0, u0, ppoly0, n1, h1, method, u1)
subroutine remapbydeltaz (n0, h0, u0, ppoly0, n1, dx1, method, u1, h1)
subroutine integraterecononinterval (n0, h0, u0, ppoly0, method, xL, xR, hC, uAve)
subroutine allocate_remapping (CS)
Private Attributes
integer, parameter remapping_plm = 1
integer, parameter remapping_ppm_h4 = 2
integer, parameter remapping_ppm_ih4 = 3
integer, parameter remapping_pqm_ih4ih3 = 4
integer, parameter remapping_pqm_ih6ih5 = 5
integer, parameter integration_pcm = 0
integer, parameter integration_plm = 1
integer, parameter integration_ppm = 3
integer, parameter integration_pqm = 5
character(len=40) mod = "MOM_remapping"
Detailed Description
Definition at line 1 of file MOM_remapping.F90.
Member Function/Subroutine Documentation
subroutine mom_remapping::allocate_remapping (type(remapping_cs), intent(inout) CS) private
Definition at line 1053 of file MOM_remapping.F90.
References regrid_ppoly_class::ppoly_init(), regrid_edge_values::tridiagedgeworkallocate(), and regrid_edge_slopes::tridiagslopeworkallocate().
Referenced by setreconstructiontype().
subroutine mom_remapping::buildgridfromh (integer, intent(in) nz, real, dimension(nz), intent(in) h, real, dimension(nz+1), intent(inout) x) private
Definition at line 174 of file MOM_remapping.F90.
Referenced by remappingunittests().
subroutine mom_remapping::checkconsistantcoords (integer, intent(in) ns, real, dimension(ns+1), intent(in) xs, integer, intent(in) nf, real, dimension(nf+1), intent(in) xf, logical, intent(in) strict, character(len=*), intent(in) msg) private
Definition at line 198 of file MOM_remapping.F90.
References ispossumerrsignificant(), and mom_error_handler::mom_error().
subroutine, public mom_remapping::dzfromh1h2 (integer, intent(in) n1, real, dimension(:), intent(in) h1, integer, intent(in) n2, real, dimension(:), intent(in) h2, real, dimension(:), intent(out) dx)
Definition at line 921 of file MOM_remapping.F90.
References mom_error_handler::mom_error().
Referenced by mom_initialization::mom_temp_salt_initialize_from_z(), and remappingunittests().
subroutine, public mom_remapping::end_remapping (type(remapping_cs), intent(inout) CS)
Definition at line 1067 of file MOM_remapping.F90.
References regrid_ppoly_class::ppoly_destroy(), regrid_edge_values::tridiagedgeworkdeallocate(), and regrid_edge_slopes::tridiagslopeworkdeallocate().
Referenced by mom_ale::end_ale(), and setreconstructiontype().
subroutine, public mom_remapping::initialize_remapping (integer, intent(in) nk, character(len=*), intent(in) remappingScheme, type(remapping_cs), intent(inout) CS)
Definition at line 971 of file MOM_remapping.F90.
References setreconstructiontype().
Referenced by mom_ale::initialize_ale(), mom_initialization::mom_temp_salt_initialize_from_z(), and remappingunittests().
subroutine mom_remapping::integraterecononinterval (integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) u0, type(ppoly_t), intent(in) ppoly0, integer, intent(in) method, real, intent(in) xL, real, intent(in) xR, real, intent(in) hC, real, intent(out) uAve) private
Definition at line 679 of file MOM_remapping.F90.
References polynomial_functions::evaluation_polynomial(), polynomial_functions::integration_polynomial(), and mom_error_handler::mom_error().
Referenced by remapbydeltaz(), and remapbyprojection().
logical function mom_remapping::ispossumerrsignificant (integer, intent(in) n1, real, intent(in) sum1, integer, intent(in) n2, real, intent(in) sum2) private
Definition at line 249 of file MOM_remapping.F90.
References mom_error_handler::mom_error().
Referenced by checkconsistantcoords().
logical function mom_remapping::issignedsumerrsignificant (integer, intent(in) n1, real, intent(in) maxTerm1, real, intent(in) sum1, integer, intent(in) n2, real, intent(in) maxTerm2, real, intent(in) sum2) private
Definition at line 325 of file MOM_remapping.F90.
subroutine mom_remapping::remapbydeltaz (integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) u0, type(ppoly_t), intent(in) ppoly0, integer, intent(in) n1, real, dimension(:), intent(in) dx1, integer method, real, dimension(:), intent(out) u1, real, dimension(:), intent(out), optional h1) private
Definition at line 564 of file MOM_remapping.F90.
References integraterecononinterval(), and mom_error_handler::mom_error().
Referenced by remapping_core(), and remappingunittests().
subroutine mom_remapping::remapbyprojection (integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) u0, type(ppoly_t), intent(in) ppoly0, integer, intent(in) n1, real, dimension(:), intent(in) h1, integer, intent(in) method, real, dimension(:), intent(out) u1) private
Definition at line 529 of file MOM_remapping.F90.
References integraterecononinterval().
Referenced by remappingunittests().
subroutine, public mom_remapping::remapdisableboundaryextrapolation (type(remapping_cs), intent(inout) CS)
Definition at line 1044 of file MOM_remapping.F90.
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().
subroutine, public mom_remapping::remapping_core (type(remapping_cs), intent(inout) CS, integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) u0, integer, intent(in) n1, real, dimension(:), intent(in) dx, real, dimension(:), intent(out) u1)
Definition at line 359 of file MOM_remapping.F90.
References regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), regrid_edge_values::edge_values_implicit_h6(), mom_error_handler::mom_error(), pcm_functions::pcm_reconstruction(), plm_functions::plm_boundary_extrapolation(), plm_functions::plm_reconstruction(), ppm_functions::ppm_boundary_extrapolation(), ppm_functions::ppm_reconstruction(), pqm_functions::pqm_boundary_extrapolation_v1(), pqm_functions::pqm_reconstruction(), and remapbydeltaz().
Referenced by mom_regridding::buildgridrho(), mom_initialization::mom_temp_salt_initialize_from_z(), remapping_main(), and remappingunittests().
subroutine, public mom_remapping::remapping_main (type(remapping_cs), intent(inout) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nk_interface_), intent(in) dxInterface, type(thermo_var_ptrs), intent(inout) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), optional u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), optional v)
Definition at line 99 of file MOM_remapping.F90.
References remapping_core().
Referenced by mom_ale::ale_main().
logical function, public mom_remapping::remappingunittests ()
Definition at line 1078 of file MOM_remapping.F90.
References buildgridfromh(), dumpgrid(), dzfromh1h2(), regrid_edge_values::edge_values_explicit_h4(), initialize_remapping(), ppm_functions::ppm_boundary_extrapolation(), ppm_functions::ppm_reconstruction(), regrid_ppoly_class::ppoly_init(), remapbydeltaz(), remapbyprojection(), and remapping_core().
Referenced by mom::unittests().
subroutine, public mom_remapping::rempaenableboundaryextrapolation (type(remapping_cs), intent(inout) CS)
Definition at line 1035 of file MOM_remapping.F90.
subroutine, public mom_remapping::setreconstructiontype (character(len=*), intent(in) string, type(remapping_cs), intent(inout) CS)
Definition at line 990 of file MOM_remapping.F90.
References allocate_remapping(), end_remapping(), mom_error_handler::mom_error(), and mom_string_functions::uppercase().
Referenced by initialize_remapping().
subroutine mom_remapping::sumhtimesq (integer, intent(in) nz, real, dimension(nz), intent(in) h, real, dimension(nz), intent(in) q, real, intent(out) sumHQ, real, intent(out), optional sumErr) private
Definition at line 285 of file MOM_remapping.F90.
Member Data Documentation
integer, parameter mom_remapping::integration_pcm = 0 private
Definition at line 71 of file MOM_remapping.F90.
integer, parameter mom_remapping::integration_plm = 1 private
Definition at line 72 of file MOM_remapping.F90.
integer, parameter mom_remapping::integration_ppm = 3 private
Definition at line 73 of file MOM_remapping.F90.
integer, parameter mom_remapping::integration_pqm = 5 private
Definition at line 74 of file MOM_remapping.F90.
character(len=40) mom_remapping::mod = "MOM_remapping" private
Definition at line 76 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_pcm = 0
Definition at line 63 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_plm = 1 private
Definition at line 64 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_ppm_h4 = 2 private
Definition at line 65 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_ppm_ih4 = 3 private
Definition at line 66 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_pqm_ih4ih3 = 4 private
Definition at line 67 of file MOM_remapping.F90.
integer, parameter mom_remapping::remapping_pqm_ih6ih5 = 5 private
Definition at line 68 of file MOM_remapping.F90.
character(len=3), public mom_remapping::remappingdefaultscheme = "PLM"
Definition at line 86 of file MOM_remapping.F90.
character(len=256), public mom_remapping::remappingschemesdoc = "PCM (1st-order accurate)\n"// "PLM (2nd-order accurate)\n"// "PPM_H4 (3rd-order accurate)\n"// "PPM_IH4 (3rd-order accurate)\n"// "PQM_IH4IH3 (4th-order accurate)\n"// "PQM_IH6IH5 (5th-order accurate)\n"
Definition at line 79 of file MOM_remapping.F90.
The documentation for this module was generated from the following file:
src/ALE/MOM_remapping.F90