MOM6: mom_eos_linear Module Reference
mom_eos_linear Module Reference
Data Types
interface calculate_density_linear
Public Member Functions
subroutine, public calculate_density_scalar_linear (T, S, pressure, rho, Rho_T0_S0, dRho_dT, dRho_dS)
subroutine, public calculate_density_array_linear (T, S, pressure, rho, start, npts, Rho_T0_S0, dRho_dT, dRho_dS)
subroutine, public calculate_density_derivs_linear (T, S, pressure, drho_dT_out, drho_dS_out, start, npts, Rho_T0_S0, dRho_dT, dRho_dS)
subroutine, public calculate_compress_linear (T, S, pressure, rho, drho_dp, start, npts, Rho_T0_S0, dRho_dT, dRho_dS)
subroutine, public calculate_2_densities_linear (T, S, pressure1, pressure2, rho1, rho2, start, npts, Rho_T0_S0, dRho_dT, dRho_dS)
subroutine, public int_density_dz_linear (T, S, z_t, z_b, rho_ref, rho_0_pres, G_e, G, Rho_T0_S0, dRho_dT, dRho_dS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine, public int_spec_vol_dp_linear (T, S, p_t, p_b, alpha_ref, G, Rho_T0_S0, dRho_dT, dRho_dS, dza, intp_dza, intx_dza, inty_dza, halo_size)
Detailed Description
Definition at line 1 of file MOM_EOS_linear.F90.
Member Function/Subroutine Documentation
subroutine, public mom_eos_linear::calculate_2_densities_linear (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, intent(in) pressure1, real, intent(in) pressure2, real, dimension(:), intent(out) rho1, real, dimension(:), intent(out) rho2, integer, intent(in) start, integer, intent(in) npts, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS)
Definition at line 156 of file MOM_EOS_linear.F90.
Referenced by mom_eos::calculate_2_densities().
subroutine, public mom_eos_linear::calculate_compress_linear (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS)
Definition at line 125 of file MOM_EOS_linear.F90.
Referenced by mom_eos::calculate_compress().
subroutine, public mom_eos_linear::calculate_density_array_linear (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS)
Definition at line 68 of file MOM_EOS_linear.F90.
subroutine, public mom_eos_linear::calculate_density_derivs_linear (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT_out, real, dimension(:), intent(out) drho_dS_out, integer, intent(in) start, integer, intent(in) npts, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS)
Definition at line 95 of file MOM_EOS_linear.F90.
Referenced by mom_eos::calculate_density_derivs().
subroutine, public mom_eos_linear::calculate_density_scalar_linear (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS)
Definition at line 45 of file MOM_EOS_linear.F90.
subroutine, public mom_eos_linear::int_density_dz_linear (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) z_t, real, dimension(nimem_,njmem_), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0_pres, real, intent(in) G_e, type(ocean_grid_type), intent(in) G, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS, real, dimension(nimem_,njmem_), intent(out) dpa, real, dimension(nimem_,njmem_), intent(out), optional intz_dpa, real, dimension(nimemb_,njmem_), intent(out), optional intx_dpa, real, dimension(nimem_,njmemb_), intent(out), optional inty_dpa)
Definition at line 186 of file MOM_EOS_linear.F90.
Referenced by mom_eos::int_density_dz().
subroutine, public mom_eos_linear::int_spec_vol_dp_linear (real, dimension(nimem_,njmem_), intent(in) T, real, dimension(nimem_,njmem_), intent(in) S, real, dimension(nimem_,njmem_), intent(in) p_t, real, dimension(nimem_,njmem_), intent(in) p_b, real, intent(in) alpha_ref, type(ocean_grid_type), intent(in) G, real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS, real, dimension(nimem_,njmem_), intent(out) dza, real, dimension(nimem_,njmem_), intent(out), optional intp_dza, real, dimension(nimemb_,njmem_), intent(out), optional intx_dza, real, dimension(nimem_,njmemb_), intent(out), optional inty_dza, integer, intent(in), optional halo_size)
Definition at line 257 of file MOM_EOS_linear.F90.
Referenced by mom_eos::int_specific_vol_dp().
The documentation for this module was generated from the following file:
src/equation_of_state/MOM_EOS_linear.F90