MOM6: mom_vert_friction Module Reference
mom_vert_friction Module Reference
Data Types
type vertvisc_cs
Public Member Functions
subroutine, public vertvisc (u, v, h, fluxes, visc, dt, OBC, ADp, CDp, G, CS, taux_bot, tauy_bot)
subroutine, public vertvisc_remnant (visc, visc_rem_u, visc_rem_v, dt, G, CS)
subroutine, public vertvisc_coef (u, v, h, fluxes, visc, dt, G, CS)
subroutine, public vertvisc_limit_vel (u, v, h, ADp, CDp, fluxes, visc, dt, G, CS)
subroutine, public vertvisc_init (MIS, Time, G, param_file, diag, ADp, dirs, ntrunc, CS)
subroutine, public updatecfltruncationvalue (Time, CS, activate)
subroutine, public vertvisc_end (CS)
Detailed Description
Definition at line 1 of file MOM_vert_friction.F90.
Member Function/Subroutine Documentation
subroutine, public mom_vert_friction::updatecfltruncationvalue (type(time_type), intent(in), target Time, type(vertvisc_cs), pointer CS, logical, intent(in), optional activate)
Definition at line 1425 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_split_rk2::initialize_dyn_split_rk2(), and mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
subroutine, public mom_vert_friction::vertvisc (real, dimension(nimemb_,njmem_,nkmem_), intent(inout) u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(inout) visc, real, intent(in) dt, type(ocean_obc_type), pointer OBC, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, type(ocean_grid_type), intent(in) G, type(vertvisc_cs), pointer CS, real, dimension(nimemb_,njmem_), intent(out), optional taux_bot, real, dimension(nimem_,njmemb_), intent(out), optional tauy_bot)
Definition at line 177 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error(), and vertvisc_limit_vel().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_vert_friction::vertvisc_coef (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(vertvisc_cs), pointer CS)
Definition at line 539 of file MOM_vert_friction.F90.
References find_coupling_coef(), and mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_vert_friction::vertvisc_end (type(vertvisc_cs), pointer CS)
Definition at line 1463 of file MOM_vert_friction.F90.
subroutine, public mom_vert_friction::vertvisc_init (type(ocean_internal_state), intent(in), target MIS, type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(accel_diag_ptrs), intent(inout) ADp, type(directories), intent(in) dirs, integer, intent(inout), target ntrunc, type(vertvisc_cs), pointer CS)
Definition at line 1245 of file MOM_vert_friction.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_pointaccel::pointaccel_init(), and mom_diag_mediator::register_diag_field().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
subroutine, public mom_vert_friction::vertvisc_limit_vel (real, dimension(nimemb_,njmem_,nkmem_), intent(inout) u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(vertvisc_cs), pointer CS)
Definition at line 1078 of file MOM_vert_friction.F90.
References mom_pointaccel::write_u_accel(), and mom_pointaccel::write_v_accel().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), and vertvisc().
subroutine, public mom_vert_friction::vertvisc_remnant (type(vertvisc_type), intent(in) visc, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) visc_rem_u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) visc_rem_v, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(vertvisc_cs), pointer CS)
Definition at line 431 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), and mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_vert_friction.F90