MOM6: mom_internal_tides Module Reference
mom_internal_tides Module Reference
Data Types
type int_tide_cs
type loop_bounds_type
Public Member Functions
subroutine, public propagate_int_tide (cg1, En_in, vel_btTide, dt, G, CS)
subroutine, public register_int_tide_restarts (G, param_file, CS, restart_CS)
subroutine, public internal_tides_init (Time, G, param_file, diag, CS)
subroutine, public internal_tides_end (CS)
Private Member Functions
subroutine refract (En, cg, freq, dt, G, NAngle)
subroutine propagate (En, cg, freq, dt, G, CS, NAngle)
subroutine propagate_x (En, speed_x, Cgx_av, dCgx, dt, G, CS, LB)
subroutine propagate_y (En, speed_y, Cgy_av, dCgy, dt, G, CS, LB)
subroutine zonal_flux_en (u, h, hL, hR, uh, dt, G, j, ish, ieh, vol_CFL)
subroutine merid_flux_en (v, h, hL, hR, vh, dt, G, J, ish, ieh, vol_CFL)
subroutine correct_halo_rotation (En, test, G, NAngle)
subroutine ppm_reconstruction_x (h_in, h_l, h_r, G, LB, simple_2nd)
subroutine ppm_reconstruction_y (h_in, h_l, h_r, G, LB, simple_2nd)
subroutine ppm_limit_pos (h_in, h_L, h_R, h_min, iis, iie, jis, jie)
Detailed Description
Definition at line 1 of file MOM_internal_tides.F90.
Member Function/Subroutine Documentation
subroutine mom_internal_tides::correct_halo_rotation (real, dimension(:,:,:,:,:), intent(inout) En, real, dimension(nimem_,njmem_,c2_), intent(in) test, type(ocean_grid_type), intent(in) G, integer, intent(in) NAngle) private
Definition at line 635 of file MOM_internal_tides.F90.
References mom_error_handler::mom_error().
Referenced by propagate_int_tide().
subroutine, public mom_internal_tides::internal_tides_end (type(int_tide_cs), pointer CS)
Definition at line 1129 of file MOM_internal_tides.F90.
subroutine, public mom_internal_tides::internal_tides_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(int_tide_cs), pointer CS)
Definition at line 959 of file MOM_internal_tides.F90.
References mom_diag_mediator::defineaxes(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
subroutine mom_internal_tides::merid_flux_en (real, dimension(nimem_), intent(in) v, real, dimension(nimem_,njmem_), intent(in) h, real, dimension(nimem_,njmem_), intent(in) hL, real, dimension(nimem_,njmem_), intent(in) hR, real, dimension(nimem_), intent(inout) vh, real, intent(in) dt, type(ocean_grid_type), intent(in) G, integer, intent(in) J, integer, intent(in) ish, integer, intent(in) ieh, logical, intent(in) vol_CFL) private
Definition at line 589 of file MOM_internal_tides.F90.
Referenced by propagate_y().
subroutine mom_internal_tides::ppm_limit_pos (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(inout) h_L, real, dimension(nimem_,njmem_), intent(inout) h_R, real, intent(in) h_min, integer, intent(in) iis, integer, intent(in) iie, integer, intent(in) jis, integer, intent(in) jie) private
Definition at line 850 of file MOM_internal_tides.F90.
subroutine mom_internal_tides::ppm_reconstruction_x (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(out) h_l, real, dimension(nimem_,njmem_), intent(out) h_r, type(ocean_grid_type), intent(in) G, type(loop_bounds_type), intent(in) LB, logical, intent(in), optional simple_2nd) private
Definition at line 689 of file MOM_internal_tides.F90.
References mom_error_handler::mom_error(), and mom_continuity_ppm::ppm_limit_pos().
subroutine mom_internal_tides::ppm_reconstruction_y (real, dimension(nimem_,njmem_), intent(in) h_in, real, dimension(nimem_,njmem_), intent(out) h_l, real, dimension(nimem_,njmem_), intent(out) h_r, type(ocean_grid_type), intent(in) G, type(loop_bounds_type), intent(in) LB, logical, intent(in), optional simple_2nd) private
Definition at line 770 of file MOM_internal_tides.F90.
References mom_error_handler::mom_error(), and mom_continuity_ppm::ppm_limit_pos().
subroutine mom_internal_tides::propagate (real, dimension(g%isd:g%ied,g%jsd:g%jed,nangle), intent(inout) En, real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(in) cg, real, intent(in) freq, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(int_tide_cs), pointer CS, integer, intent(in) NAngle) private
Definition at line 352 of file MOM_internal_tides.F90.
References propagate_x(), and propagate_y().
Referenced by propagate_int_tide().
subroutine, public mom_internal_tides::propagate_int_tide (real, dimension(nimem_,njmem_), intent(in) cg1, real, dimension(nimem_,njmem_), intent(in) En_in, real, dimension(nimem_,njmem_), intent(in) vel_btTide, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(int_tide_cs), pointer CS)
Definition at line 107 of file MOM_internal_tides.F90.
References correct_halo_rotation(), mom_error_handler::mom_error(), propagate(), mom_diag_mediator::query_averaging_enabled(), and refract().
Referenced by mom_diabatic_driver::diabatic().
subroutine mom_internal_tides::propagate_x (real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(inout) En, real, dimension(g%isdb:g%iedb,g%jsd:g%jed), intent(in) speed_x, real, intent(in) Cgx_av, real, intent(in) dCgx, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(int_tide_cs), pointer CS, type(loop_bounds_type), intent(in) LB) private
Definition at line 434 of file MOM_internal_tides.F90.
References mom_continuity_ppm::ppm_reconstruction_x(), and zonal_flux_en().
Referenced by propagate().
subroutine mom_internal_tides::propagate_y (real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(inout) En, real, dimension(g%isd:g%ied,g%jsdb:g%jedb), intent(in) speed_y, real, intent(in) Cgy_av, real, intent(in) dCgy, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(int_tide_cs), pointer CS, type(loop_bounds_type), intent(in) LB) private
Definition at line 489 of file MOM_internal_tides.F90.
References merid_flux_en(), and mom_continuity_ppm::ppm_reconstruction_y().
Referenced by propagate().
subroutine mom_internal_tides::refract (real, dimension(g%isd:g%ied,g%jsd:g%jed,nangle), intent(inout) En, real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(in) cg, real, intent(in) freq, real, intent(in) dt, type(ocean_grid_type), intent(in) G, integer, intent(in) NAngle) private
Definition at line 245 of file MOM_internal_tides.F90.
References mom_error_handler::mom_error().
Referenced by propagate_int_tide().
subroutine, public mom_internal_tides::register_int_tide_restarts (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(int_tide_cs), pointer CS, type(mom_restart_cs), pointer restart_CS)
Definition at line 894 of file MOM_internal_tides.F90.
References mom_error_handler::mom_error().
subroutine mom_internal_tides::zonal_flux_en (real, dimension(nimemb_), intent(in) u, real, dimension(nimem_), intent(in) h, real, dimension(nimem_), intent(in) hL, real, dimension(nimem_), intent(in) hR, real, dimension(nimemb_), intent(inout) uh, real, intent(in) dt, type(ocean_grid_type), intent(in) G, integer, intent(in) j, integer, intent(in) ish, integer, intent(in) ieh, logical, intent(in) vol_CFL) private
Definition at line 543 of file MOM_internal_tides.F90.
Referenced by propagate_x().
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_internal_tides.F90