MOM6: mom_pressureforce_afv Module Reference
mom_pressureforce_afv Module Reference
Data Types
type pressureforce_afv_cs
Public Member Functions
subroutine, public pressureforce_afv (h, tv, PFu, PFv, G, CS, ALE_CSp, p_atm, pbce, eta)
subroutine, public pressureforce_afv_nonbouss (h, tv, PFu, PFv, G, CS, p_atm, pbce, eta)
subroutine, public pressureforce_afv_bouss (h, tv, PFu, PFv, G, CS, ALE_CSp, p_atm, pbce, eta)
subroutine, public pressureforce_afv_init (Time, G, param_file, diag, CS, tides_CSp)
subroutine, public pressureforce_afv_end (CS)
Detailed Description
Definition at line 1 of file MOM_PressureForce_analytic_FV.F90.
Member Function/Subroutine Documentation
subroutine, public mom_pressureforce_afv::pressureforce_afv (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(inout) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_afv_cs), pointer CS, type(ale_cs), pointer ALE_CSp, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 96 of file MOM_PressureForce_analytic_FV.F90.
References pressureforce_afv_bouss(), and pressureforce_afv_nonbouss().
subroutine, public mom_pressureforce_afv::pressureforce_afv_bouss (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_afv_cs), pointer CS, type(ale_cs), pointer ALE_CSp, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 405 of file MOM_PressureForce_analytic_FV.F90.
References mom_tidal_forcing::calc_tidal_forcing(), mom_eos::int_density_dz(), mom_eos::int_density_dz_generic_plm(), mom_eos::int_density_dz_generic_ppm(), mom_error_handler::mom_error(), mom_ale::pressure_gradient_plm(), mom_ale::pressure_gradient_ppm(), mom_ale::pressurereconstructionscheme(), mom_pressureforce_mont::set_pbce_bouss(), and mom_ale::usepressurereconstruction().
Referenced by mom_pressureforce::pressureforce(), and pressureforce_afv().
subroutine, public mom_pressureforce_afv::pressureforce_afv_end (type(pressureforce_afv_cs), pointer CS)
Definition at line 791 of file MOM_PressureForce_analytic_FV.F90.
subroutine, public mom_pressureforce_afv::pressureforce_afv_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(pressureforce_afv_cs), pointer CS, type(tidal_forcing_cs), optional, pointer tides_CSp)
Definition at line 734 of file MOM_PressureForce_analytic_FV.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_pressureforce::pressureforce_init().
subroutine, public mom_pressureforce_afv::pressureforce_afv_nonbouss (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) PFu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) PFv, type(ocean_grid_type), intent(in) G, type(pressureforce_afv_cs), pointer CS, real, dimension(:,:), optional, pointer p_atm, real, dimension(nimem_,njmem_,nkmem_), intent(out), optional pbce, real, dimension(nimem_,njmem_), intent(out), optional eta)
Definition at line 121 of file MOM_PressureForce_analytic_FV.F90.
References mom_tidal_forcing::calc_tidal_forcing(), mom_eos::int_specific_vol_dp(), mom_error_handler::mom_error(), and mom_pressureforce_mont::set_pbce_nonbouss().
Referenced by mom_pressureforce::pressureforce(), and pressureforce_afv().
The documentation for this module was generated from the following file:
src/core/MOM_PressureForce_analytic_FV.F90