MOM6: mom_tracer_advect Module Reference
mom_tracer_advect Module Reference
Data Types
type tracer_advect_cs
Public Member Functions
subroutine, public advect_tracer (h_end, uhtr, vhtr, OBC, dt, G, CS, Reg)
subroutine, public tracer_advect_init (Time, G, param_file, diag, CS)
subroutine, public tracer_advect_end (CS)
Public Attributes
integer id_clock_advect
Private Member Functions
subroutine advect_x (Tr, hprev, uhr, uh_neglect, OBC, domore_u, ntr, Idt, is, ie, js, je, k, G, usePPM)
subroutine advect_y (Tr, hprev, vhr, vh_neglect, OBC, domore_v, ntr, Idt, is, ie, js, je, k, G, usePPM)
Private Attributes
integer id_clock_pass
integer id_clock_sync
Detailed Description
Definition at line 1 of file MOM_tracer_advect.F90.
Member Function/Subroutine Documentation
subroutine, public mom_tracer_advect::advect_tracer (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_end, real, dimension(nimemb_,njmem_,nkmem_), intent(in) uhtr, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vhtr, type(ocean_obc_type), pointer OBC, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(tracer_advect_cs), pointer CS, type(tracer_registry_type), pointer Reg)
Definition at line 89 of file MOM_tracer_advect.F90.
References advect_x(), advect_y(), and mom_error_handler::mom_error().
Referenced by mom::step_mom().
subroutine mom_tracer_advect::advect_x (type(tracer_type), dimension(ntr), intent(inout) Tr, real, dimension(nimem_,njmem_,nkmem_), intent(inout) hprev, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) uhr, real, dimension(nimemb_,njmem_), intent(inout) uh_neglect, type(ocean_obc_type), pointer OBC, logical, dimension(njmem_,nkmem_), intent(inout) domore_u, integer, intent(in) ntr, real, intent(in) Idt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) k, type(ocean_grid_type), intent(inout) G, logical, intent(in) usePPM) private
Definition at line 305 of file MOM_tracer_advect.F90.
Referenced by advect_tracer().
subroutine mom_tracer_advect::advect_y (type(tracer_type), dimension(ntr), intent(inout) Tr, real, dimension(nimem_,njmem_,nkmem_), intent(inout) hprev, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) vhr, real, dimension(nimem_,njmemb_), intent(inout) vh_neglect, type(ocean_obc_type), pointer OBC, logical, dimension(njmemb_,nkmem_), intent(inout) domore_v, integer, intent(in) ntr, real, intent(in) Idt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) k, type(ocean_grid_type), intent(inout) G, logical, intent(in) usePPM) private
Definition at line 549 of file MOM_tracer_advect.F90.
Referenced by advect_tracer().
subroutine, public mom_tracer_advect::tracer_advect_end (type(tracer_advect_cs), pointer CS)
Definition at line 847 of file MOM_tracer_advect.F90.
Referenced by mom::mom_end().
subroutine, public mom_tracer_advect::tracer_advect_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(tracer_advect_cs), pointer CS)
Definition at line 795 of file MOM_tracer_advect.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
Member Data Documentation
integer mom_tracer_advect::id_clock_advect
Definition at line 85 of file MOM_tracer_advect.F90.
integer mom_tracer_advect::id_clock_pass private
Definition at line 85 of file MOM_tracer_advect.F90.
integer mom_tracer_advect::id_clock_sync private
Definition at line 85 of file MOM_tracer_advect.F90.
The documentation for this module was generated from the following file:
src/tracer/MOM_tracer_advect.F90