MOM6: meso_surface_forcing Module Reference
meso_surface_forcing Module Reference
Data Types
type meso_surface_forcing_cs
Public Member Functions
subroutine, public meso_wind_forcing (state, fluxes, day, G, CS)
subroutine, public meso_buoyancy_forcing (state, fluxes, day, dt, G, CS)
subroutine, public meso_surface_forcing_init (Time, G, param_file, diag, CS)
Public Attributes
logical first_call = .true.
Private Member Functions
subroutine alloc_if_needed (ptr, isd, ied, jsd, jed)
Detailed Description
Definition at line 1 of file MESO_surface_forcing.F90.
Member Function/Subroutine Documentation
subroutine meso_surface_forcing::alloc_if_needed (real, dimension(:,:), pointer ptr, integer isd, integer ied, integer jsd, integer jed) private
Definition at line 339 of file MESO_surface_forcing.F90.
subroutine, public meso_surface_forcing::meso_buoyancy_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(meso_surface_forcing_cs), pointer CS)
Definition at line 179 of file MESO_surface_forcing.F90.
References user_surface_forcing::alloc_if_needed(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::set_forcing().
subroutine, public meso_surface_forcing::meso_surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(meso_surface_forcing_cs), pointer CS)
Definition at line 351 of file MESO_surface_forcing.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_io::slasher().
Referenced by mom_surface_forcing::surface_forcing_init().
subroutine, public meso_surface_forcing::meso_wind_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(meso_surface_forcing_cs), pointer CS)
Definition at line 116 of file MESO_surface_forcing.F90.
References user_surface_forcing::alloc_if_needed(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::set_forcing().
Member Data Documentation
logical meso_surface_forcing::first_call = .true.
Definition at line 112 of file MESO_surface_forcing.F90.
The documentation for this module was generated from the following file:
config_src/solo_driver/MESO_surface_forcing.F90