MOM6: mom_surface_forcing Module Reference
mom_surface_forcing Module Reference
Data Types
type ice_ocean_boundary_type
type surface_forcing_cs
Public Member Functions
subroutine, public convert_iob_to_fluxes (IOB, fluxes, index_bounds, Time, G, CS, state, restore_salt)
subroutine, public average_forcing (fluxes, dt, G, CS)
subroutine, public forcing_save_restart (CS, G, Time, directory, time_stamped, filename_suffix)
subroutine, public surface_forcing_init (Time, G, param_file, diag, CS, restore_salt)
subroutine, public ice_ocn_bnd_type_chksum (id, timestep, iobt)
subroutine, public set_forcing (state, fluxes, day_start, day_interval, G, CS)
subroutine, public average_forcing (fluxes, dt, G, CS)
subroutine, public forcing_save_restart (CS, G, Time, directory, time_stamped, filename_suffix)
subroutine, public surface_forcing_init (Time, G, param_file, diag, CS, tracer_flow_CSp)
subroutine, public set_forcing (state, fluxes, day_start, day_interval, G, CS)
subroutine, public average_forcing (fluxes, dt, G, CS)
subroutine, public forcing_save_restart (CS, G, Time, directory, time_stamped, filename_suffix)
subroutine, public surface_forcing_init (Time, G, param_file, diag, CS, tracer_flow_CSp)
Public Attributes
integer id_clock_forcing
Private Member Functions
subroutine surface_forcing_end (CS, fluxes)
subroutine wind_forcing_zero (state, fluxes, day, G, CS)
subroutine wind_forcing_2gyre (state, fluxes, day, G, CS)
subroutine wind_forcing_1gyre (state, fluxes, day, G, CS)
subroutine wind_forcing_gyres (state, fluxes, day, G, CS)
subroutine wind_forcing_from_file (state, fluxes, day, G, CS)
subroutine buoyancy_forcing_from_files (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_zero (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_linear (state, fluxes, day, dt, G, CS)
subroutine surface_forcing_end (CS, fluxes)
subroutine wind_forcing_zero (state, fluxes, day, G, CS)
subroutine wind_forcing_2gyre (state, fluxes, day, G, CS)
subroutine wind_forcing_1gyre (state, fluxes, day, G, CS)
subroutine wind_forcing_gyres (state, fluxes, day, G, CS)
subroutine wind_forcing_from_file (state, fluxes, day, G, CS)
subroutine wind_forcing_by_data_override (state, fluxes, day, G, CS)
subroutine buoyancy_forcing_from_files (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_from_data_override (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_zero (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_const (state, fluxes, day, dt, G, CS)
subroutine buoyancy_forcing_linear (state, fluxes, day, dt, G, CS)
subroutine surface_forcing_end (CS, fluxes)
Detailed Description
Definition at line 1 of file MOM_surface_forcing.F90.
Member Function/Subroutine Documentation
subroutine, public mom_surface_forcing::average_forcing (type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS)
Definition at line 652 of file MOM_surface_forcing.F90.
References mom_diag_mediator::query_averaging_enabled().
Referenced by mom_main(), and ocean_model_mod::update_ocean_model().
subroutine, public mom_surface_forcing::average_forcing (type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS)
Definition at line 1087 of file MOM_surface_forcing.F90.
References mom_diag_mediator::query_averaging_enabled().
subroutine, public mom_surface_forcing::average_forcing (type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS)
Definition at line 1654 of file MOM_surface_forcing.F90.
References mom_diag_mediator::query_averaging_enabled().
subroutine mom_surface_forcing::buoyancy_forcing_const (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS) private
Definition at line 1444 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine mom_surface_forcing::buoyancy_forcing_from_data_override (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 1114 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error().
Referenced by set_forcing().
subroutine mom_surface_forcing::buoyancy_forcing_from_files (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 775 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error().
subroutine mom_surface_forcing::buoyancy_forcing_from_files (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 596 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error().
Referenced by set_forcing().
subroutine mom_surface_forcing::buoyancy_forcing_linear (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS) private
Definition at line 951 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error().
Referenced by set_forcing().
subroutine mom_surface_forcing::buoyancy_forcing_linear (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS) private
Definition at line 1520 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error().
subroutine mom_surface_forcing::buoyancy_forcing_zero (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS) private
Definition at line 1349 of file MOM_surface_forcing.F90.
subroutine mom_surface_forcing::buoyancy_forcing_zero (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(surface_forcing_cs), pointer CS) private
Definition at line 856 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine, public mom_surface_forcing::convert_iob_to_fluxes (type(ice_ocean_boundary_type), intent(in), target IOB, type(forcing), intent(inout) fluxes, integer, dimension(4), intent(in) index_bounds, type(time_type), intent(in) Time, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS, type(surface), intent(in) state, logical, intent(in), optional restore_salt)
Definition at line 208 of file MOM_surface_forcing.F90.
References user_revise_forcing::user_alter_forcing().
Referenced by ocean_model_mod::update_ocean_model().
subroutine, public mom_surface_forcing::forcing_save_restart (type(surface_forcing_cs), pointer CS, type(ocean_grid_type), intent(inout) G, type(time_type), intent(in) Time, character(len=*), intent(in) directory, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename_suffix)
Definition at line 1190 of file MOM_surface_forcing.F90.
References mom_restart::save_restart().
subroutine, public mom_surface_forcing::forcing_save_restart (type(surface_forcing_cs), pointer CS, type(ocean_grid_type), intent(inout) G, type(time_type), intent(in) Time, character(len=*), intent(in) directory, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename_suffix)
Definition at line 1757 of file MOM_surface_forcing.F90.
References mom_restart::save_restart().
subroutine, public mom_surface_forcing::forcing_save_restart (type(surface_forcing_cs), pointer CS, type(ocean_grid_type), intent(inout) G, type(time_type), intent(in) Time, character(len=*), intent(in) directory, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename_suffix)
Definition at line 753 of file MOM_surface_forcing.F90.
References mom_restart::save_restart().
Referenced by mom_main(), ocean_model_mod::ocean_model_restart(), and ocean_model_mod::ocean_model_save_restart().
subroutine, public mom_surface_forcing::ice_ocn_bnd_type_chksum (character(len=*), intent(in) id, integer, intent(in) timestep, type(ice_ocean_boundary_type), intent(in) iobt)
Definition at line 1133 of file MOM_surface_forcing.F90.
subroutine, public mom_surface_forcing::set_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day_start, type(time_type), intent(in) day_interval, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS)
Definition at line 209 of file MOM_surface_forcing.F90.
References buoyancy_forcing_const(), buoyancy_forcing_from_data_override(), buoyancy_forcing_from_files(), buoyancy_forcing_linear(), buoyancy_forcing_zero(), mom_tracer_flow_control::call_tracer_set_forcing(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), meso_surface_forcing::meso_buoyancy_forcing(), meso_surface_forcing::meso_wind_forcing(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), user_revise_forcing::user_alter_forcing(), user_surface_forcing::user_buoyancy_forcing(), user_surface_forcing::user_wind_forcing(), wind_forcing_1gyre(), wind_forcing_2gyre(), wind_forcing_by_data_override(), wind_forcing_from_file(), wind_forcing_gyres(), and wind_forcing_zero().
subroutine, public mom_surface_forcing::set_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day_start, type(time_type), intent(in) day_interval, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS)
Definition at line 185 of file MOM_surface_forcing.F90.
References buoyancy_forcing_from_files(), buoyancy_forcing_linear(), buoyancy_forcing_zero(), mom_tracer_flow_control::call_tracer_set_forcing(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), user_revise_forcing::user_alter_forcing(), user_surface_forcing::user_buoyancy_forcing(), user_surface_forcing::user_wind_forcing(), wind_forcing_1gyre(), wind_forcing_2gyre(), wind_forcing_from_file(), wind_forcing_gyres(), and wind_forcing_zero().
Referenced by mom_main().
subroutine mom_surface_forcing::surface_forcing_end (type(surface_forcing_cs), pointer CS, type(forcing), intent(inout), optional fluxes) private
Definition at line 2203 of file MOM_surface_forcing.F90.
subroutine mom_surface_forcing::surface_forcing_end (type(surface_forcing_cs), pointer CS, type(forcing), intent(inout), optional fluxes) private
Definition at line 1513 of file MOM_surface_forcing.F90.
subroutine mom_surface_forcing::surface_forcing_end (type(surface_forcing_cs), pointer CS, type(forcing), intent(inout), optional fluxes) private
Definition at line 1091 of file MOM_surface_forcing.F90.
subroutine, public mom_surface_forcing::surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(surface_forcing_cs), pointer CS, type(tracer_flow_control_cs), pointer tracer_flow_CSp)
Definition at line 1782 of file MOM_surface_forcing.F90.
References mom_get_input::get_mom_input(), mom_file_parser::log_version(), meso_surface_forcing::meso_surface_forcing_init(), mom_error_handler::mom_error(), mom_io::num_timelevels(), mom_diag_mediator::register_diag_field(), mom_restart::restart_init(), mom_restart::restart_init_end(), mom_restart::restore_state(), mom_io::slasher(), user_revise_forcing::user_revise_forcing_init(), and user_surface_forcing::user_surface_forcing_init().
subroutine, public mom_surface_forcing::surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(surface_forcing_cs), pointer CS, type(tracer_flow_control_cs), pointer tracer_flow_CSp)
Definition at line 1215 of file MOM_surface_forcing.F90.
References mom_get_input::get_mom_input(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), mom_restart::restart_init(), mom_restart::restart_init_end(), mom_restart::restore_state(), mom_io::slasher(), user_revise_forcing::user_revise_forcing_init(), and user_surface_forcing::user_surface_forcing_init().
subroutine, public mom_surface_forcing::surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(surface_forcing_cs), pointer CS, logical, intent(in), optional restore_salt)
Definition at line 777 of file MOM_surface_forcing.F90.
References mom_get_input::get_mom_input(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), mom_diag_mediator::register_scalar_field(), mom_restart::restart_init(), mom_restart::restart_init_end(), mom_restart::restore_state(), mom_io::slasher(), mom_string_functions::uppercase(), and user_revise_forcing::user_revise_forcing_init().
Referenced by mom_main(), and ocean_model_mod::ocean_model_init().
subroutine mom_surface_forcing::wind_forcing_1gyre (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 381 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_1gyre (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 413 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
subroutine mom_surface_forcing::wind_forcing_2gyre (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 334 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_2gyre (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 364 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
subroutine mom_surface_forcing::wind_forcing_by_data_override (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 696 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_from_file (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 519 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and mom_string_functions::uppercase().
subroutine mom_surface_forcing::wind_forcing_from_file (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 483 of file MOM_surface_forcing.F90.
References mom_error_handler::mom_error(), and mom_string_functions::uppercase().
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_gyres (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 461 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
subroutine mom_surface_forcing::wind_forcing_gyres (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 427 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_zero (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 280 of file MOM_surface_forcing.F90.
Referenced by set_forcing().
subroutine mom_surface_forcing::wind_forcing_zero (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(surface_forcing_cs), pointer CS) private
Definition at line 308 of file MOM_surface_forcing.F90.
References mom_error_handler::calltree_enter(), and mom_error_handler::calltree_leave().
Member Data Documentation
integer mom_surface_forcing::id_clock_forcing
Definition at line 204 of file MOM_surface_forcing.F90.
The documentation for this module was generated from the following file:
config_src/coupled_driver/MOM_surface_forcing.F90