MOM6: regrid_ppoly_class Module Reference
regrid_ppoly_class Module Reference
Data Types
type ppoly_t
Public Member Functions
subroutine, public ppoly_init (ppoly, nb_cells, degree)
subroutine, public ppoly_destroy (ppoly)
Detailed Description
Definition at line 1 of file regrid_ppoly_class.F90.
Member Function/Subroutine Documentation
subroutine, public regrid_ppoly_class::ppoly_destroy (type(ppoly_t), intent(inout) ppoly)
Definition at line 53 of file regrid_ppoly_class.F90.
Referenced by mom_ale::ale_memory_deallocation(), mom_remapping::end_remapping(), and mom_regridding::regridding_memory_deallocation().
subroutine, public regrid_ppoly_class::ppoly_init (type(ppoly_t), intent(inout) ppoly, integer, intent(in) nb_cells, integer, intent(in) degree)
Definition at line 34 of file regrid_ppoly_class.F90.
Referenced by mom_ale::ale_memory_allocation(), mom_regridding::allocate_regridding(), mom_remapping::allocate_remapping(), and mom_remapping::remappingunittests().
The documentation for this module was generated from the following file:
src/ALE/regrid_ppoly_class.F90