MOM6: mom_thickness_diffuse Module Reference
mom_thickness_diffuse Module Reference
Data Types
type thickness_diffuse_cs
Public Member Functions
subroutine, public thickness_diffuse (h, uhtr, vhtr, tv, dt, G, MEKE, VarMix, CDp, CS)
subroutine, public vert_fill_ts (h, T_in, S_in, kappa, dt, T_f, S_f, G, halo_here)
subroutine, public thickness_diffuse_init (Time, G, param_file, diag, CDp, CS)
subroutine, public thickness_diffuse_end (CS)
Private Member Functions
subroutine thickness_diffuse_full (h, e, Kh_u, Kh_v, tv, uhD, vhD, dt, G, MEKE, CS, int_slope_u, int_slope_v)
subroutine add_detangling_kh (h, e, Kh_u, Kh_v, KH_u_CFL, KH_v_CFL, tv, dt, G, CS, int_slope_u, int_slope_v)
Detailed Description
Definition at line 1 of file MOM_thickness_diffuse.F90.
Member Function/Subroutine Documentation
subroutine mom_thickness_diffuse::add_detangling_kh (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nk_interface_), intent(in) e, real, dimension(nimemb_,njmem_,nk_interface_), intent(inout) Kh_u, real, dimension(nimem_,njmemb_,nk_interface_), intent(inout) Kh_v, real, dimension(nimemb_,njmem_), intent(in) KH_u_CFL, real, dimension(nimem_,njmemb_), intent(in) KH_v_CFL, type(thermo_var_ptrs), intent(in) tv, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(thickness_diffuse_cs), pointer CS, real, dimension(nimemb_,njmem_,nk_interface_), intent(inout) int_slope_u, real, dimension(nimem_,njmemb_,nk_interface_), intent(inout) int_slope_v) private
Definition at line 837 of file MOM_thickness_diffuse.F90.
Referenced by thickness_diffuse().
subroutine, public mom_thickness_diffuse::thickness_diffuse (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) uhtr, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) vhtr, type(thermo_var_ptrs), intent(in) tv, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(meke_type), pointer MEKE, type(varmix_cs), pointer VarMix, type(cont_diag_ptrs), intent(inout) CDp, type(thickness_diffuse_cs), pointer CS)
Definition at line 96 of file MOM_thickness_diffuse.F90.
References add_detangling_kh(), mom_error_handler::mom_error(), mom_diag_mediator::query_averaging_enabled(), and thickness_diffuse_full().
Referenced by mom::step_mom().
subroutine, public mom_thickness_diffuse::thickness_diffuse_end (type(thickness_diffuse_cs), pointer CS)
Definition at line 1440 of file MOM_thickness_diffuse.F90.
subroutine mom_thickness_diffuse::thickness_diffuse_full (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nk_interface_), intent(in) e, real, dimension(nimemb_,njmem_,nk_interface_), intent(in) Kh_u, real, dimension(nimem_,njmemb_,nk_interface_), intent(in) Kh_v, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimemb_,njmem_,nkmem_), intent(out) uhD, real, dimension(nimem_,njmemb_,nkmem_), intent(out) vhD, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(meke_type), pointer MEKE, type(thickness_diffuse_cs), pointer CS, real, dimension(nimemb_,njmem_,nk_interface_), intent(in), optional int_slope_u, real, dimension(nimem_,njmemb_,nk_interface_), intent(in), optional int_slope_v) private
Definition at line 284 of file MOM_thickness_diffuse.F90.
References mom_eos::calculate_density_derivs(), and vert_fill_ts().
Referenced by thickness_diffuse().
subroutine, public mom_thickness_diffuse::thickness_diffuse_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(cont_diag_ptrs), intent(inout) CDp, type(thickness_diffuse_cs), pointer CS)
Definition at line 1338 of file MOM_thickness_diffuse.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom::initialize_mom().
subroutine, public mom_thickness_diffuse::vert_fill_ts (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) T_in, real, dimension(nimem_,njmem_,nkmem_), intent(in) S_in, real, intent(in) kappa, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(out) T_f, real, dimension(nimem_,njmem_,nkmem_), intent(out) S_f, type(ocean_grid_type), intent(in) G, integer, intent(in), optional halo_here)
Definition at line 1259 of file MOM_thickness_diffuse.F90.
Referenced by mom_set_diffusivity::set_diffusivity(), mom_int_tide_input::set_int_tide_input(), and thickness_diffuse_full().
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_thickness_diffuse.F90