MOM6: regrid_consts Module Reference
regrid_consts Module Reference
Data Types
interface coordinateunits
Public Member Functions
integer function coordinatemode (string)
character(len=16) function coordinateunitsi (coordMode)
character(len=16) function coordinateunitss (string)
Public Attributes
integer, parameter regridding_layer = -1
integer, parameter regridding_zstar = 0
integer, parameter regridding_rho = 1
integer, parameter regridding_sigma = 2
integer, parameter regridding_arbitrary = 3
character(len=5), parameter regridding_layer_string = "LAYER"
character(len=2), parameter regridding_zstar_string = "Z*"
character(len=3), parameter regridding_rho_string = "RHO"
character(len=5), parameter regridding_sigma_string = "SIGMA"
character(len=5), parameter default_coordinate_mode = REGRIDDING_LAYER_STRING
Detailed Description
Definition at line 1 of file regrid_consts.F90.
Member Function/Subroutine Documentation
integer function regrid_consts::coordinatemode (character(len=*), intent(in) string)
Definition at line 35 of file regrid_consts.F90.
References mom_error_handler::mom_error(), and mom_string_functions::uppercase().
Referenced by adjustment_initialization::adjustment_initialize_temperature_salinity(), adjustment_initialization::adjustment_initialize_thickness(), mom_ale::ale_initregridding(), coordinateunitss(), dome2d_initialization::dome2d_initialize_temperature_salinity(), dome2d_initialization::dome2d_initialize_thickness(), mom_regridding::initialize_regridding(), seamount_initialization::seamount_initialize_temperature_salinity(), seamount_initialization::seamount_initialize_thickness(), and mom_regridding::uniformresolution().
character(len=16) function regrid_consts::coordinateunitsi (integer, intent(in) coordMode)
Definition at line 50 of file regrid_consts.F90.
References regrid_consts::coordinateunits::coordinateunitsi(), and mom_error_handler::mom_error().
character(len=16) function regrid_consts::coordinateunitss (character(len=*), intent(in) string)
Definition at line 65 of file regrid_consts.F90.
References coordinatemode(), regrid_consts::coordinateunits::coordinateunitsi(), and regrid_consts::coordinateunits::coordinateunitss().
Member Data Documentation
character(len=5), parameter regrid_consts::default_coordinate_mode = REGRIDDING_LAYER_STRING
Definition at line 24 of file regrid_consts.F90.
integer, parameter regrid_consts::regridding_arbitrary = 3
Definition at line 19 of file regrid_consts.F90.
integer, parameter regrid_consts::regridding_layer = -1
Definition at line 15 of file regrid_consts.F90.
character(len=5), parameter regrid_consts::regridding_layer_string = "LAYER"
Definition at line 20 of file regrid_consts.F90.
integer, parameter regrid_consts::regridding_rho = 1
Definition at line 17 of file regrid_consts.F90.
character(len=3), parameter regrid_consts::regridding_rho_string = "RHO"
Definition at line 22 of file regrid_consts.F90.
integer, parameter regrid_consts::regridding_sigma = 2
Definition at line 18 of file regrid_consts.F90.
character(len=5), parameter regrid_consts::regridding_sigma_string = "SIGMA"
Definition at line 23 of file regrid_consts.F90.
integer, parameter regrid_consts::regridding_zstar = 0
Definition at line 16 of file regrid_consts.F90.
character(len=2), parameter regrid_consts::regridding_zstar_string = "Z*"
Definition at line 21 of file regrid_consts.F90.
The documentation for this module was generated from the following file:
src/ALE/regrid_consts.F90