MOM6: ppm_functions Module Reference
ppm_functions Module Reference
Public Member Functions
subroutine, public ppm_reconstruction (N, h, u, ppoly)
subroutine, public ppm_boundary_extrapolation (N, h, u, ppoly)
Private Member Functions
subroutine ppm_limiter_standard (N, h, u, ppoly)
Detailed Description
Definition at line 1 of file PPM_functions.F90.
Member Function/Subroutine Documentation
subroutine, public ppm_functions::ppm_boundary_extrapolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 151 of file PPM_functions.F90.
Referenced by mom_ale::pressure_gradient_ppm(), mom_regridding::regridding_iteration(), mom_remapping::remapping_core(), and mom_remapping::remappingunittests().
subroutine ppm_functions::ppm_limiter_standard (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly) private
Definition at line 76 of file PPM_functions.F90.
References regrid_edge_values::bound_edge_values(), and regrid_edge_values::check_discontinuous_edge_values().
Referenced by ppm_reconstruction().
subroutine, public ppm_functions::ppm_reconstruction (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 25 of file PPM_functions.F90.
References ppm_limiter_standard().
Referenced by mom_ale::pressure_gradient_ppm(), mom_regridding::regridding_iteration(), mom_remapping::remapping_core(), and mom_remapping::remappingunittests().
The documentation for this module was generated from the following file:
src/ALE/PPM_functions.F90