MOM6: mom_diabatic_driver Module Reference
mom_diabatic_driver Module Reference
Data Types
type diabatic_cs
Public Member Functions
subroutine, public diabatic (u, v, h, tv, fluxes, visc, ADp, CDp, dt, G, CS)
subroutine, public adiabatic (h, tv, fluxes, dt, G, CS)
subroutine, public adiabatic_driver_init (Time, G, param_file, diag, CS, tracer_flow_CSp, diag_to_Z_CSp)
subroutine, public diabatic_driver_init (Time, G, param_file, useALEalgorithm, diag, ADp, CDp, CS, tracer_flow_CSp, sponge_CSp, diag_to_Z_CSp)
subroutine, public diabatic_driver_end (CS)
Public Attributes
integer id_clock_entrain
Private Member Functions
subroutine make_frazil (h, tv, G, CS)
subroutine differential_diffuse_t_s (h, tv, visc, dt, G)
subroutine adjust_salt (h, tv, G, CS)
subroutine tridiagts (G, is, ie, js, je, hold, ea, eb, T, S)
subroutine find_uv_at_h (u, v, h, u_h, v_h, G, ea, eb)
subroutine applyboundaryfluxes (CS, G, dt, fluxes, optics, ea, h, tv)
Private Attributes
integer id_clock_mixedlayer
integer id_clock_set_diffusivity
integer id_clock_uv_at_h
integer id_clock_frazil
integer id_clock_tracers
integer id_clock_tridiag
integer id_clock_pass
integer id_clock_sponge
integer id_clock_geothermal
integer id_clock_differential_diff
integer id_clock_remap
integer id_clock_kpp
Detailed Description
Definition at line 1 of file MOM_diabatic_driver.F90.
Member Function/Subroutine Documentation
subroutine, public mom_diabatic_driver::adiabatic (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, type(forcing), intent(inout) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diabatic_cs), pointer CS)
Definition at line 1055 of file MOM_diabatic_driver.F90.
References mom_tracer_flow_control::call_tracer_column_fns().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_legacy_split::register_restarts_dyn_legacy_split(), mom_set_visc::set_visc_init(), mom_set_visc::set_visc_register_restarts(), and mom::step_mom().
subroutine, public mom_diabatic_driver::adiabatic_driver_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(diabatic_cs), pointer CS, type(tracer_flow_control_cs), pointer tracer_flow_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 1382 of file MOM_diabatic_driver.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
subroutine mom_diabatic_driver::adjust_salt (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(inout) tv, type(ocean_grid_type), intent(in) G, type(diabatic_cs), intent(in) CS) private
Definition at line 1288 of file MOM_diabatic_driver.F90.
Referenced by midas_vertmap::determine_temperature(), and diabatic().
subroutine mom_diabatic_driver::applyboundaryfluxes (type(diabatic_cs), pointer CS, type(ocean_grid_type), intent(in) G, real, intent(in) dt, type(forcing), intent(in) fluxes, type(optics_type), pointer optics, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv) private
Definition at line 1794 of file MOM_diabatic_driver.F90.
References mom_forcing_type::absorbremainingsw(), mom_forcing_type::extractfluxes1d(), mom_forcing_type::forcing_singlepointprint(), and mom_error_handler::mom_error().
Referenced by diabatic().
subroutine, public mom_diabatic_driver::diabatic (real, dimension(nimemb_,njmem_,nkmem_), intent(inout) u, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) v, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, type(forcing), intent(inout) fluxes, type(vertvisc_type), intent(inout) visc, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diabatic_cs), pointer CS)
Definition at line 207 of file MOM_diabatic_driver.F90.
References adjust_salt(), mom_sponge::apply_sponge(), applyboundaryfluxes(), mom_bulk_mixed_layer::bulkmixedlayer(), mom_diag_to_z::calc_zint_diags(), mom_forcing_type::calculatebuoyancyflux2d(), mom_tracer_flow_control::call_tracer_column_fns(), mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::calltree_showquery(), mom_error_handler::calltree_waypoint(), mom_diffconvection::diffconvection_calculate(), differential_diffuse_t_s(), mom_entrain_diffusive::entrainment_diffusive(), find_uv_at_h(), mom_geothermal::geothermal(), mom_kpp::kpp_applynonlocaltransport(), mom_kpp::kpp_calculate(), make_frazil(), mom_error_handler::mom_error(), mom_forcing_type::mom_forcing_chksum(), mom_checksum_packages::mom_state_stats(), mom_variables::mom_thermovar_chksum(), mom_internal_tides::propagate_int_tide(), mom_regularize_layers::regularize_layers(), mom_set_diffusivity::set_bbl_diffusivity(), mom_set_diffusivity::set_diffusivity(), mom_int_tide_input::set_int_tide_input(), mom_opacity::set_opacity(), tridiagts(), and mom_wave_speed::wave_speed().
Referenced by mom::step_mom().
subroutine, public mom_diabatic_driver::diabatic_driver_end (type(diabatic_cs), pointer CS)
Definition at line 1671 of file MOM_diabatic_driver.F90.
References mom_diffconvection::diffconvection_end(), mom_entrain_diffusive::entrain_diffusive_end(), mom_kpp::kpp_end(), mom_opacity::opacity_end(), and mom_set_diffusivity::set_diffusivity_end().
subroutine, public mom_diabatic_driver::diabatic_driver_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in) useALEalgorithm, type(diag_ctrl), intent(inout), target diag, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, type(diabatic_cs), pointer CS, type(tracer_flow_control_cs), pointer tracer_flow_CSp, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 1425 of file MOM_diabatic_driver.F90.
References mom_bulk_mixed_layer::bulkmixedlayer_init(), mom_diffconvection::diffconvection_init(), mom_entrain_diffusive::entrain_diffusive_init(), mom_geothermal::geothermal_init(), mom_int_tide_input::int_tide_input_init(), mom_internal_tides::internal_tides_init(), mom_kappa_shear::kappa_shear_is_used(), mom_kpp::kpp_init(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_opacity::opacity_init(), mom_diag_mediator::register_diag_field(), mom_diag_to_z::register_zint_diag(), mom_regularize_layers::regularize_layers_init(), and mom_set_diffusivity::set_diffusivity_init().
Referenced by mom::initialize_mom().
subroutine mom_diabatic_driver::differential_diffuse_t_s (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(inout) tv, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G) private
Definition at line 1184 of file MOM_diabatic_driver.F90.
References mom_error_handler::mom_error().
Referenced by diabatic().
subroutine mom_diabatic_driver::find_uv_at_h (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(out) u_h, real, dimension(nimem_,njmem_,nkmem_), intent(out) v_h, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional ea, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional eb) private
Definition at line 1695 of file MOM_diabatic_driver.F90.
References mom_error_handler::mom_error().
Referenced by diabatic().
subroutine mom_diabatic_driver::make_frazil (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(inout) tv, type(ocean_grid_type), intent(in) G, type(diabatic_cs), intent(in) CS) private
Definition at line 1073 of file MOM_diabatic_driver.F90.
Referenced by diabatic().
subroutine mom_diabatic_driver::tridiagts (type(ocean_grid_type), intent(in) G, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, real, dimension(nimem_,njmem_,nkmem_), intent(in) hold, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, real, dimension(nimem_,njmem_,nkmem_), intent(inout) T, real, dimension(nimem_,njmem_,nkmem_), intent(inout) S) private
Definition at line 1344 of file MOM_diabatic_driver.F90.
Referenced by diabatic().
Member Data Documentation
integer mom_diabatic_driver::id_clock_differential_diff private
Definition at line 202 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_entrain
Definition at line 199 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_frazil private
Definition at line 200 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_geothermal private
Definition at line 202 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_kpp private
Definition at line 203 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_mixedlayer private
Definition at line 199 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_pass private
Definition at line 201 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_remap private
Definition at line 202 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_set_diffusivity private
Definition at line 199 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_sponge private
Definition at line 201 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_tracers private
Definition at line 201 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_tridiag private
Definition at line 201 of file MOM_diabatic_driver.F90.
integer mom_diabatic_driver::id_clock_uv_at_h private
Definition at line 200 of file MOM_diabatic_driver.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_diabatic_driver.F90