MOM6: mom_bulk_mixed_layer Module Reference
mom_bulk_mixed_layer Module Reference
Data Types
type bulkmixedlayer_cs
Public Member Functions
subroutine, public bulkmixedlayer (h_3d, u_3d, v_3d, tv, fluxes, dt, ea, eb, G, CS, optics, dt_diag, last_call)
subroutine, public bulkmixedlayer_init (Time, G, param_file, diag, CS)
Public Attributes
integer id_clock_detrain
Private Member Functions
subroutine convective_adjustment (h, u, v, R0, Rcv, T, S, eps, d_eb, dKE_CA, cTKE, j, G, CS, nz_conv)
subroutine mixedlayer_convection (h, d_eb, htot, Ttot, Stot, uhtot, vhtot, R0_tot, Rcv_tot, u, v, T, S, R0, Rcv, eps, dR0_dT, dRcv_dT, dR0_dS, dRcv_dS, Net_H, Net_heat, Net_salt, nsw, Pen_SW_bnd, opacity_band, Conv_en, dKE_FC, j, ksort, G, CS, tv)
subroutine find_starting_tke (htot, h_CA, fluxes, Conv_En, cTKE, dKE_FC, dKE_CA, TKE, TKE_river, Idecay_len_TKE, cMKE, dt, Idt_diag, j, ksort, G, CS)
subroutine mechanical_entrainment (h, d_eb, htot, Ttot, Stot, uhtot, vhtot, R0_tot, Rcv_tot, u, v, T, S, R0, Rcv, eps, dR0_dT, dRcv_dT, cMKE, Idt_diag, nsw, Pen_SW_bnd, opacity_band, TKE, Idecay_len_TKE, j, ksort, G, CS)
subroutine sort_ml (h, R0, eps, G, CS, ksort)
subroutine resort_ml (h, T, S, R0, Rcv, eps, d_ea, d_eb, ksort, G, CS, dR0_dT, dR0_dS, dRcv_dT, dRcv_dS)
subroutine mixedlayer_detrain_2 (h, T, S, R0, Rcv, dt, dt_diag, d_ea, j, G, CS, dR0_dT, dR0_dS, dRcv_dT, dRcv_dS, max_BL_det)
subroutine mixedlayer_detrain_1 (h, T, S, R0, Rcv, dt, dt_diag, d_ea, d_eb, j, G, CS, dRcv_dT, dRcv_dS, max_BL_det)
real function ef4 (H, E, L, dR_de)
Private Attributes
integer id_clock_mech
integer id_clock_conv
integer id_clock_adjustment
integer id_clock_eos
integer id_clock_resort
integer id_clock_pass
integer num_msg = 0
integer max_msg = 2
Detailed Description
Definition at line 1 of file MOM_bulk_mixed_layer.F90.
Member Function/Subroutine Documentation
subroutine, public mom_bulk_mixed_layer::bulkmixedlayer (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h_3d, real, dimension(nimem_,njmem_,nkmem_), intent(in) u_3d, real, dimension(nimem_,njmem_,nkmem_), intent(in) v_3d, type(thermo_var_ptrs), intent(inout) tv, type(forcing), intent(in) fluxes, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) eb, type(ocean_grid_type), intent(inout) G, type(bulkmixedlayer_cs), pointer CS, type(optics_type), pointer optics, real, intent(in), optional dt_diag, logical, intent(in), optional last_call)
Definition at line 190 of file MOM_bulk_mixed_layer.F90.
References mom_forcing_type::absorbremainingsw(), mom_eos::calculate_density_derivs(), mom_regridding::convective_adjustment(), mom_forcing_type::extractfluxes1d(), find_starting_tke(), mechanical_entrainment(), mixedlayer_convection(), mixedlayer_detrain_1(), mixedlayer_detrain_2(), mom_error_handler::mom_error(), resort_ml(), and sort_ml().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_bulk_mixed_layer::bulkmixedlayer_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(bulkmixedlayer_cs), pointer CS)
Definition at line 3234 of file MOM_bulk_mixed_layer.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
subroutine mom_bulk_mixed_layer::convective_adjustment (real, dimension(nimem_,nkmem_), intent(inout) h, real, dimension(nimem_,nkmem_), intent(inout) u, real, dimension(nimem_,nkmem_), intent(inout) v, real, dimension(nimem_,nkmem_), intent(inout) R0, real, dimension(nimem_,nkmem_), intent(inout) Rcv, real, dimension(nimem_,nkmem_), intent(inout) T, real, dimension(nimem_,nkmem_), intent(inout) S, real, dimension(nimem_,nkmem_), intent(in) eps, real, dimension(nimem_,nkmem_), intent(inout) d_eb, real, dimension(nimem_,nkmem_), intent(out) dKE_CA, real, dimension(nimem_,nkmem_), intent(out) cTKE, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, integer, intent(in), optional nz_conv) private
Definition at line 803 of file MOM_bulk_mixed_layer.F90.
real function mom_bulk_mixed_layer::ef4 (real, intent(in) H, real, intent(in) E, real, intent(in) L, real, intent(inout), optional dR_de) private
Definition at line 3465 of file MOM_bulk_mixed_layer.F90.
Referenced by mechanical_entrainment().
subroutine mom_bulk_mixed_layer::find_starting_tke (real, dimension(nimem_), intent(in) htot, real, dimension(nimem_), intent(in) h_CA, type(forcing), intent(in) fluxes, real, dimension(nimem_), intent(inout) Conv_En, real, dimension(nimem_,nkmem_), intent(in) cTKE, real, dimension(nimem_), intent(in) dKE_FC, real, dimension(nimem_,nkmem_), intent(in) dKE_CA, real, dimension(nimem_), intent(out) TKE, real, dimension(nimem_), intent(in) TKE_river, real, dimension(nimem_), intent(out) Idecay_len_TKE, real, dimension(c2_,nimem_), intent(out) cMKE, real, intent(in) dt, real, intent(in) Idt_diag, integer, intent(in) j, integer, dimension(nimem_,nkmem_), intent(in) ksort, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS) private
Definition at line 1216 of file MOM_bulk_mixed_layer.F90.
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::mechanical_entrainment (real, dimension(nimem_,nkmem_), intent(inout) h, real, dimension(nimem_,nkmem_), intent(inout) d_eb, real, dimension(nimem_), intent(inout) htot, real, dimension(nimem_), intent(inout) Ttot, real, dimension(nimem_), intent(inout) Stot, real, dimension(nimem_), intent(inout) uhtot, real, dimension(nimem_), intent(inout) vhtot, real, dimension(nimem_), intent(inout) R0_tot, real, dimension(nimem_), intent(inout) Rcv_tot, real, dimension(nimem_,nkmem_), intent(in) u, real, dimension(nimem_,nkmem_), intent(in) v, real, dimension(nimem_,nkmem_), intent(in) T, real, dimension(nimem_,nkmem_), intent(in) S, real, dimension(nimem_,nkmem_), intent(in) R0, real, dimension(nimem_,nkmem_), intent(in) Rcv, real, dimension(nimem_,nkmem_), intent(in) eps, real, dimension(nimem_), intent(in) dR0_dT, real, dimension(nimem_), intent(in) dRcv_dT, real, dimension(c2_,nimem_), intent(in) cMKE, real, intent(in) Idt_diag, integer, intent(in) nsw, real, dimension(:,:), intent(inout) Pen_SW_bnd, real, dimension(:,:,:), intent(in) opacity_band, real, dimension(nimem_), intent(inout) TKE, real, dimension(nimem_), intent(inout) Idecay_len_TKE, integer, intent(in) j, integer, dimension(nimem_,nkmem_), intent(in) ksort, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS) private
Definition at line 1395 of file MOM_bulk_mixed_layer.F90.
References ef4().
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::mixedlayer_convection (real, dimension(nimem_,nkmem_), intent(inout) h, real, dimension(nimem_,nkmem_), intent(inout) d_eb, real, dimension(nimem_), intent(out) htot, real, dimension(nimem_), intent(out) Ttot, real, dimension(nimem_), intent(out) Stot, real, dimension(nimem_), intent(out) uhtot, real, dimension(nimem_), intent(out) vhtot, real, dimension(nimem_), intent(out) R0_tot, real, dimension(nimem_), intent(out) Rcv_tot, real, dimension(nimem_,nkmem_), intent(in) u, real, dimension(nimem_,nkmem_), intent(in) v, real, dimension(nimem_,nkmem_), intent(in) T, real, dimension(nimem_,nkmem_), intent(in) S, real, dimension(nimem_,nkmem_), intent(in) R0, real, dimension(nimem_,nkmem_), intent(in) Rcv, real, dimension(nimem_,nkmem_), intent(in) eps, real, dimension(nimem_), intent(in) dR0_dT, real, dimension(nimem_), intent(in) dRcv_dT, real, dimension(nimem_), intent(in) dR0_dS, real, dimension(nimem_), intent(in) dRcv_dS, real, dimension(nimem_), intent(in) Net_H, real, dimension(nimem_), intent(in) Net_heat, real, dimension(nimem_), intent(in) Net_salt, integer, intent(in) nsw, real, dimension(:,:), intent(inout) Pen_SW_bnd, real, dimension(:,:,:), intent(in) opacity_band, real, dimension(nimem_), intent(out) Conv_en, real, dimension(nimem_), intent(out) dKE_FC, integer, intent(in) j, integer, dimension(nimem_,nkmem_), intent(in) ksort, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, type(thermo_var_ptrs), intent(inout) tv) private
Definition at line 926 of file MOM_bulk_mixed_layer.F90.
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::mixedlayer_detrain_1 (real, dimension(nimem_,nkmem0_), intent(inout) h, real, dimension(nimem_,nkmem0_), intent(inout) T, real, dimension(nimem_,nkmem0_), intent(inout) S, real, dimension(nimem_,nkmem0_), intent(inout) R0, real, dimension(nimem_,nkmem0_), intent(inout) Rcv, real, intent(in) dt, real, intent(in) dt_diag, real, dimension(nimem_,nkmem_), intent(inout) d_ea, real, dimension(nimem_,nkmem_), intent(inout) d_eb, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, real, dimension(nimem_), intent(in) dRcv_dT, real, dimension(nimem_), intent(in) dRcv_dS, real, dimension(nimem_), intent(in) max_BL_det) private
Definition at line 2952 of file MOM_bulk_mixed_layer.F90.
References mom_error_handler::mom_error().
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::mixedlayer_detrain_2 (real, dimension(nimem_,nkmem0_), intent(inout) h, real, dimension(nimem_,nkmem0_), intent(inout) T, real, dimension(nimem_,nkmem0_), intent(inout) S, real, dimension(nimem_,nkmem0_), intent(inout) R0, real, dimension(nimem_,nkmem0_), intent(inout) Rcv, real, intent(in) dt, real, intent(in) dt_diag, real, dimension(nimem_,nkmem_), intent(inout) d_ea, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, real, dimension(nimem_), intent(in) dR0_dT, real, dimension(nimem_), intent(in) dR0_dS, real, dimension(nimem_), intent(in) dRcv_dT, real, dimension(nimem_), intent(in) dRcv_dS, real, dimension(nimem_), intent(in) max_BL_det) private
Definition at line 2072 of file MOM_bulk_mixed_layer.F90.
References mom_error_handler::mom_error().
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::resort_ml (real, dimension(nimem_,nkmem0_), intent(inout) h, real, dimension(nimem_,nkmem0_), intent(inout) T, real, dimension(nimem_,nkmem0_), intent(inout) S, real, dimension(nimem_,nkmem0_), intent(inout) R0, real, dimension(nimem_,nkmem0_), intent(inout) Rcv, real, dimension(nimem_,nkmem_), intent(inout) eps, real, dimension(nimem_,nkmem_), intent(inout) d_ea, real, dimension(nimem_,nkmem_), intent(inout) d_eb, integer, dimension(nimem_,nkmem_), intent(in) ksort, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, real, dimension(nimem_), intent(in) dR0_dT, real, dimension(nimem_), intent(in) dR0_dS, real, dimension(nimem_), intent(in) dRcv_dT, real, dimension(nimem_), intent(in) dRcv_dS) private
Definition at line 1763 of file MOM_bulk_mixed_layer.F90.
Referenced by bulkmixedlayer().
subroutine mom_bulk_mixed_layer::sort_ml (real, dimension(nimem_,nkmem_), intent(in) h, real, dimension(nimem_,nkmem_), intent(in) R0, real, dimension(nimem_,nkmem_), intent(in) eps, type(ocean_grid_type), intent(in) G, type(bulkmixedlayer_cs), pointer CS, integer, dimension(nimem_,nkmem_), intent(out) ksort) private
Definition at line 1708 of file MOM_bulk_mixed_layer.F90.
Referenced by bulkmixedlayer().
Member Data Documentation
integer mom_bulk_mixed_layer::id_clock_adjustment private
Definition at line 183 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_conv private
Definition at line 183 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_detrain
Definition at line 183 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_eos private
Definition at line 184 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_mech private
Definition at line 183 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_pass private
Definition at line 184 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::id_clock_resort private
Definition at line 184 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::max_msg = 2 private
Definition at line 186 of file MOM_bulk_mixed_layer.F90.
integer mom_bulk_mixed_layer::num_msg = 0 private
Definition at line 186 of file MOM_bulk_mixed_layer.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90