MOM6: mom_ice_shelf Module Reference
mom_ice_shelf Module Reference
Data Types
type ice_shelf_cs
Public Member Functions
subroutine, public shelf_calc_flux (state, fluxes, Time, time_step, CS)
subroutine, public add_shelf_flux (G, CS, state, fluxes)
subroutine, public initialize_ice_shelf (Time, CS, fluxes, Time_in, solo_mode_in)
subroutine, public ice_shelf_save_restart (CS, Time, directory, time_stamped, filename_suffix)
subroutine, public ice_shelf_end (CS)
subroutine, public solo_time_step (CS, time_step, n, Time, min_time_step_in)
Detailed Description
Definition at line 1 of file MOM_ice_shelf.F90.
Member Function/Subroutine Documentation
subroutine, public mom_ice_shelf::add_shelf_flux (type(ocean_grid_type), intent(in) G, type(ice_shelf_cs), intent(in) CS, type(surface), intent(in) state, type(forcing), intent(inout) fluxes)
Definition at line 76 of file MOM_ice_shelf.F90.
subroutine, public mom_ice_shelf::ice_shelf_end (type(ice_shelf_cs), pointer CS)
Definition at line 150 of file MOM_ice_shelf.F90.
Referenced by mom_main(), and shelf_main().
subroutine, public mom_ice_shelf::ice_shelf_save_restart (type(ice_shelf_cs), pointer CS, type(time_type), intent(in) Time, character(len=*), intent(in), optional directory, logical, intent(in), optional time_stamped, character(len=*), intent(in), optional filename_suffix)
Definition at line 131 of file MOM_ice_shelf.F90.
Referenced by mom_main(), and shelf_main().
subroutine, public mom_ice_shelf::initialize_ice_shelf (type(time_type), intent(inout) Time, type(ice_shelf_cs), pointer CS, type(forcing), intent(inout), optional fluxes, type(time_type), intent(in), optional Time_in, logical, intent(in), optional solo_mode_in)
Definition at line 95 of file MOM_ice_shelf.F90.
References mom_get_input::get_mom_input(), mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_main(), and shelf_main().
subroutine, public mom_ice_shelf::shelf_calc_flux (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) Time, real, intent(in) time_step, type(ice_shelf_cs), pointer CS)
Definition at line 50 of file MOM_ice_shelf.F90.
References mom_error_handler::mom_error().
Referenced by mom_main().
subroutine, public mom_ice_shelf::solo_time_step (type(ice_shelf_cs), pointer CS, real, intent(in) time_step, integer, intent(inout) n, type(time_type), intent(inout) Time, real, intent(in), optional min_time_step_in)
Definition at line 162 of file MOM_ice_shelf.F90.
Referenced by shelf_main().
The documentation for this module was generated from the following file:
src/ice_shelf/MOM_ice_shelf.F90