MOM6: mom_diag_to_z Module Reference
mom_diag_to_z Module Reference
Data Types
type diag_to_z_cs
Public Member Functions
subroutine, public calculate_z_diag_fields (u, v, h, dt, G, CS)
subroutine, public calculate_z_transport (uh_int, vh_int, h, dt, G, CS)
subroutine, public find_overlap (e, Z_top, Z_bot, k_max, k_start, k_top, k_bot, wt, z1, z2)
subroutine, public find_limited_slope (val, e, slope, k)
subroutine, public calc_zint_diags (h, in_ptrs, ids, num_diags, G, CS)
subroutine, public register_z_tracer (tr_ptr, name, long_name, units, Time, G, CS)
subroutine, public mom_diag_to_z_init (Time, G, param_file, diag, CS)
subroutine, public mom_diag_to_z_end (CS)
integer function, public ocean_register_diag_with_z (tr_ptr, vardesc_tr, G, Time, CS)
integer function, public register_zint_diag (var_desc, CS, day)
Public Attributes
integer, parameter no_zspace = -1
Private Member Functions
subroutine get_z_depths (depth_file, int_depth_name, int_depth, cell_depth_name, z_axis_index, edge_index, nk_out)
integer function register_z_diag (var_desc, CS, day, missing)
Detailed Description
Definition at line 1 of file MOM_diag_to_Z.F90.
Member Function/Subroutine Documentation
subroutine, public mom_diag_to_z::calc_zint_diags (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(p3d), dimension(:), intent(in) in_ptrs, integer, dimension(:), intent(in) ids, integer, intent(in) num_diags, type(ocean_grid_type), intent(in) G, type(diag_to_z_cs), pointer CS)
Definition at line 616 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error().
Referenced by mom_diabatic_driver::diabatic(), and mom_set_diffusivity::set_diffusivity().
subroutine, public mom_diag_to_z::calculate_z_diag_fields (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diag_to_z_cs), pointer CS)
Definition at line 100 of file MOM_diag_to_Z.F90.
References find_limited_slope(), find_overlap(), and mom_error_handler::mom_error().
Referenced by mom::step_mom().
subroutine, public mom_diag_to_z::calculate_z_transport (real, dimension(nimemb_,njmem_,nkmem_), intent(in) uh_int, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vh_int, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(diag_to_z_cs), pointer CS)
Definition at line 382 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error().
Referenced by mom::step_mom().
subroutine, public mom_diag_to_z::find_limited_slope (real, dimension(:), intent(in) val, real, dimension(:), intent(in) e, real, intent(out) slope, integer, intent(in) k)
Definition at line 586 of file MOM_diag_to_Z.F90.
Referenced by calculate_z_diag_fields(), mom_tracer_z_init::tracer_z_init(), and midas_vertmap::tracer_z_init().
subroutine, public mom_diag_to_z::find_overlap (real, dimension(:), intent(in) e, real, intent(in) Z_top, real, intent(in) Z_bot, integer, intent(in) k_max, integer, intent(in) k_start, integer, intent(inout) k_top, integer, intent(inout) k_bot, real, dimension(:), intent(out) wt, real, dimension(:), intent(out) z1, real, dimension(:), intent(out) z2)
Definition at line 522 of file MOM_diag_to_Z.F90.
Referenced by calculate_z_diag_fields(), mom_tracer_z_init::tracer_z_init(), and midas_vertmap::tracer_z_init().
subroutine mom_diag_to_z::get_z_depths (character(len=*), intent(in) depth_file, character(len=*), intent(in) int_depth_name, real, dimension(:), pointer int_depth, character(len=*), intent(in) cell_depth_name, integer, intent(out) z_axis_index, integer, intent(out) edge_index, integer, intent(out) nk_out) private
Definition at line 878 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error().
Referenced by mom_diag_to_z_init().
subroutine, public mom_diag_to_z::mom_diag_to_z_end (type(diag_to_z_cs), pointer CS)
Definition at line 993 of file MOM_diag_to_Z.F90.
subroutine, public mom_diag_to_z::mom_diag_to_z_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(diag_to_z_cs), pointer CS)
Definition at line 760 of file MOM_diag_to_Z.F90.
References mom_diag_mediator::defineaxes(), get_z_depths(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), and mom_io::slasher().
Referenced by mom::initialize_mom().
integer function, public mom_diag_to_z::ocean_register_diag_with_z (real, dimension(nimem_,njmem_,nkmem_), intent(in), target tr_ptr, type(vardesc), intent(in) vardesc_tr, type(ocean_grid_type), intent(in) G, type(time_type), intent(in) Time, type(diag_to_z_cs), pointer CS)
Definition at line 1006 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error(), mom_diag_mediator::ocean_register_diag(), and register_z_diag().
integer function mom_diag_to_z::register_z_diag (type(vardesc), intent(in) var_desc, type(diag_to_z_cs), pointer CS, type(time_type), intent(in) day, real, intent(in) missing) private
Definition at line 1065 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by ocean_register_diag_with_z().
subroutine, public mom_diag_to_z::register_z_tracer (real, dimension(nimem_,njmem_,nkmem_), intent(in), target tr_ptr, character(len=*), intent(in) name, character(len=*), intent(in) long_name, character(len=*), intent(in) units, type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(diag_to_z_cs), pointer CS)
Definition at line 710 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by advection_test_tracer::initialize_advection_test_tracer(), dome_tracer::initialize_dome_tracer(), ideal_age_example::initialize_ideal_age_tracer(), mom::initialize_mom(), mom_ocmip2_cfc::initialize_ocmip2_cfc(), oil_tracer::initialize_oil_tracer(), and user_tracer_example::user_initialize_tracer().
integer function, public mom_diag_to_z::register_zint_diag (type(vardesc), intent(in) var_desc, type(diag_to_z_cs), pointer CS, type(time_type), intent(in) day)
Definition at line 1111 of file MOM_diag_to_Z.F90.
References mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init(), and mom_set_diffusivity::set_diffusivity_init().
Member Data Documentation
integer, parameter mom_diag_to_z::no_zspace = -1
Definition at line 96 of file MOM_diag_to_Z.F90.
The documentation for this module was generated from the following file:
src/diagnostics/MOM_diag_to_Z.F90