MOM6: mom_checksums Module Reference
mom_checksums Module Reference
Data Types
interface chk_sum_msg
interface chksum
interface hchksum
interface is_nan
interface qchksum
interface uchksum
interface vchksum
Public Member Functions
real function, public totalstuff (G, hThick, stuff)
subroutine, public totaltands (G, hThick, temperature, salinity, mesg)
subroutine, public mom_checksums_init (param_file)
Private Member Functions
subroutine chksum_h_2d (array, mesg, G, haloshift)
subroutine chksum_q_2d (array, mesg, G, haloshift)
subroutine chksum_u_2d (array, mesg, G, haloshift)
subroutine chksum_v_2d (array, mesg, G, haloshift)
subroutine chksum_h_3d (array, mesg, G, haloshift)
subroutine chksum_q_3d (array, mesg, G, haloshift)
subroutine chksum_u_3d (array, mesg, G, haloshift)
subroutine chksum_v_3d (array, mesg, G, haloshift)
subroutine hchksum2d (array, mesg, start_x, end_x, start_y, end_y, haloshift)
subroutine hchksum3d (array, mesg, start_x, end_x, start_y, end_y, haloshift)
subroutine chksum1d (array, mesg, start_x, end_x)
subroutine chksum2d (array, mesg, start_x, end_x, start_y, end_y)
subroutine chksum3d (array, mesg, start_x, end_x, start_y, end_y, start_z, end_z)
logical function is_nan_0d (x)
logical function is_nan_1d (x, skip_mpp)
logical function is_nan_2d (x)
logical function is_nan_3d (x)
subroutine chk_sum_msg1 (fmsg, bc0, mesg)
subroutine chk_sum_msg5 (fmsg, bc0, bcSW, bcSE, bcNW, bcNE, mesg)
subroutine chk_sum_msg3 (fmsg, aMean, aMin, aMax, mesg)
subroutine chksum_error (signal, message)
Private Attributes
integer, parameter default_shift =0
logical calculatestatistics =.false.
logical checkfornans =.true.
Detailed Description
Definition at line 1 of file MOM_checksums.F90.
Member Function/Subroutine Documentation
subroutine mom_checksums::chk_sum_msg1 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, character(len=*), intent(in) mesg) private
Definition at line 1208 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine mom_checksums::chk_sum_msg3 (character(len=*), intent(in) fmsg, real, intent(in) aMean, real, intent(in) aMin, real, intent(in) aMax, character(len=*), intent(in) mesg) private
Definition at line 1225 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine mom_checksums::chk_sum_msg5 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcSW, integer, intent(in) bcSE, integer, intent(in) bcNW, integer, intent(in) bcNE, character(len=*), intent(in) mesg) private
Definition at line 1216 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine mom_checksums::chksum1d (real, dimension(:) array, character(len=*) mesg, integer, optional start_x, integer, optional end_x) private
Definition at line 938 of file MOM_checksums.F90.
References bitcount(), and mom_error_handler::is_root_pe().
subroutine mom_checksums::chksum2d (real, dimension(:,:) array, character(len=*) mesg, integer, optional start_x, integer, optional end_x, integer, optional start_y, integer, optional end_y) private
Definition at line 975 of file MOM_checksums.F90.
References bitcount(), and mom_error_handler::is_root_pe().
subroutine mom_checksums::chksum3d (real, dimension(:,:,:) array, character(len=*) mesg, integer, optional start_x, integer, optional end_x, integer, optional start_y, integer, optional end_y, integer, optional start_z, integer, optional end_z) private
Definition at line 1020 of file MOM_checksums.F90.
References bitcount(), and mom_error_handler::is_root_pe().
subroutine mom_checksums::chksum_error (integer, intent(in) signal, character(len=*), intent(in) message) private
Definition at line 1246 of file MOM_checksums.F90.
References mom_error_handler::mom_error().
Referenced by chksum_h_2d(), chksum_h_3d(), chksum_q_2d(), chksum_q_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), chksum_v_3d(), hchksum2d(), and hchksum3d().
subroutine mom_checksums::chksum_h_2d (real, dimension(g%isd:,g%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 92 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_h_3d (real, dimension(g%isd:,g%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 456 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_q_2d (real, dimension(g%isdb:,g%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 183 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_q_3d (real, dimension(g%isdb:,g%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 547 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_u_2d (real, dimension(g%isdb:,g%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 274 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_u_3d (real, dimension(g%isdb:,g%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 638 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_v_2d (real, dimension(g%isd:,g%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 365 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::chksum_v_3d (real, dimension(g%isd:,g%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift) private
Definition at line 729 of file MOM_checksums.F90.
References chksum_error(), mom_error_handler::is_root_pe(), subchk(), and substats().
subroutine mom_checksums::hchksum2d (real, dimension(:,:) array, character(len=*) mesg, integer start_x, integer end_x, integer start_y, integer end_y, integer, optional haloshift) private
Definition at line 820 of file MOM_checksums.F90.
References chksum_error(), hsubsum2d(), and mom_error_handler::is_root_pe().
subroutine mom_checksums::hchksum3d (real, dimension(:,:,:) array, character(len=*) mesg, integer start_x, integer end_x, integer start_y, integer end_y, integer, optional haloshift) private
Definition at line 877 of file MOM_checksums.F90.
References chksum_error(), hsubsum3d(), and mom_error_handler::is_root_pe().
logical function mom_checksums::is_nan_0d (real, intent(in) x) private
Definition at line 1072 of file MOM_checksums.F90.
References mom_checksums::is_nan::is_nan_0d().
logical function mom_checksums::is_nan_1d (real, dimension(:), intent(in) x, logical, optional skip_mpp) private
Definition at line 1090 of file MOM_checksums.F90.
References mom_checksums::is_nan::is_nan_0d(), and mom_checksums::is_nan::is_nan_1d().
logical function mom_checksums::is_nan_2d (real, dimension(:,:), intent(in) x) private
Definition at line 1114 of file MOM_checksums.F90.
References mom_checksums::is_nan::is_nan_0d(), and mom_checksums::is_nan::is_nan_2d().
logical function mom_checksums::is_nan_3d (real, dimension(:,:,:), intent(in) x) private
Definition at line 1132 of file MOM_checksums.F90.
References mom_checksums::is_nan::is_nan_0d(), and mom_checksums::is_nan::is_nan_3d().
subroutine, public mom_checksums::mom_checksums_init (type(param_file_type), intent(in) param_file)
Definition at line 1234 of file MOM_checksums.F90.
References mom_file_parser::log_version().
Referenced by mom::initialize_mom().
real function, public mom_checksums::totalstuff (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsd:,:), intent(in) hThick, real, dimension(g%isd:,g%jsd:,:), intent(in) stuff)
Definition at line 1152 of file MOM_checksums.F90.
Referenced by totaltands().
subroutine, public mom_checksums::totaltands (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsd:,:), intent(in) hThick, real, dimension(g%isd:,g%jsd:,:), intent(in) temperature, real, dimension(g%isd:,g%jsd:,:), intent(in) salinity, character(len=*), intent(in) mesg)
Definition at line 1169 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe(), and totalstuff().
Member Data Documentation
logical mom_checksums::calculatestatistics =.false. private
Definition at line 83 of file MOM_checksums.F90.
logical mom_checksums::checkfornans =.true. private
Definition at line 85 of file MOM_checksums.F90.
integer, parameter mom_checksums::default_shift =0 private
Definition at line 82 of file MOM_checksums.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_checksums.F90