MOM6: mom_regularize_layers Module Reference
mom_regularize_layers Module Reference
Data Types
type regularize_layers_cs
Public Member Functions
subroutine, public regularize_layers (h, tv, dt, ea, eb, G, CS)
subroutine, public regularize_layers_init (Time, G, param_file, diag, CS)
Public Attributes
integer id_clock_pass
Private Member Functions
subroutine regularize_surface (h, tv, dt, ea, eb, G, CS)
subroutine find_deficit_ratios (e, def_rat_u, def_rat_v, G, CS, def_rat_u_2lay, def_rat_v_2lay, halo, h)
Private Attributes
integer id_clock_eos
Detailed Description
Definition at line 1 of file MOM_regularize_layers.F90.
Member Function/Subroutine Documentation
subroutine mom_regularize_layers::find_deficit_ratios (real, dimension(nimem_,njmem_,nk_interface_), intent(in) e, real, dimension(nimemb_,njmem_), intent(out) def_rat_u, real, dimension(nimem_,njmemb_), intent(out) def_rat_v, type(ocean_grid_type), intent(in) G, type(regularize_layers_cs), pointer CS, real, dimension(nimemb_,njmem_), intent(out), optional def_rat_u_2lay, real, dimension(nimem_,njmemb_), intent(out), optional def_rat_v_2lay, integer, intent(in), optional halo, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional h) private
Definition at line 748 of file MOM_regularize_layers.F90.
Referenced by regularize_surface().
subroutine, public mom_regularize_layers::regularize_layers (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) eb, type(ocean_grid_type), intent(inout) G, type(regularize_layers_cs), pointer CS)
Definition at line 109 of file MOM_regularize_layers.F90.
References mom_error_handler::mom_error(), and regularize_surface().
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_regularize_layers::regularize_layers_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(regularize_layers_cs), pointer CS)
Definition at line 898 of file MOM_regularize_layers.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
subroutine mom_regularize_layers::regularize_surface (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) ea, real, dimension(nimem_,njmem_,nkmem_), intent(inout) eb, type(ocean_grid_type), intent(inout) G, type(regularize_layers_cs), pointer CS) private
Definition at line 154 of file MOM_regularize_layers.F90.
References find_deficit_ratios(), and mom_error_handler::mom_error().
Referenced by regularize_layers().
Member Data Documentation
integer mom_regularize_layers::id_clock_eos private
Definition at line 105 of file MOM_regularize_layers.F90.
integer mom_regularize_layers::id_clock_pass
Definition at line 105 of file MOM_regularize_layers.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_regularize_layers.F90