MOM6: user_initialization Module Reference
user_initialization Module Reference
Public Member Functions
subroutine, public user_set_coord (Rlay, g_prime, G, param_file, eqn_of_state)
subroutine, public user_initialize_topography (D, G, param_file)
subroutine, public user_initialize_thickness (h, G, param_file, T)
subroutine, public user_initialize_velocity (u, v, G, param_file)
subroutine, public user_init_temperature_salinity (T, S, G, param_file, eqn_of_state)
subroutine, public user_init_mixed_layer_density (Rml, G, param_file, use_temperature, eqn_of_state, T, S, P_Ref)
subroutine, public user_initialize_sponges (G, use_temperature, tv, param_file, CSp, h)
subroutine, public user_set_open_bdry_conds (OBC, tv, G, param_file, tr_Reg)
subroutine, public user_set_rotation (G, param_file)
Private Member Functions
subroutine write_user_log (param_file)
Private Attributes
logical first_call = .true.
Detailed Description
Definition at line 1 of file user_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public user_initialization::user_init_mixed_layer_density (real, dimension(nimem_, njmem_, nkmem_), intent(out) Rml, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in) use_temperature, type(eos_type), optional, pointer eqn_of_state, real, dimension(nimem_, njmem_, nkmem_), intent(in), optional T, real, dimension(nimem_, njmem_, nkmem_), intent(in), optional S, real, intent(in), optional P_Ref)
Definition at line 186 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
subroutine, public user_initialization::user_init_temperature_salinity (real, dimension(nimem_, njmem_, nkmem_), intent(out) T, real, dimension(nimem_, njmem_, nkmem_), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Definition at line 170 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_initialize_sponges (type(ocean_grid_type), intent(in) G, logical, intent(in) use_temperature, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CSp, real, dimension(nimem_, njmem_, nkmem_), intent(in) h)
Definition at line 205 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, dimension(nimem_,njmem_, nkmem_), intent(in) T)
Definition at line 139 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 125 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize_topography().
subroutine, public user_initialization::user_initialize_velocity (real, dimension(nimemb_, njmem_, nkmem_), intent(out) u, real, dimension(nimem_, njmemb_, nkmem_), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 154 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_set_coord (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Definition at line 109 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_set_open_bdry_conds (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
Definition at line 220 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_initialization::mom_initialize().
subroutine, public user_initialization::user_set_rotation (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file)
Definition at line 234 of file user_initialization.F90.
References mom_error_handler::mom_error(), and write_user_log().
subroutine user_initialization::write_user_log (type(param_file_type), intent(in) param_file) private
Definition at line 245 of file user_initialization.F90.
References mom_file_parser::log_version().
Referenced by user_init_mixed_layer_density(), user_init_temperature_salinity(), user_initialize_sponges(), user_initialize_thickness(), user_initialize_topography(), user_initialize_velocity(), user_set_coord(), user_set_open_bdry_conds(), and user_set_rotation().
Member Data Documentation
logical user_initialization::first_call = .true. private
Definition at line 105 of file user_initialization.F90.
The documentation for this module was generated from the following file:
src/user/user_initialization.F90