MOM6: mom_mixed_layer_restrat Module Reference
mom_mixed_layer_restrat Module Reference
Data Types
type mixedlayer_restrat_cs
Public Member Functions
subroutine, public mixedlayer_restrat (h, uhtr, vhtr, tv, fluxes, dt, G, CS)
subroutine, public mixedlayer_restrat_init (Time, G, param_file, diag, CS)
Detailed Description
Definition at line 1 of file MOM_mixed_layer_restrat.F90.
Member Function/Subroutine Documentation
subroutine, public mom_mixed_layer_restrat::mixedlayer_restrat (real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_,nkmem_), intent(inout) uhtr, real, dimension(nimem_,njmemb_,nkmem_), intent(inout) vhtr, type(thermo_var_ptrs), intent(in) tv, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(mixedlayer_restrat_cs), pointer CS)
Definition at line 91 of file MOM_mixed_layer_restrat.F90.
References mom_error_handler::mom_error(), and mom_diag_mediator::query_averaging_enabled().
Referenced by mom::step_mom().
subroutine, public mom_mixed_layer_restrat::mixedlayer_restrat_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(mixedlayer_restrat_cs), pointer CS)
Definition at line 316 of file MOM_mixed_layer_restrat.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), and mom_diag_mediator::register_diag_field().
Referenced by mom::initialize_mom().
The documentation for this module was generated from the following file:
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90