MOM6: mom_regridding Module Reference
mom_regridding Module Reference
Data Types
type regridding_cs
Public Member Functions
subroutine, public initialize_regridding (nk, coordMode, interpScheme, CS)
subroutine, public end_regridding (CS)
subroutine, public regridding_main (remapCS, CS, G, h, tv, dzInterface)
subroutine, public check_grid_integrity (CS, G, h)
real function, dimension(nk),
public uniformresolution (nk, coordMode, maxDepth, rhoLight, rhoHeavy)
subroutine, public setcoordinateresolution (dz, CS)
real function, dimension(cs%nk),
public getcoordinateresolution (CS)
real function, dimension(cs%nk+1),
public getcoordinateinterfaces (CS)
character(len=20) function, public getcoordinateunits (CS)
character(len=20) function, public getcoordinateshortname (CS)
subroutine, public setregriddingboundaryextrapolation (onOff, CS)
subroutine, public setregriddingminimumthickness (minThickness, CS)
Public Attributes
character(len=158), parameter,
public regriddingcoordinatemodedoc = " LAYER - Isopycnal or stacked shallow water layers\n"// " Z* - stetched geopotential z*\n"// " SIGMA - terrain following coordinates\n"// " RHO - continuous isopycnal\n"
character(len=338), parameter,
public regriddinginterpschemedoc = " P1M_H2 (2nd-order accurate)\n"// " P1M_H4 (2nd-order accurate)\n"// " P1M_IH4 (2nd-order accurate)\n"// " PLM (2nd-order accurate)\n"// " PPM_H4 (3rd-order accurate)\n"// " PPM_IH4 (3rd-order accurate)\n"// " P3M_IH4IH3 (4th-order accurate)\n"// " P3M_IH6IH5 (4th-order accurate)\n"// " PQM_IH4IH3 (4th-order accurate)\n"// " PQM_IH6IH5 (5th-order accurate)"
character(len=6), parameter, public regriddingdefaultinterpscheme = "P1M_H2"
logical, parameter, public regriddingdefaultboundaryextrapolation = .false.
real, parameter, public regriddingdefaultminthickness = 1.e-3
Private Member Functions
subroutine checkgridsmatch (G, h, dzInterface)
subroutine buildgridzstar (CS, G, h, dzInterface)
subroutine buildgridsigma (CS, G, h, dzInterface)
subroutine buildgridrho (G, h, tv, dzInterface, remapCS, CS)
subroutine build_grid_arbitrary (G, h, dzInterface, h_new, CS)
subroutine regridding_iteration (densities, target_values, CS, n0, h0, x0, ppoly0, n1, h1, x1)
subroutine interpolate_grid (n0, h0, x0, ppoly0, target_values, degree, n1, h1, x1)
real function get_polynomial_coordinate (N, h, ppoly, target_value, degree)
subroutine inflate_vanished_layers (minThickness, N, h)
subroutine convective_adjustment (G, h, tv)
subroutine allocate_regridding (CS)
subroutine regridding_memory_deallocation (CS)
Private Attributes
integer, parameter interpolation_p1m_h2 = 0
integer, parameter interpolation_p1m_h4 = 1
integer, parameter interpolation_p1m_ih4 = 2
integer, parameter interpolation_plm = 3
integer, parameter interpolation_ppm_h4 = 4
integer, parameter interpolation_ppm_ih4 = 5
integer, parameter interpolation_p3m_ih4ih3 = 6
integer, parameter interpolation_p3m_ih6ih5 = 7
integer, parameter interpolation_pqm_ih4ih3 = 8
integer, parameter interpolation_pqm_ih6ih5 = 9
integer, parameter degree_1 = 1
integer, parameter degree_2 = 2
integer, parameter degree_3 = 3
integer, parameter degree_4 = 4
integer, parameter nb_regridding_iterations = 1
real, parameter deviation_tolerance = 1e-10
integer, parameter nr_iterations = 8
real, parameter nr_tolerance = 1e-12
real, parameter nr_offset = 1e-6
Detailed Description
Definition at line 1 of file MOM_regridding.F90.
Member Function/Subroutine Documentation
subroutine mom_regridding::allocate_regridding (type(regridding_cs), intent(inout) CS) private
Definition at line 1637 of file MOM_regridding.F90.
References regrid_ppoly_class::ppoly_init(), regrid_edge_values::tridiagedgeworkallocate(), and regrid_edge_slopes::tridiagslopeworkallocate().
Referenced by initialize_regridding().
subroutine mom_regridding::build_grid_arbitrary (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) dzInterface, real, intent(inout) h_new, type(regridding_cs), intent(in) CS) private
Definition at line 793 of file MOM_regridding.F90.
Referenced by regridding_main().
subroutine mom_regridding::buildgridrho (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) dzInterface, type(remapping_cs), intent(inout) remapCS, type(regridding_cs), intent(inout) CS) private
Definition at line 562 of file MOM_regridding.F90.
References mom_error_handler::mom_error(), regridding_iteration(), and mom_remapping::remapping_core().
Referenced by regridding_main().
subroutine mom_regridding::buildgridsigma (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) dzInterface) private
Definition at line 482 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by regridding_main().
subroutine mom_regridding::buildgridzstar (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) dzInterface) private
Definition at line 377 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by regridding_main().
subroutine, public mom_regridding::check_grid_integrity (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h)
Definition at line 1302 of file MOM_regridding.F90.
References inflate_vanished_layers().
Referenced by mom_ale::adjustgridforintegrity().
subroutine mom_regridding::checkgridsmatch (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nk_interface_), intent(in) dzInterface) private
Definition at line 305 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by regridding_main().
subroutine mom_regridding::convective_adjustment (type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv) private
Definition at line 1406 of file MOM_regridding.F90.
Referenced by mom_bulk_mixed_layer::bulkmixedlayer(), and regridding_main().
subroutine, public mom_regridding::end_regridding (type(regridding_cs), intent(inout) CS)
Definition at line 228 of file MOM_regridding.F90.
References regridding_memory_deallocation().
Referenced by mom_ale::end_ale().
real function mom_regridding::get_polynomial_coordinate (integer, intent(in) N, real, dimension(:), intent(in) h, type(ppoly_t), intent(in) ppoly, real, intent(in) target_value, integer, intent(in) degree) private
Definition at line 1136 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by interpolate_grid().
real function, dimension(cs%nk+1), public mom_regridding::getcoordinateinterfaces (type(regridding_cs), intent(in) CS)
Definition at line 1546 of file MOM_regridding.F90.
Referenced by mom_ale::ale_getcoordinate(), and mom_ale::ale_updateverticalgridtype().
real function, dimension(cs%nk), public mom_regridding::getcoordinateresolution (type(regridding_cs), intent(in) CS)
Definition at line 1535 of file MOM_regridding.F90.
Referenced by mom_ale::ale_writecoordinatefile().
character(len=20) function, public mom_regridding::getcoordinateshortname (type(regridding_cs), intent(in) CS)
Definition at line 1589 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by mom_ale::ale_updateverticalgridtype().
character(len=20) function, public mom_regridding::getcoordinateunits (type(regridding_cs), intent(in) CS)
Definition at line 1566 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by mom_ale::ale_getcoordinateunits(), mom_ale::ale_updateverticalgridtype(), and mom_ale::ale_writecoordinatefile().
subroutine mom_regridding::inflate_vanished_layers (real, intent(in) minThickness, integer, intent(in) N, real, dimension(:), intent(inout) h) private
Definition at line 1344 of file MOM_regridding.F90.
Referenced by check_grid_integrity(), and regridding_iteration().
subroutine, public mom_regridding::initialize_regridding (integer, intent(in) nk, character(len=*), intent(in) coordMode, character(len=*), intent(in) interpScheme, type(regridding_cs), intent(inout) CS)
Definition at line 180 of file MOM_regridding.F90.
References allocate_regridding(), regrid_consts::coordinatemode(), mom_error_handler::mom_error(), and mom_string_functions::uppercase().
Referenced by mom_ale::ale_initregridding().
subroutine mom_regridding::interpolate_grid (integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) x0, type(ppoly_t), intent(in) ppoly0, real, dimension(:), intent(in) target_values, integer, intent(in) degree, integer, intent(in) n1, real, dimension(:), intent(inout) h1, real, dimension(:), intent(inout) x1) private
Definition at line 1095 of file MOM_regridding.F90.
References get_polynomial_coordinate().
Referenced by regridding_iteration().
subroutine mom_regridding::regridding_iteration (real, dimension(:), intent(in) densities, real, dimension(:), intent(in) target_values, type(regridding_cs), intent(inout) CS, integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) x0, type(ppoly_t), intent(inout) ppoly0, integer, intent(in) n1, real, dimension(:), intent(out) h1, real, dimension(:), intent(out) x1) private
Definition at line 895 of file MOM_regridding.F90.
References regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h2(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), regrid_edge_values::edge_values_implicit_h6(), inflate_vanished_layers(), interpolate_grid(), p1m_functions::p1m_boundary_extrapolation(), p1m_functions::p1m_interpolation(), p3m_functions::p3m_boundary_extrapolation(), p3m_functions::p3m_interpolation(), plm_functions::plm_boundary_extrapolation(), plm_functions::plm_reconstruction(), ppm_functions::ppm_boundary_extrapolation(), ppm_functions::ppm_reconstruction(), pqm_functions::pqm_boundary_extrapolation_v1(), and pqm_functions::pqm_reconstruction().
Referenced by buildgridrho().
subroutine, public mom_regridding::regridding_main (type(remapping_cs), intent(inout) remapCS, type(regridding_cs), intent(inout) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_, nkmem_), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, real, dimension(nimem_,njmem_, nk_interface_), intent(inout) dzInterface)
Definition at line 244 of file MOM_regridding.F90.
References build_grid_arbitrary(), buildgridrho(), buildgridsigma(), buildgridzstar(), checkgridsmatch(), convective_adjustment(), and mom_error_handler::mom_error().
Referenced by mom_ale::ale_main().
subroutine mom_regridding::regridding_memory_deallocation (type(regridding_cs), intent(inout) CS) private
Definition at line 1680 of file MOM_regridding.F90.
References regrid_ppoly_class::ppoly_destroy(), regrid_edge_values::tridiagedgeworkdeallocate(), and regrid_edge_slopes::tridiagslopeworkdeallocate().
Referenced by end_regridding().
subroutine, public mom_regridding::setcoordinateresolution (real, dimension(:), intent(in) dz, type(regridding_cs), intent(inout) CS)
Definition at line 1521 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by mom_ale::ale_initregridding().
subroutine, public mom_regridding::setregriddingboundaryextrapolation (logical, intent(in) onOff, type(regridding_cs), intent(inout) CS)
Definition at line 1614 of file MOM_regridding.F90.
Referenced by mom_ale::ale_initregridding().
subroutine, public mom_regridding::setregriddingminimumthickness (real, intent(in) minThickness, type(regridding_cs), intent(inout) CS)
Definition at line 1625 of file MOM_regridding.F90.
Referenced by mom_ale::ale_initregridding().
real function, dimension(nk), public mom_regridding::uniformresolution (integer, intent(in) nk, character(len=*), intent(in) coordMode, real, intent(in) maxDepth, real, intent(in) rhoLight, real, intent(in) rhoHeavy)
Definition at line 1484 of file MOM_regridding.F90.
References regrid_consts::coordinatemode(), and mom_error_handler::mom_error().
Referenced by mom_ale::ale_initregridding().
Member Data Documentation
integer, parameter mom_regridding::degree_1 = 1 private
Definition at line 152 of file MOM_regridding.F90.
integer, parameter mom_regridding::degree_2 = 2 private
Definition at line 152 of file MOM_regridding.F90.
integer, parameter mom_regridding::degree_3 = 3 private
Definition at line 152 of file MOM_regridding.F90.
integer, parameter mom_regridding::degree_4 = 4 private
Definition at line 152 of file MOM_regridding.F90.
real, parameter mom_regridding::deviation_tolerance = 1e-10 private
Definition at line 157 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_p1m_h2 = 0 private
Definition at line 140 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_p1m_h4 = 1 private
Definition at line 141 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_p1m_ih4 = 2 private
Definition at line 142 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_p3m_ih4ih3 = 6 private
Definition at line 146 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_p3m_ih6ih5 = 7 private
Definition at line 147 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_plm = 3 private
Definition at line 143 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_ppm_h4 = 4 private
Definition at line 144 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_ppm_ih4 = 5 private
Definition at line 145 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_pqm_ih4ih3 = 8 private
Definition at line 148 of file MOM_regridding.F90.
integer, parameter mom_regridding::interpolation_pqm_ih6ih5 = 9 private
Definition at line 149 of file MOM_regridding.F90.
integer, parameter mom_regridding::nb_regridding_iterations = 1 private
Definition at line 155 of file MOM_regridding.F90.
integer, parameter mom_regridding::nr_iterations = 8 private
Definition at line 161 of file MOM_regridding.F90.
real, parameter mom_regridding::nr_offset = 1e-6 private
Definition at line 167 of file MOM_regridding.F90.
real, parameter mom_regridding::nr_tolerance = 1e-12 private
Definition at line 163 of file MOM_regridding.F90.
character(len=158), parameter, public mom_regridding::regriddingcoordinatemodedoc = " LAYER - Isopycnal or stacked shallow water layers\n"// " Z* - stetched geopotential z*\n"// " SIGMA - terrain following coordinates\n"// " RHO - continuous isopycnal\n"
Definition at line 116 of file MOM_regridding.F90.
logical, parameter, public mom_regridding::regriddingdefaultboundaryextrapolation = .false.
Definition at line 133 of file MOM_regridding.F90.
character(len=6), parameter, public mom_regridding::regriddingdefaultinterpscheme = "P1M_H2"
Definition at line 132 of file MOM_regridding.F90.
real, parameter, public mom_regridding::regriddingdefaultminthickness = 1.e-3
Definition at line 134 of file MOM_regridding.F90.
character(len=338), parameter, public mom_regridding::regriddinginterpschemedoc = " P1M_H2 (2nd-order accurate)\n"// " P1M_H4 (2nd-order accurate)\n"// " P1M_IH4 (2nd-order accurate)\n"// " PLM (2nd-order accurate)\n"// " PPM_H4 (3rd-order accurate)\n"// " PPM_IH4 (3rd-order accurate)\n"// " P3M_IH4IH3 (4th-order accurate)\n"// " P3M_IH6IH5 (4th-order accurate)\n"// " PQM_IH4IH3 (4th-order accurate)\n"// " PQM_IH6IH5 (5th-order accurate)"
Definition at line 121 of file MOM_regridding.F90.
The documentation for this module was generated from the following file:
src/ALE/MOM_regridding.F90