MOM6: mom_diag_mediator Module Reference
mom_diag_mediator Module Reference
Data Types
type axestype
type diag_ctrl
type maskcontainer
interface post_data
Public Member Functions
subroutine, public set_axes_info (G, param_file, diag, set_vertical)
subroutine, public defineaxes (diag, handles, axes)
subroutine, public set_diag_mediator_grid (G, diag)
subroutine, public enable_averaging (time_int_in, time_end_in, diag)
subroutine, public disable_averaging (diag)
logical function, public query_averaging_enabled (diag, time_int, time_end)
type(time_type) function, public get_diag_time_end (diag)
integer function, public register_diag_field (module_name, field_name, axes, init_time, long_name, units, missing_value, range, mask_variant, standard_name, verbose, do_not_log, err_msg, interp_method, tile_count)
integer function, public register_static_field (module_name, field_name, axes, long_name, units, missing_value, range, mask_variant, standard_name, do_not_log, interp_method, tile_count)
integer function, public register_scalar_field (module_name, field_name, init_time, diag, long_name, units, missing_value, range, mask_variant, standard_name, verbose, do_not_log, err_msg, interp_method, tile_count)
integer function, public ocean_register_diag (var_desc, G, diag, day)
subroutine, public diag_mediator_init (G, param_file, diag, err_msg)
subroutine, public diag_masks_set (G, missing_value, diag)
subroutine, public diag_mediator_close_registration ()
subroutine, public diag_mediator_end (time)
Public Attributes
integer doc_unit = -1
Private Member Functions
subroutine post_data_0d (diag_field_id, field, diag, is_static, mask)
subroutine post_data_2d (diag_field_id, field, diag, is_static, mask)
subroutine post_data_3d (diag_field_id, field, diag, is_static, mask)
subroutine describe_option (opt_name, value)
character(len=15) function i2s (a, n_in)
Detailed Description
Definition at line 1 of file MOM_diag_mediator.F90.
Member Function/Subroutine Documentation
subroutine, public mom_diag_mediator::defineaxes (type(diag_ctrl), intent(in), target diag, integer, dimension(:), intent(in) handles, type(axestype), intent(out) axes)
Definition at line 228 of file MOM_diag_mediator.F90.
References i2s(), and mom_error_handler::mom_error().
Referenced by mom_internal_tides::internal_tides_init(), mom_diag_to_z::mom_diag_to_z_init(), and set_axes_info().
subroutine mom_diag_mediator::describe_option (character(len=*), intent(in) opt_name, character(len=*), intent(in) value) private
Definition at line 709 of file MOM_diag_mediator.F90.
Referenced by register_diag_field(), and register_scalar_field().
subroutine, public mom_diag_mediator::diag_masks_set (type(ocean_grid_type), intent(in), target G, real, intent(in) missing_value, type(diag_ctrl), pointer diag)
Definition at line 873 of file MOM_diag_mediator.F90.
Referenced by mom::initialize_mom().
subroutine, public mom_diag_mediator::diag_mediator_close_registration ()
Definition at line 910 of file MOM_diag_mediator.F90.
Referenced by mom_main(), ocean_model_mod::ocean_model_init(), and shelf_main().
subroutine, public mom_diag_mediator::diag_mediator_end (type(time_type), intent(in) time)
Definition at line 918 of file MOM_diag_mediator.F90.
Referenced by mom_main(), and shelf_main().
subroutine, public mom_diag_mediator::diag_mediator_init (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout) diag, character(len=*), intent(out), optional err_msg)
Definition at line 818 of file MOM_diag_mediator.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
subroutine, public mom_diag_mediator::disable_averaging (type(diag_ctrl), intent(inout) diag)
Definition at line 467 of file MOM_diag_mediator.F90.
Referenced by mom::initialize_mom(), mom_main(), shelf_main(), mom::step_mom(), mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2(), and ocean_model_mod::update_ocean_model().
subroutine, public mom_diag_mediator::enable_averaging (real, intent(in) time_int_in, type(time_type), intent(in) time_end_in, type(diag_ctrl), intent(inout) diag)
Definition at line 448 of file MOM_diag_mediator.F90.
Referenced by mom_barotropic::btstep(), mom::initialize_mom(), mom_legacy_barotropic::legacy_btstep(), mom_main(), shelf_main(), mom::step_mom(), mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2(), and ocean_model_mod::update_ocean_model().
type(time_type) function, public mom_diag_mediator::get_diag_time_end (type(diag_ctrl), intent(in) diag)
Definition at line 492 of file MOM_diag_mediator.F90.
character(len=15) function mom_diag_mediator::i2s (integer, dimension(:), intent(in) a, integer, intent(in), optional n_in) private
Definition at line 929 of file MOM_diag_mediator.F90.
Referenced by defineaxes().
integer function, public mom_diag_mediator::ocean_register_diag (type(vardesc), intent(in) var_desc, type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(in) diag, type(time_type), intent(in) day)
Definition at line 721 of file MOM_diag_mediator.F90.
References mom_error_handler::mom_error(), and register_diag_field().
Referenced by mom_diag_to_z::ocean_register_diag_with_z().
subroutine mom_diag_mediator::post_data_0d (integer, intent(in) diag_field_id, real, intent(in) field, type(diag_ctrl), intent(in) diag, logical, intent(in), optional is_static, real, dimension(:,:), intent(in), optional mask) private
Definition at line 254 of file MOM_diag_mediator.F90.
subroutine mom_diag_mediator::post_data_2d (integer, intent(in) diag_field_id, real, dimension(:,:), intent(in) field, type(diag_ctrl), intent(in) diag, logical, intent(in), optional is_static, real, dimension(:,:), intent(in), optional mask) private
Definition at line 278 of file MOM_diag_mediator.F90.
References mom_error_handler::mom_error().
subroutine mom_diag_mediator::post_data_3d (integer, intent(in) diag_field_id, real, dimension(:,:,:), intent(in) field, type(diag_ctrl), intent(in) diag, logical, intent(in), optional is_static, real, dimension(:,:,:), intent(in), optional mask) private
Definition at line 362 of file MOM_diag_mediator.F90.
References mom_error_handler::mom_error().
logical function, public mom_diag_mediator::query_averaging_enabled (type(diag_ctrl), intent(in) diag, real, intent(out), optional time_int, type(time_type), intent(out), optional time_end)
Definition at line 478 of file MOM_diag_mediator.F90.
Referenced by mom_sponge::apply_sponge(), mom_surface_forcing::average_forcing(), mom_barotropic::btstep(), mom_lateral_mixing_coeffs::calc_resoln_function(), mom_lateral_mixing_coeffs::calc_slope_function_(), mom_coriolisadv::coradcalc(), mom_legacy_barotropic::legacy_btstep(), mom_mixed_layer_restrat::mixedlayer_restrat(), mom_internal_tides::propagate_int_tide(), mom_opacity::set_opacity(), and mom_thickness_diffuse::thickness_diffuse().
integer function, public mom_diag_mediator::register_diag_field (character(len=*), intent(in) module_name, character(len=*), intent(in) field_name, type(axestype), intent(in) axes, type(time_type), intent(in) init_time, character(len=*), intent(in), optional long_name, character(len=*), intent(in), optional units, real, intent(in), optional missing_value, real, dimension(2), intent(in), optional range, logical, intent(in), optional mask_variant, character(len=*), intent(in), optional standard_name, logical, intent(in), optional verbose, logical, intent(in), optional do_not_log, character(len=*), intent(out), optional err_msg, character(len=*), intent(in), optional interp_method, integer, intent(in), optional tile_count)
Definition at line 503 of file MOM_diag_mediator.F90.
References describe_option(), mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by mom_barotropic::barotropic_init(), mom_bulk_mixed_layer::bulkmixedlayer_init(), mom_coriolisadv::coriolisadv_init(), mom_diabatic_driver::diabatic_driver_init(), mom_diffconvection::diffconvection_init(), mom_entrain_diffusive::entrain_diffusive_init(), mom_hor_visc::hor_visc_init(), mom_sponge::init_sponge_diags(), advection_test_tracer::initialize_advection_test_tracer(), dome_tracer::initialize_dome_tracer(), mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2(), ideal_age_example::initialize_ideal_age_tracer(), mom_ocmip2_cfc::initialize_ocmip2_cfc(), oil_tracer::initialize_oil_tracer(), mom_int_tide_input::int_tide_input_init(), mom_internal_tides::internal_tides_init(), mom_kappa_shear::kappa_shear_init(), mom_kpp::kpp_init(), mom_legacy_barotropic::legacy_barotropic_init(), mom_meke::meke_init(), mom_mixed_layer_restrat::mixedlayer_restrat_init(), mom_diag_to_z::mom_diag_to_z_init(), mom_diagnostics::mom_diagnostics_init(), ocean_register_diag(), mom_opacity::opacity_init(), mom_pressureforce_afv::pressureforce_afv_init(), mom_pressureforce_mont::pressureforce_mont_init(), mom::register_diags(), mom_diag_to_z::register_z_diag(), mom_diag_to_z::register_z_tracer(), mom_diag_to_z::register_zint_diag(), mom_regularize_layers::regularize_layers_init(), mom_set_diffusivity::set_diffusivity_init(), mom_set_visc::set_visc_init(), mom_surface_forcing::surface_forcing_init(), mom_thickness_diffuse::thickness_diffuse_init(), user_tracer_example::user_initialize_tracer(), mom_lateral_mixing_coeffs::varmix_init(), and mom_vert_friction::vertvisc_init().
integer function, public mom_diag_mediator::register_scalar_field (character(len=*), intent(in) module_name, character(len=*), intent(in) field_name, type(time_type), intent(in) init_time, type(diag_ctrl), intent(in) diag, character(len=*), intent(in), optional long_name, character(len=*), intent(in), optional units, real, intent(in), optional missing_value, real, dimension(2), intent(in), optional range, logical, intent(in), optional mask_variant, character(len=*), intent(in), optional standard_name, logical, intent(in), optional verbose, logical, intent(in), optional do_not_log, character(len=*), intent(out), optional err_msg, character(len=*), intent(in), optional interp_method, integer, intent(in), optional tile_count)
Definition at line 653 of file MOM_diag_mediator.F90.
References describe_option(), and mom_error_handler::is_root_pe().
Referenced by mom::register_diags(), and mom_surface_forcing::surface_forcing_init().
integer function, public mom_diag_mediator::register_static_field (character(len=*), intent(in) module_name, character(len=*), intent(in) field_name, type(axestype), intent(in) axes, character(len=*), intent(in), optional long_name, character(len=*), intent(in), optional units, real, intent(in), optional missing_value, real, dimension(2), intent(in), optional range, logical, intent(in), optional mask_variant, character(len=*), intent(in), optional standard_name, logical, intent(in), optional do_not_log, character(len=*), intent(in), optional interp_method, integer, intent(in), optional tile_count)
Definition at line 615 of file MOM_diag_mediator.F90.
Referenced by mom_geothermal::geothermal_init(), and mom::write_static_fields().
subroutine, public mom_diag_mediator::set_axes_info (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout) diag, logical, intent(in), optional set_vertical)
Definition at line 119 of file MOM_diag_mediator.F90.
References defineaxes(), mom_file_parser::log_version(), and mom_string_functions::lowercase().
Referenced by mom::initialize_mom().
subroutine, public mom_diag_mediator::set_diag_mediator_grid (type(ocean_grid_type), intent(inout) G, type(diag_ctrl), intent(inout) diag)
Definition at line 244 of file MOM_diag_mediator.F90.
Member Data Documentation
integer mom_diag_mediator::doc_unit = -1
Definition at line 115 of file MOM_diag_mediator.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_diag_mediator.F90