MOM6: ideal_age_example Module Reference
ideal_age_example Module Reference
Data Types
type ideal_age_tracer_cs
type p3d
Public Member Functions
logical function, public register_ideal_age_tracer (G, param_file, CS, diag, tr_Reg, restart_CS)
subroutine, public initialize_ideal_age_tracer (restart, day, G, h, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public ideal_age_tracer_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, CS)
integer function, public ideal_age_stock (h, stocks, G, CS, names, units, stock_index)
subroutine, public ideal_age_tracer_surface_state (state, h, G, CS)
subroutine, public ideal_age_example_end (CS)
Private Attributes
integer, parameter ntr_max = 3
Detailed Description
Definition at line 1 of file ideal_age_example.F90.
Member Function/Subroutine Documentation
subroutine, public ideal_age_example::ideal_age_example_end (type(ideal_age_tracer_cs), pointer CS)
Definition at line 589 of file ideal_age_example.F90.
Referenced by mom_tracer_flow_control::tracer_flow_control_end().
integer function, public ideal_age_example::ideal_age_stock (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(:), intent(out) stocks, type(ocean_grid_type), intent(in) G, type(ideal_age_tracer_cs), pointer CS, character(len=*), dimension(:), intent(out) names, character(len=*), dimension(:), intent(out) units, integer, intent(in), optional stock_index)
Definition at line 509 of file ideal_age_example.F90.
Referenced by mom_tracer_flow_control::call_tracer_stocks().
subroutine, public ideal_age_example::ideal_age_tracer_column_physics (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(ideal_age_tracer_cs), pointer CS)
Definition at line 407 of file ideal_age_example.F90.
References mom_tracer_registry::tracer_vertdiff().
Referenced by mom_tracer_flow_control::call_tracer_column_fns().
subroutine, public ideal_age_example::ideal_age_tracer_surface_state (type(surface), intent(inout) state, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(ideal_age_tracer_cs), pointer CS)
Definition at line 560 of file ideal_age_example.F90.
References coupler_util::set_coupler_values().
Referenced by mom_tracer_flow_control::call_tracer_surface_state().
subroutine, public ideal_age_example::initialize_ideal_age_tracer (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_obc_type), pointer OBC, type(ideal_age_tracer_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 280 of file ideal_age_example.F90.
References mom_tracer_registry::add_tracer_diagnostics(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), mom_diag_to_z::register_z_tracer(), and midas_vertmap::tracer_z_init().
Referenced by mom_tracer_flow_control::tracer_flow_control_init().
logical function, public ideal_age_example::register_ideal_age_tracer (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(ideal_age_tracer_cs), pointer CS, type(diag_ctrl), intent(in), target diag, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Definition at line 141 of file ideal_age_example.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_tracer_registry::register_tracer(), and mom_io::slasher().
Referenced by mom_tracer_flow_control::call_tracer_register().
Member Data Documentation
integer, parameter ideal_age_example::ntr_max = 3 private
Definition at line 86 of file ideal_age_example.F90.
The documentation for this module was generated from the following file:
src/tracer/ideal_age_example.F90