MOM6: mom_error_handler Module Reference
mom_error_handler Module Reference
Public Member Functions
logical function, public is_root_pe ()
subroutine, public mom_mesg (message, verb, all_print)
subroutine, public mom_error (level, message, all_print)
subroutine, public mom_set_verbosity (verb)
integer function, public mom_get_verbosity ()
logical function, public mom_verbose_enough (verb)
logical function, public calltree_showquery ()
subroutine, public calltree_enter (mesg, n)
subroutine, public calltree_leave (mesg)
subroutine, public calltree_waypoint (mesg)
Private Attributes
integer verbosity = 6
integer calltreeindentlevel = 0
Detailed Description
Definition at line 1 of file MOM_error_handler.F90.
Member Function/Subroutine Documentation
subroutine, public mom_error_handler::calltree_enter (character(len=*) mesg, integer, optional n)
Definition at line 122 of file MOM_error_handler.F90.
References is_root_pe().
Referenced by mom::calculate_surface_state(), mom_diabatic_driver::diabatic(), mom_grid_initialize::initialize_masks(), mom::initialize_mom(), mom_initialization::initialize_temp_salt_fit(), mom_initialization::initialize_temp_salt_from_file(), mom_initialization::initialize_temp_salt_from_profile(), mom_initialization::initialize_temp_salt_linear(), mom_initialization::initialize_thickness_from_file(), mom_initialization::initialize_thickness_uniform(), mom_initialization::initialize_topography_from_file(), mom_initialization::initialize_topography_named(), mom_initialization::initialize_velocity_from_file(), mom_initialization::initialize_velocity_zero(), mom_initialization::limit_topography(), mom_initialization::mom_initialize(), mom_initialization::mom_initialize_rotation(), mom_main(), mom_initialization::mom_temp_salt_initialize_from_z(), ocean_model_mod::ocean_model_init(), mom_initialization::reset_face_lengths_file(), mom_initialization::reset_face_lengths_list(), mom_initialization::set_coord_from_file(), mom_initialization::set_coord_from_gprime(), mom_initialization::set_coord_from_layer_density(), mom_initialization::set_coord_from_ts_profile(), mom_initialization::set_coord_from_ts_range(), mom_initialization::set_coord_from_ts_ref(), mom_initialization::set_coord_linear(), mom_set_diffusivity::set_diffusivity(), mom_surface_forcing::set_forcing(), mom_grid_initialize::set_grid_derived_metrics(), mom_grid_initialize::set_grid_metrics(), mom_grid_initialize::set_grid_metrics_cartesian(), mom_grid_initialize::set_grid_metrics_from_mosaic(), mom_grid_initialize::set_grid_metrics_mercator(), mom_grid_initialize::set_grid_metrics_spherical(), mom_initialization::set_rotation_beta_plane(), mom_initialization::set_rotation_planetary(), mom::step_mom(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), ocean_model_mod::update_ocean_model(), mom_surface_forcing::wind_forcing_1gyre(), mom_surface_forcing::wind_forcing_2gyre(), mom_surface_forcing::wind_forcing_by_data_override(), mom_surface_forcing::wind_forcing_from_file(), mom_surface_forcing::wind_forcing_gyres(), and mom_surface_forcing::wind_forcing_zero().
subroutine, public mom_error_handler::calltree_leave (character(len=*) mesg)
Definition at line 144 of file MOM_error_handler.F90.
References is_root_pe().
Referenced by mom::calculate_surface_state(), mom_diabatic_driver::diabatic(), mom_grid_initialize::initialize_masks(), mom::initialize_mom(), mom_initialization::initialize_temp_salt_fit(), mom_initialization::initialize_temp_salt_from_file(), mom_initialization::initialize_temp_salt_from_profile(), mom_initialization::initialize_temp_salt_linear(), mom_initialization::initialize_thickness_from_file(), mom_initialization::initialize_thickness_uniform(), mom_initialization::initialize_topography_from_file(), mom_initialization::initialize_topography_named(), mom_initialization::initialize_velocity_from_file(), mom_initialization::initialize_velocity_zero(), mom_initialization::limit_topography(), mom_initialization::mom_initialize(), mom_initialization::mom_initialize_rotation(), mom_main(), mom_initialization::mom_temp_salt_initialize_from_z(), ocean_model_mod::ocean_model_init(), mom_initialization::reset_face_lengths_file(), mom_initialization::reset_face_lengths_list(), mom_initialization::set_coord_from_file(), mom_initialization::set_coord_from_gprime(), mom_initialization::set_coord_from_layer_density(), mom_initialization::set_coord_from_ts_profile(), mom_initialization::set_coord_from_ts_range(), mom_initialization::set_coord_from_ts_ref(), mom_initialization::set_coord_linear(), mom_set_diffusivity::set_diffusivity(), mom_surface_forcing::set_forcing(), mom_grid_initialize::set_grid_derived_metrics(), mom_grid_initialize::set_grid_metrics(), mom_grid_initialize::set_grid_metrics_cartesian(), mom_grid_initialize::set_grid_metrics_from_mosaic(), mom_grid_initialize::set_grid_metrics_mercator(), mom_grid_initialize::set_grid_metrics_spherical(), mom_initialization::set_rotation_beta_plane(), mom_initialization::set_rotation_planetary(), mom::step_mom(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), ocean_model_mod::update_ocean_model(), mom_surface_forcing::wind_forcing_1gyre(), mom_surface_forcing::wind_forcing_2gyre(), mom_surface_forcing::wind_forcing_by_data_override(), mom_surface_forcing::wind_forcing_from_file(), mom_surface_forcing::wind_forcing_gyres(), and mom_surface_forcing::wind_forcing_zero().
logical function, public mom_error_handler::calltree_showquery ()
Definition at line 116 of file MOM_error_handler.F90.
Referenced by mom_diabatic_driver::diabatic(), mom_set_diffusivity::set_diffusivity(), mom::step_mom(), and mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
subroutine, public mom_error_handler::calltree_waypoint (character(len=*) mesg)
Definition at line 155 of file MOM_error_handler.F90.
References is_root_pe().
Referenced by mom_diabatic_driver::diabatic(), mom::initialize_mom(), mom_main(), mom_set_diffusivity::set_diffusivity(), mom::step_mom(), and mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
logical function, public mom_error_handler::is_root_pe ()
Definition at line 47 of file MOM_error_handler.F90.
Referenced by mom_initialization::adjustetatofitbathymetry(), mom_barotropic::btstep(), calltree_enter(), calltree_leave(), calltree_waypoint(), mom_checksums::chk_sum_msg1(), mom_checksums::chk_sum_msg3(), mom_checksums::chk_sum_msg5(), mom_checksums::chksum1d(), mom_checksums::chksum2d(), mom_checksums::chksum3d(), mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_q_2d(), mom_checksums::chksum_q_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), mom_checksums::chksum_v_3d(), mom_file_parser::clearparameterblock(), mom_file_parser::close_param_file(), mom_file_parser::closeparameterblock(), mom_sum_output::depth_list_setup(), mom_diag_mediator::diag_mediator_init(), mom_document::doc_closeblock(), mom_document::doc_function(), mom_document::doc_module(), mom_document::doc_openblock(), mom_document::doc_param_char(), mom_document::doc_param_int(), mom_document::doc_param_int_array(), mom_document::doc_param_logical(), mom_document::doc_param_logical_array(), mom_document::doc_param_none(), mom_document::doc_param_real(), mom_document::doc_param_real_array(), mom_document::doc_param_time(), mom_document::doc_subroutine(), mom_entrain_diffusive::entrainment_diffusive(), mom_obsolete_params::find_obsolete_params(), mom_file_parser::get_variable_line(), mom_checksums::hchksum2d(), mom_checksums::hchksum3d(), mom_initialization::initialize_thickness_from_file(), mom_legacy_barotropic::legacy_btstep(), mom_file_parser::log_param_char(), mom_file_parser::log_param_int(), mom_file_parser::log_param_int_array(), mom_file_parser::log_param_logical(), mom_file_parser::log_param_real(), mom_file_parser::log_param_real_array(), mom_file_parser::log_param_time(), mom_file_parser::log_version(), mom_error(), mom_main(), mom_mesg(), mom_checksum_packages::mom_state_stats(), mom_initialization::mom_temp_salt_initialize_from_z(), mystats(), ocean_model_mod::ocean_model_init(), mom_document::open_doc_file(), mom_file_parser::open_param_file(), mom_file_parser::openparameterblock(), mom_file_parser::popblocklevel(), mom_file_parser::populate_param_data(), mom_restart::query_initialized_0d_name(), mom_restart::query_initialized_1d_name(), mom_restart::query_initialized_2d_name(), mom_restart::query_initialized_3d_name(), mom_restart::query_initialized_name(), mom_diag_mediator::register_diag_field(), mom_diag_mediator::register_scalar_field(), mom_initialization::reset_face_lengths_file(), mom_initialization::reset_face_lengths_list(), mom_restart::restore_state(), mom_grid_initialize::set_grid_metrics_from_mosaic(), mom_sponge::set_up_sponge_field(), shelf_main(), mom_file_parser::simplifywhitespace(), substats(), mom_checksums::totaltands(), mom_tracer_hor_diff::tracer_hordiff(), mom_tracer_registry::tracer_registry_init(), mom::unittests(), mom_write_cputime::write_cputime(), mom_sum_output::write_depth_list(), and mom_sum_output::write_energy().
subroutine, public mom_error_handler::mom_error (integer, intent(in) level, character(len=*), intent(in) message, logical, intent(in), optional all_print)
Definition at line 71 of file MOM_error_handler.F90.
References is_root_pe().
Referenced by mom_sum_output::accumulate_net_input(), mom_tracer_registry::add_tracer_diagnostics(), mom_tracer_registry::add_tracer_obc_values(), mom_diabatic_driver::adiabatic_driver_init(), mom_initialization::adjustetatofitbathymetry(), adjustment_initialization::adjustment_initialize_temperature_salinity(), adjustment_initialization::adjustment_initialize_thickness(), mom_tracer_advect::advect_tracer(), mom_ale::ale_initregridding(), mom_variables::alloc_bt_cont_type(), mom_controlled_forcing::apply_ctrl_forcing(), mom_sponge::apply_sponge(), mom_diabatic_driver::applyboundaryfluxes(), mom_barotropic::barotropic_init(), mom_barotropic::bt_mass_source(), mom_barotropic::btcalc(), mom_barotropic::btstep(), mom_regridding::buildgridrho(), mom_regridding::buildgridsigma(), mom_regridding::buildgridzstar(), mom_bulk_mixed_layer::bulkmixedlayer(), mom_bulk_mixed_layer::bulkmixedlayer_init(), mom_surface_forcing::buoyancy_forcing_from_data_override(), mom_surface_forcing::buoyancy_forcing_from_files(), mom_surface_forcing::buoyancy_forcing_linear(), mom_lateral_mixing_coeffs::calc_resoln_function(), mom_lateral_mixing_coeffs::calc_slope_function_(), mom_diag_to_z::calc_zint_diags(), mom_eos::calculate_2_densities(), mom_eos::calculate_compress(), mom_eos::calculate_density_array(), mom_eos::calculate_density_derivs(), mom_eos::calculate_density_scalar(), mom_diagnostics::calculate_diagnostic_fields(), mom::calculate_surface_state(), mom_eos::calculate_tfreeze_array(), mom_eos::calculate_tfreeze_scalar(), mom_diag_to_z::calculate_z_diag_fields(), mom_diag_to_z::calculate_z_transport(), mom_tracer_flow_control::call_tracer_column_fns(), mom_tracer_flow_control::call_tracer_register(), mom_tracer_flow_control::call_tracer_set_forcing(), mom_tracer_flow_control::call_tracer_stocks(), mom_tracer_flow_control::call_tracer_surface_state(), mom_error_checking::check_redundant_s2d(), mom_error_checking::check_redundant_v2d(), mom_remapping::checkconsistantcoords(), mom_regridding::checkgridsmatch(), mom_checksums::chksum_error(), mom_file_parser::clearparameterblock(), mom_domains::clone_md_to_d2d(), mom_domains::clone_md_to_md(), mom_file_parser::close_param_file(), mom_file_parser::closeparameterblock(), mom_continuity::continuity(), mom_continuity::continuity_init(), mom_continuity_ppm::continuity_ppm(), mom_continuity_ppm::continuity_ppm_init(), ocean_model_mod::convert_state_to_ocean_type(), mom_initialization::convert_thickness(), regrid_consts::coordinatemode(), regrid_consts::coordinateunitsi(), mom_coriolisadv::coradcalc(), mom_coriolisadv::coriolisadv_init(), mom_internal_tides::correct_halo_rotation(), mom_io::create_file(), mom_diag_mediator::defineaxes(), mom_initialization::depress_surface(), mom_sum_output::depth_list_setup(), mom_entrain_diffusive::determine_dskb(), mom_entrain_diffusive::determine_ea_kb(), mom_diabatic_driver::diabatic(), mom_diabatic_driver::diabatic_driver_init(), mom_diag_mediator::diag_mediator_init(), mom_diffconvection::diffconvection_init(), mom_diabatic_driver::differential_diffuse_t_s(), dome2d_initialization::dome2d_initialize_temperature_salinity(), dome2d_initialization::dome2d_initialize_thickness(), dome_initialization::dome_initialize_sponges(), mom_remapping::dzfromh1h2(), mom_coms::efp_list_sum_across_pes(), mom_entrain_diffusive::entrain_diffusive_init(), mom_entrain_diffusive::entrainment_diffusive(), coupler_util::extract_coupler_values(), mom_forcing_type::extractfluxes1d(), mom_interface_heights::find_eta_3d(), mom_tidal_forcing::find_in_files(), mom_obsolete_params::find_obsolete_params(), mom_grid_initialize::find_root(), mom_document::find_unused_unit_number(), mom_diabatic_driver::find_uv_at_h(), mom_geothermal::geothermal(), mom_geothermal::geothermal_init(), mom_tracer_flow_control::get_chl_from_model(), mom_get_input::get_mom_input(), mom_regridding::get_polynomial_coordinate(), mom_grid::get_tr_flux_units(), mom_file_parser::get_variable_line(), mom_diag_to_z::get_z_depths(), mom_regridding::getcoordinateshortname(), mom_regridding::getcoordinateunits(), mom_spatial_means::global_i_mean(), mom_spatial_means::global_j_mean(), mom_hor_visc::hor_visc_init(), mom_hor_visc::horizontal_viscosity(), mom_ocmip2_cfc::init_tracer_cfc(), mom_ale::initialize_ale(), dome_tracer::initialize_dome_tracer(), mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2(), mom_ice_shelf::initialize_ice_shelf(), ideal_age_example::initialize_ideal_age_tracer(), mom_grid_initialize::initialize_masks(), mom::initialize_mom(), mom_ocmip2_cfc::initialize_ocmip2_cfc(), oil_tracer::initialize_oil_tracer(), mom_regridding::initialize_regridding(), mom_sponge::initialize_sponge(), mom_initialization::initialize_sponges_file(), mom_initialization::initialize_temp_salt_from_file(), mom_initialization::initialize_temp_salt_from_profile(), mom_initialization::initialize_thickness_from_file(), mom_initialization::initialize_thickness_search(), mom_initialization::initialize_thickness_uniform(), mom_initialization::initialize_topography_from_file(), mom_initialization::initialize_topography_named(), mom_initialization::initialize_velocity_from_file(), mom_eos::int_density_dz(), mom_eos::int_specific_vol_dp(), mom_int_tide_input::int_tide_input_init(), mom_remapping::integraterecononinterval(), mom_internal_tides::internal_tides_init(), mom_remapping::ispossumerrsignificant(), mom_kappa_shear::kappa_shear_init(), mom_kpp::kpp_init(), mom_legacy_barotropic::legacy_barotropic_init(), mom_legacy_barotropic::legacy_bt_mass_source(), mom_legacy_barotropic::legacy_btcalc(), mom_legacy_barotropic::legacy_btstep(), mom_legacy_barotropic::legacy_set_dtbt(), mom_meke::meke_alloc_register_restart(), mom_meke::meke_init(), mom_document::mesghasbeendocumented(), meso_surface_forcing::meso_buoyancy_forcing(), meso_surface_forcing::meso_surface_forcing_init(), meso_surface_forcing::meso_wind_forcing(), mom_bulk_mixed_layer::mixedlayer_detrain_1(), mom_bulk_mixed_layer::mixedlayer_detrain_2(), mom_mixed_layer_restrat::mixedlayer_restrat(), mom_mixed_layer_restrat::mixedlayer_restrat_init(), mom_diag_to_z::mom_diag_to_z_init(), mom_diagnostics::mom_diagnostics_init(), mom_domains::mom_domains_init(), mom_grid::mom_grid_init(), mom_initialization::mom_initialize(), mom_initialization::mom_initialize_rotation(), mom_initialization::mom_initialize_topography(), mom_main(), mom_set_verbosity(), mom_sum_output::mom_sum_output_init(), mom_initialization::mom_temp_salt_initialize_from_z(), mom_io::num_timelevels(), ocean_model_mod::ocean_model_data1d_get(), ocean_model_mod::ocean_model_data2d_get(), ocean_model_mod::ocean_model_flux_init(), ocean_model_mod::ocean_model_init(), mom_diag_mediator::ocean_register_diag(), mom_diag_to_z::ocean_register_diag_with_z(), mom_opacity::opacity_from_chl(), mom_opacity::opacity_init(), mom_open_boundary::open_boundary_init(), mom_document::open_doc_file(), mom_file_parser::open_param_file(), mom_file_parser::openparameterblock(), mom_file_parser::popblocklevel(), mom_file_parser::populate_param_data(), mom_diag_mediator::post_data_2d(), mom_diag_mediator::post_data_3d(), mom_internal_tides::ppm_reconstruction_x(), mom_continuity_ppm::ppm_reconstruction_x(), mom_internal_tides::ppm_reconstruction_y(), mom_continuity_ppm::ppm_reconstruction_y(), mom_pressureforce_afv::pressureforce_afv_bouss(), mom_pressureforce_afv::pressureforce_afv_init(), mom_pressureforce_afv::pressureforce_afv_nonbouss(), mom_pressureforce::pressureforce_init(), mom_pressureforce_mont::pressureforce_mont_bouss(), mom_pressureforce_mont::pressureforce_mont_init(), mom_pressureforce_mont::pressureforce_mont_nonbouss(), mom_internal_tides::propagate_int_tide(), mom_eos::query_compressible(), mom_restart::query_initialized_0d(), mom_restart::query_initialized_0d_name(), mom_restart::query_initialized_1d(), mom_restart::query_initialized_1d_name(), mom_restart::query_initialized_2d(), mom_restart::query_initialized_2d_name(), mom_restart::query_initialized_3d(), mom_restart::query_initialized_3d_name(), mom_restart::query_initialized_name(), mom_open_boundary::radiation_open_bdry_conds(), mom_io::read_axis_data(), mom_sum_output::read_depth_list(), mom_initialization::read_face_length_list(), mom_file_parser::read_param_char(), mom_file_parser::read_param_char_array(), mom_file_parser::read_param_int(), mom_file_parser::read_param_int_array(), mom_file_parser::read_param_logical(), mom_file_parser::read_param_real(), mom_file_parser::read_param_real_array(), mom_file_parser::read_param_time(), mom_tracer_z_init::read_z_edges(), mom_coms::real_to_efp(), mom_coms::real_to_ints(), mom_internal_tides::refract(), advection_test_tracer::register_advection_test_tracer(), mom_barotropic::register_barotropic_restarts(), mom_controlled_forcing::register_ctrl_forcing_restarts(), mom_diag_mediator::register_diag_field(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_internal_tides::register_int_tide_restarts(), mom_legacy_barotropic::register_legacy_barotropic_restarts(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), mom_restart::register_restart_field_ptr0d(), mom_restart::register_restart_field_ptr1d(), mom_restart::register_restart_field_ptr2d(), mom_restart::register_restart_field_ptr3d(), mom_dynamics_legacy_split::register_restarts_dyn_legacy_split(), mom_dynamics_split_rk2::register_restarts_dyn_split_rk2(), mom_dynamics_unsplit::register_restarts_dyn_unsplit(), mom_dynamics_unsplit_rk2::register_restarts_dyn_unsplit_rk2(), mom_diagnostics::register_time_deriv(), mom_tracer_registry::register_tracer(), mom_diag_to_z::register_z_diag(), mom_diag_to_z::register_z_tracer(), mom_diag_to_z::register_zint_diag(), mom_regridding::regridding_main(), mom_regularize_layers::regularize_layers(), mom_regularize_layers::regularize_layers_init(), mom_regularize_layers::regularize_surface(), mom_remapping::remapbydeltaz(), mom_remapping::remapping_core(), mom_io::reopen_file(), mom_coms::reproducing_sum_2d(), mom_coms::reproducing_sum_3d(), mom_initialization::reset_face_lengths_file(), mom_initialization::reset_face_lengths_list(), mom_initialization::reset_face_lengths_named(), mom_restart::restart_error(), mom_restart::restart_init(), mom_restart::restore_state(), mom_restart::save_restart(), mom_eos::select_eqn_of_state(), mom_set_diffusivity::set_bbl_diffusivity(), mom_initialization::set_coord_from_file(), mom_initialization::set_coord_from_ts_profile(), coupler_util::set_coupler_values(), mom_set_diffusivity::set_diffusivity(), mom_set_diffusivity::set_diffusivity_init(), mom_barotropic::set_dtbt(), mom_surface_forcing::set_forcing(), mom_grid_initialize::set_grid_derived_metrics(), mom_grid_initialize::set_grid_metrics(), mom_grid_initialize::set_grid_metrics_from_mosaic(), mom_grid_initialize::set_grid_metrics_spherical(), mom_int_tide_input::set_int_tide_input(), mom_opacity::set_opacity(), mom_initialization::set_rotation_beta_plane(), mom_barotropic::set_up_bt_obc(), mom_legacy_barotropic::set_up_bt_obc(), mom_sponge::set_up_sponge_field(), mom_sponge::set_up_sponge_ml_density(), mom_set_visc::set_visc_init(), mom_set_visc::set_viscous_bbl(), mom_set_visc::set_viscous_ml(), mom_regridding::setcoordinateresolution(), mom_remapping::setreconstructiontype(), mom_ice_shelf::shelf_calc_flux(), shelf_main(), mom_file_parser::simplifywhitespace(), mom_io::slasher(), regrid_solvers::solve_linear_system(), mom_meke::step_forward_meke(), mom_tracer_flow_control::store_stocks(), mom_surface_forcing::surface_forcing_init(), mom_obsolete_params::test_obsolete_char(), mom_obsolete_params::test_obsolete_int(), mom_obsolete_params::test_obsolete_logical(), mom_obsolete_params::test_obsolete_real(), mom_thickness_diffuse::thickness_diffuse(), mom_thickness_diffuse::thickness_diffuse_init(), mom_tidal_forcing::tidal_forcing_init(), mom_tracer_advect::tracer_advect_init(), mom_tracer_flow_control::tracer_flow_control_init(), mom_tracer_hor_diff::tracer_hor_diff_init(), mom_tracer_hor_diff::tracer_hordiff(), mom_tracer_registry::tracer_registry_init(), mom_tracer_z_init::tracer_z_init(), mom_regridding::uniformresolution(), mom::unittests(), ocean_model_mod::update_ocean_model(), mom_vert_friction::updatecfltruncationvalue(), user_surface_forcing::user_buoyancy_forcing(), user_change_diffusivity::user_change_diff(), user_change_diffusivity::user_change_diff_init(), user_initialization::user_init_mixed_layer_density(), user_initialization::user_init_temperature_salinity(), user_initialization::user_initialize_sponges(), user_initialization::user_initialize_thickness(), user_initialization::user_initialize_topography(), user_tracer_example::user_initialize_tracer(), user_initialization::user_initialize_velocity(), user_tracer_example::user_register_tracer_example(), user_initialization::user_set_coord(), user_initialization::user_set_open_bdry_conds(), user_initialization::user_set_rotation(), user_surface_forcing::user_surface_forcing_init(), user_surface_forcing::user_wind_forcing(), mom_lateral_mixing_coeffs::varmix_init(), mom_verticalgrid::verticalgridinit(), mom_vert_friction::vertvisc(), mom_vert_friction::vertvisc_coef(), mom_vert_friction::vertvisc_init(), mom_vert_friction::vertvisc_remnant(), mom_wave_speed::wave_speed(), mom_wave_speed::wave_speed_init(), mom_surface_forcing::wind_forcing_from_file(), mom_write_cputime::write_cputime(), mom_sum_output::write_depth_list(), mom_sum_output::write_energy(), mom_pointaccel::write_u_accel(), and mom_pointaccel::write_v_accel().
integer function, public mom_error_handler::mom_get_verbosity ()
Definition at line 105 of file MOM_error_handler.F90.
subroutine, public mom_error_handler::mom_mesg (character(len=*), intent(in) message, integer, intent(in), optional verb, logical, intent(in), optional all_print)
Definition at line 55 of file MOM_error_handler.F90.
References is_root_pe().
Referenced by adjustment_initialization::adjustment_initialize_thickness(), mom_barotropic::barotropic_init(), benchmark_init_topog_local(), benchmark_initialization::benchmark_initialize_thickness(), benchmark_initialization::benchmark_initialize_topography(), mom_barotropic::btstep(), circle_obcs_initialization::circle_obcs_initialize_thickness(), mom_file_parser::close_param_file(), mom_continuity::continuity_init(), mom_coriolisadv::coriolisadv_init(), dome2d_initialization::dome2d_initialize_thickness(), dome_initialization::dome_initialize_thickness(), dome_initialization::dome_initialize_topography(), external_gwave_initialization::external_gwave_initialize_thickness(), mom_initialization::initialize_topography_named(), mom_internal_tides::internal_tides_init(), mom_legacy_barotropic::legacy_barotropic_init(), mom_legacy_barotropic::legacy_btstep(), lock_exchange_initialization::lock_exchange_initialize_thickness(), mom_meke::meke_alloc_register_restart(), mom_meke::meke_init(), mom_domains::mom_domains_init(), mom_grid::mom_grid_init(), mom_initialization::mom_initialize(), mom_main(), mom_checksum_packages::mom_state_stats(), mystats(), mom_opacity::opacity_init(), mom_file_parser::open_param_file(), mom_tracer_z_init::read_z_edges(), mom_coms::reproducing_sum_2d(), mom_coms::reproducing_sum_3d(), seamount_initialization::seamount_initialize_thickness(), mom_eos::select_eqn_of_state(), mom_surface_forcing::set_forcing(), shelf_main(), and mom_lateral_mixing_coeffs::varmix_init().
subroutine, public mom_error_handler::mom_set_verbosity (integer, intent(in) verb)
Definition at line 94 of file MOM_error_handler.F90.
References mom_error().
Referenced by mom::initialize_mom(), and mom_main().
logical function, public mom_error_handler::mom_verbose_enough (integer, intent(in) verb)
Definition at line 110 of file MOM_error_handler.F90.
Member Data Documentation
integer mom_error_handler::calltreeindentlevel = 0 private
Definition at line 43 of file MOM_error_handler.F90.
integer mom_error_handler::verbosity = 6 private
Definition at line 33 of file MOM_error_handler.F90.
The documentation for this module was generated from the following file:
src/framework/MOM_error_handler.F90