MOM6: mom_legacy_barotropic Module Reference
mom_legacy_barotropic Module Reference
Data Types
type bt_obc_type
type legacy_barotropic_cs
type local_bt_cont_u_type
type local_bt_cont_v_type
type memory_size_type
Public Member Functions
subroutine, public legacy_btstep (use_fluxes, U_in, V_in, eta_in, dt, bc_accel_u, bc_accel_v, fluxes, pbce, eta_PF_in, U_Cor, V_Cor, accel_layer_u, accel_layer_v, eta_out, uhbtav, vhbtav, G, CS, visc_rem_u, visc_rem_v, etaav, uhbt_out, vhbt_out, OBC, BT_cont, eta_PF_start, taux_bot, tauy_bot, uh0, vh0, u_uh0, v_vh0)
subroutine, public legacy_set_dtbt (G, CS, eta, pbce, BT_cont, gtot_est, SSH_add)
subroutine, public legacy_btcalc (h, G, CS, h_u, h_v, may_use_default)
subroutine, public legacy_bt_mass_source (h, eta, fluxes, set_cor, dt_therm, dt_since_therm, G, CS)
subroutine, public legacy_barotropic_init (u, v, h, eta, Time, G, param_file, diag, CS, restart_CS, BT_cont, tides_CSp)
subroutine, public legacy_barotropic_end (CS)
subroutine, public register_legacy_barotropic_restarts (G, param_file, CS, restart_CS)
Private Member Functions
subroutine apply_velocity_obcs (OBC, ubt, vbt, uhbt, vhbt, ubt_trans, vbt_trans, eta, ubt_old, vbt_old, BT_OBC, G, MS, halo, dtbt, bebt, use_BT_cont, Datu, Datv, BTCL_u, BTCL_v, uhbt0, vhbt0)
subroutine apply_eta_obcs (OBC, eta, ubt, vbt, BT_OBC, G, MS, halo, dtbt)
subroutine set_up_bt_obc (OBC, eta, BT_OBC, G, MS, halo, use_BT_cont, Datu, Datv, BTCL_u, BTCL_v)
subroutine destroy_bt_obc (BT_OBC)
real function find_uhbt (u, BTC)
real function uhbt_to_ubt (uhbt, BTC, guess)
real function find_vhbt (v, BTC)
real function vhbt_to_vbt (vhbt, BTC, guess)
subroutine set_local_bt_cont_types (BT_cont, BTCL_u, BTCL_v, G, MS, BT_Domain, halo)
subroutine bt_cont_to_face_areas (BT_cont, Datu, Datv, G, MS, halo, maximize)
subroutine swap (a, b)
subroutine find_face_areas (Datu, Datv, G, CS, MS, rescale_faces, eta, halo, add_max)
Private Attributes
integer id_clock_sync =-1
integer id_clock_calc =-1
integer id_clock_calc_pre =-1
integer id_clock_calc_post =-1
integer id_clock_pass_step =-1
integer id_clock_pass_pre =-1
integer id_clock_pass_post =-1
integer, parameter harmonic = 1
integer, parameter arithmetic = 2
integer, parameter hybrid = 3
integer, parameter from_bt_cont = 4
integer, parameter hybrid_bt_cont = 5
character *(20), parameter hybrid_string = "HYBRID"
character *(20), parameter harmonic_string = "HARMONIC"
character *(20), parameter arithmetic_string = "ARITHMETIC"
character *(20), parameter bt_cont_string = "FROM_BT_CONT"
Detailed Description
Definition at line 1 of file MOM_legacy_barotropic.F90.
Member Function/Subroutine Documentation
subroutine mom_legacy_barotropic::apply_eta_obcs (type(ocean_obc_type), pointer OBC, real, dimension(sziw_(ms),szjw_(ms)), intent(inout) eta, real, dimension(szibw_(ms),szjw_(ms)), intent(in) ubt, real, dimension(sziw_(ms),szjbw_(ms)), intent(in) vbt, type(bt_obc_type), intent(in) BT_OBC, type(ocean_grid_type), intent(inout) G, type(memory_size_type), intent(in) MS, integer, intent(in) halo, real, intent(in) dtbt) private
Definition at line 2337 of file MOM_legacy_barotropic.F90.
subroutine mom_legacy_barotropic::apply_velocity_obcs (type(ocean_obc_type), pointer OBC, real, dimension(szibw_(ms),szjw_(ms)), intent(inout) ubt, real, dimension(sziw_(ms),szjbw_(ms)), intent(inout) vbt, real, dimension(szibw_(ms),szjw_(ms)), intent(inout) uhbt, real, dimension(sziw_(ms),szjbw_(ms)), intent(inout) vhbt, real, dimension(szibw_(ms),szjw_(ms)), intent(inout) ubt_trans, real, dimension(sziw_(ms),szjbw_(ms)), intent(inout) vbt_trans, real, dimension(sziw_(ms),szjw_(ms)), intent(in) eta, real, dimension(szibw_(ms),szjw_(ms)), intent(in) ubt_old, real, dimension(sziw_(ms),szjbw_(ms)), intent(in) vbt_old, type(bt_obc_type), intent(in) BT_OBC, type(ocean_grid_type), intent(inout) G, type(memory_size_type), intent(in) MS, integer, intent(in) halo, real, intent(in) dtbt, real, intent(in) bebt, logical, intent(in) use_BT_cont, real, dimension(szibw_(ms),szjw_(ms)), intent(in) Datu, real, dimension(sziw_(ms),szjbw_(ms)), intent(in) Datv, type(local_bt_cont_u_type), dimension(szibw_(ms),szjw_(ms)), intent(in) BTCL_u, type(local_bt_cont_v_type), dimension(sziw_(ms),szjbw_(ms)), intent(in) BTCL_v, real, dimension(szibw_(ms),szjw_(ms)), intent(in) uhbt0, real, dimension(sziw_(ms),szjbw_(ms)), intent(in) vhbt0) private
Definition at line 2150 of file MOM_legacy_barotropic.F90.
References mom_barotropic::find_uhbt(), and mom_barotropic::find_vhbt().
subroutine mom_legacy_barotropic::bt_cont_to_face_areas (type(bt_cont_type), intent(inout) BT_cont, real, dimension(ms%isdw-1:ms%iedw,ms%jsdw:ms%jedw), intent(out) Datu, real, dimension(ms%isdw:ms%iedw,ms%jsdw-1:ms%jedw), intent(out) Datv, type(ocean_grid_type), intent(in) G, type(memory_size_type), intent(in) MS, integer, intent(in), optional halo, logical, intent(in), optional maximize) private
Definition at line 3170 of file MOM_legacy_barotropic.F90.
subroutine mom_legacy_barotropic::destroy_bt_obc (type(bt_obc_type), intent(inout) BT_OBC) private
Definition at line 2564 of file MOM_legacy_barotropic.F90.
subroutine mom_legacy_barotropic::find_face_areas (real, dimension(ms%isdw-1:ms%iedw,ms%jsdw:ms%jedw), intent(out) Datu, real, dimension(ms%isdw:ms%iedw,ms%jsdw-1:ms%jedw), intent(out) Datv, type(ocean_grid_type), intent(in) G, type(legacy_barotropic_cs), pointer CS, type(memory_size_type), intent(in) MS, logical, intent(in), optional rescale_faces, real, dimension(ms%isdw:ms%iedw,ms%jsdw:ms%jedw), intent(in), optional eta, integer, intent(in), optional halo, real, intent(in), optional add_max) private
Definition at line 3211 of file MOM_legacy_barotropic.F90.
real function mom_legacy_barotropic::find_uhbt (real, intent(in) u, type(local_bt_cont_u_type), intent(in) BTC) private
Definition at line 2827 of file MOM_legacy_barotropic.F90.
real function mom_legacy_barotropic::find_vhbt (real, intent(in) v, type(local_bt_cont_v_type), intent(in) BTC) private
Definition at line 2944 of file MOM_legacy_barotropic.F90.
subroutine, public mom_legacy_barotropic::legacy_barotropic_end (type(legacy_barotropic_cs), pointer CS)
Definition at line 3964 of file MOM_legacy_barotropic.F90.
subroutine, public mom_legacy_barotropic::legacy_barotropic_init (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_), intent(in) eta, type(time_type), intent(in), target Time, type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(legacy_barotropic_cs), pointer CS, type(mom_restart_cs), pointer restart_CS, type(bt_cont_type), optional, pointer BT_cont, type(tidal_forcing_cs), optional, pointer tides_CSp)
Definition at line 3418 of file MOM_legacy_barotropic.F90.
References mom_variables::alloc_bt_cont_type(), mom_barotropic::find_face_areas(), legacy_btcalc(), legacy_set_dtbt(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_diag_mediator::register_diag_field().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split().
subroutine, public mom_legacy_barotropic::legacy_bt_mass_source (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_), intent(in) eta, type(forcing), intent(in) fluxes, logical, intent(in) set_cor, real, intent(in) dt_therm, real, intent(in) dt_since_therm, type(ocean_grid_type), intent(in) G, type(legacy_barotropic_cs), pointer CS)
Definition at line 3316 of file MOM_legacy_barotropic.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split().
subroutine, public mom_legacy_barotropic::legacy_btcalc (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(inout) G, type(legacy_barotropic_cs), pointer CS, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional h_u, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional h_v, logical, intent(in), optional may_use_default)
Definition at line 2585 of file MOM_legacy_barotropic.F90.
References mom_error_handler::mom_error().
Referenced by legacy_barotropic_init(), and mom_dynamics_legacy_split::step_mom_dyn_legacy_split().
subroutine, public mom_legacy_barotropic::legacy_btstep (logical, intent(in) use_fluxes, real, dimension(nimemb_,njmem_,nkmem_), intent(in) U_in, real, dimension(nimem_,njmemb_,nkmem_), intent(in) V_in, real, dimension(nimem_,njmem_), intent(in) eta_in, real, intent(in) dt, real, dimension(nimemb_,njmem_,nkmem_), intent(in) bc_accel_u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) bc_accel_v, type(forcing), intent(in) fluxes, real, dimension(nimem_,njmem_,nkmem_), intent(in) pbce, real, dimension(nimem_,njmem_), intent(in) eta_PF_in, real, dimension(nimemb_,njmem_,nkmem_), intent(in) U_Cor, real, dimension(nimem_,njmemb_,nkmem_), intent(in) V_Cor, real, dimension(nimemb_,njmem_,nkmem_), intent(out) accel_layer_u, real, dimension(nimem_,njmemb_,nkmem_), intent(out) accel_layer_v, real, dimension(nimem_,njmem_), intent(inout) eta_out, real, dimension(nimemb_,njmem_), intent(out) uhbtav, real, dimension(nimem_,njmemb_), intent(out) vhbtav, type(ocean_grid_type), intent(inout) G, type(legacy_barotropic_cs), pointer CS, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional visc_rem_u, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional visc_rem_v, real, dimension(nimem_,njmem_), intent(out), optional etaav, real, dimension(nimemb_,njmem_), intent(out), optional uhbt_out, real, dimension(nimem_,njmemb_), intent(out), optional vhbt_out, type(ocean_obc_type), optional, pointer OBC, type(bt_cont_type), optional, pointer BT_cont, real, dimension(:,:), optional, pointer eta_PF_start, real, dimension(:,:), optional, pointer taux_bot, real, dimension(:,:), optional, pointer tauy_bot, real, dimension(:,:,:), optional, pointer uh0, real, dimension(:,:,:), optional, pointer vh0, real, dimension(:,:,:), optional, pointer u_uh0, real, dimension(:,:,:), optional, pointer v_vh0)
Definition at line 390 of file MOM_legacy_barotropic.F90.
References mom_barotropic::apply_eta_obcs(), mom_barotropic::apply_velocity_obcs(), mom_barotropic::bt_cont_to_face_areas(), mom_barotropic::destroy_bt_obc(), mom_diag_mediator::enable_averaging(), mom_barotropic::find_face_areas(), mom_barotropic::find_uhbt(), mom_barotropic::find_vhbt(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), mom_diag_mediator::query_averaging_enabled(), mom_barotropic::set_local_bt_cont_types(), mom_barotropic::set_up_bt_obc(), mom_barotropic::swap(), mom_tidal_forcing::tidal_forcing_sensitivity(), mom_barotropic::uhbt_to_ubt(), and mom_barotropic::vhbt_to_vbt().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split().
subroutine, public mom_legacy_barotropic::legacy_set_dtbt (type(ocean_grid_type), intent(inout) G, type(legacy_barotropic_cs), pointer CS, real, dimension(nimem_,njmem_), intent(in), optional eta, real, dimension(nimem_,njmem_,nkmem_), intent(in), optional pbce, type(bt_cont_type), optional, pointer BT_cont, real, intent(in), optional gtot_est, real, intent(in), optional SSH_add)
Definition at line 2034 of file MOM_legacy_barotropic.F90.
References mom_barotropic::bt_cont_to_face_areas(), mom_barotropic::find_face_areas(), mom_error_handler::mom_error(), and mom_tidal_forcing::tidal_forcing_sensitivity().
Referenced by legacy_barotropic_init(), and mom_dynamics_legacy_split::step_mom_dyn_legacy_split().
subroutine, public mom_legacy_barotropic::register_legacy_barotropic_restarts (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(legacy_barotropic_cs), pointer CS, type(mom_restart_cs), pointer restart_CS)
Definition at line 3979 of file MOM_legacy_barotropic.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::register_restarts_dyn_legacy_split().
subroutine mom_legacy_barotropic::set_local_bt_cont_types (type(bt_cont_type), intent(inout) BT_cont, type(local_bt_cont_u_type), dimension(szibw_(ms),szjw_(ms)), intent(out) BTCL_u, type(local_bt_cont_v_type), dimension(sziw_(ms),szjbw_(ms)), intent(out) BTCL_v, type(ocean_grid_type), intent(inout) G, type(memory_size_type), intent(in) MS, type(mom_domain_type), intent(inout) BT_Domain, integer, intent(in), optional halo) private
Definition at line 3062 of file MOM_legacy_barotropic.F90.
References mom_barotropic::swap().
subroutine mom_legacy_barotropic::set_up_bt_obc (type(ocean_obc_type), pointer OBC, real, dimension(sziw_(ms),szjw_(ms)), intent(in) eta, type(bt_obc_type), intent(inout) BT_OBC, type(ocean_grid_type), intent(inout) G, type(memory_size_type), intent(in) MS, integer, intent(in) halo, logical, intent(in) use_BT_cont, real, dimension(szibw_(ms),szjw_(ms)), intent(in) Datu, real, dimension(sziw_(ms),szjbw_(ms)), intent(in) Datv, type(local_bt_cont_u_type), dimension(szibw_(ms),szjw_(ms)), intent(in) BTCL_u, type(local_bt_cont_v_type), dimension(sziw_(ms),szjbw_(ms)), intent(in) BTCL_v) private
Definition at line 2421 of file MOM_legacy_barotropic.F90.
References mom_error_handler::mom_error(), mom_barotropic::uhbt_to_ubt(), and mom_barotropic::vhbt_to_vbt().
subroutine mom_legacy_barotropic::swap (real, intent(inout) a, real, intent(inout) b) private
Definition at line 3205 of file MOM_legacy_barotropic.F90.
real function mom_legacy_barotropic::uhbt_to_ubt (real, intent(in) uhbt, type(local_bt_cont_u_type), intent(in) BTC, real, intent(in), optional guess) private
Definition at line 2846 of file MOM_legacy_barotropic.F90.
real function mom_legacy_barotropic::vhbt_to_vbt (real, intent(in) vhbt, type(local_bt_cont_v_type), intent(in) BTC, real, intent(in), optional guess) private
Definition at line 2963 of file MOM_legacy_barotropic.F90.
Member Data Documentation
integer, parameter mom_legacy_barotropic::arithmetic = 2 private
Definition at line 379 of file MOM_legacy_barotropic.F90.
character*(20), parameter mom_legacy_barotropic::arithmetic_string = "ARITHMETIC" private
Definition at line 385 of file MOM_legacy_barotropic.F90.
character*(20), parameter mom_legacy_barotropic::bt_cont_string = "FROM_BT_CONT" private
Definition at line 386 of file MOM_legacy_barotropic.F90.
integer, parameter mom_legacy_barotropic::from_bt_cont = 4 private
Definition at line 381 of file MOM_legacy_barotropic.F90.
integer, parameter mom_legacy_barotropic::harmonic = 1 private
Definition at line 378 of file MOM_legacy_barotropic.F90.
character*(20), parameter mom_legacy_barotropic::harmonic_string = "HARMONIC" private
Definition at line 384 of file MOM_legacy_barotropic.F90.
integer, parameter mom_legacy_barotropic::hybrid = 3 private
Definition at line 380 of file MOM_legacy_barotropic.F90.
integer, parameter mom_legacy_barotropic::hybrid_bt_cont = 5 private
Definition at line 382 of file MOM_legacy_barotropic.F90.
character*(20), parameter mom_legacy_barotropic::hybrid_string = "HYBRID" private
Definition at line 383 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_calc =-1 private
Definition at line 373 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_calc_post =-1 private
Definition at line 374 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_calc_pre =-1 private
Definition at line 374 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_pass_post =-1 private
Definition at line 375 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_pass_pre =-1 private
Definition at line 375 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_pass_step =-1 private
Definition at line 375 of file MOM_legacy_barotropic.F90.
integer mom_legacy_barotropic::id_clock_sync =-1 private
Definition at line 373 of file MOM_legacy_barotropic.F90.
The documentation for this module was generated from the following file:
src/core/MOM_legacy_barotropic.F90