MOM6: mom_wave_speed Module Reference
mom_wave_speed Module Reference
Data Types
type wave_speed_cs
Public Member Functions
subroutine, public wave_speed (h, tv, G, cg1, CS, full_halos)
subroutine, public wave_speed_init (Time, G, param_file, diag, CS)
Detailed Description
Definition at line 1 of file MOM_wave_speed.F90.
Member Function/Subroutine Documentation
subroutine, public mom_wave_speed::wave_speed (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_), intent(out) cg1, type(wave_speed_cs), optional, pointer CS, logical, intent(in), optional full_halos)
Definition at line 66 of file MOM_wave_speed.F90.
References mom_eos::calculate_density_derivs(), and mom_error_handler::mom_error().
Referenced by mom_lateral_mixing_coeffs::calc_resoln_function(), mom_diagnostics::calculate_diagnostic_fields(), and mom_diabatic_driver::diabatic().
subroutine, public mom_wave_speed::wave_speed_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(wave_speed_cs), pointer CS)
Definition at line 380 of file MOM_wave_speed.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_diagnostics::mom_diagnostics_init(), and mom_lateral_mixing_coeffs::varmix_init().
The documentation for this module was generated from the following file:
src/diagnostics/MOM_wave_speed.F90