MOM6: sloshing_initialization Module Reference
sloshing_initialization Module Reference
Public Member Functions
subroutine, public sloshing_initialize_topography (D, G, param_file, max_depth)
subroutine, public sloshing_initialize_thickness (h, G, param_file)
subroutine, public sloshing_initialize_temperature_salinity (T, S, h, G, param_file, eqn_of_state)
Private Attributes
character(len=40) mod = "sloshing_initialization"
Detailed Description
Definition at line 1 of file sloshing_initialization.F90.
Member Function/Subroutine Documentation
subroutine, public sloshing_initialization::sloshing_initialize_temperature_salinity (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Definition at line 203 of file sloshing_initialization.F90.
Referenced by mom_initialization::mom_initialize().
subroutine, public sloshing_initialization::sloshing_initialize_thickness (real, dimension(nimem_,njmem_, nkmem_), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Definition at line 88 of file sloshing_initialization.F90.
Referenced by mom_initialization::mom_initialize().
subroutine, public sloshing_initialization::sloshing_initialize_topography (real, dimension(nimem_,njmem_), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Definition at line 64 of file sloshing_initialization.F90.
Referenced by mom_initialization::mom_initialize_topography().
Member Data Documentation
character(len=40) sloshing_initialization::mod = "sloshing_initialization" private
Definition at line 54 of file sloshing_initialization.F90.
The documentation for this module was generated from the following file:
src/user/sloshing_initialization.F90