MOM6: regrid_edge_values Module Reference
regrid_edge_values Module Reference
Data Types
type edgevaluearrays
Public Member Functions
subroutine, public bound_edge_values (N, h, u, edge_values)
subroutine, public average_discontinuous_edge_values (N, edge_values)
subroutine, public check_discontinuous_edge_values (N, u, edge_values)
subroutine, public edge_values_explicit_h2 (N, h, u, edge_values)
subroutine, public edge_values_explicit_h4 (N, h, u, edge_values)
subroutine, public edge_values_implicit_h4 (N, h, u, work, edge_values)
subroutine, public edge_values_implicit_h6 (N, h, u, work, edge_values)
subroutine, public tridiagedgeworkallocate (N, work)
subroutine, public tridiagedgeworkdeallocate (work)
Detailed Description
Definition at line 1 of file regrid_edge_values.F90.
Member Function/Subroutine Documentation
subroutine, public regrid_edge_values::average_discontinuous_edge_values (integer, intent(in) N, real, dimension(:,:), intent(inout) edge_values)
Definition at line 147 of file regrid_edge_values.F90.
Referenced by p1m_functions::p1m_interpolation(), and p3m_functions::p3m_limiter().
subroutine, public regrid_edge_values::bound_edge_values (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, real, dimension(:,:), intent(inout) edge_values)
Definition at line 48 of file regrid_edge_values.F90.
Referenced by p1m_functions::p1m_interpolation(), p3m_functions::p3m_limiter(), ppm_functions::ppm_limiter_standard(), and pqm_functions::pqm_limiter().
subroutine, public regrid_edge_values::check_discontinuous_edge_values (integer, intent(in) N, real, dimension(:), intent(in) u, real, dimension(:,:), intent(inout) edge_values)
Definition at line 186 of file regrid_edge_values.F90.
Referenced by ppm_functions::ppm_limiter_standard(), and pqm_functions::pqm_limiter().
subroutine, public regrid_edge_values::edge_values_explicit_h2 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, real, dimension(:,:), intent(inout) edge_values)
Definition at line 234 of file regrid_edge_values.F90.
Referenced by mom_regridding::regridding_iteration().
subroutine, public regrid_edge_values::edge_values_explicit_h4 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, real, dimension(:,:), intent(inout) edge_values)
Definition at line 287 of file regrid_edge_values.F90.
References polynomial_functions::evaluation_polynomial(), and regrid_solvers::solve_linear_system().
Referenced by mom_regridding::regridding_iteration(), mom_remapping::remapping_core(), and mom_remapping::remappingunittests().
subroutine, public regrid_edge_values::edge_values_implicit_h4 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(edgevaluearrays), intent(inout) work, real, dimension(:,:), intent(inout) edge_values)
Definition at line 416 of file regrid_edge_values.F90.
References polynomial_functions::evaluation_polynomial(), regrid_solvers::solve_linear_system(), and regrid_solvers::solve_tridiagonal_system().
Referenced by mom_ale::pressure_gradient_ppm(), mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine, public regrid_edge_values::edge_values_implicit_h6 (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(edgevaluearrays), intent(inout) work, real, dimension(:,:), intent(inout) edge_values)
Definition at line 547 of file regrid_edge_values.F90.
References polynomial_functions::evaluation_polynomial(), regrid_solvers::solve_linear_system(), and regrid_solvers::solve_tridiagonal_system().
Referenced by mom_regridding::regridding_iteration(), and mom_remapping::remapping_core().
subroutine, public regrid_edge_values::tridiagedgeworkallocate (integer, intent(in) N, type(edgevaluearrays), intent(inout) work)
Definition at line 1006 of file regrid_edge_values.F90.
Referenced by mom_ale::ale_memory_allocation(), mom_regridding::allocate_regridding(), and mom_remapping::allocate_remapping().
subroutine, public regrid_edge_values::tridiagedgeworkdeallocate (type(edgevaluearrays), intent(inout) work)
Definition at line 1028 of file regrid_edge_values.F90.
Referenced by mom_ale::ale_memory_deallocation(), mom_remapping::end_remapping(), and mom_regridding::regridding_memory_deallocation().
The documentation for this module was generated from the following file:
src/ALE/regrid_edge_values.F90