MOM6: mom_tracer_flow_control Module Reference
mom_tracer_flow_control Module Reference
Data Types
type tracer_flow_control_cs
Public Member Functions
subroutine, public call_tracer_register (G, param_file, CS, diag, tr_Reg, restart_CS)
subroutine, public tracer_flow_control_init (restart, day, G, h, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public get_chl_from_model (Chl_array, G, CS)
subroutine, public call_tracer_set_forcing (state, fluxes, day_start, day_interval, G, CS)
subroutine, public call_tracer_column_fns (h_old, h_new, ea, eb, fluxes, dt, G, tv, optics, CS)
subroutine, public call_tracer_stocks (h, stock_values, G, CS, stock_names, stock_units, num_stocks, stock_index, got_min_max, global_min, global_max, xgmin, ygmin, zgmin, xgmax, ygmax, zgmax)
subroutine, public call_tracer_surface_state (state, h, G, CS)
Private Member Functions
subroutine store_stocks (pkg_name, ns, names, units, values, index, stock_values, set_pkg_name, max_ns, ns_tot, stock_names, stock_units)
subroutine tracer_flow_control_end (CS)
Detailed Description
Definition at line 1 of file MOM_tracer_flow_control.F90.
Member Function/Subroutine Documentation
subroutine, public mom_tracer_flow_control::call_tracer_column_fns (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(thermo_var_ptrs), intent(in) tv, type(optics_type), pointer optics, type(tracer_flow_control_cs), pointer CS)
Definition at line 302 of file MOM_tracer_flow_control.F90.
References advection_test_tracer::advection_test_tracer_column_physics(), dome_tracer::dome_tracer_column_physics(), ideal_age_example::ideal_age_tracer_column_physics(), mom_error_handler::mom_error(), mom_ocmip2_cfc::ocmip2_cfc_column_physics(), oil_tracer::oil_tracer_column_physics(), and user_tracer_example::tracer_column_physics().
Referenced by mom_diabatic_driver::adiabatic(), and mom_diabatic_driver::diabatic().
subroutine, public mom_tracer_flow_control::call_tracer_register (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_flow_control_cs), pointer CS, type(diag_ctrl), intent(in), target diag, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Definition at line 102 of file MOM_tracer_flow_control.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), advection_test_tracer::register_advection_test_tracer(), dome_tracer::register_dome_tracer(), ideal_age_example::register_ideal_age_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), and user_tracer_example::user_register_tracer_example().
Referenced by mom::initialize_mom().
subroutine, public mom_tracer_flow_control::call_tracer_set_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day_start, type(time_type), intent(in) day_interval, type(ocean_grid_type), intent(in) G, type(tracer_flow_control_cs), pointer CS)
Definition at line 273 of file MOM_tracer_flow_control.F90.
References mom_error_handler::mom_error().
Referenced by mom_surface_forcing::set_forcing().
subroutine, public mom_tracer_flow_control::call_tracer_stocks (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(:), intent(out) stock_values, type(ocean_grid_type), intent(in) G, type(tracer_flow_control_cs), pointer CS, character(len=*), dimension(:), intent(out), optional stock_names, character(len=*), dimension(:), intent(out), optional stock_units, integer, intent(out), optional num_stocks, integer, intent(in), optional stock_index, logical, dimension(:), intent(inout), optional got_min_max, real, dimension(:), intent(out), optional global_min, real, dimension(:), intent(out), optional global_max, real, dimension(:), intent(out), optional xgmin, real, dimension(:), intent(out), optional ygmin, real, dimension(:), intent(out), optional zgmin, real, dimension(:), intent(out), optional xgmax, real, dimension(:), intent(out), optional ygmax, real, dimension(:), intent(out), optional zgmax)
Definition at line 362 of file MOM_tracer_flow_control.F90.
References ideal_age_example::ideal_age_stock(), mom_error_handler::mom_error(), mom_ocmip2_cfc::ocmip2_cfc_stock(), oil_tracer::oil_stock(), store_stocks(), and user_tracer_example::user_tracer_stock().
Referenced by mom_sum_output::write_energy().
subroutine, public mom_tracer_flow_control::call_tracer_surface_state (type(surface), intent(inout) state, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(tracer_flow_control_cs), pointer CS)
Definition at line 501 of file MOM_tracer_flow_control.F90.
References advection_test_tracer::advection_test_tracer_surface_state(), dome_tracer::dome_tracer_surface_state(), ideal_age_example::ideal_age_tracer_surface_state(), mom_error_handler::mom_error(), mom_ocmip2_cfc::ocmip2_cfc_surface_state(), oil_tracer::oil_tracer_surface_state(), and user_tracer_example::user_tracer_surface_state().
Referenced by mom::calculate_surface_state().
subroutine, public mom_tracer_flow_control::get_chl_from_model (real, dimension(nimem_,njmem_,nkmem_), intent(out) Chl_array, type(ocean_grid_type), intent(in) G, type(tracer_flow_control_cs), pointer CS)
Definition at line 246 of file MOM_tracer_flow_control.F90.
References mom_error_handler::mom_error().
Referenced by mom_opacity::set_opacity().
subroutine mom_tracer_flow_control::store_stocks (character(len=*), intent(in) pkg_name, integer, intent(in) ns, character(len=*), dimension(:), intent(in) names, character(len=*), dimension(:), intent(in) units, real, dimension(:), intent(in) values, integer, intent(in) index, real, dimension(:), intent(inout) stock_values, character(len=*), intent(inout) set_pkg_name, integer, intent(in) max_ns, integer, intent(inout) ns_tot, character(len=*), dimension(:), intent(inout), optional stock_names, character(len=*), dimension(:), intent(inout), optional stock_units) private
Definition at line 453 of file MOM_tracer_flow_control.F90.
References mom_error_handler::mom_error().
Referenced by call_tracer_stocks().
subroutine mom_tracer_flow_control::tracer_flow_control_end (type(tracer_flow_control_cs), pointer CS) private
Definition at line 539 of file MOM_tracer_flow_control.F90.
References advection_test_tracer::advection_test_tracer_end(), dome_tracer::dome_tracer_end(), ideal_age_example::ideal_age_example_end(), mom_ocmip2_cfc::ocmip2_cfc_end(), oil_tracer::oil_tracer_end(), and user_tracer_example::user_tracer_example_end().
subroutine, public mom_tracer_flow_control::tracer_flow_control_init (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_obc_type), pointer OBC, type(tracer_flow_control_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 190 of file MOM_tracer_flow_control.F90.
References advection_test_tracer::initialize_advection_test_tracer(), dome_tracer::initialize_dome_tracer(), ideal_age_example::initialize_ideal_age_tracer(), mom_ocmip2_cfc::initialize_ocmip2_cfc(), oil_tracer::initialize_oil_tracer(), mom_error_handler::mom_error(), and user_tracer_example::user_initialize_tracer().
Referenced by mom::initialize_mom().
The documentation for this module was generated from the following file:
src/tracer/MOM_tracer_flow_control.F90