MOM6: user_surface_forcing Module Reference
user_surface_forcing Module Reference
Data Types
type user_surface_forcing_cs
Public Member Functions
subroutine, public user_wind_forcing (state, fluxes, day, G, CS)
subroutine, public user_buoyancy_forcing (state, fluxes, day, dt, G, CS)
subroutine, public user_surface_forcing_init (Time, G, param_file, diag, CS)
subroutine, public user_wind_forcing (state, fluxes, day, G, CS)
subroutine, public user_buoyancy_forcing (state, fluxes, day, dt, G, CS)
subroutine, public user_surface_forcing_init (Time, G, param_file, diag, CS)
Private Member Functions
subroutine alloc_if_needed (ptr, isd, ied, jsd, jed)
subroutine alloc_if_needed (ptr, isd, ied, jsd, jed)
Detailed Description
Definition at line 1 of file user_surface_forcing.F90.
Member Function/Subroutine Documentation
subroutine user_surface_forcing::alloc_if_needed (real, dimension(:,:), pointer ptr, integer isd, integer ied, integer jsd, integer jed) private
Definition at line 308 of file user_surface_forcing.F90.
Referenced by meso_surface_forcing::meso_buoyancy_forcing(), meso_surface_forcing::meso_wind_forcing(), user_buoyancy_forcing(), and user_wind_forcing().
subroutine user_surface_forcing::alloc_if_needed (real, dimension(:,:), pointer ptr, integer isd, integer ied, integer jsd, integer jed) private
Definition at line 308 of file user_surface_forcing.F90.
subroutine, public user_surface_forcing::user_buoyancy_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(user_surface_forcing_cs), pointer CS)
Definition at line 167 of file user_surface_forcing.F90.
References alloc_if_needed(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::set_forcing().
subroutine, public user_surface_forcing::user_buoyancy_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(user_surface_forcing_cs), pointer CS)
Definition at line 167 of file user_surface_forcing.F90.
References alloc_if_needed(), and mom_error_handler::mom_error().
subroutine, public user_surface_forcing::user_surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(user_surface_forcing_cs), pointer CS)
Definition at line 320 of file user_surface_forcing.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::surface_forcing_init().
subroutine, public user_surface_forcing::user_surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in), target diag, type(user_surface_forcing_cs), pointer CS)
Definition at line 320 of file user_surface_forcing.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_error().
subroutine, public user_surface_forcing::user_wind_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(user_surface_forcing_cs), pointer CS)
Definition at line 104 of file user_surface_forcing.F90.
References alloc_if_needed(), and mom_error_handler::mom_error().
Referenced by mom_surface_forcing::set_forcing().
subroutine, public user_surface_forcing::user_wind_forcing (type(surface), intent(inout) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(user_surface_forcing_cs), pointer CS)
Definition at line 104 of file user_surface_forcing.F90.
References alloc_if_needed(), and mom_error_handler::mom_error().
The documentation for this module was generated from the following file:
config_src/ice_solo_driver/user_surface_forcing.F90