MOM6: mom_kpp Module Reference
mom_kpp Module Reference
This module provides the K-profile parameterization (aka KPP) of Large et al., 1994 (ftp://128.171.154.9/pub/rlukas/Thibault/Large%20etal%20RevGeo%201994.pdf). KPP is implemented via the CVMix package (https://code.google.com/p/cvmix) which this module invokes.
Data Types
type kpp_cs
Control structure for containing KPP parameters/data.
Public Member Functions
logical function, public kpp_init (paramFile, G, diag, Time, CS, passive)
Initialize the CVmix KPP module and set up diagnostics Returns True if KPP is to be used, False otherwise.
subroutine, public kpp_calculate (CS, G, h, Temp, Salt, u, v, EOS, uStar, buoyFlux, Kt, Ks, Kv, nonLocalTransHeat, nonLocalTransScalar)
Calculates diffusivity and non-local transport according to KPP parameterization.
subroutine, public kpp_applynonlocaltransport (CS, G, h, nonLocalTrans, surfFlux, dt, scalar, isHeat, isSalt)
Applies the KPP non-local transport of surface fluxes; only available for tracers.
subroutine, public kpp_end (CS)
Clear pointers, dealocate memory.
Public Attributes
logical, parameter verbose = .False.
Private Attributes
integer, parameter, private nlt_shape_cvmix = 0
Use the CVmix profile.
integer, parameter, private nlt_shape_linear = 1
Linear, Cs.G(s) = 1-s.
integer, parameter, private nlt_shape_parabolic = 2
Parabolic, Cs.G(s) = (1-s)^2.
integer, parameter, private nlt_shape_cubic = 3
Cubic, G(s) =.
integer, parameter, private nlt_shape_cubic_lmd = 4
Original shape, Cs.G(s) = 27/4.s.(1-s)^2.
Detailed Description
This module provides the K-profile parameterization (aka KPP) of Large et al., 1994 (ftp://128.171.154.9/pub/rlukas/Thibault/Large%20etal%20RevGeo%201994.pdf). KPP is implemented via the CVMix package (https://code.google.com/p/cvmix) which this module invokes.
Definition at line 5 of file MOM_KPP.F90.
Member Function/Subroutine Documentation
subroutine, public mom_kpp::kpp_applynonlocaltransport (type(kpp_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nk_interface_), intent(in) nonLocalTrans, real, dimension(nimem_,njmem_), intent(in) surfFlux, real, intent(in) dt, real, dimension(nimem_,njmem_,nkmem_), intent(inout) scalar, logical, intent(in), optional isHeat, logical, intent(in), optional isSalt)
Applies the KPP non-local transport of surface fluxes; only available for tracers.
Parameters
[in] cs Control structure
[in] g Ocean grid
[in] h Layer/level thicknesses (units of H)
[in] nonlocaltrans Non-local transport (non-dimensional)
[in] surfflux Surface source of scalar (m/s * scalar)
[in] dt Time-step (s)
[in,out] scalar Scalar or temperature (scalar units)
[in] isheat Indicates scalar is heat for diagnostics
[in] issalt Indicates scalar is salt for diagnostics
Definition at line 792 of file MOM_KPP.F90.
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_kpp::kpp_calculate (type(kpp_cs), pointer CS, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(in) Temp, real, dimension(nimem_,njmem_,nkmem_), intent(in) Salt, real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, type(eos_type), pointer EOS, real, dimension(nimem_,njmem_), intent(in) uStar, real, dimension(nimem_,njmem_,nk_interface_), intent(in) buoyFlux, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) Kt, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) Ks, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) Kv, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) nonLocalTransHeat, real, dimension(nimem_,njmem_,nk_interface_), intent(inout) nonLocalTransScalar)
Calculates diffusivity and non-local transport according to KPP parameterization.
Parameters
cs Control structure
[in] g Ocean grid
[in] h Layer/level thicknesses (units of H)
[in] temp Pot. temperature (degrees C)
[in] salt Salinity (ppt)
[in] u Velocity components (m/s)
[in] v Velocity components (m/s)
eos Equation of state
[in] ustar Piston velocity (m/s)
[in] buoyflux Forcing buoyancy flux (m2/s3)
[in,out] kt (in) Vertical diffusivity of heat in interior (m2/s) (out) Vertical diffusivity including KPP (m2/s)
[in,out] ks (in) Vertical diffusivity of salt in interior (m2/s) (out) Vertical diffusivity including KPP (m2/s)
[in,out] kv (in) Vertical viscosity in interior (m2/s) (out) Vertical viscosity including KPP (m2/s)
[in,out] nonlocaltransheat Temp non-local transport (m/s)
[in,out] nonlocaltransscalar scalar non-local transport (m/s)
Definition at line 308 of file MOM_KPP.F90.
Referenced by mom_diabatic_driver::diabatic().
subroutine, public mom_kpp::kpp_end (type(kpp_cs), pointer CS)
Clear pointers, dealocate memory.
Parameters
cs Control structure
Definition at line 844 of file MOM_KPP.F90.
Referenced by mom_diabatic_driver::diabatic_driver_end().
logical function, public mom_kpp::kpp_init (type(param_file_type), intent(in) paramFile, type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(in), target diag, type(time_type), intent(in) Time, type(kpp_cs), pointer CS, logical, intent(out), optional passive)
Initialize the CVmix KPP module and set up diagnostics Returns True if KPP is to be used, False otherwise.
Parameters
[in] paramfile File parser
[in] g Ocean grid
[in] diag Diagnostics
[in] time Time
cs Control structure
[out] passive Copy of passiveMode
Definition at line 108 of file MOM_KPP.F90.
References mom_file_parser::closeparameterblock(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_file_parser::openparameterblock(), and mom_diag_mediator::register_diag_field().
Referenced by mom_diabatic_driver::diabatic_driver_init().
Member Data Documentation
integer, parameter, private mom_kpp::nlt_shape_cubic = 3 private
Cubic, G(s) =.
Definition at line 36 of file MOM_KPP.F90.
integer, parameter, private mom_kpp::nlt_shape_cubic_lmd = 4 private
Original shape, Cs.G(s) = 27/4.s.(1-s)^2.
Definition at line 37 of file MOM_KPP.F90.
integer, parameter, private mom_kpp::nlt_shape_cvmix = 0 private
Use the CVmix profile.
Definition at line 33 of file MOM_KPP.F90.
integer, parameter, private mom_kpp::nlt_shape_linear = 1 private
Linear, Cs.G(s) = 1-s.
Definition at line 34 of file MOM_KPP.F90.
integer, parameter, private mom_kpp::nlt_shape_parabolic = 2 private
Parabolic, Cs.G(s) = (1-s)^2.
Definition at line 35 of file MOM_KPP.F90.
logical, parameter mom_kpp::verbose = .False.
Definition at line 101 of file MOM_KPP.F90.
The documentation for this module was generated from the following file:
src/parameterizations/vertical/MOM_KPP.F90