MOM6: mom_ocmip2_cfc Module Reference
mom_ocmip2_cfc Module Reference
Data Types
type ocmip2_cfc_cs
type p3d
Public Member Functions
logical function, public register_ocmip2_cfc (G, param_file, CS, diag, tr_Reg, restart_CS)
subroutine, public initialize_ocmip2_cfc (restart, day, G, h, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public ocmip2_cfc_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, CS)
integer function, public ocmip2_cfc_stock (h, stocks, G, CS, names, units, stock_index)
subroutine, public ocmip2_cfc_surface_state (state, h, G, CS)
subroutine, public ocmip2_cfc_end (CS)
Private Member Functions
subroutine init_tracer_cfc (h, tr, tr_desc, land_val, IC_val, G, CS)
Private Attributes
integer, parameter ntr = 2
Detailed Description
Definition at line 1 of file MOM_OCMIP2_CFC.F90.
Member Function/Subroutine Documentation
subroutine mom_ocmip2_cfc::init_tracer_cfc (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimem_,njmem_,nkmem_), intent(out) tr, type(vardesc), intent(in) tr_desc, real, intent(in) land_val, real, intent(in) IC_val, type(ocean_grid_type), intent(in) G, type(ocmip2_cfc_cs), pointer CS) private
Definition at line 488 of file MOM_OCMIP2_CFC.F90.
References mom_error_handler::mom_error(), and midas_vertmap::tracer_z_init().
Referenced by initialize_ocmip2_cfc().
subroutine, public mom_ocmip2_cfc::initialize_ocmip2_cfc (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_obc_type), pointer OBC, type(ocmip2_cfc_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Definition at line 370 of file MOM_OCMIP2_CFC.F90.
References mom_tracer_registry::add_tracer_diagnostics(), init_tracer_cfc(), mom_error_handler::mom_error(), mom_diag_mediator::register_diag_field(), and mom_diag_to_z::register_z_tracer().
Referenced by mom_tracer_flow_control::tracer_flow_control_init().
subroutine, public mom_ocmip2_cfc::ocmip2_cfc_column_physics (real, dimension(nimem_,njmem_,nkmem_), intent(in) h_old, real, dimension(nimem_,njmem_,nkmem_), intent(in) h_new, real, dimension(nimem_,njmem_,nkmem_), intent(in) ea, real, dimension(nimem_,njmem_,nkmem_), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(ocmip2_cfc_cs), pointer CS)
Definition at line 529 of file MOM_OCMIP2_CFC.F90.
References coupler_util::extract_coupler_values(), and mom_tracer_registry::tracer_vertdiff().
Referenced by mom_tracer_flow_control::call_tracer_column_fns().
subroutine, public mom_ocmip2_cfc::ocmip2_cfc_end (type(ocmip2_cfc_cs), pointer CS)
Definition at line 742 of file MOM_OCMIP2_CFC.F90.
Referenced by mom_tracer_flow_control::tracer_flow_control_end().
integer function, public mom_ocmip2_cfc::ocmip2_cfc_stock (real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(:), intent(out) stocks, type(ocean_grid_type), intent(in) G, type(ocmip2_cfc_cs), pointer CS, character(len=*), dimension(:), intent(out) names, character(len=*), dimension(:), intent(out) units, integer, intent(in), optional stock_index)
Definition at line 615 of file MOM_OCMIP2_CFC.F90.
Referenced by mom_tracer_flow_control::call_tracer_stocks().
subroutine, public mom_ocmip2_cfc::ocmip2_cfc_surface_state (type(surface), intent(inout) state, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(ocmip2_cfc_cs), pointer CS)
Definition at line 669 of file MOM_OCMIP2_CFC.F90.
References coupler_util::set_coupler_values().
Referenced by mom_tracer_flow_control::call_tracer_surface_state().
logical function, public mom_ocmip2_cfc::register_ocmip2_cfc (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(ocmip2_cfc_cs), pointer CS, type(diag_ctrl), intent(in), target diag, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Definition at line 156 of file MOM_OCMIP2_CFC.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_tracer_registry::register_tracer(), and mom_io::slasher().
Referenced by mom_tracer_flow_control::call_tracer_register().
Member Data Documentation
integer, parameter mom_ocmip2_cfc::ntr = 2 private
Definition at line 98 of file MOM_OCMIP2_CFC.F90.
The documentation for this module was generated from the following file:
src/tracer/MOM_OCMIP2_CFC.F90