MOM6: mom_coriolisadv Module Reference
mom_coriolisadv Module Reference
Data Types
type coriolisadv_cs
Public Member Functions
subroutine, public coradcalc (u, v, h, uh, vh, CAu, CAv, AD, G, CS)
subroutine, public coriolisadv_init (Time, G, param_file, diag, AD, CS)
subroutine, public coriolisadv_end (CS)
Public Attributes
integer, parameter sadourny75_energy = 1
Private Member Functions
subroutine gradke (u, v, h, uh, vh, KE, KEx, KEy, k, G, CS)
Private Attributes
integer, parameter arakawa_hsu90 = 2
integer, parameter robust_enstro = 3
integer, parameter sadourny75_enstro = 4
integer, parameter arakawa_lamb81 = 5
integer, parameter al_blend = 6
character *(20), parameter sadourny75_energy_string = "SADOURNY75_ENERGY"
character *(20), parameter arakawa_hsu_string = "ARAKAWA_HSU90"
character *(20), parameter robust_enstro_string = "ROBUST_ENSTRO"
character *(20), parameter sadourny75_enstro_string = "SADOURNY75_ENSTRO"
character *(20), parameter arakawa_lamb_string = "ARAKAWA_LAMB81"
character *(20), parameter al_blend_string = "ARAKAWA_LAMB_BLEND"
integer, parameter ke_arakawa = 10
integer, parameter ke_simple_gudonov = 11
integer, parameter ke_gudonov = 12
character *(20), parameter ke_arakawa_string = "KE_ARAKAWA"
character *(20), parameter ke_simple_gudonov_string = "KE_SIMPLE_GUDONOV"
character *(20), parameter ke_gudonov_string = "KE_GUDONOV"
integer, parameter pv_adv_centered = 21
integer, parameter pv_adv_upwind1 = 22
character *(20), parameter pv_adv_centered_string = "PV_ADV_CENTERED"
character *(20), parameter pv_adv_upwind1_string = "PV_ADV_UPWIND1"
Detailed Description
Definition at line 1 of file MOM_CoriolisAdv.F90.
Member Function/Subroutine Documentation
subroutine, public mom_coriolisadv::coradcalc (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_,nkmem_), intent(in) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(in) vh, real, dimension(nimemb_,njmem_,nkmem_), intent(out) CAu, real, dimension(nimem_,njmemb_,nkmem_), intent(out) CAv, type(accel_diag_ptrs), intent(inout) AD, type(ocean_grid_type), intent(in) G, type(coriolisadv_cs), pointer CS)
Definition at line 165 of file MOM_CoriolisAdv.F90.
References gradke(), mom_error_handler::mom_error(), and mom_diag_mediator::query_averaging_enabled().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_coriolisadv::coriolisadv_end (type(coriolisadv_cs), pointer CS)
Definition at line 1004 of file MOM_CoriolisAdv.F90.
subroutine, public mom_coriolisadv::coriolisadv_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(accel_diag_ptrs), intent(inout), target AD, type(coriolisadv_cs), pointer CS)
Definition at line 827 of file MOM_CoriolisAdv.F90.
References mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), mom_diag_mediator::register_diag_field(), and mom_string_functions::uppercase().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
subroutine mom_coriolisadv::gradke (real, dimension(nimemb_,njmem_ ,nkmem_), intent(in) u, real, dimension(nimem_ ,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_ ,njmem_ ,nkmem_), intent(in) h, real, dimension(nimemb_,njmem_ ,nkmem_), intent(in) uh, real, dimension(nimem_,njmemb_ ,nkmem_), intent(in) vh, real, dimension(nimem_ ,njmem_), intent(out) KE, real, dimension(nimemb_,njmem_), intent(out) KEx, real, dimension(nimem_ ,njmemb_), intent(out) KEy, integer, intent(in) k, type(ocean_grid_type), intent(in) G, type(coriolisadv_cs), pointer CS) private
Definition at line 741 of file MOM_CoriolisAdv.F90.
Referenced by coradcalc().
Member Data Documentation
integer, parameter mom_coriolisadv::al_blend = 6 private
Definition at line 143 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::al_blend_string = "ARAKAWA_LAMB_BLEND" private
Definition at line 149 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::arakawa_hsu90 = 2 private
Definition at line 139 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::arakawa_hsu_string = "ARAKAWA_HSU90" private
Definition at line 145 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::arakawa_lamb81 = 5 private
Definition at line 142 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::arakawa_lamb_string = "ARAKAWA_LAMB81" private
Definition at line 148 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::ke_arakawa = 10 private
Definition at line 151 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::ke_arakawa_string = "KE_ARAKAWA" private
Definition at line 154 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::ke_gudonov = 12 private
Definition at line 153 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::ke_gudonov_string = "KE_GUDONOV" private
Definition at line 156 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::ke_simple_gudonov = 11 private
Definition at line 152 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::ke_simple_gudonov_string = "KE_SIMPLE_GUDONOV" private
Definition at line 155 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::pv_adv_centered = 21 private
Definition at line 158 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::pv_adv_centered_string = "PV_ADV_CENTERED" private
Definition at line 160 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::pv_adv_upwind1 = 22 private
Definition at line 159 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::pv_adv_upwind1_string = "PV_ADV_UPWIND1" private
Definition at line 161 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::robust_enstro = 3 private
Definition at line 140 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::robust_enstro_string = "ROBUST_ENSTRO" private
Definition at line 146 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::sadourny75_energy = 1
Definition at line 138 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::sadourny75_energy_string = "SADOURNY75_ENERGY" private
Definition at line 144 of file MOM_CoriolisAdv.F90.
integer, parameter mom_coriolisadv::sadourny75_enstro = 4 private
Definition at line 141 of file MOM_CoriolisAdv.F90.
character*(20), parameter mom_coriolisadv::sadourny75_enstro_string = "SADOURNY75_ENSTRO" private
Definition at line 147 of file MOM_CoriolisAdv.F90.
The documentation for this module was generated from the following file:
src/core/MOM_CoriolisAdv.F90