MOM6: polynomial_functions Module Reference
polynomial_functions Module Reference
Public Member Functions
real function, public evaluation_polynomial (coefficients, nb_coefficients, x)
real function, public integration_polynomial (xi0, xi1, C, n)
Detailed Description
Definition at line 1 of file polynomial_functions.F90.
Member Function/Subroutine Documentation
real function, public polynomial_functions::evaluation_polynomial (real, dimension(:), intent(in) coefficients, integer, intent(in) nb_coefficients, real, intent(in) x)
Definition at line 25 of file polynomial_functions.F90.
Referenced by regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), regrid_edge_values::edge_values_implicit_h6(), and mom_remapping::integraterecononinterval().
real function, public polynomial_functions::integration_polynomial (real, intent(in) xi0, real, intent(in) xi1, real, dimension(:), intent(in) C, integer, intent(in) n)
Definition at line 57 of file polynomial_functions.F90.
Referenced by mom_remapping::integraterecononinterval().
The documentation for this module was generated from the following file:
src/ALE/polynomial_functions.F90