MOM6: p1m_functions Module Reference
p1m_functions Module Reference
Public Member Functions
subroutine, public p1m_interpolation (N, h, u, ppoly)
subroutine, public p1m_boundary_extrapolation (N, h, u, ppoly)
Detailed Description
Definition at line 1 of file P1M_functions.F90.
Member Function/Subroutine Documentation
subroutine, public p1m_functions::p1m_boundary_extrapolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 93 of file P1M_functions.F90.
Referenced by mom_regridding::regridding_iteration().
subroutine, public p1m_functions::p1m_interpolation (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) u, type(ppoly_t), intent(inout) ppoly)
Definition at line 44 of file P1M_functions.F90.
References regrid_edge_values::average_discontinuous_edge_values(), and regrid_edge_values::bound_edge_values().
Referenced by mom_regridding::regridding_iteration().
The documentation for this module was generated from the following file:
src/ALE/P1M_functions.F90