MOM6: mom_continuity Module Reference
mom_continuity Module Reference
Data Types
type continuity_cs
Public Member Functions
subroutine, public continuity (u, v, hin, h, uh, vh, dt, G, CS, uhbt, vhbt, OBC, visc_rem_u, visc_rem_v, u_cor, v_cor, uhbt_aux, vhbt_aux, u_cor_aux, v_cor_aux, BT_cont)
subroutine, public continuity_init (Time, G, param_file, diag, CS)
subroutine, public continuity_end (CS)
Public Attributes
integer, parameter ppm_scheme = 1
Private Attributes
integer id_clock_pass
integer id_clock_vertvisc
character(len=20), parameter ppm_string = "PPM"
Detailed Description
Definition at line 1 of file MOM_continuity.F90.
Member Function/Subroutine Documentation
subroutine, public mom_continuity::continuity (real, dimension(nimemb_,njmem_,nkmem_), intent(in) u, real, dimension(nimem_,njmemb_,nkmem_), intent(in) v, real, dimension(nimem_,njmem_,nkmem_), intent(in) hin, real, dimension(nimem_,njmem_,nkmem_), intent(inout) h, real, dimension(nimemb_,njmem_,nkmem_), intent(out) uh, real, dimension(nimem_,njmemb_,nkmem_), intent(out) vh, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(continuity_cs), pointer CS, real, dimension(nimemb_,njmem_), intent(in), optional uhbt, real, dimension(nimem_,njmemb_), intent(in), optional vhbt, type(ocean_obc_type), optional, pointer OBC, real, dimension(nimemb_,njmem_,nkmem_), intent(in), optional visc_rem_u, real, dimension(nimem_,njmemb_,nkmem_), intent(in), optional visc_rem_v, real, dimension(nimemb_,njmem_,nkmem_), intent(out), optional u_cor, real, dimension(nimem_,njmemb_,nkmem_), intent(out), optional v_cor, real, dimension(nimemb_,njmem_), intent(in), optional uhbt_aux, real, dimension(nimem_,njmemb_), intent(in), optional vhbt_aux, real, dimension(nimemb_,njmem_,nkmem_), intent(inout), optional u_cor_aux, real, dimension(nimem_,njmemb_,nkmem_), intent(inout), optional v_cor_aux, type(bt_cont_type), optional, pointer BT_cont)
Definition at line 75 of file MOM_continuity.F90.
References mom_continuity_ppm::continuity_ppm(), and mom_error_handler::mom_error().
Referenced by mom_dynamics_legacy_split::adjustments_dyn_legacy_split(), mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
subroutine, public mom_continuity::continuity_end (type(continuity_cs), pointer CS)
Definition at line 212 of file MOM_continuity.F90.
References mom_continuity_ppm::continuity_ppm_end().
subroutine, public mom_continuity::continuity_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(continuity_cs), pointer CS)
Definition at line 162 of file MOM_continuity.F90.
References mom_continuity_ppm::continuity_ppm_init(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), and mom_string_functions::uppercase().
Referenced by mom_dynamics_legacy_split::initialize_dyn_legacy_split(), mom_dynamics_split_rk2::initialize_dyn_split_rk2(), mom_dynamics_unsplit::initialize_dyn_unsplit(), and mom_dynamics_unsplit_rk2::initialize_dyn_unsplit_rk2().
Member Data Documentation
integer mom_continuity::id_clock_pass private
Definition at line 58 of file MOM_continuity.F90.
integer mom_continuity::id_clock_vertvisc private
Definition at line 58 of file MOM_continuity.F90.
integer, parameter mom_continuity::ppm_scheme = 1
Definition at line 70 of file MOM_continuity.F90.
character(len=20), parameter mom_continuity::ppm_string = "PPM" private
Definition at line 71 of file MOM_continuity.F90.
The documentation for this module was generated from the following file:
src/core/MOM_continuity.F90