MOM6: config_src/ice_solo_driver/ice_shelf_driver.F90 File Reference
ice_shelf_driver.F90 File Reference
#include <MOM_memory.h>
#include "version_variable.h"
Functions/Subroutines
program shelf_main
Function/Subroutine Documentation
program shelf_main ()
Definition at line 1 of file ice_shelf_driver.F90.
References mom_file_parser::close_param_file(), mom_diag_mediator::diag_mediator_close_registration(), mom_diag_mediator::diag_mediator_end(), mom_diag_mediator::disable_averaging(), mom_diag_mediator::enable_averaging(), mom_get_input::get_mom_input(), mom_ice_shelf::ice_shelf_end(), mom_ice_shelf::ice_shelf_save_restart(), mom_ice_shelf::initialize_ice_shelf(), mom_error_handler::is_root_pe(), mom_file_parser::log_version(), mom_error_handler::mom_error(), mom_coms::mom_infra_end(), mom_error_handler::mom_mesg(), mom_write_cputime::mom_write_cputime_init(), mom_restart::save_restart(), mom_ice_shelf::solo_time_step(), mom_write_cputime::write_cputime(), and mom_write_cputime::write_cputime_start_clock().