MOM6: mom_eos_unesco::calculate_density_unesco Interface Reference
mom_eos_unesco::calculate_density_unesco Interface Reference
Private Member Functions
subroutine calculate_density_scalar_unesco (T, S, pressure, rho)
subroutine calculate_density_array_unesco (T, S, pressure, rho, start, npts)
Detailed Description
Definition at line 35 of file MOM_EOS_UNESCO.F90.
Member Function/Subroutine Documentation
subroutine mom_eos_unesco::calculate_density_unesco::calculate_density_array_unesco (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts) private
Definition at line 91 of file MOM_EOS_UNESCO.F90.
Referenced by mom_eos::calculate_density_array(), and mom_eos_unesco::calculate_density_scalar_unesco().
subroutine mom_eos_unesco::calculate_density_unesco::calculate_density_scalar_unesco (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho) private
Definition at line 61 of file MOM_EOS_UNESCO.F90.
Referenced by mom_eos::calculate_density_scalar().
The documentation for this interface was generated from the following file:
src/equation_of_state/MOM_EOS_UNESCO.F90