MOM6: regrid_consts::coordinateunits Interface Reference
regrid_consts::coordinateunits Interface Reference
Public Member Functions
character(len=16) function coordinateunitsi (coordMode)
character(len=16) function coordinateunitss (string)
Detailed Description
Definition at line 26 of file regrid_consts.F90.
Member Function/Subroutine Documentation
character(len=16) function regrid_consts::coordinateunits::coordinateunitsi (integer, intent(in) coordMode)
Definition at line 50 of file regrid_consts.F90.
Referenced by regrid_consts::coordinateunitsi(), and regrid_consts::coordinateunitss().
character(len=16) function regrid_consts::coordinateunits::coordinateunitss (character(len=*), intent(in) string)
Definition at line 65 of file regrid_consts.F90.
Referenced by regrid_consts::coordinateunitss().
The documentation for this interface was generated from the following file:
src/ALE/regrid_consts.F90