MOM6: mom_io::file_exists Interface Reference
mom_io::file_exists Interface Reference
Private Member Functions
file_exist
logical function mom_file_exists (file_name, MOM_Domain)
Detailed Description
Definition at line 101 of file MOM_io.F90.
Member Function/Subroutine Documentation
mom_io::file_exists::file_exist () private
Referenced by mom_domains::mom_domains_init(), and mom_io::mom_file_exists().
logical function mom_io::file_exists::mom_file_exists (character(len=*), intent(in) file_name, type(mom_domain_type), intent(in) MOM_Domain) private
Definition at line 585 of file MOM_io.F90.
Referenced by mom_io::mom_file_exists().
The documentation for this interface was generated from the following file:
src/framework/MOM_io.F90