MOM6: mom_restart::query_initialized Interface Reference
mom_restart::query_initialized Interface Reference
Private Member Functions
logical function query_initialized_name (name, CS)
logical function query_initialized_0d (f_ptr, CS)
logical function query_initialized_1d (f_ptr, CS)
logical function query_initialized_2d (f_ptr, CS)
logical function query_initialized_3d (f_ptr, CS)
logical function query_initialized_0d_name (f_ptr, name, CS)
logical function query_initialized_1d_name (f_ptr, name, CS)
logical function query_initialized_2d_name (f_ptr, name, CS)
logical function query_initialized_3d_name (f_ptr, name, CS)
Detailed Description
Definition at line 137 of file MOM_restart.F90.
Member Function/Subroutine Documentation
logical function mom_restart::query_initialized::query_initialized_0d (real, target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 330 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_0d_name (real, target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 446 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_1d (real, dimension(:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 359 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_1d_name (real, dimension(:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 483 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_2d (real, dimension(:,:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 388 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_2d_name (real, dimension(:,:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 520 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_3d (real, dimension(:,:,:), target f_ptr, type(mom_restart_cs), pointer CS) private
Definition at line 417 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_3d_name (real, dimension(:,:,:), target f_ptr, character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 557 of file MOM_restart.F90.
logical function mom_restart::query_initialized::query_initialized_name (character(len=*) name, type(mom_restart_cs), pointer CS) private
Definition at line 294 of file MOM_restart.F90.
Referenced by mom_restart::query_initialized_0d_name(), mom_restart::query_initialized_1d_name(), mom_restart::query_initialized_2d_name(), and mom_restart::query_initialized_3d_name().
The documentation for this interface was generated from the following file:
src/framework/MOM_restart.F90