MOM6: mom_file_parser::read_param Interface Reference
mom_file_parser::read_param Interface Reference
Private Member Functions
subroutine read_param_int (CS, varname, value, fail_if_missing)
subroutine read_param_real (CS, varname, value, fail_if_missing)
subroutine read_param_logical (CS, varname, value, fail_if_missing)
subroutine read_param_char (CS, varname, value, fail_if_missing)
subroutine read_param_char_array (CS, varname, value, fail_if_missing)
subroutine read_param_time (CS, varname, value, timeunit, fail_if_missing)
subroutine read_param_int_array (CS, varname, value, fail_if_missing)
subroutine read_param_real_array (CS, varname, value, fail_if_missing)
Detailed Description
Definition at line 124 of file MOM_file_parser.F90.
Member Function/Subroutine Documentation
subroutine mom_file_parser::read_param::read_param_char (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, character(len=*), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 680 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_char().
subroutine mom_file_parser::read_param::read_param_char_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, character(len=*), dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 703 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_char_array().
subroutine mom_file_parser::read_param::read_param_int (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, integer, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 562 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_int().
subroutine mom_file_parser::read_param::read_param_int_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, integer, dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 591 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_int_array().
subroutine mom_file_parser::read_param::read_param_logical (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, logical, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 731 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_logical().
subroutine mom_file_parser::read_param::read_param_real (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, real, intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 621 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_real().
subroutine mom_file_parser::read_param::read_param_real_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, real, dimension(:), intent(inout) value, logical, intent(in), optional fail_if_missing) private
Definition at line 650 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_real_array().
subroutine mom_file_parser::read_param::read_param_time (type(param_file_type), intent(in) CS, character(len=*), intent(in) varname, type(time_type), intent(inout) value, real, intent(in), optional timeunit, logical, intent(in), optional fail_if_missing) private
Definition at line 754 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_time().
The documentation for this interface was generated from the following file:
src/framework/MOM_file_parser.F90