MOM6: mom_file_parser::log_param Interface Reference
mom_file_parser::log_param Interface Reference
Private Member Functions
subroutine log_param_int (CS, modulename, varname, value, desc, units, default)
subroutine log_param_real (CS, modulename, varname, value, desc, units, default)
subroutine log_param_logical (CS, modulename, varname, value, desc, units, default)
subroutine log_param_char (CS, modulename, varname, value, desc, units, default)
subroutine log_param_time (CS, modulename, varname, value, desc, units, default, timeunit)
subroutine log_param_int_array (CS, modulename, varname, value, desc, units, default)
subroutine log_param_real_array (CS, modulename, varname, value, desc, units, default)
Detailed Description
Definition at line 129 of file MOM_file_parser.F90.
Member Function/Subroutine Documentation
subroutine mom_file_parser::log_param::log_param_char (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, character(len=*), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, character(len=*), intent(in), optional default) private
Definition at line 1296 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_char(), and mom_file_parser::get_param_char_array().
subroutine mom_file_parser::log_param::log_param_int (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default) private
Definition at line 1165 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_int().
subroutine mom_file_parser::log_param::log_param_int_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, integer, dimension(:), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, integer, intent(in), optional default) private
Definition at line 1189 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_int_array().
subroutine mom_file_parser::log_param::log_param_logical (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, logical, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, logical, intent(in), optional default) private
Definition at line 1268 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_logical().
subroutine mom_file_parser::log_param::log_param_real (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default) private
Definition at line 1214 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_real().
subroutine mom_file_parser::log_param::log_param_real_array (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, real, dimension(:), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, real, intent(in), optional default) private
Definition at line 1239 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_real_array().
subroutine mom_file_parser::log_param::log_param_time (type(param_file_type), intent(in) CS, character(len=*), intent(in) modulename, character(len=*), intent(in) varname, type(time_type), intent(in) value, character(len=*), intent(in), optional desc, character(len=*), intent(in), optional units, type(time_type), intent(in), optional default, real, intent(in), optional timeunit) private
Definition at line 1321 of file MOM_file_parser.F90.
Referenced by mom_file_parser::get_param_time().
The documentation for this interface was generated from the following file:
src/framework/MOM_file_parser.F90