MOM6: src/initialization/MOM_initialization.F90 File Reference
MOM_initialization.F90 File Reference
#include <MOM_memory.h>
#include "version_variable.h"
Data Types
module mom_initialization
type mom_initialization::mom_initialization_struct
Functions/Subroutines
real function my_psi (ig, jg)
subroutine mystats (array, missing, k, mesg)
Function/Subroutine Documentation
real function initialize_velocity_circular::my_psi (integer ig, integer jg) private
Definition at line 1873 of file MOM_initialization.F90.
Referenced by mom_initialization::initialize_velocity_circular().
subroutine mom_temp_salt_initialize_from_z::mystats (real, dimension(:,:), intent(in) array, real, intent(in) missing, integer k, character(len=*) mesg) private
Definition at line 4078 of file MOM_initialization.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_mesg().
Referenced by mom_initialization::mom_temp_salt_initialize_from_z().