MOM6: src/framework/MOM_checksums.F90 File Reference
MOM_checksums.F90 File Reference
#include "version_variable.h"
Data Types
module mom_checksums
interface mom_checksums::hchksum
interface mom_checksums::qchksum
interface mom_checksums::uchksum
interface mom_checksums::vchksum
interface mom_checksums::chksum
interface mom_checksums::chk_sum_msg
interface mom_checksums::is_nan
Functions/Subroutines
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function subchk (array, G, di, dj)
subroutine substats (G, array, mesg)
integer function hsubsum2d (array, start_x, end_x, start_y, end_y, di, dj)
integer function hsubsum3d (array, start_x, end_x, start_y, end_y, di, dj)
Function/Subroutine Documentation
integer function hchksum2d::hsubsum2d (real, dimension(:,:) array, integer start_x, integer end_x, integer start_y, integer end_y, integer di, integer dj) private
Definition at line 859 of file MOM_checksums.F90.
References bitcount().
Referenced by mom_checksums::hchksum2d().
integer function hchksum3d::hsubsum3d (real, dimension(:,:,:) array, integer start_x, integer end_x, integer start_y, integer end_y, integer di, integer dj) private
Definition at line 916 of file MOM_checksums.F90.
References bitcount().
Referenced by mom_checksums::hchksum3d().
integer function chksum_h_2d::subchk (real, dimension(g%isd:,g%jsd:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 141 of file MOM_checksums.F90.
References bitcount().
Referenced by mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_q_2d(), mom_checksums::chksum_q_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), mom_checksums::chksum_v_3d(), and subchk().
integer function chksum_h_3d::subchk (real, dimension(g%isd:,g%jsd:,:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 505 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_v_3d::subchk (real, dimension(g%isd:,g%jsdb:,:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 778 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_u_2d::subchk (real, dimension(g%isdb:,g%jsd:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 323 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_q_3d::subchk (real, dimension(g%isdb:,g%jsdb:,:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 596 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_q_2d::subchk (real, dimension(g%isdb:,g%jsdb:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 232 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_u_3d::subchk (real, dimension(g%isdb:,g%jsd:,:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 687 of file MOM_checksums.F90.
References bitcount(), and subchk().
integer function chksum_v_2d::subchk (real, dimension(g%isd:,g%jsdb:), intent(in) array, type(ocean_grid_type), intent(in) G, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 414 of file MOM_checksums.F90.
References bitcount(), and subchk().
subroutine chksum_v_2d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsdb:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 428 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_q_2d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isdb:,g%jsdb:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 246 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_h_2d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsd:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 155 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
Referenced by mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_q_2d(), mom_checksums::chksum_q_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), and mom_checksums::chksum_v_3d().
subroutine chksum_q_3d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isdb:,g%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 610 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_u_3d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isdb:,g%jsd:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 701 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_v_3d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 792 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_h_3d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isd:,g%jsd:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 519 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
subroutine chksum_u_2d::substats (type(ocean_grid_type), intent(in) G, real, dimension(g%isdb:,g%jsd:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 337 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().